### ISSUE TITLE
Fabric API mod keeps flipflopping between Curseforge and Modrinth

### ISSUE THREAD

**Issue by bentterp** [PrismLauncher/PrismLauncher#2088] opened 2024-02-03 05:00 UTC
### Operating System

Windows

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

Whenever I update the whole list of mods, the updater picks up the same version of the Fabric API mod but from the other location as an update. 
This doesn't happen if I just select the Fabric API mod and try to update that

### Steps to reproduce

Install a bunch of mods and run the updater a couple of times

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-02-03 06:55
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2076

**Closed as not planned by Trial97** 2024-02-03 06:55 UTC
