### ISSUE TITLE
Names of mods overlap mods summers

### ISSUE THREAD

**Issue by Levakiv** [PrismLauncher/PrismLauncher#171] opened 2022-10-20 12:27 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launche 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

Names of mods overlap summers of mods.
![image](https://user-images.githubusercontent.com/68151306/196946872-43bff999-c6da-4b6b-a2b9-11fca4496cb9.png)

### Steps to reproduce

Add instance;
Go to the mod edit page
use "Download mods"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by forkiesassds** [comment] 2022-10-20 13:06
Duplicate of #20

**Closed as completed** 2022-10-20 13:11 UTC
