### ISSUE TITLE
Adding folders/color-code to the mods tab

### ISSUE THREAD

**Issue by Operu** [PrismLauncher/PrismLauncher#1546] opened 2023-08-20 11:17 UTC
### Role

When I play modded and I manage my mods it's hard to see which mods are content mods, performance mods, libraries, QOL mods, etc.

### Suggestion

Add a feature in the mod menu to organize mods into folders or colorcode them.

### Benefit

So I can manage my mods in a more organized way, and to get an overview of what I have installed

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment] 2023-08-21 11:19
Duplicate of #154

**Closed as not planned by TheKodeToad** 2023-08-21 11:19 UTC
Labels: status: duplicate, status: invalid
