### ISSUE TITLE
Allow us to increase the GUI size

### ISSUE THREAD

**Issue by Dragon232347** [PrismLauncher/PrismLauncher#3167] opened 2024-12-05 23:57 UTC
### Role

Just installed prism as an alternative to CF

### Suggestion

Add a slider or something idc to let us increaase the GUI scale

### Benefit

Accessiblity & QoL

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Alright look. imma be honest I have seen the issues detailing this exact issue and every single one is marked as not planned and it's pissing me off. I'm disabled and just generally do not like small GUI because of it. It's absurd that this has been shot down multiple times bc it's a pretty major and basic accessibility feature. As much as I hate curseforge I have to struggle to see what i'm doing if I use prism.

**Comment by Trial97** [comment] 2024-12-06 06:45
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/324

**Closed as not planned by Trial97** 2024-12-06 06:45 UTC
Labels: type: enhancement
