### ISSUE TITLE
"Open Folder" button does not open folder

### ISSUE THREAD

**Issue by koffiato** [PrismLauncher/PrismLauncher#2051] opened 2024-01-21 14:24 UTC
### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.1

### Description of bug

Right clicking on an instance and clicking on the Open Folder button should bring up the instance folder, but instead it prints out
`    12.082 D | Opening directory "/home/koffiato/.local/share/PrismLauncher/instances/FastSky"
    24.470 W | [qt.qpa.wayland]: Creating a popup with a parent, QWidgetWindow(0x56c0e929b300, name="MainWindowWindow") which does not match the current topmost grabbing popup, QWidgetWindow(0x56c0e9230e60, name="QMenuClassWindow") With some shell surface protocols, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly. Please fix the transient parent of the popup.
`

Using the prismlauncher-8.0-1.1 package from ChaoticAUR on Arch (KDE on Wayland).

### Steps to reproduce

* Right click on an instance
* Click on Open Folder button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment] 2024-01-21 14:32
Will be fixed in the upcoming 8.1 release.

Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1490

**Closed as not planned by Scrumplex** 2024-01-21 14:32 UTC
