### ISSUE TITLE
Automatically download & delete Mod Dependencies

### ISSUE THREAD

**Issue by echoless3484** [PrismLauncher/PrismLauncher#622] opened 2022-12-15 03:00 UTC
### Role

I make Modpacks and play Modded Minecraft

### Suggestion

I want Prism Launcher to automatically download Core Mods and other Requriements

### Benefit

It would be so much easier to debug issues without searching through logs and taking pictures of the fabric menu

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment] 2022-12-15 12:44
Duplicate of #116

**Closed as not planned by flowln** 2022-12-15 12:44 UTC
Labels: type: enhancement

**Comment by InfiniteCoder01** [comment] 2025-04-23 12:41
Actually, deleting dependencies was not part of #116 and it would be really useful (or at least a way to tell which mods were installed as dependencies)
