### ISSUE TITLE
Crash when reinstalling mod

### ISSUE THREAD

**Issue by FBanna** [PrismLauncher/PrismLauncher#3188] opened 2024-12-10 19:09 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

QT 6.7.3

### Description of bug

The launcher crashed when clicking reinstall with no valid mod versions available. This should not be the result of reinstalling when no mod versions are available. Maybe a pop up should appear

### Steps to reproduce

Mods -> Change Version -> reinstall when no versions are found

### Suspected cause

No valid mod version is available.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-12-10 21:05
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/3001
also fixed in nightly 
Where can I download unstable builds of Prism Launcher?
You can download unstable builds [here](https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop).

    :warning: Caution
    Unstable builds have more bugs and are therefore more likely to break! By using the latest commit you are using software which has not been properly tested. For this reason we recommend using Portable or AppImage builds, or least making a backup.

**Closed as not planned by Trial97** 2024-12-10 21:05 UTC
