### ISSUE TITLE
GLXBadFBConfig error with minecraft 1.19 and 1.20

### ISSUE THREAD

**Issue by Dividfoxx** [PrismLauncher/PrismLauncher#1654] opened 2023-09-25 12:14 UTC
### Operating System

Asaki Linux aarch64

### Version of Prism Launcher

6.0 or whatevers latest on the AUR

### Version of Qt

6.5.2

### Description of bug

After successfully installing the version (1.19.4 fabric) minecraft crashed with the error message _GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig.
Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions)._
but aka.ms/mcdriver was useless and dint help. couldn't find anything related to this launcher online except for some outdated polyMC stuff on a forum Idk what to do.
Can anyone help?

### Steps to reproduce

Pick a minecraft version between 1.19 and 1.20 (I was using 1.19.4 but it also gave the same result on 1.20) and select fabric under the menu, wait for it to load up and be greeted by an error message

### Suspected cause

It seems to be something to do with OpenGL's graphics that newer versions need to run on to work. people seem to have gotten past this by spoofing the mesa version with 4.3 (https://www.planetminecraft.com/blog/glfw-error-65543-glx-failed-to-create-context-glxbadfbconfig-solution/). People seem to also be saying that it also happened on 1.17 and 1.18 on the forum but I haven't checked.
 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by AAlieZZ** [comment] 2023-09-28 00:36
Same issue, but it was able to launch the game by switching the GPU from NVIDIA to iGPU.

**Comment by Trial97** [comment] 2023-09-28 07:50
First, if you have problems with Nvidia have a look here:https://github.com/PrismLauncher/PrismLauncher/issues/1137#issuecomment-1629146459 is confirmed that Nvidia optimization tend to break things. 
As for the original issue, the cause is missing drivers, from what I know Asahi Linux is experimental, and try to ask them how to install the missing drivers.
Also, the latest version of AUR should be develop (look into Help>about) the fact that the aur package reports 6.0 is wrong as it always points to latest develop

**Comment by Trial97** [comment] 2023-09-28 10:04
I had a look at the release notes of asking:https://asahilinux.org/2022/03/asahi-linux-alpha-release/ and it looks like it doesn't yet support GPU acceleration. 
I'm closing this issue as is not related in any way with the launcher.

**Closed as not planned by Trial97** 2023-09-28 10:04 UTC

**Comment by AAlieZZ** [comment] 2023-09-30 07:27
> this issue as is not related in any way with the launcher.

This is caused by the NVIDIA driver, I tried switching to [nvidia-open-dkms](https://archlinux.org/packages/extra/x86_64/nvidia-open-dkms/) and it worked fine!

**Comment by ghost** [comment] 2023-11-17 21:53
Not an nvidia issue. Also occurs on amdgpu. Issue appeared when upgrading from 7.x -> 8.x of prism.

#954

**Comment by HalJordan** [comment] 2024-03-21 05:28
Yeah, definitely not limited to nvidia. I'm able to run several other games/apps that rely on opengl INCLUDING using the POS put out by the FTB team. So it's not minecraft. It's not my drivers. It's something that the prism launcher is(not) doing.

It's happened before in the same way, then suddenly fixed itself but I was too busy with life to document when that happened.
