### ISSUE TITLE
Bar between `Name` and `Version` is unmovable

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#2842] opened 2024-09-19 20:39 UTC
### Operating System

macOS

### Version of Prism Launcher

9.0-develop (dc67807 -Debug)

### Version of Qt

6.7.2

### Description of bug

Between `Name` bar and `Version` bar is unmovable

### Steps to reproduce

Go to mods tab on 9.0
try moving between tabs

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment] 2024-09-19 20:41
I couldn't find any similar issues. 

You used to be able to move `Version` tab by moving the end, which was weird but worked. However that part works correctly, but now there's no way to move tab. 

As shown here
<img width="1065" alt="Screen Shot 2024-09-19 at 4 33 38 PM" src="https://github.com/user-attachments/assets/a67bb64a-7efd-405c-95da-b3d8ac95f13e">

**Comment by Aces-and-Jacks** [comment] 2024-09-19 20:44
Tho resource pack tab and shader pack tab sections do still work the old way

**Comment by Trial97** [comment] 2024-09-20 12:54
It may be a mac thing as on linux I can't reproduce it

**Comment by TayouVR** [comment] 2024-09-20 19:47
this is a cross OS thing
basically what we changed is, that all columns can now have their size changed, but "Enable", "Image" and "Name" are left aligned, while the rest is right aligned.
this is generally the intended behaviour since the name column should be the one growing in size as the window is resized.

The issue is now, that Qt doesn't handle resizing of right aligned columns correctly, so the resize handle is on the right side.

This won't be fixed until we rewrite the UI using QML, so I'm going to close this for now.

**Closed as not planned by TayouVR** 2024-09-20 19:47 UTC

**Comment by Aces-and-Jacks** [comment] 2024-09-22 21:32
8.4

https://github.com/user-attachments/assets/a1b25dc3-aa83-4e27-a669-d1018165689e

9.0

https://github.com/user-attachments/assets/c3a96260-8a28-4e54-809f-0ee0567cb9fc

**Comment by Aces-and-Jacks** [comment] 2024-09-22 22:03
Never mind on the vids. I figured something else out
