### ISSUE TITLE
Unable to login through microsoft account [First time user]

### ISSUE THREAD

**Issue by asterixasteroid** [PrismLauncher/PrismLauncher#2765] opened 2024-08-29 15:49 UTC
### Operating System

Windows

### Version of Prism Launcher

prism launcher 8.4

### Version of Qt

qt 6.6.3

### Description of bug

after downloading prism launcher for the first time i have tried to log in 

i am not able to log in through the Microsoft account. It shows the following words

"Failed to get authorization for Xbox services: Operation canceled"

ive looked at other people's post regarding this and performed every possible solution but it still shows the same 

### Steps to reproduce

go to settings>accounts>add microsoft account>try your account>shows logging in as x box user>after a minute or two,shows failed to get authorisation for xbox servicces:operations cancelled

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-08-29 15:59
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Comment by Trial97** [comment] 2024-08-29 16:00
also ` xbox servicces:operations cancelled` means something on your network is blocking the requests

**Closed as not planned by Trial97** 2024-08-29 15:59 UTC

**Comment by asterixasteroid** [comment] 2024-08-29 16:01
ive tried changing network but it still doesnt work

**Comment by asterixasteroid** [comment] 2024-08-29 16:03
also ive noticed that iget an email whenever i try logging in saying prism launcher wants access of my microsoft account.is that normal? 

perhaps that might probably be the reason its blocking the authorization?

**Comment by Trial97** [comment] 2024-08-29 16:04
```ensure that you sign in using a password: Sign in to https://account.live.com/proofs/manage/additional and add a password as a way to sign in```

see the mentioned issue for more solutions

**Comment by asterixasteroid** [comment] 2024-08-29 16:41
I Have performed the above action,it still doesnt seem to help
