### ISSUE TITLE
Dependency Check keeps changing providers of dependencies

### ISSUE THREAD

**Issue by SwordSt0ne** [PrismLauncher/PrismLauncher#2881] opened 2024-10-03 04:27 UTC
### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

Dependencies keep switching providers due to mods coming from different providers (i.e., Modrinth and CurseForge)

### Steps to reproduce

Create an instance. Download Fabric API and download some mods that rely on it from CurseForge and then some from Modrinth.
Make sure they all rely on Fabric API. Now use 'Verify Dependencies'. Each time you use it, the Fabric API will keep downloading from different providers. The same bug occurs with other dependencies.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-10-03 05:38
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1926

**Closed as not planned by Trial97** 2024-10-03 05:38 UTC
