### ISSUE TITLE
Prism launcher unable to create an instance

### ISSUE THREAD

**Issue by A-Rock-With-Internet** [PrismLauncher/PrismLauncher#2581] opened 2024-06-28 12:35 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.7.2

### Description of bug

Prism launcher showing a blank window to open a new instance that never loads

### Steps to reproduce

![Screenshot from 2024-06-28 17-33-44](https://github.com/PrismLauncher/PrismLauncher/assets/173546998/e7098641-2ff7-461c-852d-a5e21184bac6)
![Screenshot from 2024-06-28 17-33-54](https://github.com/PrismLauncher/PrismLauncher/assets/173546998/31cf0b24-3849-4d0b-a6f8-439fb86f9f89)
![Screenshot from 2024-06-28 17-34-10](https://github.com/PrismLauncher/PrismLauncher/assets/173546998/05dfe42f-6ab5-4717-b6ee-51b63fe38996)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by A-Rock-With-Internet** [comment] 2024-06-28 12:36
dragging and dropping modpacks also has the same issue
the issue disapears after a (full) reinstallation
but then appears again after a little while

**Comment by Trial97** [comment] 2024-06-28 12:38
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2388

**Closed as not planned by Trial97** 2024-06-28 12:38 UTC
