### ISSUE TITLE
Broken mod version detection and duplicate install dependencies

### ISSUE THREAD

**Issue by Goldn7799** [PrismLauncher/PrismLauncher#1907] opened 2023-12-02 14:35 UTC
### Operating System

Windows

### Version of Prism Launcher

PrismLauncher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

when update the mod, some mod indicate same current and new version are same, and for some dependencies, having clone install but same package.

### Steps to reproduce

using check updates

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-12-02 19:13
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1745

**Closed as not planned by Trial97** 2023-12-02 19:13 UTC
