### ISSUE TITLE
Allow Prism to make zips with other modpack formats in them when exporting. (I don't know how to explain this well, sorry.)

### ISSUE THREAD

**Issue by MagmaSlime123** [PrismLauncher/PrismLauncher#452] opened 2022-11-14 05:27 UTC
### Role

I play modded MC.

### Suggestion

Allow Prism to make zips with other modpack formats in them when exporting. (I don't know how to explain this well, sorry.)

### Benefit

So people don't need to install 50 other launchers for their modpack format(s).

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Prism should be an all-in-one power-user launcher, like GD & AT are, iirc.

**Comment by txtsd** [comment] 2022-11-14 05:55
Duplicate of #269

**Closed as not planned** 2022-11-14 05:56 UTC
Labels: type: enhancement
