### ISSUE TITLE
Minimum height of launcher settings in 9.0+ is bigger then 8.4

### ISSUE THREAD

**Issue by Josh65-2201** [PrismLauncher/PrismLauncher#3049] opened 2024-11-02 20:19 UTC
### Operating System

Windows

### Version of Prism Launcher

9.1

### Version of Qt

6.7.2

### Description of bug

The minimum height of the launcher settings window in 9.0+ (Dark mode) is much bigger then it was in 8.4 (Light mode)
![image](https://github.com/user-attachments/assets/cec232f2-21a5-492c-af71-742fef157d22)

### Steps to reproduce

1. Open launcher settings
2. Drag height to as small as possible
3. Compare to 8.4

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-11-02 22:13
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/3015

**Closed as not planned by Trial97** 2024-11-02 22:13 UTC
