### ISSUE TITLE
Download Curseforge mods with embedded browser windows

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#769] opened 2023-01-21 00:46 UTC
### Role

I recently migrated from GDLauncher to play modded Minecraft.

### Suggestion

Download third-party blocked mods or resource packs from browser windows embedded in the application.

### Benefit

Reduces clutter in the user's downloads folder.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When downloading a third-party blocked mod or resource pack, Prism Launcher should download the blocked mod or pack by opening the download pages an embedded web browser window, rather than opening them on the desktop. This feature is already present on GDLauncher, and I would love to see it here. Thank you for developing this launcher.

**Comment by theofficialgman** [comment] 2023-01-21 00:53
GDLauncher is effectively chromium. it is an electron app (aka: a browser) so implementing embedded browser windows is literally free for them. GDLauncher is a browser itself.

Prism is based of the lightweight toolkit QT (5/6). While it does have a webengine extension, I don't think the devs are interested in adding it (and all the mess that comes with it) simply for this feature that already works using your actuall browser

**Comment by flowln** [comment] 2023-01-21 00:57
Duplicate of #542

**Closed as not planned by flowln** 2023-01-21 00:57 UTC
Labels: type: enhancement
