### ISSUE TITLE
Highlight not worked mods without dependents

### ISSUE THREAD

**Issue by anioji** [PrismLauncher/PrismLauncher#2442] opened 2024-05-26 21:24 UTC
### Role

Modpacker, Player

### Suggestion

When you disable a mod, the mods that depend on it are highlighted as "Maybe not working"

### Benefit

I build modpacks in this launcher 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Good day. 
I wanted to make a dependency analyzer and mark those mods that may not start due to disabling or removing their dependencies

And perhaps there are not enough workers

Also, I would like that when you hover over them, those missing mod dependencies are shown

You can highlight an entire line in the launcher with a non-working mod

![Screenshot from 2024-05-27 02-19-54](https://github.com/PrismLauncher/PrismLauncher/assets/140120605/20e70171-4664-4f29-9a89-75fc2ce6063b)

**Comment by Trial97** [comment] 2024-05-26 21:43
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/280
or https://github.com/PrismLauncher/PrismLauncher/issues/1844

**Closed as not planned by Trial97** 2024-05-26 21:43 UTC
Labels: status: duplicate, type: enhancement
