### ISSUE TITLE
[Windows] updating from 5.x to 6.x without reinstalling breaks prism

### ISSUE THREAD

**Issue by HumanGamer** [PrismLauncher/PrismLauncher#660] opened 2022-12-21 22:47 UTC
### Operating System

Windows

### Version of Prism Launcher

Previously I had 5.1, now I have 6.1

### Version of Qt

Qt 6.4.0 (on 6.1)

### Description of bug

I updated from 5.1 to 6.1 with the installer and now the launcher can't login, download mods or modpacks, etc. It just loads forever.

### Steps to reproduce

Install 5.1 with the installer, (setup instances, install modpacks etc, and add microsoft account), then Install 6.1 with the installer.

(This is what caused it for me)

### Suspected cause

I don't have a clue. But now I can't play my game...

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by HumanGamer** [comment] 2022-12-21 22:58
I just managed to solve the issue by uninstalling the app and reinstalling in a different location. It seems like the cause is updating the launcher when it's installed in C:\Program Files\PrismLauncher

I'm going to keep this open though since this is clearly a bug.

**Comment by minelolpride** [comment] 2022-12-22 03:56
I could reproduce. I am using a portable installation and upgrading from 5.2 to 6.1 caused the launcher to stop communicating with the network. The log file reports `No functional TLS backend was found` a bunch. Unpacking a fresh install resolves the issue. Of course, I never attempted to upgrade to 6.0 *then* 6.1 first. Didn't see any notice to make a fresh install either.

**Comment by dunsparce9** [comment] 2022-12-22 16:57
Can reproduce (also 5.1 > 6.1). Installed in non-admin folder in C: (not program files). Resolved by deleting everything except instances and config files, then re-extracting the 6.1 zip.

**Comment by dimaguy** [comment] 2022-12-23 00:10
I could reproduce, all it took for me to fix it was to delete the tls folder in the program files and reinstalling, so I'd wager that the issue is there

**Comment by masonbesmer** [comment] 2022-12-23 01:59
> I could reproduce, all it took for me to fix it was to delete the tls folder in the program files and reinstalling, so I'd wager that the issue is there

Confirmed this resolves the issue

**Comment by YoYoK3nny** [comment] 2022-12-24 04:19
A simple solution would be to have the installer uninstall the previous version before installing the new version.

**Comment by maiavixen** [comment] 2022-12-25 02:26
I could reproduce this problem too. I was able to fix the issue with 

> I could reproduce, all it took for me to fix it was to delete the tls folder in the program files and reinstalling, so I'd wager that the issue is there

**Comment by Anthonity** [comment] 2022-12-29 10:14
where is the tls folder

**Comment by Anthonity** [comment] 2022-12-29 10:30
I deleted the C:\Users\<username>\AppData\Local\Programs\PrismLauncher folder and reinstalled it with the installer. It fixed it for me

**Comment by manuelgrabowski** [comment] 2022-12-30 00:05
Reinstalling fixed it for me too, however it happened again ten minutes later. Reinstalling again also fixed it the second time, but it doesn't seem to be a permanent fix?

Edit: So far it has kept working after the second reinstall. Maybe something didn't get removed properly on the first one.

**Comment by DoctorNefario** [comment] 2023-01-03 03:43
These steps solved this problem for me:

1. Use File Explorer to search for `.dll` in the PrismLauncher folder
2. The results should be sorted by "Date Modified", and as you scroll down you should notice that some of the DLLs have an earlier date.
3. Delete all DLLs with the earlier date.

If step 3 doesn't solve the issue try the following:
Instead delete **every** DLL from the PrismLauncher folder.
Then, unzip the zip file corresponding to the Prism version you chose, (e.g. `MSVC-arm64` for `MSVC-arm64-Setup`) into the PrismLauncher folder, and skip any duplicates. *Make sure you don't mix MSVC and MinGW, they are different.*

I think this issue might be a result of unknowingly switching from MinGW to MSVC during the upgrade.

**Comment by AidanWarner97** [comment] 2023-01-06 20:42
> These steps solved this problem for me:
> 
>     1. Use File Explorer to search for `.dll` in the PrismLauncher folder
> 
>     2. Delete all the files it found
> 
>     3. Unzip the zip file corresponding to the Prism version you chose, (e.g. `MSVC-arm64` for `MSVC-arm64-Setup`) into the PrismLauncher folder, and skip any duplicates.
> 
> 
> I think this issue might be a result of unknowingly switching from MinGW to MSVC during the upgrade.

This is what fixed the issue for me

**Comment by Leah96xxx** [comment] 2023-01-22 17:28
I too encountered this issue upgrading directly from 5.x to 6.1 (I can't remember exactly which 5.x version I was on), and can confirm that deleting the tls folder resolved the issue.

While troubleshooting, I did notice a heap of TLS backend errors in the logs. The installer seemed to stick while extracting tls\qschannelbackend.dll, both with and without the tls folder being deleted. Not sure if that file is maybe the issue or not.

**Comment by fatpowaranga** [comment] 2023-01-23 12:18
For anyone using portable, what worked for me is deleting the tls folder and extracting that from a fresh 6.1 zip download. All good from there.

**Comment by lily-es** [comment] 2023-02-01 20:46
Also had this bug happen to me by upgrading from 5.1 to 6.1. Deleting the tls folder and reinstalling fixed it for me too

**Comment by Eario** [comment] 2023-02-07 03:34
could reproduce, as well as confirm the tls folder deletion fix.

**Comment by madcaker** [comment] 2023-02-07 10:00
Also happens on the linux flatpak version.

**Comment by madcaker** [comment] 2023-02-07 10:17
To fix on the flatpak version you need to *completely* reinstall it by deleting all user data.

**Comment by IdrisQe** [comment] 2023-02-07 20:17
If anyone wants to follow the "delete everything" process, I reccommend moving the following elsewhere before moving them back once Prism is reinstalled:

-instances folder so you don't lose your instances
-icons folder so you don't lose your custom icons
-prismlauncher.cfg to keep your user settings
-qt.conf (i think this is a config too? not sure how qt works admittedly)
-optionally the non-instance mods folder though I'm still not entirely certain what this is even used for

Everything else should be deletable and replaced with no issues.

I did this process when I encountered this issue and it worked just fine.

But one more point: If you go the route of just deleting all the dlls, make sure you replace them with the correct version.
I still had the .exe from the 6.3 Win-MSVC version but didn't know which version I had installed, tried moving over the dlls from the 6.3 Win-MinGW version since I figured "well they're both for Windows", and that broke it entirely so I had to do the complete uninstall/reinstall instead. Or maybe I just messed up by copying from the plain .zip when i previously used the setup .exe - i dunno, either way be careful it's probably best to just uninstall entirely and reinstall, keeping the configs and personal folders.

**Comment by DoctorNefario** [comment] 2023-02-08 02:27
> If you go the route of just deleting all the dlls, make sure you replace them with the correct version.

Absolutely, the problem is that the MSVC executable is trying to use MinGW DLLs.

Additionally, instead of deleting *every* DLL I've found that you can just delete the ones that have a "modified" date before 2023, then everything should work without needing to extract anything.

**Comment by YoYoK3nny** [comment] 2023-02-08 05:21
> -optionally the non-instance mods folder though I'm still not entirely certain what this is even used for

Any mods stored there will be used instead of downloading them from curseforge, etc... when installing a new instance (at least, definitely for any mods that don't allow third-party launchers)

> If anyone wants to follow the "delete everything" process, I reccommend moving the following elsewhere before moving them back once Prism is reinstalled:
> 
> -instances folder so you don't lose your instances -icons folder so you don't lose your custom icons -prismlauncher.cfg to keep your user settings

None of these things should be stored with the app itself, configure Prism to store them elsewhere. Then it doesn't matter, just uninstall the app and reinstall.

**Comment by IdrisQe** [comment] 2023-02-13 20:41
> Any mods stored there will be used instead of downloading them from curseforge, etc... when installing a new instance (at least, definitely for any mods that don't allow third-party launchers)

Oh okay. Not entirely sure the point of that since most packs use a lot of different mod versions from eachother, but I see why it exists.

> None of these things should be stored with the app itself, configure Prism to store them elsewhere. Then it doesn't matter, just uninstall the app and reinstall.

True, but by default they are inside the appdata folder or wherever else PrismLauncher has been installed, so many people have them all there. Personally I keep them in Documents/My Games since that seems to be the default place for a lot of games to store user data. If anything, it might be a good idea to change the default location specifically to avoid this kind of issue when un-savvy users try to update PrismLauncher. (Alternatively an updater could be included in the program itself, though that could be a lot of unnecessary work.)

**Comment by YoYoK3nny** [comment] 2023-02-14 05:09
> Oh okay. Not entirely sure the point of that since most packs use a lot of different mod versions from eachother, but I see why it exists.

You'd be surprised how many happen to use exactly the same mod versions.

> True, but by default they are inside the appdata folder or wherever else PrismLauncher has been installed, so many people have them all there. Personally I keep them in Documents/My Games since that seems to be the default place for a lot of games to store user data. If anything, it might be a good idea to change the default location specifically to avoid this kind of issue when un-savvy users try to update PrismLauncher. (Alternatively an updater could be included in the program itself, though that could be a lot of unnecessary work.)

An addition to the first time setup wizard perhaps? Though it would really only be needed for the savvy users and anyone using the alternative install methods.

The old updater is still in the codebase (last I looked), the devs have just opted to not use it. The system behind it seems kinda complicated to replicate, so makes sense. Surely they have something planned in that regard, I reckon they'll get to it at some point. (Something like what Notepad++ uses would even be enough, can be modified to suit needs)


Additionally (in regards to your earlier comment), you shouldn't need to worry about the qt.conf file. Afaik, nothing user specific should ever be in there.

**Comment by ayunami2000** [comment] 2023-02-18 00:48
I also have this issue, and its pretty urgent. I could not login to accounts or install modpacks from URLs or even launch the game when requiring downloads.

EDIT: Also my suggested fix would be release an installer that replaces the old DLL's.

**Comment by r-xnny** [comment] 2023-03-14 14:06
> I could reproduce, all it took for me to fix it was to delete the tls folder in the program files and reinstalling, so I'd wager that the issue is there

Upgraded from 5.2 to 6.3 and ran into this issue, just doing this also fixed it for me. Though my install directory is a folder in %localappdata%.

**Comment by Zaldos** [comment] 2023-03-15 18:26
Hi I also ran into this issue.
Was installed in "C:\PrismLauncher". Fixed by uninstalling and reinstalling in the same location.

**Comment by FrAndroidd** [comment] 2023-04-29 02:31
I got this issue too and not even reinstalling fixed it, but by logging in using a VPN (I used ProtonVPN, though I guess it would work with any VPN) it worked just fine and I can start Minecraft with my account without a VPN. This is a workaround while the bug gets fixed

**Comment by bop34** [comment] 2023-05-21 21:04
Deleting the `tls` folder worked for me

**Comment by DioEgizio** [comment] 2023-06-06 05:35
Fixed in https://github.com/PrismLauncher/PrismLauncher/pull/1100, keeping pinned until we release 7.0

**Closed as completed by DioEgizio** 2023-06-06 05:35 UTC
Labels: platform: Windows

**Comment by archwes** [comment] 2024-06-05 02:11
I'm not sure if I'm in the right place to report this, but I'm running Prism Launcher on version 8.3 with Windows 11 and I had a similar problem, where the client tried to connect my Microsoft account three times before returning an error message. After several unsuccessful searches and solutions, I decided to activate the "Default" option under Proxy settings and my problem was solved instantly!

**Comment by Snaping14** [comment] 2024-07-18 09:26
I had encountered this issue as well, possible solution was to be more patient. I hope this helps anyone else encountering the issue. 
Relevant posts I found:
[reddit](https://www.reddit.com/r/PrismLauncher/comments/100pd5t/i_cant_add_my_microsoft_account_61_windows_10/), [github](https://github.com/PrismLauncher/PrismLauncher/issues/706), [microsoft forums](https://answers.microsoft.com/en-us/xbox/forum/all/cant-log-in-to-minecraft-side-launcher/8b42493e-aa09-4bbb-927a-805c4f640659)
### Potential Fixes?:
1. Just wait...
2. log into microsoft account in browser (maybe doesn't have to be while prism is "working")
3. Something else I didn't notice
Not sure if anything was happening in the background while I was doing this but maybe we could get some sort of info on what it's currently doing _specifically_ at each point of the loading bar?
### All Steps Taken: 
(bolded steps possibly related to solution)

1. Launched Prism Launcher
2. Tried to add Microsoft account (got the same issue stated here)
![image](https://github.com/user-attachments/assets/51bb1084-29e4-41c5-b5cb-52be7bd1b705)
3. Closed Prism, Tried to install prism without uninstalling. (install went successful)
5. Retried steps 1&2 and also thought I was still having this bug.
6. Closed Prism
7. Tried deleting all files/folders related to prism (AppData/Roaming & AppData/Local)
8. Downloaded "PrismLauncher-Windows-MSVC-Setup-8.4.exe" from [here](https://github.com/PrismLauncher/PrismLauncher/releases)
9. Installed via this newly acquired installed (install successfull)
10. Launched Prism Launcher and Tried adding a Microsoft account again. However, this Time **I didn't close it**
11. Noticed someone mentioning microsoft account security info, So I then went to [this](https://support.microsoft.com/en-us/account-billing/microsoft-account-security-info-verification-codes-bf2505ca-cae5-c5b4-77d1-69d3343a5452), which pointed me to this [this](https://account.live.com/proofs/manage/additional)
12. I was prompted to log into my microsoft, and so **I logged into my microsoft account** (which is also the one that owns minecraft)
13. Tried to "Add a new way to sign in or verify" and decided to add a passkey _(tbh I have no idea why I decided to do this)_ and used my Dashlane to be my passkey password manager since I use dashlane anyways. 
14. I was then looking through the security things (and contemplating whether or not to remove all of the "sign-in and verification options" and **after ≈3 minutes** a new tab opens up with the verification/allow access screen _*idk what it's specifically called*_ 
15. Issue fixed 👍



### System info:
| Header           | Details                                                   |
|------------------|-----------------------------------------------------------|
| Processor        | AMD Ryzen 5 3600 6-Core Processor                         |
| Video Card       | NVIDIA GeForce RTX 3070                                   |
| Operating System | Windows 10 Home                                           |
| OS Version       | 10.0.19045 Build 19045                                    |
| RAM              | 64 GB                                                     |
| Prism Version    | [8.4](https://github.com/PrismLauncher/PrismLauncher/releases/tag/8.4) |

PS Sorry for the necro. I figured I'd post in case anyone who has this issue and finds this while looking for information as I did.
PSS Thanks @Scrumplex for their support with this issue
