### ISSUE TITLE
Cannot scale down new instance window when using scaling

### ISSUE THREAD

**Issue by Desyncfy** [PrismLauncher/PrismLauncher#2529] opened 2024-06-16 23:23 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.7.1

### Description of bug

You can't make the "New instance" window small enough to hit the confirm button when using high resolutions with scaling. Tested with Linux + Gnome 46 at 200% scaling.

### Steps to reproduce

* Set scaling to a large-ish number (like 200%, but if you have a really high res display you may have to be bigger) In Gnome on Linux you can find this in the Settings app in Displays > Scale
* Open Prism Launcher
* Create a new instance
* See that you can't access the confirm button
* Attempt to make the window smaller (you can't make it smaller vertically)

### Suspected cause

I believe that this is caused by the new instance window's minimum size being to big.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-06-17 05:41
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2242
Also fixed and will be released in 8.4

**Closed as not planned by Trial97** 2024-06-17 05:41 UTC

**Comment by 4LAMESTUDIO** [comment] 2026-04-04 22:28
the same happens to me on windows 11
