### ISSUE TITLE
Prism Launcher stops responding/freezes after launching a Minecraft instance.

### ISSUE THREAD

**Issue by RealPhoenixDev** [PrismLauncher/PrismLauncher#1898] opened 2023-11-26 11:18 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

After launching minecraft prism launcher stops responding (gets grayed out by windows and suggests closing the program) until closed and reopened.

### Steps to reproduce

1. Create an instance
2. Launch Minecraft
3. Done, Prism launcher is not responding

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-11-26 15:03
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1311

**Closed as not planned by Trial97** 2023-11-26 15:03 UTC
