### ISSUE TITLE
Easy download Optifine

### ISSUE THREAD

**Issue by thomasangelo1** [PrismLauncher/PrismLauncher#2042] opened 2024-01-18 12:49 UTC
### Goal

You cannot download Optifine from the launcher itself. I think this is quite inconvenient. I know they are not on CurseForge or Modrinth. Therefore, the idea is to connect the official Optifine website to the Launcher so that it can be downloaded directly from there. Or make separate versions with Optifine in the Launcher

### Motivation

It’s inconvenient, since ordinary users who used pirated launchers (where such a function already existed, or there were separate versions with Optifine) are already used to it. And some people don’t even know that Optifine is a mod

### Specification

Or connect the Optifine website, so that any user can download from the Optifine Launcher. Or separate versions with Optifine. 
 Example: 1.16.5 Optifine 
 Or 
 1.16.5 ForgeOptifine, this will be the Forge mod loader, which initially has Optifine built into it 

### Drawbacks

There are unlikely to be any shortcomings

### Unresolved Questions

The question remains: what will be better? 
 Make separate versions by type  
 1.16.5 Optifine 
 or 1.16.5 ForgeOptifine. 
 Or connect the official Optifine website for this.  
 Option 1 will be simpler, but less free. 
 Option 2 is the opposite. 
 You can do everything together, but it will be more difficult and longer (In time)

### Alternatives Considered

Add Assemblies that replace Optifine with Fabrik. These assemblies can be marked as “From Lauchner himself"

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment] 2024-01-18 13:20
Duplicate of #808. Still, here's an explanation of why it's not viable:

From optifine.net

>  The mod OptiFine is Copyright © 2011-2021 by sp614x and the intellectual property of the author.
It may be not be reproduced under any circumstances except for personal, private use as long as it remains in its unaltered, unedited form.
It may not be placed on any web site or otherwise distributed publicly without advance written permission.
Use of this mod on any other website or as a part of any public display is strictly prohibited and a violation of copyright.

It's likely other launchers are either rehosting the versions (which isn't allowed) or trying to download them from optifine.net (which uses dynamic links presumably because the author doesn't want downloads to be automatated)

With older versions it's fairly easy to install OptiFine. With newer versions alternatives such as Sodium exist (which paired with other mods can offer a similar set of features) - but if you have issues with it you can still install OptiFine with OptiFabric or Forge which doesn't involve fiddling with zip files.

**Closed as not planned by TheKodeToad** 2024-01-18 13:20 UTC
Labels: status: duplicate, status: invalid
