### ISSUE TITLE
Add optional categories in the mods menu

### ISSUE THREAD

**Issue by Insane-Owl** [PrismLauncher/PrismLauncher#1431] opened 2023-07-25 02:07 UTC
### Role

I play modded Minecraft.

### Suggestion

I want to be able to add categories in the mods menu.

### Benefit

so I don't have to go through every mod that I have installed to find and enable/disable them.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I want to be able to add categories in the mods menu to better categorize my mods. e.g., the user can add a "performance mods" category, or a "physics mods" category.

**Comment by SanicFan19** [comment] 2023-12-19 15:07
This would be amazing for organization!

**Comment by CarJem** [comment] 2024-01-18 13:46
I'm going to list a couple more reasons why this would be amazing just to provide the developers with more reasoning:
- Categories would allow Mod Pack developers, like myself, to group mods by purpose to ease with maintence, some examples of group names include, Performance/Fixes, Clientside Only Mods, and so on
- Prism already has a metadata system, it's just a matter of adding support for say a single editable string section for each mod, and giving it a column in the mods list

**Comment by Sarund9** [comment] 2024-01-24 18:58
Came here to ask for this exact feature.
From a technical perspective this is:
- Add a new "category" column.
- Each installed mod now has a new metadata value: "user_category"
- Add a new button to the context menu when hovering a mod: 'Edit Category'
- The button opens a text edit dialog that lets the user change the user_category value

Possible additional features and details:
- If multiple mods are selected, edit the category of every selected mod
- The text edit dialog should have a drop-down showing existing categories present in this instance
- Change an entire category value (IE edit every mod with category "foo" to category "bar")
- Add the ability to filter by category, and by extension other values such as version (I do not know if this is already a thing)
- Could add this feature to Resource Packs, Shader packs, Worlds, Servers, Screenshots (In that order of priority, Screenshots should probably just have folders instead)

**Comment by TheKodeToad** [comment] 2024-02-19 11:30
Duplicate of #154

**Closed as not planned by TheKodeToad** 2024-02-19 11:30 UTC
Labels: status: duplicate, status: invalid
