### ISSUE TITLE
"Operation canceled" when adding Microsoft account

### ISSUE THREAD

**Issue by sparr** [PrismLauncher/PrismLauncher#1049] opened 2023-05-01 00:21 UTC
### Version of Prism Launcher

6.3

### Version of Qt

5.15.9

### Description of bug

When trying to add my Microsoft account in PrismLauncher on my Steam Deck I get directed to the microsoft login website, but the link and copy/open buttons fail to open my browser. I open Chrome and copy the link to visit it, then copy in the code. The site asks me to authorize Prism for a few things, and I agree. The website says I'm done and can close the window, so I go back to PrismLauncher. It continues to display a progress bar for a bit with text I didn't copy, but then proceeds to a red error message in the add account window, saying "Failed to get authorization for Xbox services: Operation canceled"

### Steps to reproduce

Steps in Description

### Suspected cause

This could be related to https://github.com/MultiMC/Launcher/issues/4506 and may also be related to the fact that the official Minecraft launcher goes into an infinite loading animation when I try to open the microsoft login dialog.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Axolotl48** [comment] 2023-05-01 07:25
I'm also having this issue
edit: I just needed to install and select a version of java

**Comment by TahaKhan090** [comment] 2023-08-05 11:07
I just waited for 1 day and it got fixed its probably about xbox's servers

**Comment by Trial97** [comment] 2023-11-16 10:40
closing as this was most probably caused by a temporary Microsoft outage.

**Closed as not planned by Trial97** 2023-11-16 10:40 UTC

**Comment by mohammadaboalnadar** [comment] 2024-06-14 11:54
![image](https://github.com/PrismLauncher/PrismLauncher/assets/60301549/54dc5448-135f-4ecd-90a1-1b4cd86fd56c)

Login has been failing for about 6 months for me on prism launcher. I only have this issue on prism launcher and other similar launchers, I can log in to the official Minecraft launcher without issue. I tried looking up the problem multiple times and tried lots of solutions including

- Whitelisting the launcher on my firewall (Shouldn't be an issue anyway because all online functions are working perfectly fine except log in
- Restarting the launcher, my PC, and my home network router multiple times on multiple occasions
- Uninstalling and reinstalling prism launcher
- Waiting for an update and successfully downloading and installing it
- Uninstalling Xbox services and reinstalling them
- Changing my DNS
- Changing the network I'm connected to while trying to log in
- Changing the browser I'm using to confirm the Microsoft login
- Using the recent nightly version as per the notification about regional issues with logging in using the recommended log in and the legacy log in and neither worked
- Using a VPN and trying to log in using the stable release launcher and the nightly version launcher using the legacy and the recommended logins and all of them produce the same error `Failed to get authorization for Xbox services: Operation canceled`

none of those attempts resulted in anything changing. The only launcher I'm able to use other than the official Minecraft launcher is the Forge launcher which sucks.

# Steps to reproduce
- Add Microsoft account
- Proceed with instructions
- Launcher hangs for a minute on the `Logging in as an Xbox user` step
![image](https://github.com/PrismLauncher/PrismLauncher/assets/60301549/4834e544-0fbb-4a3e-b5fe-b14a42fbe33f)
- Launcher times out with an error reading: `Failed to get authorization for Xbox services: Operation canceled`
![image](https://github.com/PrismLauncher/PrismLauncher/assets/60301549/54dc5448-135f-4ecd-90a1-1b4cd86fd56c)

# Log File
[PrismLauncher-0.log](https://github.com/user-attachments/files/15837624/PrismLauncher-0.log)

**Comment by Trial97** [comment] 2024-06-14 12:01
My answer is: did you try the latest development (with the new login method)?
PS. from the logs the Microsoft server refuses to respond to the authorize API

**Comment by mohammadaboalnadar** [comment] 2024-06-14 12:06
I did try and I tried a bunch of other things listed in the comment. I am out of ideas right now.

**Comment by Trial97** [comment] 2024-06-14 12:10
Even the timeout PR that is yet merged in the dev?

**Comment by Trial97** [comment] 2024-06-14 12:12
For that PR see https://github.com/PrismLauncher/PrismLauncher/issues/2302#issuecomment-2118984209
And be aware that there is an outrage now: https://bugs.mojang.com/browse/WEB-7179

**Comment by ratatik337** [comment] 2024-06-27 12:58
could this problem be related to the fact i live in russia?

edited
just suddenly its one of the sanctions or something

**Comment by Trial97** [comment] 2024-06-27 13:00
Posible
