### ISSUE TITLE
Launcher crash when instance path contain weird charecters

### ISSUE THREAD

**Issue by foxwhite25** [PrismLauncher/PrismLauncher#2182] opened 2024-03-02 16:16 UTC
### Operating System

Windows

### Version of Prism Launcher

8.0

### Version of Qt

version 6.6.0

### Description of bug

This happens when I download the All The Mods - Gravitas² modpack, because of it's name, prisma automatically created the instance directory with the charecter `²` and caused the launcher to crash upon launch. After I changed the directory name to plain ascii the issue is fixed.

### Steps to reproduce

Download the All The Mods - Gravitas² modpack with default name

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-03-02 16:23
I'm pretty sure this is a duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1659 or https://github.com/PrismLauncher/PrismLauncher/issues/131

**Closed as not planned by Trial97** 2024-03-02 16:23 UTC
