### ISSUE TITLE
settings window for an instance is invisble

### ISSUE THREAD

**Issue by FunnyIvri** [PrismLauncher/PrismLauncher#2393] opened 2024-05-11 06:27 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.7.0

### Description of bug

when i try to look at the settings window for an instance, it just is invisible it click anywhere near it does nothing suggesting its not invisible but infinitely small

[Screenshot showing the bug](https://github.com/PrismLauncher/PrismLauncher/assets/122040253/f051b794-d75b-4466-a55e-8aaa6f1857d3)

### Steps to reproduce

not sure i just installed prism MC from the flatpak app, installed divine destiny 2 from the curse forge option tried to view its settings and it was invisible tried restarting, using the show console when game running, but everything led to the weird invisible thing.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-05-11 06:31
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2388

**Closed as not planned by Trial97** 2024-05-11 06:31 UTC

**Comment by FunnyIvri** [comment] 2024-05-11 06:43
The actual prism app is running and working, the other settings menus work, the only thing that dosent run, is the instance settings

**Comment by Trial97** [comment] 2024-05-11 06:47
I understand that but this looks like the same regression to me: after introducing qt6 in flatpack some windows are no longer visible.
Try some solution from there: https://github.com/PrismLauncher/PrismLauncher/issues/2388#issuecomment-2102771011
