### ISSUE TITLE
Reforge the data's system in the instances for a better and faster backup sharing throw the same launcher

### ISSUE THREAD

**Issue by SoyMidas** [PrismLauncher/PrismLauncher#2435] opened 2024-05-25 18:09 UTC
### Role

Modded Minecraft. 

### Suggestion

I want to propose a reforge of metadata of the instances to make easier the backups.

### Benefit

It's not new, in web frameworks like node is normally used. The thing is that if you don't want to move all the backup with mods and resurcepacks included, this can make the process easier and lighter

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

    I'm spanish, so i'm going to write it in spanish and then use ChatGPT to translate all. Perhaps there is any issue.

---

# Español

Bueno, la idea principal es crear un sistema como el archivo "package.json", aquí un ejemplo:

```json
{
  "name": "101-berich-game",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/react": "^3.0.3",
    "@astrojs/tailwind": "^5.0.1",
    "@types/react": "^18.0.21",
    "@types/react-dom": "^18.0.6",
    "astro": "^3.2.3",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "tailwindcss": "^3.0.24"
  }
}
```

Con este sistema se podría dividir diferentes instancias: Nombre, versión, loader, mods, resurcepacks, shaderpacks... Todo lo que queramos, con un sencillo movimiento como:

```json
{
  "name": "1.20.6",
  "minecraft": "1.20.6",
  "loader": {
    "type": "fabric",
    "version": "0.15.11",
    },
  "mods": {
    "sodium": "0.5.5",
    "EMI": "1.1.6+1.20.2+fabric",
    "Shulker Box Tooltip": "4.0.7+1.20.2",
    ...
    },
  "resurcepacks" {
    "name": "version",
    ...
    },
  "shaders" {
    "name": "version",
    ...
    },
  ...
}
```

De esta manera, cuando llegue la hora de exportar los datos habrán las opciones de siempre y la opción ligera (package + config + saves) lo que pesará **mucho menos** y lo unico que pesará en mayor parte serán los mundos. Y a la hora de importar, el launcher leerá este archivo .txt o .json o lo que sea y irá cargando todo lo necesario y descargando los mods necesarios.

## Problemas: 
- Que no se descarge por el launcher, en ese caso se deberá incluir en el sistema de backup normal y corriente.
- Que hay que cambiar bastantes opciones de las que ya estan escritas, pero proporcionará flexibilidad para organizar: mods, resource packs y shaders

---

# English

Well, the main idea is to create a system like the "package.json" file. Here's an example:

```json
{
  "name": "101-berich-game",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/react": "^3.0.3",
    "@astrojs/tailwind": "^5.0.1",
    "@types/react": "^18.0.21",
    "@types/react-dom": "^18.0.6",
    "astro": "^3.2.3",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "tailwindcss": "^3.0.24"
  }
}
```

With this system, different instances can be divided: Name, version, loader, mods, resource packs, shader packs... Everything we want, with a simple setup like:

```json
{
  "name": "1.20.6",
  "minecraft": "1.20.6",
  "loader": {
    "type": "fabric",
    "version": "0.15.11",
    },
  "mods": {
    "sodium": "0.5.5",
    "EMI": "1.1.6+1.20.2+fabric",
    "Shulker Box Tooltip": "4.0.7+1.20.2",
    ...
    },
  "resurcepacks" {
    "name": "version",
    ...
    },
  "shaders" {
    "name": "version",
    ...
    },
  ...
}
```

This way, when it's time to export the data, there will be the usual options and the lightweight option (package + config + saves), which will weigh **much less**, and the only significant weight will be from the worlds. And when importing, the launcher will read this .txt or .json file or whatever it is and load everything needed, downloading the necessary mods.

## Issues:
- If it doesn't download through the launcher, it will need to be included in the regular backup system.
- Quite a few options that are already written will need to be changed, but it will provide flexibility to organize: mods, resource packs, and shaders.

It's a risk move, but could be a great change <3 :3

**Comment by Trial97** [comment] 2024-05-25 20:46
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1182

**Closed as not planned by Trial97** 2024-05-25 20:46 UTC
Labels: type: enhancement
