### ISSUE TITLE
User-mode data execution prevention breaks Prism on WIndows 7/8.1

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#134] opened 2022-10-19 20:41 UTC
### Operating System

Windows

### Version of PolyMC

Prism Launcher 5.0 (Legacy)

### Version of Qt

Qt 5.15.6

### Description of bug

The legacy launcher does not want to work under Windows 7 after selecting Java runtime. It executes and creates a log file, but does not create a window and then closes.
It does work as expected under Windows 10, even with the compatibility layer set to Windows 7.

I have attached the logs from Windows 7 and Windows 10

[PrismLauncher-0 windows 7.log](https://github.com/PrismLauncher/PrismLauncher/files/9824090/PrismLauncher-0.windows.7.log)
[PrismLauncher-3 windows 10.log](https://github.com/PrismLauncher/PrismLauncher/files/9824092/PrismLauncher-3.windows.10.log)

### Steps to reproduce

- Have Windows 7
- Open Prism Launcher Legacy
- Select language and Java runtime

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by timoreo22** [comment] 2022-10-19 20:45
You are missing let's encrypt's certificate, this will cause issues
Downloading and "installing" this certificate should work : https://letsencrypt.org/certs/isrg-root-x1-cross-signed.pem

**Comment by ghost** [comment] 2022-10-19 20:54
> You are missing let's encrypt's certificate, this will cause issues Downloading and "installing" this certificate should work : https://letsencrypt.org/certs/isrg-root-x1-cross-signed.pem

Hmm, okay. But how do I install a ".pem" certificate?

**Comment by he3als** [comment] 2022-10-19 21:48
Download the certificate, open Command Prompt as admin and do a command like this:
```
certutil –addstore -enterprise –f "Root" <pathtocertificatefile>
```

Source: https://superuser.com/questions/1031444/importing-pem-certificates-on-windows-7-on-the-command-line/1032179

**Comment by ghost** [comment] 2022-10-20 00:14
Thanks, it did install successfully, although the launcher still refuses to work.
But now, I think the news thing may be causing this issue? The log ends straight on it
![firefox_WiuRxYLnam](https://user-images.githubusercontent.com/89755606/196827625-c52580d9-49c2-474c-ac78-53614be9f237.png)

Has anyone got the launcher to open on Windows 7?

**Comment by Pablete1234** [comment] 2022-10-20 05:06
Can confirm, does not launch on windows 7. The logs simply stop after the RSS Feed line.
```
  [...]
    0.017 D Loading accounts...
    0.017 C "Failed to read the account list file (accounts.json)."
    0.017 D <> Accounts loaded.
    0.017 D <> Cache initialized.
    0.017 D Downloading Translations Index...
    0.017 D Task "NetJob(Translations Index)" starting for the first time
    0.028 D <> Icon theme set.
    0.028 D <> Application theme set.
    0.138 D Reloading news.
    0.138 D Task "NetJob(News RSS Feed)" starting for the first time
```

Then nothing else after that

**Comment by DioEgizio** [comment] 2022-10-20 07:23
https://twitter.com/msys2org/status/1582254491914891264
https://twitter.com/msys2org/status/1582638803088392192

might be related to one of these? (we use msys2 for building on windows)

**Comment by DioEgizio** [comment] 2022-10-20 07:46
intresting enough, it works fine on develop (because debug builds, i guess? or lto?) but it has some very weird graphical artifacts, soooo i don't know what to think, apart from the fact that msys2 is killing windows 7 support

**Comment by DioEgizio** [comment] 2022-10-20 07:49
> intresting enough, it works fine on develop (because debug builds, i guess? or lto?) but it has some very weird graphical artifacts, soooo i don't know what to think, apart from the fact that msys2 is killing windows 7 support

those graphical artifacts cause these type of stuff to come in logs too:

>     2.982 C OpenThemeData() failed for theme 12 (TOOLBAR). (Impossibile trovare elemento.)

**Comment by DioEgizio** [comment] 2022-10-20 07:49
and gdb doesn't give any useful information either :p

**Comment by he3als** [comment] 2022-10-20 09:12
Maybe the legacy builds could be built with an older version of msys2?

**Comment by DioEgizio** [comment] 2022-10-20 09:13
what do you mean

**Comment by he3als** [comment] 2022-10-20 11:48
> what do you mean

So that the legacy builds on Windows 7 still work. Maybe it could be configured in GitHub Actions?

**Comment by DioEgizio** [comment] 2022-10-20 11:49
i don't quite understand what you mean

**Comment by Pablete1234** [comment] 2022-10-20 11:51
What they mean is if newer versions of mysys2 drop support, the legacy builds could continue to be built using older versions of mysys2 still having support for win7.

**Comment by DioEgizio** [comment] 2022-10-20 11:52
we would have to host custom msys2 repos ourself and of the installer, and of the github actions and so on

**Comment by Mattia98** [comment] 2022-10-22 12:31
Can confirm Prism legacy zip from the website doesn't launch on 7 after the wizard. Crashes on same log entry.

I did try to compile it myself and it works for me. 
I did find one bug introduced sometime between 5.0 tag and current master but I'd have to report that separately (I first compiled the latest master, after finding the bug I compiled the 5.0 tag and there the bug wasn't present). Launcher segfaults when importing a CurseForge zip. 
So it seems to be some issue with the build system maybe? Because my msys is up to date AFAIK, I just updated it to install the build dependencies.

**Comment by DioEgizio** [comment] 2022-10-22 12:38
> Can confirm Prism legacy zip from the website doesn't launch on 7 after the wizard. Crashes on same log entry.
> 
> I did try to compile it myself and it works for me. I did find one bug introduced sometime between 5.0 tag and current master but I'd have to report that separately (I first compiled the latest master, after finding the bug I compiled the 5.0 tag and there the bug wasn't present). Launcher segfaults when importing a CurseForge zip. So it seems to be some issue with the build system maybe? Because my msys is up to date AFAIK, I just updated it to install the build dependencies.

#225

**Comment by ghost** [comment] 2022-10-22 15:36
> Can confirm Prism legacy zip from the website doesn't launch on 7 after the wizard. Crashes on same log entry.
> 
> I did try to compile it myself and it works for me. I did find one bug introduced sometime between 5.0 tag and current master but I'd have to report that separately (I first compiled the latest master, after finding the bug I compiled the 5.0 tag and there the bug wasn't present). Launcher segfaults when importing a CurseForge zip. So it seems to be some issue with the build system maybe? Because my msys is up to date AFAIK, I just updated it to install the build dependencies.

Your comment inspired me to try and build the launcher and surely enough everything seems to work apart from some UI glitches like someone has pointed out here iirc.

![firefox_zf7TWOQRRd](https://user-images.githubusercontent.com/89755606/197347890-e4bb1493-4c2a-4f47-ba0f-e4e3fba3c353.png)

So either the builds provided on the website are broken or some code changes after the release fixed the issue. 
I'll keep this issue open for now, though

**Comment by Mattia98** [comment] 2022-10-22 16:14
> > Can confirm Prism legacy zip from the website doesn't launch on 7 after the wizard. Crashes on same log entry.
> > I did try to compile it myself and it works for me. I did find one bug introduced sometime between 5.0 tag and current master but I'd have to report that separately (I first compiled the latest master, after finding the bug I compiled the 5.0 tag and there the bug wasn't present). Launcher segfaults when importing a CurseForge zip. So it seems to be some issue with the build system maybe? Because my msys is up to date AFAIK, I just updated it to install the build dependencies.
> 
> Your comment inspired me to try and build the launcher and surely enough everything seems to work apart from some UI glitches like someone has pointed out here iirc.
> 
> ![firefox_zf7TWOQRRd](https://user-images.githubusercontent.com/89755606/197347890-e4bb1493-4c2a-4f47-ba0f-e4e3fba3c353.png)
> 
> So either the builds provided on the website are broken or some code changes after the release fixed the issue. I'll keep this issue open for now, though

Yes I've also noticed those glitches. Changing the theme in the settings works around the issue.
I doubt it's a code change since for me it works on the 5.0 tag.

**Comment by DioEgizio** [comment] 2022-10-22 16:19
that's what i meant for "it has some very weird graphical artifacts"

i guess there were some regressions in msys2 or smth :p

**Comment by he3als** [comment] 2022-10-23 14:56
Just as a note, I am using a regular GitHub Actions build (legacy) on Windows 7 and it is working completely normal.

https://github.com/PrismLauncher/PrismLauncher/actions/runs/3307262514

![rEi7DdmIB1](https://user-images.githubusercontent.com/65787561/197399231-570c2a19-7967-4160-a558-5a1663102536.png)

**Comment by DioEgizio** [comment] 2022-10-23 16:22
that's because you aren't using the system theme

**Comment by he3als** [comment] 2022-10-23 18:50
> that's because you aren't using the system theme

System theme also works completely normal with no bugs.

**Comment by he3als** [comment] 2022-10-23 19:43
> > > Can confirm Prism legacy zip from the website doesn't launch on 7 after the wizard. Crashes on same log entry.
> > > I did try to compile it myself and it works for me. I did find one bug introduced sometime between 5.0 tag and current master but I'd have to report that separately (I first compiled the latest master, after finding the bug I compiled the 5.0 tag and there the bug wasn't present). Launcher segfaults when importing a CurseForge zip. So it seems to be some issue with the build system maybe? Because my msys is up to date AFAIK, I just updated it to install the build dependencies.
> > 
> > 
> > Your comment inspired me to try and build the launcher and surely enough everything seems to work apart from some UI glitches like someone has pointed out here iirc.
> > ![firefox_zf7TWOQRRd](https://user-images.githubusercontent.com/89755606/197347890-e4bb1493-4c2a-4f47-ba0f-e4e3fba3c353.png)
> > So either the builds provided on the website are broken or some code changes after the release fixed the issue. I'll keep this issue open for now, though
> 
> Yes I've also noticed those glitches. Changing the theme in the settings works around the issue. I doubt it's a code change since for me it works on the 5.0 tag.

Does disabling Aero/DWM cause it to not have any glitches?

**Comment by ghost** [comment] 2022-10-23 20:14
> Does disabling Aero/DWM cause it to not have any glitches?

No, the only solution to fix the graphical glitches is to switch the User Interface from "System" to anything else, then there is no graphical glitches, but also no Aero elements such as the loading bar inside the launcher (it gets replaced by a custom one).

It seems to me the Windows 7 non-classic theme is troubling the launcher in some way.

**Comment by he3als** [comment] 2022-10-23 20:16
It works fine with the classic theme though, I will test out Aero Basic.

Edit: Can confirm, the issues only happen with the non-classic themes.

**Comment by AwesomeKalin** [comment] 2022-10-24 15:28
I can confirm that this also occurs on Windows 8.1 too, although the development version that @he3als mentions does work

**Comment by he3als** [comment] 2022-10-24 16:59
Is your system updated with all of the runtimes you may need? I installed a bunch of runtimes like all of the [.NET runtimes](https://dotnet.microsoft.com/en-us/download/dotnet-framework), [updated DirectX](https://www.microsoft.com/en-gb/download/details.aspx?id=8109), [C++ redistributables](https://github.com/abbodi1406/vcredist), etc... It could be something to do with that.

**Comment by DioEgizio** [comment] 2022-10-24 17:36
> Is your system updated with all of the runtimes you may need? I installed a bunch of runtimes like all of the [.NET runtimes](https://dotnet.microsoft.com/en-us/download/dotnet-framework), [updated DirectX](https://www.microsoft.com/en-gb/download/details.aspx?id=8109), [C++ redistributables](https://github.com/abbodi1406/vcredist), etc... It could be something to do with that.

Prism doesn't touch MSVC, it's all MINGW

**Comment by DioEgizio** [comment] 2022-10-25 11:47
thanks to clang and lldb, yes this is an issue with data execution prevention

> * thread # 1, stop reason = Exception 0xc0000005 encountered at address 0x05035c: User-mode data execution prevention (DEP) violation at location 0x0005035c

**Comment by he3als** [comment] 2022-10-25 12:21
I have DEP disabled, so that's why it worked for me.

**Comment by DioEgizio** [comment] 2022-10-25 18:01
i just remembered that this issue also happened in early polymc days (https://github.com/PolyMC/PolyMC/issues/276)
so this isn't a new issue, it's caused by smth msys2 didn't enable before but it now does

**Comment by TheLastRar** [comment] 2022-10-30 21:01
Can you check #352 (once it builds)

**Comment by ghost** [comment] 2022-10-30 23:27
> Can you check #352 (once it builds)

Ay, the graphical glitches seem to be gone now. Nice!

![explorer_nijXBCr2Zm](https://user-images.githubusercontent.com/89755606/198907065-32dca5e9-f812-4df2-b84e-d0850f2a9884.png)
![prismlauncher_NbFXDbsqin](https://user-images.githubusercontent.com/89755606/198907070-f828a689-c3fc-4a84-aa24-063275b5228f.png)

**Comment by DioEgizio** [comment] 2022-10-31 06:52
Fixed in develop

**Closed as completed by DioEgizio** 2022-10-31 06:52 UTC
Labels: platform: Windows
