### ISSUE TITLE
Global Resourcepacks

### ISSUE THREAD

**Issue by ItsCryptic** [PrismLauncher/PrismLauncher#768] opened 2023-01-21 00:21 UTC
### Role

I just play Minecraft and would like Prism to always have my resourcepacks instead of me having to copy it every new instance I make

### Suggestion

Global resourcepacks!

### Benefit

I really don't want to have to keep copying my resource packs to every instance!

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment] 2023-01-21 00:54
Effectively a duplicate of #38 / #422

**Closed as not planned by flowln** 2023-01-21 00:54 UTC
Labels: type: enhancement
