### ISSUE TITLE
Prism launches in offline mode after connecting an account

### ISSUE THREAD

**Issue by RossComputerGuy** [PrismLauncher/PrismLauncher#699] opened 2023-01-02 08:57 UTC
### Operating System

Linux

### Version of Prism Launcher

6.1 (Flatpak)

### Version of Qt

5.15.7

### Description of bug

After adding the first account, Prism is always launching in offline mode. This can be resolved by deleting the Prism Launcher config directory and adding an account but shouldn't be necessary.
```
   51.798 C Task "MSASilent(0x558dbf56c310)" failed:  "Microsoft user authentication ended with a network error."
   51.798 D RefreshSchedule: Background account refresh failed:  "Microsoft user authentication ended with a network error."
   51.866 D Download succeeded: "https://i18n.prismlauncher.org/index_v2.json"
   51.866 D Task "NetJob(Translations Index)" succeeded
```

### Steps to reproduce

1. Add an account to Prism
2. Add an instance
3. Relaunch Prism
4. Try loading a modpack and you'll get an error like [this](https://mclo.gs/mbMGaJs)

### Suspected cause

Unknown, if more information was printed by Prism then debugging could be easier. This is likely not a DNS issue due to `login.microsoftonline.com` being resolved.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment] 2023-01-02 09:07
There should be a log line that starts with `DeviceFlow::onRefreshFinished: Error` before which should tell you about the network error that happened.

**Comment by Scrumplex** [comment] 2023-01-02 09:13
Never mind. That line only gets printed if it was *not* a network error.

Relevant code: https://github.com/PrismLauncher/PrismLauncher/blob/67ac3da8a0eac959343fe86ca143b97f0f76543c/libraries/katabasis/src/DeviceFlow.cpp#L438-L444

**Comment by RossComputerGuy** [comment] 2023-01-02 09:15
Yeah, this is all I see (internal ID and token was removed from pasted logs).
```
    0.075 D <> Log initialized.
    0.075 D <> No migration needed from "PolyMC"
    0.076 D <> No migration needed from "MultiMC"
    0.076 D "Prism Launcher" , (c) 2013-2021  "Prism Launcher Contributors\n© 2021-2022 PolyMC Contributors \n© 2012-2021 MultiMC Contributors"
    0.076 D Version                    :  "6.1"
    0.076 D Git commit                 :  "cb8c389303fe774003b49919a8ef6ded55e1c2b8"
    0.076 D Git refspec                :  ""
    0.076 D Work dir before adjustment :  "/home/ross"
    0.076 D Work dir after adjustment  :  "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher"
    0.076 D Adjusted by                :  "Persistent data path"
    0.076 D Binary path                :  "/app/bin"
    0.076 D Application root path      :  "/app"
    0.076 D <> Paths set.
    0.131 D Detected default console font: "Migu 1C" , substitutions: ""
    0.147 D <> Settings loaded.
    0.159 D Detecting proxy settings...
    0.159 D Using no proxy is an option!
    0.159 D <> Network done.
    0.168 D Loading Qt Language File for ja ...
    0.168 D Loading Application Language File for ja ...
    0.168 D Your language is "ja"
    0.168 D <> Translations loaded.
    0.172 D Started watching  "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/icons"
    0.173 D Adding  "icons/FTBRevelationIcon"
    0.258 D Adding  "icons/FTB Revelation"
    0.262 D Adding  "icons/FTB One"
    0.265 D Sorting icon list...
    0.272 D <> Instance icons intialized.
    0.272 D [Theme] <> Icon themes initialized.
    0.272 D [Theme] <> Initializing Widget Themes
    0.272 D [Theme] Determining System Theme...
    0.272 D [Theme] System theme seems to be: "fusion"
    0.272 D [Theme] Considering theme from theme factory: "breeze"
    0.272 D [Theme] Considering theme from theme factory: "windows"
    0.272 D [Theme] Considering theme from theme factory: "fusion"
    0.273 D [Theme] System theme has been determined to be: "Fusion"
    0.273 D [Theme] Loading Built-in Theme: "system"
    0.273 D [Theme] Loading Built-in Theme: "dark"
    0.273 D [Theme] Loading Built-in Theme: "bright"
    0.273 D [Theme] Theme Folder Path:  "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/themes"
    0.274 D [Theme] Loading JSON Theme from: "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/themes/Tokyo Night Storm/theme.json"
    0.275 D [Theme] Loading JSON Theme from: "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/themes/Tokyo Night Light/theme.json"
    0.277 D [Theme] Loading JSON Theme from: "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/themes/Tokyo Night/theme.json"
    0.278 D [Theme] <> Widget themes initialized.
    0.278 D Instance path              :  "instances"
    0.278 D Loading Instances...
    0.279 D Discovering instances in "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances"
    0.279 D Found instance ID "FTB One"
    0.280 D Found instance ID "FTB Revelation"
    0.280 D Will load group list now.
    0.280 D Group list loaded.
    0.281 D Loaded instance  "FTB One 1.3.0"  from  "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/FTB One"
    0.282 D Loaded instance  "FTB Revelation 3.6.0"  from  "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/FTB Revelation"
    0.282 D <> Instances loaded.
    0.282 D Loading accounts...
    0.283 D AccountList: Queued default account with internal ID  ""  to refresh first
    0.284 D Task "MSASilent(0x5652494bb650)" starting for the first time
    0.284 D AuthFlow: "Logging in with Microsoft account."
    0.284 D DeviceFlow::refresh: Token: ... ""
    0.300 D RefreshSchedule: Processing account  "ComputerGuy2389"  with internal ID  ""
    0.300 D <> Accounts loaded.
    0.303 D <> Cache initialized.
    0.303 D Downloading Translations Index...
    0.303 W Removing cache entry because of old age!
    0.303 D Task "NetJob(Translations Index)" starting for the first time
    0.305 D <> Icon theme set.
    0.305 D [Theme] applying theme "Tokyo Night"
    0.305 D <> Application theme set.
GameMode ERROR: D-Bus error: Could not call method 'QueryStatus' on 'org.freedesktop.portal.Desktop': Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
   50.410 D Reloading news.
   50.410 D Task "NetJob(News RSS Feed)" starting for the first time
   50.412 D Task "ComponentUpdateTask(0x5652496cc010)" starting for the first time
   50.412 D Loading components
   50.418 D Component list save is scheduled for "FTB One 1.3.0"
   50.427 D Resolving dependencies
   50.427 D "Req: net.minecraft == 1.19" Is met.
   50.428 D "Req: org.lwjgl3" Is met.
   50.428 D Task "ComponentUpdateTask(0x5652496cc010)" succeeded
   50.428 D Component list update/resolve task succeeded for "FTB One 1.3.0"
   50.495 D <> Main window shown.
   50.498 D Task "Net::Download(0x56524958f6f0)" starting for the first time
   50.498 D Downloading  "https://i18n.prismlauncher.org/index_v2.json"
   50.498 D Task "Net::Download(0x5652496cb1b0)" starting for the first time
   50.498 D Downloading  "https://prismlauncher.org/feed/feed.xml"
   50.513 D Dir changed: "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/translations"
   50.514 D Loading Qt Language File for ja ...
   50.514 D Loading Application Language File for ja ...
   50.515 C Task "MSASilent(0x5652494bb650)" failed:  "Microsoft user authentication ended with a network error."
   50.515 D RefreshSchedule: Background account refresh failed:  "Microsoft user authentication ended with a network error."
   50.722 D Download succeeded: "https://i18n.prismlauncher.org/index_v2.json"
   50.722 D Task "NetJob(Translations Index)" succeeded
   50.722 D Got translations index!
   50.722 W Removing cache entry because of old age!
   50.722 D Task "NetJob(Translation for ja)" starting for the first time
   50.722 D Task "Net::Download(0x5652498e3ec0)" starting for the first time
   50.722 D Downloading  "https://i18n.prismlauncher.org/bd64abdc748babd48514829910f9af5b3e931039.class"
   50.722 D Dir changed: "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/translations"
   50.724 D Loading Qt Language File for ja ...
   50.724 D Loading Application Language File for ja ...
   50.745 D Download succeeded: "https://prismlauncher.org/feed/feed.xml"
   50.745 D Task "NetJob(News RSS Feed)" succeeded
   50.745 D Finished loading RSS feed.
   50.748 D Loaded news entry "Prism Launcher Release 6.1, now available"
   50.748 D Loaded news entry "Prism Launcher Release 6.0, now available"
   50.748 D Loaded news entry "Prism Launcher Release 5.2, now available"
   50.748 D Loaded news entry "Prism Launcher Release 5.1, now available"
   50.748 D Loaded news entry "Prism Launcher Release 5.0, now available"
   50.748 D Loaded news entry "PolyMC Update 1.4.2, now available"
   50.748 D Loaded news entry "PolyMC Update 1.4.1, now available"
   50.748 D Loaded news entry "PolyMC Update 1.4.0, now available"
   50.748 D Loaded news entry "PolyMC Update 1.3.2, now available"
   50.748 D Loaded news entry "PolyMC Update 1.3.1, now available"
   50.748 D Loaded news entry "PolyMC Update 1.3.0, now available"
   50.748 D Loaded news entry "PolyMC Update 1.2.2, now available (CurseForge Hotfix)"
   50.748 D Loaded news entry "PolyMC Update 1.2.1, now available"
   50.748 D Loaded news entry "PolyMC Update 1.2.0, now available"
   50.748 D Loaded news entry "PolyMC Update 1.1.1, now available"
   50.748 D Loaded news entry "PolyMC Update 1.1.0, now available"
   50.748 D Loaded news entry "Moving on"
   50.748 D Loaded news entry "Modrinth support and Mod downloading"
   50.748 D Loaded news entry "New maintainers and step down."
   50.748 D News loading succeeded.
   50.971 D Download succeeded: "https://i18n.prismlauncher.org/bd64abdc748babd48514829910f9af5b3e931039.class"
   50.971 D Task "NetJob(Translation for ja)" succeeded
   50.971 D Got translation: "ja"
   50.972 D Loading Qt Language File for ja ...
   50.972 D Loading Application Language File for ja ...
   50.973 D Dir changed: "/home/ross/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/translations"
   50.974 D Loading Qt Language File for ja ...
   50.974 D Loading Application Language File for ja ...
   55.171 D Component list save performed now for "FTB One 1.3.0"
   81.054 D [HttpMetaCache] Saving metacache with 20 entries
```

**Comment by falkreon** [comment] 2023-07-16 16:17
Experiencing this too.

relevant log lines
```
     0.168 D | <> Instances loaded.
     0.170 D | Loading accounts...
     0.170 D | AccountList: Queued default account with internal ID  "{redacted}"  to refresh first
     0.170 D | Task "MSASilent(0x55c140f6b520)" starting for the first time
     0.171 D | AuthFlow: "Logging in with Microsoft account."
     0.171 D | DeviceFlow::refresh: Token: ... "{redacted}"
     0.205 D | RefreshSchedule: Processing account  "Falkreon"  with internal ID  "{redacted}"
     0.205 D | <> Accounts loaded.
```

The symptoms seem the same - accounts.json indicates that everything is happy and active, and log lines suggest success, but the account appears as "Offline" in the accounts list and I can't start an instance in online mode. I have to fully delete the account and recreate it to work around the problem. If I *add* my microsoft account with the broken one still in the list, the new one becomes broken and the old one magically starts working. Either way, the problem eventually resurfaces.

This is on
- Prism Launcher 6.3
  - AppImage
  - Channel: Stable
  - Commit: 39bba9cbfadc0aac3ef571a80e78a9fa3f5a0028
- KDE Neon 5.26
  - Plasma 5.26.5
  - Kernel 5.15.0-58-generic
  - Qt 5.15.8

**Comment by Laxystem** [comment] 2023-08-15 08:13
Can confirm, on Pop! OS 22.04, GNOME, Prism 7.2 on flatpak, stable.

**Comment by Trial97** [comment] 2024-01-15 14:09
Can you try reproduce it using the nightly builds: https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop ?

**Comment by Trial97** [comment] 2024-04-12 16:25
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-04-12 16:25 UTC
Labels: area: auth, status: not enough info
