### ISSUE TITLE
Crash 'Illegal character'

### ISSUE THREAD

**Issue by Delivator** [PrismLauncher/PrismLauncher#987] opened 2023-04-11 11:33 UTC
### Version of Prism Launcher

6.3

### Version of Qt

6.4.2

### Description of bug

The instance does not start. Error in console:
```
java.net.URISyntaxException: Illegal character in path at index 64: file:/D:/Games/PrismLauncher/instances/Delivator's%20Vanilla-%20[1.19.4]/.minecraft/.quilt/transform-cache-client/transformed-mod-minecraft-v1.19.4.jar
```

### Steps to reproduce

- Create a new instance
- Set the name to `Delivator's Vanilla+ [1.19.4]`
- Start the instance

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment] 2023-04-11 13:42
Could you post the whole error including the full stack trace?

**Comment by Delivator** [comment] 2023-04-11 16:09
Ups yeah meant to do that but forgot. Not at home right now, will do it later!

**Comment by telans** [comment] 2023-06-20 03:08
Cannot reproduce

**Comment by Trial97** [comment] 2023-10-01 19:29
Any updates on this?
It is still reproducible on the latest release?

**Comment by Trial97** [comment] 2024-01-15 15:13
Closing this as no further information was provided. Feel free to repoen it once you can reproduce it on the latest version(8.0)

**Closed as not planned by Trial97** 2024-01-15 15:13 UTC
Labels: status: not enough info
