### ISSUE TITLE
Prism crashes when trying to download libraries

### ISSUE THREAD

**Issue by Macxds** [PrismLauncher/PrismLauncher#3048] opened 2024-11-02 14:26 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.1 Installer

### Version of Qt

Qt 6.7.3

### Description of bug

Imported Curseforge's "The Chocolate Edition" through the downloader. As I hit play, the window for downloading libraries opens and crashes Prism. This happens only with this instance that i have.
Log: [PrismLauncher-0.log](https://github.com/user-attachments/files/17607258/PrismLauncher-0.log)

### Steps to reproduce

1. Selected "The Chocolate Edition" instance
2. Press play
3. Library downloader opens
4. Crash

### Suspected cause

Apparently Qt has the following error: QWindowsWindow::setGeometry: Unable to set geometry 480x138+855+612 (frame: 496x177+847+581) on QWidgetWindow/"ProgressDialogWindow" on "HP2159". Resulting geometry: 480x204+855+612 (frame: 496x243+847+581) margins: 8, 31, 8, 8 minimum size: 480x138 MINMAXINFO(maxSize=POINT(x=0, y=0), maxpos=POINT(x=0, y=0), maxtrack=POINT(x=0, y=0), mintrack=POINT(x=496, y=177)))

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-11-02 22:27
I prepared a portable debug build: https://media.githubusercontent.com/media/Trial97/prism_gdb/refs/heads/master/PrismLauncher-Windows-MinGW-w64-Portable-ba07a13-Debug.zip?download=true (portable build + debuger)

Download and extract that file.
Start prism using the gdbprismlauncher.bat file(the extension may be missing), not the normal executable; do not touch the opened command prompt(black thing with text)
Try to reproduce the crash;if the application is stuck leave it a few minutes(it takes a while to generate all the backtrace)

Once it completely closes there will be a gdbcrash.log file. Please share that file( is a stacktrace of the crash)

The source code for how I created that zip can be found here https://github.com/Trial97/prism_gdb/tree/master

**Comment by Macxds** [comment] 2024-11-03 18:29
Ok, I have run the program, here's the log 
[gdbcrash.log](https://github.com/user-attachments/files/17611578/gdbcrash.log)
BUT, the instance has no problem in launching, the launcher downloaded the libraries and files from Mojang without any sorts of problems. Could this be related to the fact that this is a newer version(10) compared the one I'm using(9.1), or could it be something wrong with my pc?

**Comment by Trial97** [comment] 2024-11-03 18:49
yes there were some fixes: one exactly for a crash when downloading resources like mods and modpacks.
I will close this for now as you are not able to reproduce it with the newer version.
Please feel free to reopen it if it happens again(and similarly post the crashlog).

**Closed as completed by Trial97** 2024-11-03 18:49 UTC

**Comment by jpuentes5** [comment] 2025-06-08 03:45
Having a similar issue

[PrismLauncher-0.log](https://github.com/user-attachments/files/20642716/PrismLauncher-0.log)

**Comment by lordofpipes** [comment] 2025-09-12 09:21
Not sure what changed or when, but updating to nightly may fix this. See https://discord.com/channels/1031648380885147709/1031648381514289175/1415981396710789161
