### ISSUE TITLE
Konami Code pressed cat button not rainbow.

### ISSUE THREAD

**Issue by Omay238** [PrismLauncher/PrismLauncher#1583] opened 2023-08-30 18:21 UTC
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 6.5.0

### Description of bug

The cat button should show a rainbow texture, but it is just black, at least in dark mode. This only happens when the button is toggled on. When it is off, it shows the rainbow.

### Steps to reproduce

* Enter Konami Code
* Press Cat Button if disabled
* See no rainbow on the cat button.

### Suspected cause

It may be that there is no special sprite for the pressed cat button with Konami Code, or the cat button is not included in whatever filter is used for the rainbowification.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TayouVR** [comment] 2023-08-30 19:23
I can't reproduce this on windows, recent dev version (f99b04bd1656a8e5cd871c1fadc1550e663fc33a) with the default dark theme, or any other themes I have installed.
Can you send a screenshot of how it looks?

this is how it looks for me:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/31988415/355c8879-401d-4d8b-bce0-a6f4ce83b396)

**Comment by Omay238** [comment] 2023-08-31 18:19
You are using windows, so it is likely a Mac bug. Here's how it looks on my computer:
<img width="798" alt="Screenshot 2023-08-31 at 12 18 27 PM" src="https://github.com/PrismLauncher/PrismLauncher/assets/70179858/2c01ca6e-33ed-434f-8be8-e9e9804d45ce">
I'll try installing the development version, and see if it's fixed there.

**Comment by TayouVR** [comment] 2023-08-31 21:07
the dev version probably won't fix it, must be some quirk with that button and macOS specifically..

**Comment by Omay238** [comment] 2023-08-31 22:28
Yeah, it still looks the same. Also, some parts don't have the rainbow other than the button. (bottom right and bottom left)

**Comment by TheKodeToad** [comment] 2023-08-31 22:31
This wouldn't be trivial to fix, so I don't think we should :crying_cat_face:

**Closed as not planned by TheKodeToad** 2023-08-31 22:31 UTC

**Comment by TayouVR** [comment] 2023-09-01 09:10
I think if anything this could be fixed if we (somehow) make the entire background one consistent rainbow. Maybe as part of some custom background feature. It still would collide with themes though. (Some of the ones I have break various parts of the rainbow too)

generally; its an easter egg and if you actually want the rainbow to be there all the time, it should be part of a custom theme (which could account for everything then). ^^
