### ISSUE TITLE
Stuck at "working" while trying to login into mojang account

### ISSUE THREAD

**Issue by s0me1newithhand7s** [PrismLauncher/PrismLauncher#2818] opened 2024-09-14 12:51 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.7.2

### Description of bug

i was trying to log in my mojang account after prism launcher logged me of.
tried reinstalling launcher,
system is up-to-date.

p.s.
there was similar issues, but reinstalling haven't helped me 

### Steps to reproduce

have mojang account (but no offline)
be on nixos unstable

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-09-14 12:52
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-09-14 12:52 UTC
