### ISSUE TITLE
Unable to open prism Launcher after updating to 8.4

### ISSUE THREAD

**Issue by Sar4h-3** [PrismLauncher/PrismLauncher#2910] opened 2024-10-12 14:09 UTC
### Operating System

Windows

### Version of Prism Launcher

8.4

### Version of Qt

n/a

### Description of bug

After updating Prism from 8.3 to 8.4, Prism refuses to open. Even after using the installer from the website, the issue persists. 
After starting, there is a small time of the spinning circle next to the cursor, but nothing more.
Even starting with Admin doesn't change it
Looking into starting logs after the update, they are completely empty. Update log:
[PrismLauncherUpdater-0_redacted.log](https://github.com/user-attachments/files/17350304/PrismLauncherUpdater-0_redacted.log)

### Steps to reproduce

- update from 8.3 to 8.4
- try to launch Prism

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-10-12 14:26
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2555

**Comment by Trial97** [comment] 2024-10-12 14:27
also https://github.com/PrismLauncher/PrismLauncher/issues/2885

**Closed as not planned by Trial97** 2024-10-12 14:26 UTC
