### ISSUE TITLE
I would like to see a tag feature added.

### ISSUE THREAD

**Issue by teacat923** [PrismLauncher/PrismLauncher#2645] opened 2024-07-14 00:35 UTC
### Role

I play Minecraft with mods.

### Suggestion

Ability to tag mods. If possible, the ability to batch select mods with specific tags.

### Benefit

When you put in a large number of mods, it will be easier to recognize what the mods were to add.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Hello, my name is Kuuneko, a Prism Launcher user.
Thanks again for your great launcher.
I would like to add something about the tagging feature.
How to use it: mods that add industrial elements should be tagged with "industrial" to make it easier to recognize them. It is useless to do a Google search every time you get confused.
Also, mods with prerequisite mods should be tagged to indicate dependencies. (This helps with sinytra, etc.)
By searching and specifying only mods with specific tags, you will save time you have wasted so far and easily understand information you did not understand.

P.S.
This text was translated using a translation tool. I am Japanese and my English is not very good. If there are any bad parts in the proposal, please do not hesitate to let me know.

**Comment by Trial97** [comment] 2024-07-14 06:11
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/154

**Closed as not planned by Trial97** 2024-07-14 06:11 UTC
Labels: type: enhancement
