### ISSUE TITLE
Mod updater classes mod from different source as different mod

### ISSUE THREAD

**Issue by SirenGlitch** [PrismLauncher/PrismLauncher#2076] opened 2024-01-29 18:13 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

Mods such as Fabric API and Cloth Config from Modrinth are detected as different mods to the ones from CurseForge and vice versa.

Example:

Fabric API from Modrinth
![Mod in Mod List](https://github.com/PrismLauncher/PrismLauncher/assets/110285018/d25a473c-e8ef-45c5-b0d4-5d4ac5a89bf4)

Architectury (CurseForge version) "requiring" Fabric API from CurseForge
![Check for Updates result](https://github.com/PrismLauncher/PrismLauncher/assets/110285018/c5ed0241-b3b6-4c6b-8725-dc0fc8a10416)

### Steps to reproduce

- Make Fabric instance with Architectury API (CurseForge) and Fabric API (Modrinth)
- Check for Updates
- Observe result

[Full Mod List for semi-guaranteed reproduction](https://github.com/PrismLauncher/PrismLauncher/files/14088025/ModList.md)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-01-29 20:01
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1745

**Closed as not planned by Trial97** 2024-01-29 20:01 UTC
