### ISSUE TITLE
Datapacks not supported for *New Worlds via Flatpak

### ISSUE THREAD

**Issue by Nate-Rich** [PrismLauncher/PrismLauncher#2752] opened 2024-08-25 03:59 UTC
### Role

Datapack development

### Suggestion

New Worlds need datapack support (Linux FlatPak)

### Benefit

Testing. Simplicity. Intuitive for everyone.

### This suggestion is unique

- [ ] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.
- [X] This is brought up elsewhere as a bug, but I would strongly suggest making this a more intuitive feature in all versions.
- [X] Similar, but slightly different issues are frequently reported - I see why.

### You may use the editor below to elaborate further.

I need to be able to pre-load a datapack into a New Worlds. The thing is, this was an issue before this was a FlatPak specific issue. It would be nice to just fix the bug with the flatpak, but I would suggest a more complete solution. 

The user should have both the option to both add datapacks to all worlds in a given instance and to the world as it is created. I have no idea how to do this myself, but we'll see how motivated I am. TY

**Comment by Trial97** [comment] 2024-08-25 06:03
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/922

**Closed as not planned by Trial97** 2024-08-25 06:03 UTC
Labels: type: enhancement
