### ISSUE TITLE
Auto-download dependencies for mods

### ISSUE THREAD

**Issue by SolDev69** [PrismLauncher/PrismLauncher#118] opened 2022-10-19 16:28 UTC
### Role

Downloading mods with dependencies

### Suggestion

Auto-downloading of dependencies similarly to the CurseForge launcher.

### Benefit

Easier to download mods with dependencies (instead of having to check the mod page for dependencies manually)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by MoustacheOff** [comment] 2022-10-19 16:44
Already exists: #116

**Comment by DioEgizio** [comment] 2022-10-19 17:22
duplicate of #116

**Closed as not planned by DioEgizio** 2022-10-19 17:22 UTC
Labels: type: enhancement
