### ISSUE TITLE
Deletes all worlds when updating a modpack

### ISSUE THREAD

**Issue by FlooferLand** [PrismLauncher/PrismLauncher#2904] opened 2024-10-11 13:18 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.7.3

### Description of bug

When updating a modpack instance from the Modrinth tab 1-2 times in a row _(I had to update it a 2nd time because the first time over it removed half of the mods)_ it deletes every world in the saves folder and resets every setting back to what the modpack originally shipped with.

I have spent over 10 hours in a singleplayer world, I am very pissed right now :)

### Steps to reproduce

1. Install a modpack
2. Create a world
3. Update the modpack via the Modrinth tab

### Suspected cause

The launcher should only replace any existing files when updating and shouldn't wipe everything before updating the modpack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment] 2024-10-11 13:21
Could you link the modpack you were playing with? This issue has not been reported before

**Comment by FlooferLand** [comment] 2024-10-11 13:26
It's the [Steam N Rails modpack](https://modrinth.com/modpack/steam-n-rails-modpack)

I don't think the modpack matters but I could be wrong.
I would try to reproduce this myself, but when I tried installing a random modpack to test it with the entire launcher crashed mid-install

**Comment by TheKodeToad** [comment] 2024-10-11 13:31
Oh dear, maybe we should bring back the warning about modpacks being experimental since there seem to be quite a lot of problems

**Comment by FlooferLand** [comment] 2024-10-11 13:48
I agree, I really like this launcher but after a bug this bad I'm moving back to MultiMC
I was doing actual scripting via ComputerCraft, so losing that world stings even more seeing I've lost hundreds of lines of code. I can't find a way to recover the files.

**Comment by Trial97** [comment] 2024-10-11 14:17
From what version did you update?

**Comment by TheKodeToad** [comment] 2024-10-11 14:20
A log from when this issue occurred would be handy for trying to fix this.

Also, sorry about your world. That sounds frustrating. There are tools to try and recover deleted files, also I would check backups or trash just in case.

**Comment by TheKodeToad** [comment] 2024-10-11 14:28
Running `grep "Steam 'n' Rails Modpack-(version).mrpack" ~/.local/share/PrismLauncher -rl` or `grep "Steam 'n' Rails Modpack-(version).mrpack" ~/.var/app/org.prismlauncher.PrismLauncher -rl` for flatpak - replacing (version) with the version you updated to when this happened - should find it

**Comment by FlooferLand** [comment] 2024-10-11 14:33
Sorry, I ended up deleting the app and all the data after realizing I couldn't recover anything from it.
This issue should be pretty easy to reproduce though.

**Comment by Trial97** [comment] 2024-10-11 14:38
> This issue should be pretty easy to reproduce though.

To be surprised but sadly is not easily reproducible.
Can you at least provide us with the version you updated?

**Comment by FlooferLand** [comment] 2024-10-11 18:06
@Trial97 I usually click update buttons in launchers since its the only way to check for updates (ex: GDLauncher) so I ended up updating to the same version (1.0.5 -> 1.0.5)

**Comment by Trial97** [comment] 2024-10-11 18:18
Yeah, I tested that exact scenario but I was not able to reproduce it.
Thanks for your response and again sorry for your lost data.

**Comment by FlooferLand** [comment] 2024-10-11 23:53
I might have an idea of what caused the data loss, which was dumb of me if it was the case.

There is a mod i use that makes its own folder within `.minecraft` and in order to share that data between all of my instances I set up bindmounts since symbolic links crash the mod. _(on Linux bindmounts are basically just mounting a folder over to another folder as if its a partition; symbolic link with extra steps)_
I only now noticed that instead of referencing my `.minecraft/modfolder` as the destination I accidentally referenced `.minecraft` itself in my `/etc/fstab`, so it was mounting the folder on top of `.minecraft`

I'm not sure to what extent that breaks the file-system, it could still possibly be unrelated? Probably not.
Thank you all for being so fast though, there's already an attempted fix for it even with the little info i managed to provide

**Comment by TheKodeToad** [comment] 2024-10-12 09:02
So far we have just attempted a few safety measures which should make this impossible.
Although to be honest, it already did seem impossible with the modpack you were using.

**Comment by TheKodeToad** [comment] 2024-10-12 10:20
As far as can see it is not possible for our modpack updater to do this, at least not with the modpack you mentioned. Closing for now, will reopen if it can be confirmed this issue exists

**Closed as completed by TheKodeToad** 2024-10-12 10:20 UTC
Labels: help wanted

**Comment by SaliraDaxius** [comment] 2026-01-03 10:32
Just had this occur while updating a private modpack I'm developing through a .mrpack, via the "Update from file" button within the Modrinth tab. The world was deleted after updating the pack but before the first launch of the game after the update.

Weird and interesting thing that may give you some hints on where to look: It left the entire *folder structure* of the world intact, while deleting all the files themselves.

How can I get a log from PrismLauncher itself? Apologies if this is a dumb question, it's 5am and I need to sleep.

Edit to add: I tried to intentionally get this to happen, but haven't been able to reproduce it yet.

**Comment by Trial97** [comment] 2026-01-03 21:53
Here are the paths where you can find Prism logs:
Portable (Windows / Linux)
./logs/PrismLauncher-0.log In the PrismLauncher folder
Windows
%APPDATA%/PrismLauncher/logs/PrismLauncher-0.log
Scoop
%HOMEPATH%\scoop\persist\prismlauncher\logs\PrismLauncher-0.log
macOS
~/Library/Application Support/PrismLauncher/logs/PrismLauncher-0.log
Linux
~/.local/share/PrismLauncher/logs/PrismLauncher-0.log
Flatpak
~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/logs/PrismLauncher-0.log

**Comment by Trial97** [comment] 2026-01-03 21:56
Also, @SaliraDaxius, are you able to reproduce this consistently?
If so, can you provide the steps and files?

**Comment by SaliraDaxius** [comment] 2026-01-03 22:49
@Trial97 

[PrismLauncher-0.log](https://github.com/user-attachments/files/24418844/PrismLauncher-0.log)

Here's the log. Searched through it myself and you can see that starting at line 3108 it is scheduling my save for removal.

[Analogous-0.1.0.zip](https://github.com/user-attachments/files/24418985/Analogous-0.1.0.zip)

Here is the .mrpack contained within a .zip because Github wouldn't let me directly upload the .mrpack. I had an older version of this pack that I updated with this file through the "Update from file" button, as shown below:

<img width="1232" height="733" alt="Image" src="https://github.com/user-attachments/assets/8573757c-28b6-4f46-a8c1-ff8cac975bad" />

I haven't yet been able to reproduce it since this one occurrence, I shall experiment further today and report back if I find any success.

Edit to add: The custom font is applied system-wide, and is not a modification of Prism Launcher itself.

**Comment by SaliraDaxius** [comment] 2026-01-03 23:17
Update: I'm able to reproduce it consistently now. Here's a log of the event: 

[removed for privacy as issue is resolved]

Reproduction steps:
1. Open Prism Launcher 9.4
2. Add Instance, and provide the .mrpack file inside this .zip to the Import tab:
[removed for privacy as issue is resolved]
3. Confirm the import, then edit the pack, go to the Worlds tab, and observe the intact world shown
4. Switch to the Modrinth tab, select "Update from file", and provide the .mrpack inside the following .zip file:
[removed for privacy as issue is resolved]
5. Once the pack is updated, return to the worlds tab and see that the world is now gone
6. Open the saves folder, and see the intact folder structure of the world with all the files themselves missing

In case this issue ends up being OS-specific, I am on NixOS (a Linux distro).

**Comment by Trial97** [comment] 2026-01-04 00:18
If the saves files are in the mrpack(or any file) they are considered part of the modpack and are handled by the Launcher.
The update mechanism for Prism is as follows:
- First pack install saves a list of files that were extracted 
- on update extract all(partially install the pack) in separate location
- because we collected the extracted files' paths, we start removing the files that were in the original pack but did not receive an update
- Once the removal is done, the pack is copied from the temporary directory to the actual instance, saving the new list of files and stuff

So the current behavior is intended: is a mechanism to delete old files that are not needed in new version.

**Comment by SaliraDaxius** [comment] 2026-01-04 00:21
Understandable if this is intended. Though I feel like at least a warning somewhere in this process is warranted, possibly right before the update from file runs if it's going to replace/remove your saves so you have a chance to back it up if needed. I had no idea this would happen until it did.

**Comment by Trial97** [comment] 2026-01-04 01:10
@SaliraDaxius drafted a pull request that does that https://github.com/PrismLauncher/PrismLauncher/pull/4622
