### ISSUE TITLE
Make failure for AUR packages

### ISSUE THREAD

**Issue by Big-Iron-Cheems** [PrismLauncher/PrismLauncher#1716] opened 2023-10-16 10:41 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.2-1

### Version of Qt

Qt 6.6.0-2

### Description of bug

Trying to build the releases hosted on the AUR (specifically packages `prismlauncher` and `prismlauncher-qt5`) fails, both [logs](https://pastebin.com/fuudQHmp) indicate the issue happening in `launcher/CMakeFiles/Launcher_logic.dir/translations/TranslationsModel.cpp.o`.

### Steps to reproduce

- Start the installation via `yay -S prismlauncher` or `yay -S prismlauncher-qt5`.
- Proceed with the default options, and wait for the build process to start
- Once it reaches about 50%, the build fails as stated

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-10-16 10:57
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1708

**Comment by Trial97** [comment] 2023-10-17 21:01
Reopening this as it looks like it is still a problem on the stable version

**Comment by Kragwulf** [comment] 2023-10-19 17:07
Confirming this is happening for me as well.

**Comment by txtsd** [comment] 2023-10-20 18:48
https://github.com/txtsd/ankylosaurus/actions/runs/6591222551/job/17909414669#step:11:742

**Comment by ghost** [comment] 2023-10-20 19:20
> https://github.com/txtsd/ankylosaurus/actions/runs/6591222551/job/17909414669#step:11:742

What's that?

**Comment by Kragwulf** [comment] 2023-10-20 19:40
> > https://github.com/txtsd/ankylosaurus/actions/runs/6591222551/job/17909414669#step:11:742
> 
> What's that?

That is the log from their attempt to install Prism Launcher from the AUR. It shows the exact error and when it happens.
This is also exactly what I'm experiencing.

**Comment by txtsd** [comment] 2023-10-20 19:43
> > https://github.com/txtsd/ankylosaurus/actions/runs/6591222551/job/17909414669#step:11:742
> 
> What's that?

It's the error in a log of prismlauncher being built in a clean Arch container.

**Comment by txtsd** [comment] 2023-10-20 20:31
I pushed an update to [prismlauncher](https://aur.archlinux.org/packages/prismlauncher) on the AUR. It should build without failure now.

**Closed as completed by txtsd** 2023-10-20 20:31 UTC
Labels: area: packaging, platform: Linux
