### ISSUE TITLE
Suggestion: Notification and indicator on modpacks that can be updated

### ISSUE THREAD

**Issue by Svish** [PrismLauncher/PrismLauncher#2625] opened 2024-07-08 10:15 UTC
### Role

I play modpacks through Prism

### Suggestion

I want Prism to notify me and show which modpacks can be updated

### Benefit

So I don't have to check manually myself, which means I'm basically only discovering new versions "by chance"

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When having installed a modpack via Prism, at least from CurseForge, it can be updated via the Prism UI. Since Prism knows which version I have, which versions exist, and seem to order those versions correctly, it would be great if Prism could notify me and put some sort of indicator on the modpacks which are no longer the latest version. That way I wouldn't have to check manually which packs have updates, making it much easier to stay updated.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/142162/4f2efdaa-6faa-4118-99e3-db7693e4eb18)

**Comment by Trial97** [comment] 2024-07-08 10:19
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/37

**Closed as not planned by Trial97** 2024-07-08 10:19 UTC
Labels: type: enhancement
