### ISSUE TITLE
Multiple FTB modpacks fail to launch due to null manifest error

### ISSUE THREAD

**Issue by RossComputerGuy** [PrismLauncher/PrismLauncher#290] opened 2022-10-24 17:29 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 5.15.6

### Description of bug

Game crashes with this error:
```
Instance update failed because: Null jar is specified in the metadata, aborting.
```

### Steps to reproduce

Try to launch the following modpacks:
- FTB One
- FTB Endeavour
- FTB Revelation
- FTB Inventions

### Suspected cause

Not sure, these packed worked before on PolyMC.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment] 2022-11-27 22:48
Does it work using the latest release (5.2)?

**Comment by RossComputerGuy** [comment] 2022-11-28 03:53
Yeah, latest flatpak version works now.

**Comment by NE451** [comment] 2022-11-28 14:34
Sorry to open this again but I have the same problem. 

Operating System
Linux Mint 21, Vanessa 

Version of Prism Launcher
Prism Launcher 5.2. Tried the Flatpak version, portable and tarball. 

Version of Qt
Qt 5.15.6

Description of bug
Game crashes with this error:

Instance update failed because: Null jar is specified in the metadata, aborting.
Steps to reproduce
Try to launch the following modpacks:

FTB One
FTB Inventions
CurseForge Classic Reforged

Suspected cause
Not sure, these packed worked before on PolyMC. Tried fresh install, nothing.

This issue is unique
Not unique, seems to be back. I'm adding a screenshot and I can post logs if necessary.

![Screenshot from 2022-11-28 15-30-59](https://user-images.githubusercontent.com/18534552/204303977-f9cdb27d-08e7-4f66-a50e-b71af665a0c0.png)

**Comment by Trial97** [comment] 2023-08-21 12:20
You are using Java 17 on a pack that requires Java 8.
I do not seem to be able to reproduce it using the latest release, can you try to reproduce it on 7.2?

**Comment by Trial97** [comment] 2024-01-15 15:13
Closing this as no further information was provided. Feel free to repoen it once you can reproduce it on the latest version(8.0)

**Closed as not planned by Trial97** 2024-01-15 15:13 UTC
Labels: status: not enough info
