### ISSUE TITLE
Install Prism Launcher system-wide on Windows by default

### ISSUE THREAD

**Issue by mariobrostech** [PrismLauncher/PrismLauncher#384] opened 2022-11-03 02:50 UTC
### Role

I use multiple accounts on my computer, and I would like for them to all have access to Prism Launcher.

### Suggestion

I would like for Prism Launcher to install system-wide by default and only install to AppData when admin rights aren't given to the installer.

### Benefit

If Prism Launcher is installed system-wide, I would no longer have to install it on each user account I wish to use.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

A lot of other application installers do this, and I think that allowing Prism Launcher to do the same would be beneficial for multi-user systems. Prism Launcher's installer could ask for administrative permissions by default, and, if granted, it could be installed system-wide to Program Files. Otherwise, if denied, Prism Launcher could install to the user's AppData folder as it currently does.

**Comment by txtsd** [comment] 2022-11-03 03:27
Duplicate of #296

**Closed as not planned** 2022-11-03 03:27 UTC
Labels: type: enhancement
