### ISSUE TITLE
Default config files for instances

### ISSUE THREAD

**Issue by BLACK4585** [PrismLauncher/PrismLauncher#2131] opened 2024-02-17 11:47 UTC
### Role

I play Minecraft and create a lot of new instances for private projects, version test for servers etc.

### Suggestion

It would be great if you are able to create an options.txt files once with your preferences. Then, when adding new instances regardless of a Modpack, Modloader or Vanilla, you can tick a checkbox to use (copy) that options.txt file so your Minecraft is automatically configured. Like the Minecraft Launcher does, since every Version uses the same directory.

### Benefit

Not to have to configure MC every single time from the ground up

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-02-19 07:06
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/175

**Closed as not planned by Trial97** 2024-02-19 07:06 UTC
Labels: type: enhancement
