### ISSUE TITLE
Launcher crashes multiple times when trying to update a modpack

### ISSUE THREAD

**Issue by Frontear** [PrismLauncher/PrismLauncher#1316] opened 2023-07-05 19:36 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

Pressing Update Modpack would download and update the modpack, showing the Blocked Mods dialog first, accepting that and continuing.

### Steps to reproduce

* Have an outdated modpack (currently have SteamPunk [LPS] v3.5, but this has happened which each version on different modpacks)
* Edit -> CurseForge -> Update
* Menu pops up, crashes before it gets to the Blocked Mods section

Attached are the 5 times it crashed consistently.

[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/11961324/PrismLauncher-0.log)
[PrismLauncher-1.log](https://github.com/PrismLauncher/PrismLauncher/files/11961325/PrismLauncher-1.log)
[PrismLauncher-2.log](https://github.com/PrismLauncher/PrismLauncher/files/11961326/PrismLauncher-2.log)
[PrismLauncher-3.log](https://github.com/PrismLauncher/PrismLauncher/files/11961321/PrismLauncher-3.log)
[PrismLauncher-4.log](https://github.com/PrismLauncher/PrismLauncher/files/11961322/PrismLauncher-4.log)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Frontear** [comment] 2023-07-05 19:47
Deleting .LAUNCHER_TEMP in instances/ fixes it. I'm not sure if that's a coincidence or not but something to look into. The original .LAUNCHER_TEMP was 2G+ in size.

**Comment by zerogott** [comment] 2023-07-06 15:26
Can confirm.
I cant download a single modpack atm.
Once the download reaches resolving modpack id the launcher crashes.

**Comment by Ryex** [comment] 2023-07-08 21:42
based on logs this is a Duplicate of #1299

**Closed as not planned by Ryex** 2023-07-08 21:42 UTC
