### ISSUE TITLE
Bad link shown when importing Modrinth pack by double clicking file

### ISSUE THREAD

**Issue by helpimnotdrowning** [PrismLauncher/PrismLauncher#1496] opened 2023-08-06 15:52 UTC
### Operating System

Windows

### Version of Prism Launcher

7.2

### Version of Qt

6.5.1

### Description of bug

When importing a Modrinth modpack by double clicking its file in Explorer, it shows the New Instance/Import menu with the wrong link in the file input box:
`C:\Users\helpi\AppData\Roaming\PrismLauncher\file:\C:\Users\helpi\Desktop\1.20.mrpack`

The expected result is `C:\Users\helpi\Desktop\1.20.mrpack`

### Steps to reproduce

* Export an instance as mrpack
* Open the file with the file association (Double click in Desktop/Explorer)
* Filename is wrong, begins with Prismlauncher data root + "file:\"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-10-03 20:39
duplicate of #1183

**Closed as completed by Trial97** 2023-10-03 20:39 UTC
