### ISSUE TITLE
Discord RPC support

### ISSUE THREAD

**Issue by RealFX-Code** [PrismLauncher/PrismLauncher#2200] opened 2024-03-06 14:17 UTC
### Role

I play minecraft, while using discord :D

### Suggestion

I would love to see Discord RPC integration in prismlauncher.

### Benefit

It would be cool to see what profile I'm running through discord.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Showing what people are doing in prismlauncher, "In the menus", "Creating a profile", "Browsing mods", etc. would be cool to see.

**Comment by Trial97** [comment] 2024-03-06 14:24
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/232

**Closed as not planned by Trial97** 2024-03-06 14:24 UTC
Labels: type: enhancement
