### ISSUE TITLE
Auto updated Distant Horizon showing up as ${mod_name}

### ISSUE THREAD

**Issue by smiRaphi** [PrismLauncher/PrismLauncher#2467] opened 2024-06-04 14:36 UTC
### Operating System

Windows 11

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3.

### Description of bug

Distant Horizon shows up as "${mod_name}" with version "${version}" after using the internal auto updater.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/87574679/9a01bff4-770e-46ad-8add-06f1ef1818f2)
The description is also just "${description}" and the issues link is "${issues}"
![image](https://github.com/PrismLauncher/PrismLauncher/assets/87574679/fa0e2e19-e19b-4501-a2d5-77f7c370ed10)

### Steps to reproduce

Set up a fabric profile on mc 1.20.6 and install download Distant Horizon over Curseforge, start minecraft and Distant Horizon will ask you if you want to auto update, confirm and close Minecraft, now the mod won't show proper name or version.
(auto updating might need to be enabled first, go to settings -> top left icon that has water, grass & sand -> Advanced options -> Auto Updater -> set Enable Auto Updates to True)

### Suspected cause

string formatting messes up for whatever reason

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-06-04 14:46
Duplicate of #2364

**Closed as not planned by Trial97** 2024-06-04 14:46 UTC
