### ISSUE TITLE
Mod pages crash when opened.

### ISSUE THREAD

**Issue by Aqua56** [PrismLauncher/PrismLauncher#3086] opened 2024-11-10 14:42 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.1 but did happen before, don't know when started.

### Version of Qt

Qt 6.7.3. but again don't know when started.

### Description of bug

I opened a mod page prism launcher loaded a bit and crashed

### Steps to reproduce

Open instance menu.
Click download mods from Modrinth.
Did happen with other mods but this time Resource Explorer, and it just crashes.
But knowing my laptop, probably won't work for you.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-11-10 15:34
Duplicate of another but it was already fixed on the nightly builds:https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop 
If you reproduce it with mentioned build then feel free to report back and I will reopen this issue

**Closed as not planned by Trial97** 2024-11-10 15:34 UTC
