### ISSUE TITLE
Suggestion for a "Modpack Update Available" icon or notification

### ISSUE THREAD

**Issue by elwood612** [PrismLauncher/PrismLauncher#2210] opened 2024-03-11 12:47 UTC
### Role

Modpack author

### Suggestion

A way to notify the user that a modpack needs updating

### Benefit

When joining a modded server, the only way for the user to know if the server has updated is to load the game first. This way, the user would know immediately.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'm making a modpack for some older, non-tech savvy people and right now there seems to be no visual indicator for when I update the modpack. They have to load up the game, see that the server has updated because of the red X in the Minecraft server list, then quit the game and update the modpack, and then reopen the game.

It just makes sense to me that a simple (toggleable!) icon or exclamation point on the instance icon would help inform users when a modpack is able / needs to be updated.

**Comment by Trial97** [comment] 2024-03-11 12:51
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/838
Relevant issues:
- https://github.com/PrismLauncher/PrismLauncher/issues/37
- https://github.com/PrismLauncher/PrismLauncher/issues/671

Suggestion use packwiz: https://packwiz.infra.link/tutorials/installing/packwiz-installer/

**Closed as not planned by Trial97** 2024-03-11 12:51 UTC
Labels: type: enhancement
