### ISSUE TITLE
Suggestion for less clutter in downloads folder

### ISSUE THREAD

**Issue by DiamondBotYT** [PrismLauncher/PrismLauncher#3227] opened 2024-12-20 16:12 UTC
Add the deletion of copied mod files for downloaded modpacks (the mods that do not support third-party downloads). When downloading a modpack, some mods don't support third-party downloads (like downloading from prism) and you have to download them via your browser but the mods are then copied instead of moved (cut & pasted) from downloads to the instance's mods folder. I am suggesting the function be changed to cut & paste rather than copy & paste.

**Comment by Trial97** [comment] 2024-12-20 16:40
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/874

**Closed as not planned by Trial97** 2024-12-20 16:39 UTC
