### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Bloonhero3201** [PrismLauncher/PrismLauncher#2870] opened 2024-09-29 14:44 UTC
### Operating System

Linux

### Version of Prism Launcher

newest

### Version of Qt

Qt 6.7.3

### Description of bug

it crashes when i try to play the demo

### Steps to reproduce

open the demo on an acc that doesnt own the game

### Suspected cause

log: Prism Launcher version: 8.4 (flatpak)

Launched instance in online mode

login.microsoftonline.com resolves to:
    [2603:1036:3000:60::16, 2603:1036:3000:60::15, 2603:1036:3000:60::10, 2603:1036:3000:60::14, 2603:1036:3000:60::17, 2603:1036:3000:60::e, 2603:1036:3000:60::d, 2603:1036:3000:60::12, 40.126.7.32, 40.126.28.14, 40.126.7.35, 40.126.28.22, 40.126.28.21, 40.126.28.12, 40.126.28.18, 40.126.28.20]

session.minecraft.net resolves to:
    [2620:1ec:bdf::70, 13.107.246.70]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::70, 13.107.246.70]

api.mojang.com resolves to:
    [2620:1ec:bdf::70, 13.107.246.70]

Minecraft folder is:
/home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.21.1/.minecraft

Java path is:
/app/jdk/21/bin/java

Java is version 21.0.4, using 64 (amd64) architecture, from Flathub.

AMD Custom APU 0932
Advanced Micro Devices, Inc. [AMD/ATI] Device 1435 (rev ae)

Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Device 0123

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.2.3 (git-b235da6781)

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.21.1/natives

Traits:
traits feature:is_quick_play_multiplayer
traits FirstThreadOnMacOS
traits feature:is_quick_play_singleplayer
traits XR:Initial

Libraries:
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-freetype-natives-linux/3.3.3/lwjgl-freetype-natives-linux-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.3/lwjgl-glfw-natives-linux-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.3/lwjgl-jemalloc-natives-linux-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-linux/3.3.3/lwjgl-natives-linux-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.3/lwjgl-openal-natives-linux-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.3/lwjgl-opengl-natives-linux-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.3/lwjgl-stb-natives-linux-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.3/lwjgl-tinyfd-natives-linux-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/brigadier/1.3.10/brigadier-1.3.10.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/datafixerupper/8.0.16/datafixerupper-8.0.16.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-x86_64.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/minecraft/1.21.1/minecraft-1.21.1-client.jar

Native libraries:

Params:
  --username  --version 1.21.1 --gameDir /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.21.1/.minecraft --assetsDir /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/assets --assetIndex 17 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx5120m, -Duser.language=en]

Minecraft process ID: 231

[08:39:09] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 351 milliseconds
[08:39:13] [main/WARN]: Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(SourceFile:140) ~[minecraft-1.21.1-client.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(SourceFile:135) ~[minecraft-1.21.1-client.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(SourceFile:527) ~[minecraft-1.21.1-client.jar:?]
	at ac.a(SourceFile:70) [minecraft-1.21.1-client.jar:?]
	at fgo.a(SourceFile:2547) [minecraft-1.21.1-client.jar:?]
	at fgo.a(SourceFile:2517) [minecraft-1.21.1-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:210) [minecraft-1.21.1-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-09-29 08:39:13
Description: Argument parsing

java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.base/java.util.UUID.fromString1(UUID.java:282)
	at java.base/java.util.UUID.fromString(UUID.java:260)
	at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
	at net.minecraft.client.main.Main.main(SourceFile:186)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at java.base/java.util.UUID.fromString1(UUID.java:282)
	at java.base/java.util.UUID.fromString(UUID.java:260)
	at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:186)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.1.52-valve16-1-neptune-61
	Java Version: 21.0.4, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 305354448 bytes (291 MiB) / 536870912 bytes (512 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Custom APU 0932
	Identifier: AuthenticAMD Family 23 Model 145 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Device
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MiB): 258.00
	Graphics card #0 deviceId: 0x1435
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 8431.19
	Virtual memory used (MiB): 7859.04
	Swap memory total (MiB): 1024.00
	Swap memory used (MiB): 1024.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 1479.66, total: 1481.44
	Space in storage for workdir (MiB): available: 558285.69, total: 960947.13
	JVM Flags: 2 total; -Xms512m -Xmx5120m
	Launched Version: 1.21.1
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3+5
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: ERR
	GL debug messages: <disabled>
	Is Modded: Probably not. Client jar signature and brand is untouched
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.21.1/.minecraft/crash-reports/crash-2024-09-29_08.39.13-client.txt
Process exited with code 255.
Clipboard copy at: 29 Sep 2024 08:39:39 -0600

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by maskersss** [comment] 2024-09-29 15:07
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1810 i think

**Comment by Trial97** [comment] 2024-09-29 15:09
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1810
 Already fixed in nightly builds

**Closed as not planned by Trial97** 2024-09-29 15:09 UTC

**Comment by Bloonhero3201** [comment] 2024-09-29 17:21
no dont close it its still not working

**Comment by Trial97** [comment] 2024-09-29 17:57
>log: Prism Launcher version: 8.4 (flatpak) 

So obviously on 8.4 will not work you need a version that is not released yet
