### ISSUE TITLE
Join server on launch isn't working

### ISSUE THREAD

**Issue by EchoEllet** [PrismLauncher/PrismLauncher#2396] opened 2024-05-11 16:49 UTC
### Operating System

Windows

### Version of Prism Launcher

8.2

### Version of Qt

 6.6.2

### Description of bug

I would like to configure a instance so it automatically join a server without doing anything manual to automate the process, maybe this feature was working in earlier versions of Minecraft?

I tried on both 1.20.6 and 1.20.1, both modded (fabric and forge) and vanilla

I searched in the issue tracker and didn't find any other issues but there might be with different title

### Steps to reproduce

1. Create a new instance
2. Go to the settings, Miscellaneous
3. Enable `Set a Server to join on launch` and type any server address like `localhost`

![image](https://github.com/PrismLauncher/PrismLauncher/assets/73608287/ae203c8c-5042-4d4a-a3a7-eb7313a48a4e)

Or open the `Instance.cfg` and edit the `JoinServerOnLaunchAddress` property

4. Launch the instance and the game launched like it would normally

### Suspected cause

It might be because of some recent update of Minecraft or The quick-play feature?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-05-11 16:54
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2124

And update prism this was fixed in 8.3

**Closed as not planned by Trial97** 2024-05-11 16:54 UTC
Labels: status: duplicate
