### ISSUE TITLE
A modpack validator/checker

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#2098] opened 2024-02-05 05:25 UTC
### Role

I play modded Minecraft

### Suggestion

Check if modpack contents match the modpack they were downloaded from

### Benefit

So if there's a mod that you accidentally deleted or if a mod goes missing and you had no idea knowledge of it

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

So basically I updated a modpack and some mods went missing, as stated on #1023 (I think it's mainly a curseforge issue but I'm not sure). So I deleted and redownloaded a modpack I had and noticed it...you know now that I think about it I don't know if I checked with the version I had or if it was a new one...Regardless I think some mods had disappeared. 

So basically, if possible, a feature where it'll check what mods you currently have compared to what mods are on the modpack version page. If you added mods it'll disregard those and only check the ones that match the modpack. If some aren't there then Prism Launcher would show which mods are missing (and if possible same with resource packs and shaders). Maybe use the `.index` to check? 

Tho I understand that this may not be possible to do.

**Comment by Trial97** [comment] 2024-02-05 07:01
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1078
And for tracking the mods that need to be updated in a modpack there is already a similar issue.

**Closed as not planned by Trial97** 2024-02-05 07:01 UTC
Labels: type: enhancement
