### ISSUE TITLE
Bad naming on the overwrite/create modpack selection screen

### ISSUE THREAD

**Issue by cootshk** [PrismLauncher/PrismLauncher#2127] opened 2024-02-14 15:07 UTC
### Operating System

macOS

### Version of Prism Launcher

PrismLauncher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

<img width="515" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/83678457/60d48a69-805d-41e0-8a22-f1ce8ceb8025">

Pressing "OK" overwrites the other version
"Abort" makes a new version
"Reset" cancels the operation

### Steps to reproduce

1. Install a modpack (i used fabulously optimized, from modrinth)
2. install a different version of that same modpack

### Suspected cause

Bad naming

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Lutitious** [comment] 2024-02-14 15:10
On linux this is not an issue as it has appropriate names, not sure about windows

![image](https://github.com/PrismLauncher/PrismLauncher/assets/25961265/40c68996-23d8-4e69-9c26-a856bc77a7a4)

**Comment by Trial97** [comment] 2024-02-14 15:25
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1910
Also already fixed in nightly builds(it will come to 8.1)

**Closed as not planned by Trial97** 2024-02-14 15:25 UTC
