### ISSUE TITLE
the bug is that it won't log me in even with the right information i put it in here is proof                                                            https://1drv.ms/i/c/c9c39cdc4f9fbbd5/ESAefnvopW5JssZ3RbVH72oBn-948EzH5y2-XB_lxBudqQ

### ISSUE THREAD

**Issue by Kirbyzilla2024** [PrismLauncher/PrismLauncher#2899] opened 2024-10-09 09:13 UTC
### Operating System

Windows

### Version of Prism Launcher

it wont let me get on no matter how many times i try to make a account and do it correctly it wont log me in and i cant play mods
![Screenshot 2024-10-09 015936](https://github.com/user-attachments/assets/fd1d3521-c27c-43d9-b14a-c2ffce5ef68c)

### Version of Qt

prism launcher 8.4

### Description of bug

it happend because i was trying to log in that is how iyt happened 

### Steps to reproduce

- fix it please it is a issue 

### Suspected cause

maybe it has to do with the services not working could you fix it 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-10-09 09:16
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-10-09 09:16 UTC
