### ISSUE TITLE
No warning for deleting instances

### ISSUE THREAD

**Issue by he3als** [PrismLauncher/PrismLauncher#143] opened 2022-10-19 21:57 UTC
### Operating System

Windows

### Description of bug

If you click the 'Delete' button on an instance, you should normally get a warning. However, there is no warning. This is problematic as people can easily permanently delete instances.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RuiNtD** [comment] 2022-10-20 00:17
Instances are moved to the system's recycle bin and not permanently deleted, so you can easily restore them from the recycle bin. Normally you should be able to hit Ctrl-Z, but that seems to be broken (#150).

**Comment by he3als** [comment] 2022-10-20 07:09
Maybe a warning could be shown after someone deletes an instance about it being moved to the recycle bin, that you can use CTRL + Z and a little checkbox to not show the warning again?

Also, for configurations without a recycle bin, the regular warning could show instead or there could be a deleted instances folder in the PrismLauncher user data folder.

**Comment by ghost** [comment] 2022-10-22 15:36
> Instances are moved to the system's recycle bin and not permanently deleted

That seems to broken on the flatpak version as it saves to the wrong location

![image](https://user-images.githubusercontent.com/110736028/197347959-30ed0ac1-45bc-4350-b4d0-9a68b9e441fb.png)

**Comment by RuiNtD** [comment] 2022-10-22 16:21
> That seems to broken on the flatpak version as it saves to the wrong location

I'll throw this into a new issue later tonight once I can confirm it myself.

**Comment by Scrumplex** [comment] 2022-10-22 17:07
> That seems to broken on the flatpak version as it saves to the wrong location

We are using Qt's [`QFile::moveToTrash()`](https://doc.qt.io/qt-5/qfile.html#moveToTrash) so this would be a Qt bug either way. This might be fixed by upgrading to Qt 6. We were planning to do that for the Flatpak.

**Comment by Scrumplex** [comment] 2022-11-27 22:39
Trash on Flatpak is disabled now. It will ask for confirmation for permanent deletion instead.

**Closed as completed by Scrumplex** 2022-11-27 22:39 UTC
