### ISSUE TITLE
Allow exporting instances using CLI

### ISSUE THREAD

**Issue by chowder3907** [PrismLauncher/PrismLauncher#1915] opened 2023-12-04 05:13 UTC
### Role

I want to backup instances using cron

### Suggestion

I want there to be a -e flag in the CLI that allows me to export an instance

### Benefit

So I can easily automate backups of instances in case of world corruption

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2023-12-04 06:55
Duplicate of #771

**Closed as not planned by Trial97** 2023-12-04 06:55 UTC
Labels: type: enhancement
