### ISSUE TITLE
Issue templates still contain PolyMC information

### ISSUE THREAD

**Issue by he3als** [PrismLauncher/PrismLauncher#140] opened 2022-10-19 21:45 UTC
### Description of bug

![image](https://user-images.githubusercontent.com/65787561/196810720-fb4ee095-c7e8-4442-8741-1f66fbf27efd.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RuiNtD** [comment] 2022-10-20 00:22
Duplicate of #106

**Closed as completed** 2022-10-20 06:36 UTC
