### ISSUE TITLE
Launcher does not switch JRE

### ISSUE THREAD

**Issue by Heavy0331** [PrismLauncher/PrismLauncher#1423] opened 2023-07-24 06:30 UTC
### Operating System

Pop!_OS 22.04 (Linux)

### Version of Prism Launcher

Prism Launcher 7.1 (Flatpak)

### Version of Qt

Qt 5.15.10

### Description of bug

The Launcher believes that the jre at the path that is explicitly marked as version "1.8.0_372" in the JRE selection screen is version 17 when launching it
![Screenshot from 2023-07-24 01-25-01](https://github.com/PrismLauncher/PrismLauncher/assets/73771358/8739a76e-f2fb-4dd2-8d4a-3abd62c233ee)
![Screenshot from 2023-07-24 01-24-37](https://github.com/PrismLauncher/PrismLauncher/assets/73771358/b006a7d1-21f1-49aa-9221-7c0af1d9f02f)
```Prism Launcher version: 7.1


Launched instance in online mode

authserver.mojang.com resolves to:
    [**.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**]

session.minecraft.net resolves to:
    [****:****:****:****:****:****:****:****, ****:****:****:****:****:****:****:****, **.**.**.**, **.**.**.**]

textures.minecraft.net resolves to:
    [****:****:****:****:****:****:****:****, ****:****:****:****:****:****:****:****, **.**.**.**, **.**.**.**]

api.mojang.com resolves to:
    [****:****:****:****:****:****:****:****, ****:****:****:****:****:****:****:****, **.**.**.**, **.**.**.**]


Minecraft folder is:
/home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.7.10/.minecraft


Java path is:
/app/jdk/8/jre/bin/java


Java is version 17.0.7, using 64 (amd64) architecture, from Flathub.


Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]

DeviceName: Onboard - Video

Subsystem: Dell Device 086f

OpenGL version string: 4.6.0 NVIDIA 525.116.04

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.7.10/natives

Libraries:
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  --username  --version 1.7.10 --gameDir /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.7.10/.minecraft --assetsDir /home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Launcher: standard

This instance is not compatible with Java version 17.
Please switch to one of the following Java versions for this instance:
Java version 8
Go to instance Java settings to change your Java version or disable the Java compatibility check if you know what you're doing.
Log upload triggered at: 24 Jul 2023 01:25:20 -0500
Log upload canceled
Log upload triggered at: 24 Jul 2023 01:25:49 -0500```

### Steps to reproduce

- Download Prism Launcher from the flatpak ref
- create a minecraft instance that requires java 8 to run
- go to Settings > Java > Browse
- switch from JRE 17 to JRE 8
- launch

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment] 2023-07-24 10:00
Duplicate of #1250

**Closed as not planned by TheKodeToad** 2023-07-24 10:00 UTC
Labels: status: duplicate, status: invalid
