### ISSUE TITLE
Add "Check for update" to Resource & Shader pack tabs.

### ISSUE THREAD

**Issue by Squtzy** [PrismLauncher/PrismLauncher#3088] opened 2024-11-10 16:16 UTC
### Role

I play minecraft with both resource and shader packs

### Suggestion

Add a "Check for updates" button similar to the one in the mods tab for resouce and shader pack tabs.

### Benefit

Easier to make sure you are running the latest version of said things like with mods.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-11-10 16:23
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1207

**Closed as not planned by Trial97** 2024-11-10 16:23 UTC
Labels: type: enhancement

**Comment by Squtzy** [comment] 2024-11-10 18:24
> Duplicate of #1207

Mind if I ask why it is not planned to make this?

**Comment by Trial97** [comment] 2024-11-10 19:24
Sorry but I thought that it was clear: the mentioned issue was already implemented and marked as complete, the feature you requested is already in the nightly builds and is planned to be released in 10.0.
I closed this as a duplicate because it is a duplicate of the mentioned issue.

**Comment by Squtzy** [comment] 2024-11-10 22:29
> Sorry but I thought that it was clear: the mentioned issue was already implemented and marked as complete, the feature you requested is already in the nightly builds and is planned to be released in 10.0. I closed this as a duplicate because it is a duplicate of the mentioned issue.

Ohhhhh my bad, I understood it was a duplicate but I must've been to dumb to realize it was already implemented lol
