### ISSUE TITLE
Crashing when trying to import files

### ISSUE THREAD

**Issue by mhzen** [PrismLauncher/PrismLauncher#2235] opened 2024-03-23 01:40 UTC
### Operating System

Linux

### Version of Prism Launcher

8.2

### Version of Qt

6.6.2

### Description of bug

When trying to import a modpack or adding mods to instances will cause prism to crash. Weirdly enough the modpack/mod files will get imported when prism is relaunched. This doesn't happen with drag-and-drop. This also doesn't happen when using the flatpak package (i used `prismlauncher-bin` from the aur)

Here a video demonstration
[Screencast_20240323_082132.webm](https://github.com/PrismLauncher/PrismLauncher/assets/88493761/47bfb3ae-09a3-46b7-8d42-800bf1255efe)

And here's some log:
https://gist.github.com/warofzen/3cf550dd1fd19ee768f268b0d47eb237

### Steps to reproduce

1. Open Prism
2. Import a modpack from a file or Add mods via the add file in instance
3. ???
4. Crash

### Suspected cause

Im not really sure so myself. Might be arch thing since it doesn't happen with flatpak.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-03-23 06:13
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2214
They seem to have the same root cause as both happen when you try to select a file.

**Closed as not planned by Trial97** 2024-03-23 06:13 UTC
