### ISSUE TITLE
QT 6.6.1-1 breaks Prismlauncher

### ISSUE THREAD

**Issue by Severus157** [PrismLauncher/PrismLauncher#1909] opened 2023-12-02 18:10 UTC
### Operating System

Linux

### Version of Prism Launcher

PristmLauncher 8.

### Version of Qt

6.6.1-1

### Description of bug

After updating the system to Kernel Version 6.6.3.arch1-1 and QT Version 6.6.1-1 Prismlauncher 8 breaks the System. Prismlauncher cannot be started again with error message:
`prismlauncher: symbol lookup error: prismlauncher: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API`

### Steps to reproduce

Trying to start prismlauncher

### Suspected cause

System Update

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-12-02 19:11
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1903
See fix: https://github.com/PrismLauncher/PrismLauncher/issues/1903#issuecomment-1834562231

**Closed as not planned by Trial97** 2023-12-02 19:11 UTC
