### ISSUE TITLE
Unable to export an instance as valid .mrpack on Prism Launcher but can on MultiMC

### ISSUE THREAD

**Issue by amycol** [PrismLauncher/PrismLauncher#1283] opened 2023-06-27 18:33 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

Modrinth gives the error "Error while validating uploaded file: Invalid Input: Field downloads of list files with index 9 failed validation with error: invalid URL" when uploading a .mrpack file generated by Prism Launcher but when using the same instance in MultiMC (copy and pasting the instance folder from Prism Launcher to MultiMC)

### Steps to reproduce

Export an instance as .mrpack and upload it to Modrinth. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment] 2023-06-27 18:39
I believe this is a duplicate of #1226, if so a fix has already been made (it's just not fully released)

**Closed as not planned by TheKodeToad** 2023-06-27 18:39 UTC
Labels: status: duplicate, status: invalid
