### ISSUE TITLE
Prism Launcher settings windows are max out and cannot smaller

### ISSUE THREAD

**Issue by chocobolt** [PrismLauncher/PrismLauncher#3015] opened 2024-10-28 11:26 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.7.3

### Description of bug

![image](https://github.com/user-attachments/assets/92dc1d9d-09ec-4b60-92f3-0495c2b32b98)
The prism launcher settings page are so big, and cannot make it smaller which make me cannot see bottom

### Steps to reproduce

Open settings, 
Page are so big,
Cannot smaller

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-10-28 11:36
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/220
(it is not limited to SteamOS but is extended to low res computers)

**Closed as not planned by Trial97** 2024-10-28 11:36 UTC
