### ISSUE TITLE
Indexing mods hangs when paths have Chinese, cyrillic or with diacritics characters

### ISSUE THREAD

**Issue by Scrumplex** [PrismLauncher/PrismLauncher#226] opened 2022-10-22 12:19 UTC
### Operating System

Windows

### Version of Prism Launcher

5.0

### Version of Qt

6.4.0

### Description of bug

When indexing mod metadata and there are mods with Chinese characters, the launcher just hangs.

### Steps to reproduce

- Add chinese characters to mod filenames.
- Try to index

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by snowlinouo** [comment] 2022-10-23 02:50
Setting the instance name to Chinese, the Updater Mod will also cause the launcher to not respond

`PrismLauncher-0.log`
```
  465.449 W "Could not open file fabric-api.pw.toml!"
  465.449 W Reason:  "File could not be opened for reading"
  465.449 C Failed to generate metadata at last step!
  465.449 D "Failed to generate metadata for Fabric API"
  465.449 D Task "Task(FlameHasher: D:/Game/PrismLauncher/instances/測試/.minecraft/mods/fabric-api-0.64.0+1.19.2.jar)" starting for the first time
```

![UP](https://user-images.githubusercontent.com/113241163/197370869-0114d2d3-bf82-4af1-af02-839ebfbeded8.png)

**Comment by TenTeypek** [comment] 2022-11-01 16:52
Also happens when the file path has letters with diacritics

**Comment by ghost** [comment] 2022-11-03 16:30
Seems to also happen with cyrrilic letters.

**Comment by snowlinouo** [comment] 2022-11-03 18:32
Same problem happens with Mandarin Phonetic Symbols
The instance name is: ㄅㄆㄇ

`PrismLauncher-1.log`
```
  299.335 W "Could not open file modmenu.pw.toml!"
  299.335 W Reason:  "File could not be opened for reading"
  299.335 C Failed to generate metadata at last step!
  299.335 D "Failed to generate metadata for Mod Menu"
  299.335 D Task "Task(FlameHasher: D:/Game/PrismLauncher/instances/ㄅㄆㄇ/.minecraft/mods/modmenu-4.0.6.jar)" starting for the first time
```

![image](https://user-images.githubusercontent.com/113241163/199805557-9a9235a8-dcab-48c5-a9bb-06f82d854653.png)

**Comment by txtsd** [comment] 2022-11-04 13:39
Is this a Qt problem or a tomlplusplus problem?

**Comment by marzer** [comment] 2022-11-05 13:46
> Is this a Qt problem or a tomlplusplus problem?

@txtsd I've tried pretty hard to make toml++ 100% UTF-8 compliant, so it _shouldn't_ be in toml++. If you give it malformed UTF-8 it might do weird stuff, though. Is someone here able to provide me with a repro TOML file for me to have a look into it?

**Comment by flowln** [comment] 2022-11-05 13:52
@marzer  The issue doesn't seem to be in the TOML parsing itself, but rather in the `parse_file` function, when the file path has non-latin characters. The issue is no longer present when reading the file through Qt, and passing the data to toml++. In my tests, the path containing the TOML file had the string `paçoca` in it, and that seems to prevent toml++ from working correctly :/

**Comment by marzer** [comment] 2022-11-05 13:55
Ohhhh right, so something about the way the `std::ofstream` handles the paths gets messed up when they have non-ASCII characters. Hmmmn. Perhaps I should widen them to `wchar_t` path strings on windows before passing them to the ofstream...

**Comment by marzer** [comment] 2022-11-05 14:13
Interesting. Can confirm that indeed does fix the problem. I'll push a fix to the toml++ for that now.

**Comment by flowln** [comment] 2022-11-05 14:20
Thank you! :D

**Comment by marzer** [comment] 2022-11-05 14:22
Fixed in https://github.com/marzer/tomlplusplus/commit/cc741c9f5f2a62856a2a2e9e275f61eb0591c09c :)

**Closed as completed** 2022-11-10 13:34 UTC
