### ISSUE TITLE
Adding a microsoft account that is backed by github credentials is stuck forever in a loop

### ISSUE THREAD

**Issue by wyvern800** [PrismLauncher/PrismLauncher#1582] opened 2023-08-30 15:30 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 5.15.10

### Description of bug

Adding a microsoft account that is backed by github credentials is stuck forever in a loop, cause whenever I click to proceed, it will redirect me to my microsoft profile page.

### Steps to reproduce

Steps:

1. Click to add a Microsoft account  (that is backed by github credentials). copy the code and click to open the link.
2. Put the code and press next. 

Now you should be delivered to a your microsoft profile and nothing happens. That way seems I can not connect my account to be able to play. its been a week since I discovered this issue.

### Suspected cause

Seems like the link to bind account is having an error and so we're being redirected to normal microsoft profile page.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by blanky6739** [comment] 2023-08-30 20:28
Can confirm, mac + prism 7.2

**Comment by wyvern800** [comment] 2023-08-30 22:49
The only way to workaround that, is to click 'Choose a different way of authentication' then 'Using password', so after that you'll be able to connect your account, although its a still a bug xD

**Comment by wyvern800** [comment] 2023-08-30 22:50
> Reference in ne

The only way to workaround that, is to click 'Choose a different way of authentication' then 'Using password', so after that you'll be able to connect your account, although its a still a bug xD

**Comment by wyvern800** [comment] 2023-08-30 22:50
> Can confirm, mac + prism 7.2

The only way to workaround that, is to click 'Choose a different way of authentication' then 'Using password', so after that you'll be able to connect your account, although its a still a bug xD

**Comment by Ego-Matthisum** [comment] 2024-03-28 16:20
I have had the same issue, for me the following worked:

#### Using GitHub Account

1. After clicking _Add Microsoft_ and clicking next, don't enter your username/E-Mail but click _Sign-in options_
2. Choose _Forgot Username_ and enter te E-Mail adress associated with your account and click next
3. You should receive a one-time passcode to your E-Mail, enter the code and continue
4. You should now be able too connect PrismLauncher

Edit: Changed "MultiMC" to "PrismLauncher".

**Comment by Trial97** [comment] 2024-04-12 16:26
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-04-12 16:26 UTC
Labels: area: auth

**Comment by bschaatsbergen** [comment] 2024-04-23 17:10
> I have had the same issue, for me the following worked:
> 
> #### Using GitHub Account
> 1. After clicking _Add Microsoft_ and clicking next, don't enter your username/E-Mail but click _Sign-in options_
> 2. Choose _Forgot Username_ and enter te E-Mail adress associated with your account and click next
> 3. You should receive a one-time passcode to your E-Mail, enter the code and continue
> 4. You should now be able too connect MultiMC

This worked, thanks 👍🏼
