### ISSUE TITLE
Add graalvm

### ISSUE THREAD

**Issue by NeonSupernova** [PrismLauncher/PrismLauncher#2950] opened 2024-10-21 14:47 UTC
### Role

General java performance enhancements

### Suggestion

Add a graalvm source to the new java management

### Benefit

To make setting up a faster performing java instance

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Essentially, [graalvm](https://www.graalvm.org/downloads/) is a faster java, since it runs on llvm. Unfortunately, at the moment, it is difficult to install without already having JDK tools installed. I believe the performance uplift of graalvm is enough to warrant it being a recommended install.

**Comment by Trial97** [comment] 2024-10-21 14:48
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2949

**Closed as not planned by Trial97** 2024-10-21 14:48 UTC
Labels: type: enhancement
