### ISSUE TITLE
Provider information for modpacks from curseforge doesn't link the modpack website

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#2097] opened 2024-02-05 04:49 UTC
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

When a modpack is downloaded from modrinth, on the modrinth tab next to provider information it links to the modpack's page. If done the same for curseforge it does not link to the modpack's page. 

### Steps to reproduce

Install curseforge modpack. 
Check provider information. 
No link. 

### Suspected cause

Something with curseforge's API maybe?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment] 2024-02-05 04:52
I didn't know what words to search if there was a duplicate and what I tried didn't show anything similar so I'm pretty sure this is unique. I wasn't sure if it was a bug or feature, but since it works with modrinth modpacks and not curseforge modpacks I figured it'd be a bug. 

<img width="1044" alt="Screen Shot 2024-02-04 at 11 52 08 PM" src="https://github.com/PrismLauncher/PrismLauncher/assets/106651342/597d9aa4-4b9c-47bf-b76c-c8625f59f143">

<img width="1044" alt="Screen Shot 2024-02-04 at 11 52 27 PM" src="https://github.com/PrismLauncher/PrismLauncher/assets/106651342/f3cc7d7e-441e-4771-93d4-a94b4c78faa3">

Here's an example of what I mean

**Comment by Trial97** [comment] 2024-02-05 06:55
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1731
And implemented in nightly builds

**Closed as not planned by Trial97** 2024-02-05 06:55 UTC
