### ISSUE TITLE
${name} mod?

### ISSUE THREAD

**Issue by Djspac3** [PrismLauncher/PrismLauncher#2384] opened 2024-05-08 20:04 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

i don't know just there shouldn't be a mod named ${name} ????
also extra but i don't know what to look for for if its unique just searched for ${name}

### Steps to reproduce

i don't know just edit the mods it will appear at the top
[(folder 1.20.4 will be edited to show soon)](https://github.com/Djspac3/prism-instances)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-05-08 20:07
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2364

**Comment by Trial97** [comment] 2024-05-08 20:08
basically, the mod provides both forge and fabric files but when is built for fabric the forge file remain but are not populated

**Closed as not planned by Trial97** 2024-05-08 20:07 UTC

**Comment by Djspac3** [comment] 2024-05-09 18:44
Oh, so it's just the mod has some forge data with the fabric ohhhh ok so it's a bug on the mods end
