### ISSUE TITLE
If possible, add a resource pack picker and shader pack picker akin to the mod picker

### ISSUE THREAD

**Issue by GoldenFurredFox** [PrismLauncher/PrismLauncher#299] opened 2022-10-25 02:16 UTC
### Role

I commonly use shader packs and resource packs at random for certain review purposes, and downloading them using my browser can be a hassle.

### Suggestion

I want Prism Launcher to repurpose the mod picker in the edit instance window for picking resource and/or shader packs, preferably both.

### Benefit

It would help me immensely in pack review since I would have to go through fewer steps to download and review packs.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TayouVR** [comment] 2022-10-25 12:34
somewhat Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/153

(maybe rename to only shaderpacks, as those are not already mentioned in the other issue)

**Comment by DioEgizio** [comment] 2022-10-25 13:06
shaderpacks cannot be downloaded from the curseforge api anyways

**Comment by DioEgizio** [comment] 2022-10-25 13:06
Duplicate of #153

**Closed as not planned** 2022-10-25 13:07 UTC
Labels: status: duplicate, type: enhancement
