### ISSUE TITLE
cant downlode

### ISSUE THREAD

**Issue by wangdashiii** [PrismLauncher/PrismLauncher#3139] opened 2024-11-25 12:34 UTC
### Operating System

Windows

### Version of Prism Launcher

may somethings wrong
![image](https://github.com/user-attachments/assets/5401b3d5-4797-488d-a489-63a0b92f12b5)

### Version of Qt

9.1

### Description of bug

cant downlode

### Steps to reproduce

only curseforge

### Suspected cause

may url 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-11-25 12:45
forge maven down
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/3133

**Closed as not planned by Trial97** 2024-11-25 12:45 UTC
