### ISSUE TITLE
Support curseforge format

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#1282] opened 2023-06-27 18:00 UTC
### Role

I love making builds and posting them on curseforge. I switched from ATlauncher to this one and it's a little disappointing that I can only use prizm and modrith

### Suggestion

curseforge format support for export

### Benefit

It will be easier to develop your modpack on at least 2 sites

**Comment by TheKodeToad** [comment] 2023-06-27 18:38
Duplicate of #269; it's currently a WIP by trial97

**Closed as not planned by TheKodeToad** 2023-06-27 18:38 UTC
Labels: status: duplicate, status: invalid
