### ISSUE TITLE
Support for NeoForged

### ISSUE THREAD

**Issue by Lordfirespeed** [PrismLauncher/PrismLauncher#1577] opened 2023-08-29 14:29 UTC
### Role

I play modded minecraft :)

### Suggestion

Support NeoForged as a mod loader when creating instances 

### Benefit

NeoForged may supercede Forge in future versions 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

See [here](https://neoforged.net/news/theproject/) - the majority of the Forge team has proverbially 'jumped ship' to this new project, so it seems like original Forge's days may be numbered.

**Comment by TheKodeToad** [comment] 2023-08-29 14:30
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1356

(I'm so quick 🚀 x2)

**Closed as not planned** 2023-08-29 14:29 UTC
Labels: status: duplicate, status: invalid

**Comment by TheKodeToad** [comment] 2023-08-29 14:38
oops
