### ISSUE TITLE
JRE version-specific arguments

### ISSUE THREAD

**Issue by ColonelGerdauf** [PrismLauncher/PrismLauncher#2973] opened 2024-10-23 18:12 UTC
### Role

I use specific arguments in my instances

### Suggestion

Put a arguments section for each specific subversion

### Benefit

EOU/QOL; significantly simplifies the setup of a new instance

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The simple way to do this is to make a dedicated tab in `Java`, that has arguments for any version 8, 17, 21, and even 11.

Alternatively, there is space at the bottom half of the `Java >> Management` tab. That is sufficient space for inputting specific arguments for each Java version. In this case Prism should store the version class as is describe above, so that the settings do not get wiped when the version(s) are getting manually updated.

The reason this would be needed is that there are arguments that are specific for each version (like X/Shen/serial or NUMA). The `JVM Arguments` section that is provided is only good so long as the user limits themselves to a specific sub section of Minecraft versions. Beyond that can get burdensome to jot down the arguments elsewhere or to save the arguments in a dummy instance.

**Comment by Vanqy9316** [comment] 2024-10-26 15:02
to extend upon this, since the support for direct download of different JVM/JRE vendors has been added, id like to see support for the feature requested here to apply to each JVM individually, inside their respective Java version individually. so for example graalVM now supports ZGC but only in Java 21. similar constraints should happen to other JVMs too.
there are a few big writeups about java flags out there, especially from brucethemoose and its forks. java flags are in a constant change, and the feature could help to simply things.

**Comment by Trial97** [comment] 2024-10-27 00:07
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/789

**Closed as not planned by Trial97** 2024-10-27 00:07 UTC
Labels: type: enhancement
