### ISSUE TITLE
Make Prismlauncher detectable as a game on mac

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#1958] opened 2023-12-16 01:41 UTC
### Role

I play modded Minecraft

### Suggestion

I want it to be detected as a game on mac

### Benefit

So that it gets categorized correctly. No real benefit honestly

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'm not sure if I worded my issue right but basically for certain applications on mac that are games, the system is able to detect that and it gets categorized as a game...which I'm pretty sure the developer would need to put in. 

There's no real issue or benefit, just more of a cool feature. I'm not really sure on the policy for implementing things that are only for a single OS so if this isn't really worth putting in you can just close this

**Comment by Avakining** [comment] 2024-07-05 20:37
Seems to be a duplicate of #1644

**Comment by Trial97** [comment] 2024-07-05 21:53
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1644

**Closed as not planned by Trial97** 2024-07-05 21:53 UTC
Labels: type: enhancement

**Comment by Aces-and-Jacks** [comment] 2024-07-06 13:30
Well game mode is similar. I just want it to be categorized as a game. If that's included in game mode then that'd be good
