### ISSUE TITLE
Incorrect warning about 32-bit Java

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#3192] opened 2024-12-11 16:59 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.8.1

### Description of bug

This warning shouldn't be shown on 64-bit systems.
![warning](https://github.com/user-attachments/assets/7ced30c9-5aa7-4fb2-a62f-5a7c07c3f767)

### Steps to reproduce

Start Prism for the first time.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-12-11 17:11
Fixed in nightly it will be a thing in 9.2.
Also, this is a duplicate of a closed issue.

**Closed as completed by Trial97** 2024-12-11 17:11 UTC
