### ISSUE TITLE
Java (JVM) Arguments 

### ISSUE THREAD

**Issue by MrRoooo** [PrismLauncher/PrismLauncher#3021] opened 2024-10-28 20:54 UTC
### Role

Modded MineCraft

### Suggestion

In the Java setting, allow a JVM Args dropdown for each JAVA version (8,16,17,21) with my set of java args for each different version. 

### Benefit

Modded MineCraft has so maybe different packs on so many different MineCraft version, it will be helpful to have the Args dropdown as args are different between JAVA.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-10-28 20:56
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2973

**Closed as not planned by Trial97** 2024-10-28 20:56 UTC
Labels: type: enhancement
