### ISSUE TITLE
allow the user to add a note to any one mod in the instance's mod list

### ISSUE THREAD

**Issue by TheAwesome98-Real** [PrismLauncher/PrismLauncher#2688] opened 2024-07-28 16:45 UTC
### Role

i play with large numbers of mods, and create modpacks.

### Suggestion

i want there to be a new "notes" column in the list of mods in the instance options, where the user can write free-form text.

### Benefit

this would allow me to write things such as why i have a mod installed, or why a mod is disabled.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

if a notes column were added to the mod list (or even other lists like resource packs and shaders), it would allow the user to write information they may need to remember. for example, i may disable a mod because i don't like its functionality, or found an alternative, but may want to keep it available if i need to enable it later. or, i may disable a mod because it crashes the game when enabled alongside another mod, so i could remind myself which mod, so i can figure out why and submit a fix.

**Comment by Trial97** [comment] 2024-07-28 16:47
Duplicate of categories issue(there will not be any free-form column other than tags/categories)

**Closed as not planned by Trial97** 2024-07-28 16:47 UTC
Labels: type: enhancement

**Comment by TheAwesome98-Real** [comment] 2024-07-28 17:18
> Duplicate of categories issue(there will not be any free-form column other than tags/categories)

oh, which issue is it? i can't find it

**Comment by Trial97** [comment] 2024-07-28 17:21
https://github.com/PrismLauncher/PrismLauncher/issues/1076
https://github.com/PrismLauncher/PrismLauncher/issues/154
