### ISSUE TITLE
Sinytra in Versions Instead of Mods

### ISSUE THREAD

**Issue by SaltSouls** [PrismLauncher/PrismLauncher#2960] opened 2024-10-21 23:05 UTC
### Role

I play modded Minecraft and also make modpacks.

### Suggestion

Add Sinytra connector and Extras to the versions tab.

### Benefit

Will allow installing and updating fabric mods as well as forge.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

So this is a little more than just adding Sinytra and Extras to the version tab. It would also entail making it so having those mods enabled would count as having fabric installed and allowing users to install forge and fabric mods at the same time; instead of currently having to switch back and forth between forge and fabric. To do this without headache(on the users end) it would likely require a rework of how the mod install/tagging system works. I suggest allowing users to specify if they want to install a forge or fabric version of a mod when looking through mods, and then internally label said installed mod as forge or fabric for update purposes.

This could be done by having a toggle in the mod installer, that way the shown mods are either only forge or fabric. I imagine this is something that wouldn't be too hard to do(I don't know as I don't work with electron) seeing as how the launcher already has the capability of determining whether or not to show forge/fabric mods based on the selected mod launcher. All in all, this would just make things easier for users as far as installing and updating forge/fabric mods at the same time when using Sinytra Connector.

**Comment by SaltSouls** [comment] 2024-10-21 23:32
So I'll retract the first part of this suggestion as I see there is already a way to download fabric mods using the filters when downloading mods. The only change I would suggest at this point is making it so when updating the mods, it will recognize Sinytra as having fabric installed, and will update any downloaded mod tagged as fabric, that way we don't have to switch to fabric loader every time you want to update your fabric mods.

**Comment by Trial97** [comment] 2024-10-22 06:10
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1521

**Closed as not planned by Trial97** 2024-10-22 06:10 UTC
Labels: type: enhancement
