### ISSUE TITLE
Both "Game log" and "Other log" didnt encode accented Vietnamese

### ISSUE THREAD

**Issue by BoNuong** [PrismLauncher/PrismLauncher#2722] opened 2024-08-11 13:48 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

It replace every accented Vietnamese character like "ứ" with "?"

### Steps to reproduce

1. Copy and paste any accented character like "í", "ứ",...
2. Open Game Log and Other Logs

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-08-11 13:52
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2419

**Closed as not planned by Trial97** 2024-08-11 13:52 UTC

**Comment by BoNuong** [comment] 2024-08-11 13:55
> Duplicate of: #2419

I've been try adding -Dfile.encoding=UTF-8 to java argument but it even worse

**Comment by BoNuong** [comment] 2024-08-11 13:57
> Duplicate of: #2419

It display something like this "sáº¡ch; pháº¥n Ä‘áº¥u á»•n Ä‘á»‹nh vÃ tÄƒng trÆ°á»Ÿng kinh táº¿ nhanh hÆ¡n"
