### ISSUE TITLE
Blocked Mods sometimes don't transfer correctly or validate hashes.

### ISSUE THREAD

**Issue by Frontear** [PrismLauncher/PrismLauncher#958] opened 2023-03-30 02:40 UTC
### Operating System

Windows

### Version of Prism Launcher

Latest from dev branch.

### Version of Qt

Qt 6.4.2

### Description of bug

When downloading BMP1, "BetterDefaultBiomes" does not correctly get detected. Furthermore, I notice that it does not transfer all the mods correctly, namely TALPM jar does not transfer. This results in a broken install that does not correctly work on any modpack server. I had to manually transfer the blocked mods over in order to make it work.

### Steps to reproduce

* New instance
* Select curseforge -> BMP1 by LunaPixelStudios
* When blocked mods pop up press Open Missing, download mods, notice one of the mods does not match hash check.
* Try copy-pasting jars after install, notice how some do not "replace", meaning they were missing from the install.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment] 2023-05-04 03:27
in this specific case it's because the mods jar name doesn't match the name provided by the pack file `BetterDefaultBiomes-1.16.4+-Alpha 2.6.1.jar` vs `BetterDefaultBiomes-1.16.4+-Alpha+2.6.1.jar` . if you manually drag the file onto the dialog it matches fine. we already have a check that tries to relax the filename match by replacing ` `  with `+` I guess I'll add an additional check that does the reverse.

I'm unable re reproduce the case of TALPM not transferring.

**Closed as completed** 2023-05-06 07:55 UTC
