### ISSUE TITLE
Add a toggle for displaying mod icon images

### ISSUE THREAD

**Issue by AnAwesomGuy** [PrismLauncher/PrismLauncher#2270] opened 2024-04-04 11:39 UTC
### Role

I play modded Minecraft.

### Suggestion

Add a toggle for displaying mod icon images.

### Benefit

reduce clutter in the modlist.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

many mods, especially older ones, dont have any mod icons, so having mod icons just causes clutter. i personally like it more compact without the mod icons anyway. also, why is the "enable" column so wide?
![example](https://github.com/PrismLauncher/PrismLauncher/assets/79700396/80703c34-c48e-4f0d-9715-0ef314e929d1)

**Comment by Trial97** [comment] 2024-04-04 12:03
Duplicate of: #1804

**Closed as not planned by Trial97** 2024-04-04 12:03 UTC
Labels: type: enhancement
