### ISSUE TITLE
Improve Resource Packs and Shader Packs lists similar to Mods list

### ISSUE THREAD

**Issue by Superniquito** [PrismLauncher/PrismLauncher#2028] opened 2024-01-12 00:03 UTC
### Role

I use resource and shader packs

### Suggestion

Resource Packs and Shader Packs lists should be identical to the mods lists

### Benefit

Currently you cannot check for updates in any way

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Currentlly the following issues are present:
Both Resouce and Shader packs:
- Lack provider column for Modrinth or CurseForge
- Lack version column
- Have the file name instead of the In-game display name
- Lack "Check for Updates" right click menu
- Lack "Visit pack's page" right click menu and link on the bottom display
Shader packs only:
- Lack description
- Lack Icons

**Comment by Trial97** [comment] 2024-01-12 06:39
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1207
Feel free to extend that one with additional information if needed

**Closed as not planned by Trial97** 2024-01-12 06:39 UTC
Labels: type: enhancement
