### ISSUE TITLE
Allow disabling all Java segments in Settings, like you can in the instance editor.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [PrismLauncher/PrismLauncher#2138] opened 2024-02-18 13:31 UTC
### Role

I need certain arguments for networking some of the time, per https://www.reddit.com/r/SteamDeck/comments/yhqz0m/psa_a_solution_for_those_unable_to_play_modded/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button. I have them application-wide (rather than instance-specific) consequently.

### Suggestion

I sometimes need to disable all Java arguments when using other network configurations.

### Benefit

Allow me to disable them in Settings, like I can for individual instances.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

1.	> ![20240218T133141GMT](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/03eb4394-c452-4a5f-963b-1afa0f7287d6)
1.	> ![20240218T133153GMT](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/dd812522-df46-4d15-b279-5414a178b835)

**Comment by Trial97** [comment] 2024-02-19 06:46
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1764

**Closed as not planned by Trial97** 2024-02-19 06:46 UTC
Labels: type: enhancement

**Comment by RokeJulianLockhart** [comment] 2024-02-19 14:01
> https://github.com/PrismLauncher/PrismLauncher/issues/2138#issuecomment-1951804024

@Trial97, I don't see how this is a duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1764#issue-1967157229, because that report itself doesn't make much sense — the feature it refers to as *inoperative* doesn't even exist, per https://github.com/PrismLauncher/PrismLauncher/issues/2138#issue-2140990984...

Regardless, I believe I've described the request better — could you at least consider closing that one for that purpose? After all, its description is confusing to me, so I expect it shall be to others.

**Comment by Trial97** [comment] 2024-02-19 14:10
Ok maybe I missed the duplicate issue(there are a lot of them).
But regarding what you describe I think there is https://github.com/PrismLauncher/PrismLauncher/issues/789
Similar to what you suggest: have a normal java profile and one with network arguments.
And sorry for closing this without double-checking the issue, but lately the number of the issues keeps increasing and most of them are duplicates of older issues.

**Comment by RokeJulianLockhart** [comment] 2024-02-19 14:14
> https://github.com/PrismLauncher/PrismLauncher/issues/2138#issuecomment-1952531530

No worries, @Trial97, although https://github.com/PrismLauncher/PrismLauncher/issues/2138#issuecomment-1952531530 is definitely not what I'm requesting. To clarify, please look at the bottom halves of the images supplied in https://github.com/PrismLauncher/PrismLauncher/issues/2138#issue-2140990984 - whereas the instance editor provides Qt checkboxes to allow the user to save the contents of their counterpart forms yet not use the data stored in them, Settings does not. I'm requesting that these pages be unified (to lessen the disparities of functionality within them and allow the codebase to be more consistent and consequently easier to maintain).

Does that make sense? Please consider reopening this.

---

I understand the burden of an issue triager. Lots of incoherent reports and duplicates which must be dealt with.

**Comment by Trial97** [comment] 2024-02-19 14:26
For me looks like both this one and the Java profile solve the same issue and if the profile one is implemented then this one will become obsolete.
Also, disabling global settings is not desired as you should always have a default value for that setting.
I will leave the reopening of this issue to other maintainers as I'm not sure if we want to support this.

**Comment by RokeJulianLockhart** [comment] 2024-02-19 15:25
> https://github.com/PrismLauncher/PrismLauncher/issues/2138#issuecomment-1952560306

@Trial97,

1.	> For me looks like both this one and the Java profile solve the same issue and if the profile one is implemented then this one will become obsolete.

	The profile provides similar functionality, but I would want to be able to disable the forms per-profile when that exists, too.

1.	> Also, disabling global settings is not desired as you should always have a default value for that setting.

	That's a good point, although from what I can conceieve, it's actually quite easily solvable — although to the user they appear “disabled”, they merely default to their default values when in the disabled state, thus rendering them as they are by default. To demonstrate this to the user, it could be communicated that these become defaults when disabled somewhere in the page.
