### ISSUE TITLE
Better error on "Account refresh failed"

### ISSUE THREAD

**Issue by samueldcorbin** [PrismLauncher/PrismLauncher#2218] opened 2024-03-16 22:35 UTC
### Role

I play modded Minecraft and develop Minecraft mods

### Suggestion

I want it to point the user to *how* to "log in manually again".

### Benefit

Users will be less frustrated and will know what to do.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The current error message for "Account refresh failed" is terrible. It just says "The account has expired and needs to be logged into manually again."

Which account? How does the user log in again? How do they do it manually? It's barely better than "there was an error".

It should either link the player to the Accounts page of Settings, or at least tell them to look there, and it should probably also say "You may need to re-add your account."

**Comment by Atemo-C** [comment] 2024-03-30 22:55
I agree. I stumbled upon this issue exactly because I was confused about what to do. Removing my account and re-adding it worked, but it could definitely be made clearer to the user.

**Comment by Trial97** [comment] 2024-04-04 07:08
Related to #2171

**Comment by Trial97** [comment] 2024-04-12 16:30
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2171

**Closed as not planned by Trial97** 2024-04-12 16:30 UTC
Labels: type: enhancement, area: auth
