### ISSUE TITLE
Mod updater hangs the launcher or doesn't work sometimes

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#260] opened 2022-10-23 12:37 UTC
### Operating System

Windows

### Version of Prism Launcher

5.0-develop

### Version of Qt

5.15.6

### Description of bug

The mod updater can randomly hang the whole launcher at some point while requesting metadata information.

### Steps to reproduce

Use the mod updater with the default options, press confirm all to create metadata for all mods which don't have it

...

See issue 

If there isn't any issue, repeat until there is

### Suspected cause

Curseforge API? Sure thing, disabling the usage of CF in the mod updater elluminates the issue.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment] 2022-10-24 03:36
In addition: since lately, even disabling any use or curseforge API doesn't help as _the mod updater can't get any metadata from Modrinth too_. Come on Prism you're better than this. An ancient instance of Packwiz I have does it better.

As in, unchecking the other mod provider option doesn't help much for me now as it literally isn't able to create or request metadata for any mods. It might be a recent chnge in develop (as I'm running the latest develop)

**Comment by ghost** [comment] 2022-10-27 14:21
can i please have any sort of bump on this because the mod updated does NOT work at all and that's NOT fine

**Comment by ghost** [comment] 2022-11-02 08:17
still true as of 5.1

**Comment by ZekeZDev** [comment] 2022-11-02 08:24
I will look into replicating this and if I can easily I will bump to high priority.

**Comment by DioEgizio** [comment] 2022-11-02 08:53
I cannot reproduce

**Comment by Scrumplex** [comment] 2022-11-02 09:03
Maybe Windows only?

**Comment by DioEgizio** [comment] 2022-11-02 11:44
Many people can't reproduce on windows either

**Comment by ToothyDev** [comment] 2022-11-02 11:47
Can't reproduce any part of the issue. Windows, both 5.0 and 5.1

**Comment by ghost** [comment] 2022-11-03 05:40
I really have no idea. I might try a fresh launcher install; it might be dependent on one's location, internet provider, etc, also note that this is on a legacy build

**Comment by ghost** [comment] 2022-11-03 16:19
https://bytebin.lucko.me/P3dHmBFR77 - Launcher log.

**Comment by ghost** [comment] 2022-11-03 16:30
seems to be a dupe of #226 .

**Comment by DioEgizio** [comment] 2022-11-03 16:39
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/226

**Closed as not planned by DioEgizio** 2022-11-03 16:39 UTC
