### ISSUE TITLE
Curseforge Launcher not detected

### ISSUE THREAD

**Issue by SantiFixes** [PrismLauncher/PrismLauncher#2172] opened 2024-02-28 21:14 UTC
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

![Screen Shot 2024-02-27 at 5 24 34 PM](https://github.com/PrismLauncher/PrismLauncher/assets/161650507/48b0bcba-90a7-4c3a-a7a5-d4bd7c76def4)

### Steps to reproduce

Put in mods like usual and then launched and the error came up

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-02-28 21:16
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2170 Also all forge versions are broken
This is a known issue and we are working on a fix so be patient

**Closed as not planned by Trial97** 2024-02-28 21:16 UTC
