### ISSUE TITLE
Ability to update to latest nightly version

### ISSUE THREAD

**Issue by maskersss** [PrismLauncher/PrismLauncher#3029] opened 2024-10-30 10:34 UTC
### Role

I use Prism.

### Suggestion

I want to be able to update to the latest nightly version within the launcher,

### Benefit

so that I can get new features from it without reinstalling Prism.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

i was thinking about having a setting to toggle between updating to the latest release and to the latest nightly version which would be on the 1st option by default ; iirc multimc used to have this before - you could choose between stable and develop?
might be a good idea to add a disclaimer about nightly versions not being stable, not sure

**Comment by Trial97** [comment] 2024-10-30 10:48
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1826

**Closed as not planned by Trial97** 2024-10-30 10:48 UTC
Labels: type: enhancement
