### ISSUE TITLE
Binary AUR versions incompatible with most recent version of the cmark package on Arch Linux

### ISSUE THREAD

**Issue by fotnite-vevo** [PrismLauncher/PrismLauncher#2087] opened 2024-02-03 00:19 UTC
### Operating System

Arch Linux

### Version of Prism Launcher

Prism Launcher 8.0 (specifically the current prismlauncher-bin and prismlauncher-qt5-bin packages)

### Version of Qt

Qt 6.6.1 and Qt 5.15.12

### Description of bug

Expectation: Prism Launcher opens window when launched

What happens: Prism Launcher gives the message: `prismlauncher: error while loading shared libraries: libcmark.so.0.30.3: cannot open shared object file: No such file or directory`, and then immediately exits

### Steps to reproduce

1) Attempt to launch prismlauncher

### Suspected cause

Binary AUR packages for Prism Launcher expect `cmark` version 0.30.3, but Arch Linux ships version 0.31.0. Either downgrading to version 0.30.3, or installing one of the source packages from the AUR instead, works around the issue. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Wyrmlet** [comment] 2024-02-03 00:26
Happens to me as well. Same error, downgrading helps for now.

**Comment by Arthurmeade12** [comment] 2024-02-03 03:14
Although this is not recommended (by ArchLinux itself), I ran ```sudo ln -s /usr/lib/libcmark.so.0.31.0 /usr/lib/libcmark.so.0.30.3``` to fix the issue. Apparently the new Cmark version works just as well. Maybe if Prism depended on ```libcmark.so``` instead of a specific version of Cmark, this issue would never arise again. ```libcmark.so``` was already linked when I went hunting in /usr/lib.

**Comment by Trial97** [comment] 2024-02-03 06:59
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/991
Same issue: the binary on the arch is broken see: https://github.com/PrismLauncher/PrismLauncher/issues/991#issuecomment-1523906002

**Closed as not planned by Trial97** 2024-02-03 06:59 UTC
Labels: status: invalid

**Comment by DioEgizio** [comment] 2024-02-03 07:08
we don't even dynamically link to libcmark on the "official" builds, that's kinda weird

**Comment by Trial97** [comment] 2024-02-03 07:11
Well it looks like if you install it fresh(or maybe even reinstall) it works as intended

**Comment by caliarch** [comment] 2024-02-03 14:23
If you installed from the aur, let's say you use paru, you delete the prismlauncher folder from the cloned cache for paru (so `~/.cache/paru/clone/prismlauncher` for prismlauncher package) and then you do a `paru -Syu prismlauncher`. That's how I got it to work, you just need to rebuild it, basically.

**Comment by DioEgizio** [comment] 2024-02-03 14:24
yeah as i thought it's not for the binary packages

**Comment by caliarch** [comment] 2024-02-03 14:31
In short, it's only prevalent for the source built packages by the user. I think this should be written somewhere so that there aren't this many people that will put issues and whatnot in the future for things like this.

**Comment by DioEgizio** [comment] 2024-02-03 14:34
this is a normal arch thing that happens with every package

**Comment by Scrumplex** [comment] 2024-02-03 15:20
You can also use `--rebuild` for paru and yay
