### ISSUE TITLE
Allow download of portable jdk and autoset the java installation to the executable on windows

### ISSUE THREAD

**Issue by s1csty9** [PrismLauncher/PrismLauncher#1346] opened 2023-07-11 17:57 UTC
### Role

I play minecraft without java installed on my system (no installation permissions allowed by my admin)

### Suggestion

I think that Prism Launcher would benefit from letting users optionally download a portable version of Java jdk and set the java installation to javaw.exe in the bin folder, which is what I do and it works perfectly.

### Benefit

This would make it easier for a lot of users to run minecraft on prism without java being already installed since there is no automated java installation. A more important reason (which I believe is what makes this necessary) is that some users do not have admin on their computers like me, so we cannot install java on our own and this would make the process of getting prism to run a lot easier.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I have the portable jdk files and also some ideas on how this would be implemented through code.  [This](https://ruintd.github.io/PrismLauncherPortable/) project appears to do something similar to what I have described, however I haven't looked too far into it.

**Comment by YoYoK3nny** [comment] 2023-07-12 12:00
While this would be useful for those using the portable zip, it is made redundant for those using the PrismLauncherPortable package that is made for the PortableApps.com Platform as that bootstrap for the app already handles this to some extent as the PortableApps.com Platform already provides a selection of portable java runtimes (including portable jdk)

The only downside of that package is that it will only use the first java runtime it finds in the portablejava search path.

**Comment by Scrumplex** [comment] 2023-07-12 13:31
Duplicate of #1021

**Closed as not planned by Scrumplex** 2023-07-12 13:31 UTC
Labels: type: enhancement
