### ISSUE TITLE
Mark mods as client or server side only locally

### ISSUE THREAD

**Issue by Rinma** [PrismLauncher/PrismLauncher#2395] opened 2024-05-11 13:39 UTC
### Role

I play modded Minecraft and host servers

### Suggestion

I want to mark mods as "client side only" or "server side only"

### Benefit

I could export mods that are only needed on the client or on the server

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Currently, I have the problem that my Server does not start anymore, because of a client-side only mod I added and exported to the zip file I use to push the mods to my server.

With the optional possibility to mark mods as client or server side only in Prismlauncher, it would be possible to create export packages for a modded server and optional client side only mods, where my friends could decide whether they want them or not.

To mark a mod, the right-click context menu could be used, maybe near the options for activate and deactivate a mod.

```
├─────────────┤
│Delete       │
│Activate     │
│Deactivate   │
│Mark as ->   │
│-Client Side │
│-Server Side │
├─────────────┤
```

![export](https://github.com/PrismLauncher/PrismLauncher/assets/1405824/4a919e12-084f-4ad3-b825-0895a3a9bf0c)
![mod-list](https://github.com/PrismLauncher/PrismLauncher/assets/1405824/3e1ca262-959a-4348-805d-97895c9ce5f1)

**Comment by Trial97** [comment] 2024-05-11 13:48
The env stuff is done in: https://github.com/PrismLauncher/PrismLauncher/issues/962 
The user grouping in: https://github.com/PrismLauncher/PrismLauncher/issues/154 or https://github.com/PrismLauncher/PrismLauncher/issues/1055 or https://github.com/PrismLauncher/PrismLauncher/issues/1076

So consider it as a duplicate of one of the mentioned issues

**Closed as not planned by Trial97** 2024-05-11 13:48 UTC
Labels: type: enhancement
