### ISSUE TITLE
Mod update lock

### ISSUE THREAD

**Issue by ColonelGerdauf** [PrismLauncher/PrismLauncher#1756] opened 2023-10-28 04:02 UTC
### Role

Often update mods from a modpack; have run into mods with unusual/reversed mod order in Modrinth.

### Suggestion

To be able to prohibit specific mods from updating beyond a certain point.

### Benefit

Ability to update unlisted mods or mods from a modpack without having to worry about mod regressions every time you press "update (all)"

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Viable use cases:
- mods that have reverted versions in a modpack for compatibility reasons
- mods that had to be manually modified to fix specific issues such as library lookups or instance/loader subversions
- mods that have an unresolved disorder in the mod listing (can sometimes happen on Modrinth)

**Comment by Trial97** [comment] 2023-10-28 06:59
This looks like a duplicate of the following two issues:
- https://github.com/PrismLauncher/PrismLauncher/issues/764
- https://github.com/PrismLauncher/PrismLauncher/issues/83
If you consider that this is a separate ticket let us know.

**Closed as completed by Trial97** 2023-10-28 06:59 UTC
Labels: type: enhancement
