### ISSUE TITLE
Arch Linux: Possible to close main launcher window whlie instance edit dialog open.

### ISSUE THREAD

**Issue by tomasz-brak** [PrismLauncher/PrismLauncher#1729] opened 2023-10-19 06:40 UTC
### Operating System

Arch Linux, KDE plasma.

### Version of Prism Launcher

7.2

### Version of Qt

5.15.11

### Description of bug

It is possible to close the main launcher window when an instance edit dialog is open. It is also possible to close the instance edit dialog when mod downloader is open.

### Steps to reproduce

1. Create an instance.
2. Open it using edit
3. Go to mods
4. Click download 
5. Close the main launcher and the instance edit view
6. Floating mod downloaded with no additional windows open.

### Suspected cause

Maybe KDE is messing something with windows. It can also be wayland

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment] 2023-10-19 06:57
This is intended behavior. Perhaps we could make the mod downloader a modal and thereby preventing the edit window from closing if its open, but I think it's useful that you can just interact with the edit window, while browsing for mods

**Closed as not planned by Scrumplex** 2023-10-19 06:57 UTC
