### ISSUE TITLE
Create Servers like with ATLauncher

### ISSUE THREAD

**Issue by HoodBlah** [PrismLauncher/PrismLauncher#3142] opened 2024-11-27 18:42 UTC
### Role

Hosting home servers

### Suggestion

Be able to create servers as easily as instances

### Benefit

It would make the server creation process but easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

ATLauncher has the option to create servers and I think that would be a good feature for Prism to have as well.

**Comment by Trial97** [comment] 2024-11-27 20:35
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/864

**Closed as not planned by Trial97** 2024-11-27 20:35 UTC
Labels: type: enhancement
