### ISSUE TITLE
Prism Launcher won't detect newly installed java binaries

### ISSUE THREAD

**Issue by An12854** [PrismLauncher/PrismLauncher#1326] opened 2023-07-07 20:57 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.1 from flathub

### Version of Qt

Qt 5.15.10

### Description of bug

PrismLauncher won't detect openjdk11 but recognizes openjdk 8 and 17, even after a reinstallation of openjdk11 and PrismLauncher itself (it detects java 11 if i install prismlauncher-git from AUR)

### Steps to reproduce

*Open terminal
*Install openjdk11 (in my case `sudo pacman -S openjdk11-src`)
*Open PrismLauncher
*Try to auto-detect java versions

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by getchoo** [comment] 2023-07-08 00:15
seems like a duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/905. as dio said there, flatpak does not have access to these paths. you will need to give it access to the filesystem using flatseal or plasma settings

**Closed as not planned** 2023-07-08 00:15 UTC
