### ISSUE TITLE
Mod updater not giving correct output when trying to update a single disabled mod. 

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#1697] opened 2023-10-09 02:01 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt version 6.5.1

### Description of bug

When attempting to check a mod for updates that is currently disabled, the mod updater will close and simply give a message that the mod updater aborted. 
However, when selecting multiple mods where some are activated and some are not, it properly gives a popup stating "Deactivated mods will not be updated (to prevent duplicate versions)" . 

### Steps to reproduce

Check a deactivated mod for updates

### Suspected cause

There should be a dialogue added for the other cases (single mod selected but deactivated). 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-10-09 06:41
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1469

**Closed as not planned by Trial97** 2023-10-09 06:41 UTC
