### ISSUE TITLE
Binary .log file hangs launcher for long time when edit window is opened

### ISSUE THREAD

**Issue by Fourmisain** [PrismLauncher/PrismLauncher#2582] opened 2024-06-28 13:26 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

I ran into this when using [ViaFabricPlus](https://modrinth.com/mod/viafabricplus):
When launching the game and opening the edit instance window, it'll hang the whole launcher for 20-30 seconds on my system.
Clicking the "Other logs" tab will hang it again, showing it defaults to loading a file like `000008.log` in `.minecraft\config\viafabricplus\ViaLoader\viabedrock\blob_cache`:
![example](https://github.com/PrismLauncher/PrismLauncher/assets/8464472/1bb65554-c26c-4568-80b9-f37b591321f4)

This file is apparently cleared out when Minecraft is exited, but while it is running, it'll be a 1MiB file of mostly null bytes by default.

Switching between any regular log file and the binary one hangs the launcher every time.

The "Other logs" Clean button will also delete this binary file, which it probably shouldn't.

### Steps to reproduce

1. create a new fabric 1.21 instance
2. install [ViaFabricPlus](https://modrinth.com/mod/viafabricplus)
3. launch the instance
4. while it is running, edit the instance - this will hang PrismLauncher for ~20s
5. click "Other logs" - this will hang PrismLauncher again for ~20s

### Suspected cause

I think there are multiple issues here:
 - Qt seems _extremely_ slow when inserting/displaying binary data in a text component (vaguely related to #309)
 - The edit window seems to "preload" the "Other logs" tab, even though we're not looking at it (and it'll reload when clicked anyway)  
    _This alone seems like a big performance detriment even for regular logs, since it can process the the current running log twice_
 - "Other logs" defaults to the first log in the list, which by current sorting (or file traversal?) order makes it prioritize logs in the `config` folder above logs in the `logs` folder

Potential fixes:
 - Blacklist all logs from `.minecraft\config\viafabricplus\ViaLoader\viabedrock\blob_cache`
 - Detect and ignore binary log files (e.g. by trying to decode them, then doing a [git-like check](https://stackoverflow.com/questions/6119956/how-to-determine-if-git-handles-a-file-as-binary-or-as-text/6134127#6134127) if there's still a null character)
 - Filter null characters (and other non-displayable characters) before inserting/displaying them may prevent Qt from hanging/lagging so much
 - Ask ViaFabricPlus to change the file extension

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-06-28 13:35
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/485 or https://github.com/PrismLauncher/PrismLauncher/issues/1450

**Closed as not planned by Trial97** 2024-06-28 13:35 UTC

**Comment by Fourmisain** [comment] 2024-06-28 14:26
Dang, I thought I searched through everything, sorry about that.
