### ISSUE TITLE
Ability to use include/exclude lists when exporting modpacks

### ISSUE THREAD

**Issue by Blue-Beaker** [PrismLauncher/PrismLauncher#2871] opened 2024-09-30 03:22 UTC
### Role

I make modpack

### Suggestion

Load include/exclude list when exporting modpacks

### Benefit

So I wont need to check needed files every time I export.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I want a feature to import a predefined include/exclude list when exporting modpacks, so I don't need to check/uncheck needed/unneeded files manually every time I export the modpack.  
The include/exclude list defines what file to include, and what file not to include in the modpack. So I can just create the list and load it every time I need to export and publish the modpack.  
The pattern of the list file will be similar to a `.gitignore` file: https://git-scm.com/docs/gitignore#_pattern_format  
For example, when I want to exclude optifine, and include crafttweaker scripts, I write the list as below:  
```
/mods/Optifine*.jar
!/scripts
```

**Comment by Trial97** [comment] 2024-10-02 05:58
Use packwiz.
Also duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2516

**Closed as not planned by Trial97** 2024-10-02 05:58 UTC
Labels: type: enhancement

**Comment by Blue-Beaker** [comment] 2024-10-04 12:15
> Use packwiz. Also duplicate of #2516

Packwiz is crashing on my modpack instance, because I have symlinks for the backups folder.
Maybe I should write my own pack exporter. Or write a script to copy only the included files to make a instance for export, and export that instead.
