### ISSUE TITLE
Ability to use GitHub Releases to auto-update mods not released to Modrinth/CurseForge

### ISSUE THREAD

**Issue by TheMuffinPony** [PrismLauncher/PrismLauncher#3233] opened 2024-12-22 20:08 UTC
### Role

I use Prism Launcher to manage many 'utility' mods (Litematica, Carpet, ...).

### Suggestion

I want Prism to auto-update some mods from GitHub releases.

### Benefit

I'm lazy, have a few GitHub-only mods, and want them to auto-update too.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

## Background

One of the main reasons I got Prism launcher (from MultiMC) is that it can handle auto-updating mods... but it only supports mods from Modrinth and CurseForge.  I use mods from GitHub too!

The most notable GitHub mods are masa's mods (Litematica, MiniHUD, Malilib, etc.) that are now maintained by Sakura Ryoko (with permission from masa).  She uploads releases weekly only to GitHub (and not Modrinth/Curseforge), which is totally fine except that I'm lazy and want the auto updater.

## Solution

My proposed solution is to add GitHub as a mod provider, similar to Modrinth and CurseForge.  Instead of searching for mods, though, people would have to specify the URL directly (e.g. `sakura-ryoko/litematica`).  Metadata would have to be specified somewhere, e.g. somewhere in the repository, within Prism itself (for a few select known-good mods), or manually by the user.

## Concerns
I can see a few issues with this:
1. People could be compromised, since GitHub releases aren't checked at all (unlike Modrinth or CurseForge).
2. Hacks and other morally dubious mods released on GitHub will be easier to download and update.
3. It isn't straightforward how mods should be updated, since GitHub wasn't designed specifically for Minecraft mod distribution.
4. It will be a lot of effort for Prism to maintain.

I think all of these can be (mostly) fixed by requiring users to write their own regular expressions to extract metadata from the releases: people who can write them usually know what they are doing (so they won't get viruses), aren't more likely to hack with this feature, and are willing to tinker, putting the onus on them rather than Prism.

## Obtaining metadata and finding the file to download

> [!WARNING]
> Yapping alert!  This section is technical and goes on.  It describes how I envision this system working with examples of a simple and a complex repository.  You probably don't need to read this unless you are a developer or want to know whether this system is feasible or not.

Most releases are automatically named as `modname-version.jar` when built and releases usually are titled with the version of the mod; what's tricky is finding the version(s) of the game the mod is built for and, for some mods, finding which file to download (as there are multiple versions, e.g. Forge and Fabric releases).  Using regular expressions, though, these can be extracted, and the name of the file to download can be generated based on what the regex extracts.

### Simple example: Litematica (Sakura Ryoko)

[Litematica](https://github.com/sakura-ryoko/litematica) is a popular mod where the latest versions aren't offered on Modrinth or CurseForge.  Each release, such as the latest one [1.21.4-0.21.0-sakura.9](https://github.com/sakura-ryoko/litematica/releases/tag/1.21.4-0.21.0-sakura.9), only contains one file (plus the source code files GitHub adds).  The file is named following the format `litematica-fabric-[mod version].jar`.  Since the mod version is literally in the title, it would be easy to do a simple string substitution to find the file to download.  Prism could also just download the only file it sees, and warn the user if there are multiple.

### Tricky example: Baritone

[Baritone](https://github.com/cabaletta/baritone) comes to mind as an example of a tricky repository: each release has a myriad of files, but at least they are consistently named.  Consider the latest release as of writing, [v1.11.1](https://github.com/cabaletta/baritone/releases/tag/v1.11.1).

As Fabric user, I need the Fabric standalone version, which follows the naming convention `baritone-standalone-fabric-[mod_version].jar` (where `[mod_version]` is the version of the mod, e.g. `1.11.1`).

The version of the mod is always specified in the title as, e.g. `v1.11.1` (note the extra `v`).  Using a regular expression, we can yeet the v to pull out just the version number.  The game version is a bit more tricky, since that's added manually to the description, which looks like this:
> For Minecraft 1.21.3 only. Forge IS supported. Fabric IS supported. NeoForge IS supported.

Since this format is usually consistent (with the occasional multi-version release), it wouldn't be too hard to write a regular expression to match potentially multiple versions: `(?<=^For\s+(?:Minecraft|1\.\d+\.\d+|and|\s|,)*)1\.\d+\.\d+`.  Just as with Litematica, the game version (1.21.3) isn't needed to download the file, but Prism can use it to know whether there's a version of the mod available for the game without downloading it first.

As with Litematica, the version string can be combined with a template string (e.g. `baritone-standalone-fabric-$1.jar`, where `$1` represents the mod version) to find the file to download.

**Comment by Trial97** [comment] 2024-12-22 20:30
> ![image](https://github.com/user-attachments/assets/e119d4de-a62c-4d67-aca9-996b3be76068)

No this is not unique, duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1155

**Closed as not planned by Trial97** 2024-12-22 20:30 UTC
Labels: type: enhancement
