### ISSUE TITLE
crash on loading curseforge modpack from zip

### ISSUE THREAD

**Issue by gmodmurderserver** [PrismLauncher/PrismLauncher#621] opened 2022-12-15 01:34 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.0

### Version of Qt

Qt 6.4.0

### Description of bug

when you load from zip it waits a couple of seconds before crashing.

it shouldn't do that.

### Steps to reproduce

make a curseforge modpack zip, import it, crash.

### Suspected cause

it looks like right after loading the included texture packs it crashes. but it might be more than that.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LawsOfScience** [comment] 2022-12-15 05:34
I am also having this issue, except the crash is nearly instantaneous after clicking "Ok" once the zip is selected.
Running a 2020 MacBook Pro on macOS Ventura 13.0.1
I'm happy to supply error logs if told where to look.

EDIT: I tried this on PolyMC and found this error, so maybe something similar is happening in this launcher as well?
<img width="413" alt="image" src="https://user-images.githubusercontent.com/24637919/207781158-21e7595d-97d3-48f7-bffd-17ccf332a631.png">

**Comment by flowln** [comment] 2022-12-15 12:46
Duplicate of #609

**Closed as not planned by flowln** 2022-12-15 12:46 UTC
