### ISSUE TITLE
Sort instances

### ISSUE THREAD

**Issue by lynrayy** [PrismLauncher/PrismLauncher#1663] opened 2023-09-29 03:47 UTC
### Role

-

### Suggestion

-

### Benefit

-

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Please allow to manually sort instances in the list

**Comment by TheKodeToad** [comment] 2023-09-29 10:06
If you're not going to use a template you may as well open a blank issue xd

**Comment by Trial97** [comment] 2023-09-29 10:09
And also it looks like this is not easily achievable: https://github.com/PrismLauncher/PrismLauncher/pull/30#issuecomment-1287411591

**Comment by TheKodeToad** [comment] 2023-09-29 10:15
Sorting the groups shouldn't be too hard though and would be nice

**Comment by lynrayy** [comment] 2023-09-29 11:21
_If you're not going to use a template you may as well open a blank issue xd_

I don't really know what is ROLE and BENEFIT fields and don't want to think about it reading description. The only thing what template needs - auto title with [SUGGESTION] preffix

**Comment by lynrayy** [comment] 2023-09-29 11:22
I didn’t think that there were so many unnecessary fields that I need to think about, but I don’t want to cancel the action

**Comment by Trial97** [comment] 2023-11-22 06:54
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/688

**Closed as not planned by Trial97** 2023-11-22 06:54 UTC
Labels: type: enhancement
