### ISSUE TITLE
Quick Setup window opens on every start

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#3191] opened 2024-12-11 16:53 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.8.1

### Description of bug

Quick Setup should only be shown on first start. However, every time you restart the launcher, Quick Setup opens, asking you to configure Java.

### Steps to reproduce

Install Prism and restart it multiple times.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-12-11 17:11
Fixed in nightly it will be a thing in 9.2.
Also, this is a duplicate of a closed issue.

**Closed as completed by Trial97** 2024-12-11 17:11 UTC
