### ISSUE TITLE
Importing a modrinth modpack changes certain character in file names within modpack

### ISSUE THREAD

**Issue by andrwcrr** [PrismLauncher/PrismLauncher#2487] opened 2024-06-09 00:30 UTC
### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt version 6.6.3

### Description of bug

When importing a modrinth modpack into Prism Launcher, any files with a `+` in their name will have it changed to a `-`. This is incorrect because when importing modpacks with preconfigured mods (and in my case a shader), the mod/shader will not be able to recognise its respective config file due to a name change and the intended configurations will not be applied.

### Steps to reproduce

* Make a modrinth modpack
* Include a file containing a `+` in its file name
* Import the modpack into Prism
* Notice the `+` has now changed to a `-`

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by andrwcrr** [comment] 2024-06-09 00:31
This may not be specific to modrinth modpacks, it's just that I haven't tested any other modpack types. I also forgot to specify that I am on Windows 11.

**Comment by Trial97** [comment] 2024-06-09 13:08
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2455
Also fixed in https://github.com/PrismLauncher/PrismLauncher/pull/2425

**Closed as not planned by Trial97** 2024-06-09 13:08 UTC
