### ISSUE TITLE
PreLaunch Commands on import are broken

### ISSUE THREAD

**Issue by Merith-TK** [PrismLauncher/PrismLauncher#1144] opened 2023-06-09 17:59 UTC
### Operating System

Windows

### Version of Prism Launcher

7.0

### Version of Qt

6.5.1

### Description of bug

All instances (pre-existing and newly imported) with an PreLaunchCommand in their Instance.CFG, are broken

https://mclo.gs/WIv3YMz

### Steps to reproduce

Have a PrelaunchCommand that relies upon  Quoted variables, 

Break

Here is an (verified correct) instance.cfg modpack I have had for a *while*
[vanillia-multimc.zip](https://github.com/PrismLauncher/PrismLauncher/files/11708949/vanillia-multimc.zip)

### Suspected cause

Unknown, suspected possible changes in `instance.cfg` configurations?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by getchoo** [comment] 2023-06-09 22:50
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1134

**Closed as not planned** 2023-06-09 23:09 UTC

**Comment by Merith-TK** [comment] 2023-06-10 00:14
***how in the name of the gods was this an duplicate of?! I fekking SEARCHED WTF***

**Comment by Ryex** [comment] 2023-06-10 03:18
it happens. no worries.
