### ISSUE TITLE
Installing a Modpack from Modrinth doesn't track the provider for included mods

### ISSUE THREAD

**Issue by LunaticWasTaken** [PrismLauncher/PrismLauncher#1921] opened 2023-12-06 06:37 UTC
### Operating System

Windows 11 64bit

### Version of Prism Launcher

8.0 from latest GH Action

### Version of Qt

6.6.0

### Description of bug

Whenever i download a modpack from modrinth, all the installed mods won't have a tracked provider.

This leads to the issue that whenever you download another mod with dependencies (notably fabric-api) it will always re-download a duplicate of fabric-api, even tho it's already installed.

### Steps to reproduce

- Download a Modpack
- Install a Modpack (i only tried modrinth, cuz i hate curseforge with a passion)
- Install a new mod to the pack, often leads to duplicate dependencies

### Suspected cause

When download a modpack, i assume the instance doesn't receive a provider for all the included mods.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-12-06 06:50
Duplicate of #1730

**Closed as not planned by Trial97** 2023-12-06 06:50 UTC
