### ISSUE TITLE
Prismlauncher Flatpak/COPR package: Java 8 java.lang.NullPointerException

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#1681] opened 2023-10-04 18:05 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.2 (Flatpak and COPR package) on Fedora 38

### Version of Qt

Qt 5.15.10

### Description of bug

JDK 8 (and JRE 8) seem to have a problem when switching between servers (e.g. minigame servers) in a server network (e.g. Hypixel, GommeHD). The issue occurs when running an instance that requires java 8 on the prismlauncher flatpak or COPR package, which are both relevant for fedora linux. When switching between these servers, the game didn't crash, but it takes at least five seconds for the warps to complete.

When i started investigating the long warp times, i found an error repeatedly scrambling my minecraft log, as seen in the bug reproduction steps. Since it looks like a java error, this could also affect other players using the flatpak or COPR package. I wonder if other users could also encounter this problem.

### Steps to reproduce

1. Create an instance running 1.8.9 with or without forge (and mods)
2. Start instance, join a minecraft server like gommehd.net or hypixel.net
3. Enter a minigame on the server
4.1 See minecraft taking like 5+ seconds to warp into the minigame server
4.2 Watch the minecraft log spamming the following FATAL error (if anyone even wants to investigate):

[20:03:47] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_372]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_372]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.scoreboard.Scoreboard.func_96511_d(SourceFile:229) ~[auo.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147247_a(NetHandlerPlayClient.java:1813) ~[bcy.class:?]
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:113) ~[hr.class:?]
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:13) ~[hr.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_372]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_372]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 12 more

### Suspected cause

The problem's probably caused by java 8 (i tried both jre and jdk, but obviously it didn't make a difference). But since i used the flatpak, java was already bundled.

I checked the java vendor, which turned out to be Oracle Corporation. That means the pre-installed java on fedora, shipped by red hat, couldn't interfere. I also checked out the native prismlauncher rpm (the COPR package which also includes all java versions required), but it didn't work either.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-10-04 18:15
Can this be reproduced using the original Minecraft launcher?
Regarding the Minecraft logs, we appreciate if you use a paste service like https://mclo.gs/ (are more easier to read there).

**Comment by ghost** [comment] 2023-10-04 18:19
sorry. Here's a more human-readable version. hope this helps
![issue](https://github.com/PrismLauncher/PrismLauncher/assets/137926343/b1085e46-d44a-4709-87e7-24ff8bfb78a1)

**Comment by Trial97** [comment] 2023-10-04 18:22
Also please note that this is most probably an issue with java or the servers you are trying to connect. As from what you describe the game launches and doesn't crash. 
A better place to ask about this is on Discord: https://discord.gg/ArX2nafFz2

**Comment by ghost** [comment] 2023-10-04 18:33
Surely you're right about the fact that it isn't the prismlauncher's issue. But since java is shipped within these specific prismlauncher packages, what else could i possibly do? (On java 17 everything worked, so the problem can't be the servers)

Yeah thanks for reviewing this anyway

**Comment by Trial97** [comment] 2023-10-04 21:00
If Java 17 works then use that.
Also from the code we should already ship the flatpak version with either both java 8 and java 17 or just one of them(I'm not a flatpak expert).
And the reason why I sent you to discord is because the community there is more active and can help you better with this kind of stuff.
As the solution was found, I will close this issue.

**Closed as completed by Trial97** 2023-10-04 21:00 UTC

**Comment by BBernYY** [comment] 2024-12-13 19:45
This is exactly what I'm experiencing right now, hypixel serverswaps are logging said error (including on vanilla minecraft laucher launches) when using java 8.

As you mentioned, this issue is resolved when using java 17. Is it possible to fix the issue in 1.8.9? (either by using a newer version of java in 1.8.9 or by solving the issue alltogether)

This is the only instance of the problem I have found online, any help would be greatly appreciated!
