### ISSUE TITLE
Error transferring https://user.auth.xboxlive.com/user/authenticate

### ISSUE THREAD

**Issue by HyperProxy** [PrismLauncher/PrismLauncher#2065] opened 2024-01-24 18:30 UTC
### Operating System

macOS 13.4.1

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6

### Description of bug

Expected Result: Account added to accounts menu in Prism Launcher
What happened: After entering my Microsoft account password and approving Prism's authentication with Microsoft, Prism account adding fails with error : `XBox user authentication failed: Error transferring https://user.auth.xboxlive.com/user/authenticate - server replied: Forbidden`

### Steps to reproduce

- Install Prism Launcher
- Settings -> Accounts -> Add Microsoft
- Follow prompts

### Suspected cause

I believe that there is an error in the request sent FROM Prism TO Microsoft's Xbox user authentication service. The Microsoft server checker reports authentication and login to be online, and the 405 or Forbidden response means that the type of request sent to the server is not accepted by the service.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-01-24 18:45
I'm able to login fine in prism: so this is most probably Microsoft server fault or is a duplicate of one of many auth issues: https://github.com/PrismLauncher/PrismLauncher/issues?q=is%3Aissue+is%3Aopen+label%3AAuth+label%3Abug

**Closed as not planned by Trial97** 2024-01-24 18:45 UTC
Labels: area: auth
