### ISSUE TITLE
Allow using git(hub) as mod provider

### ISSUE THREAD

**Issue by 500-internal-server-error** [PrismLauncher/PrismLauncher#2593] opened 2024-06-30 10:19 UTC
### Role

Normal player

### Suggestion

Add git(hub) as a mod provider

### Benefit

Some mods do not get updated officially but have forks by a third party that are updated

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It would be a useful stopgap solution while waiting for the mod to be updated by the original developer - I find myself doing this every so often. Basically a temporary source override. Example: [litematica](https://www.curseforge.com/minecraft/mc-mods/litematica) (source [here](https://github.com/maruohon/litematica/tree/pre-rewrite/fabric/1.20.x)) is still on 1.20.6, but has an updated fork to 1.21 [here](https://github.com/sakura-ryoko/litematica/tree/pre-rewrite/fabric/1.21) in the form of github releases. Other times the mod is simple enough for me to do the updating myself, resulting in a git repo on disk, though perhaps that may be a bit too hard to support.

**Comment by Trial97** [comment] 2024-06-30 10:23
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1155

**Closed as not planned by Trial97** 2024-06-30 10:23 UTC
Labels: type: enhancement
