### ISSUE TITLE
enable deep link to folders option as per M*ltiMC

### ISSUE THREAD

**Issue by MattHardwick34** [PrismLauncher/PrismLauncher#2340] opened 2024-04-24 17:24 UTC
### Role

Player, Server Op

### Suggestion

upstream app has deep links to config, screenshot folders etc. - enable these with option in settings

### Benefit

for people who are constantly in and out of the minecraft folders/config etc. it saves a lot of time

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/36822930/1db57adb-7868-4baa-bafc-79b76e960d09)
vs
![image](https://github.com/PrismLauncher/PrismLauncher/assets/36822930/bfbb9c48-40d8-4bd9-abfe-ef8be10cf28f)
I appreciate these buttons aren't for everyone so if we could have an option in the settings to enable this, configure, customise, or even just a on/off for the old way that would be lovely! thank you

**Comment by Trial97** [comment] 2024-04-24 17:34
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/248

There is requesting just bringing back the mods folder but it can be extended.

**Closed as not planned by Trial97** 2024-04-24 17:34 UTC
Labels: type: enhancement
