### ISSUE TITLE
Mod List Headers Unable To Be Resized (Except Image)

### ISSUE THREAD

**Issue by IdrisQe** [PrismLauncher/PrismLauncher#1893] opened 2023-11-25 03:32 UTC
### Operating System

Windows

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

The Mod List is bugged out since I updated to 8.0, with the Names section being too small to see anything but the first letter, and only the Image section can be resized, making it impossible to fix.
![gif](https://github.com/PrismLauncher/PrismLauncher/assets/40530630/e688b9dc-da84-4c9c-a298-a17b7b72fb0e)

The Image Section also keeps reverting to its default very-long size every time the mods list is opened.

### Steps to reproduce

1. Check Mods List
2. Try to resize any section aside from Image

### Suspected cause

I'm guessing something got messed up when the Image section was being added?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-11-25 06:46
fixed in: https://github.com/PrismLauncher/PrismLauncher/pull/1849
and duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1778

**Closed as not planned by Trial97** 2023-11-25 06:46 UTC

**Comment by IdrisQe** [comment] 2023-11-27 23:20
Apologies, I tried to find a relevant bug but couldn't, didn't realize there was one already. Github's weird searching fails me again. Glad it's getting fixed though.
