### ISSUE TITLE
Prism Launcher Crashing when try to install a Modpack

### ISSUE THREAD

**Issue by louanfontenele** [PrismLauncher/PrismLauncher#1299] opened 2023-07-02 15:51 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

When I try to install a modpack, the client simply closes and does not complete the installation.

### Steps to reproduce

Add new instance. search for https://www.curseforge.com/minecraft/modpacks/medieval-mc-forge-mmc3, install.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment] 2023-07-02 21:00
Can't reproduce
can you provide the PrismLauncher-0.log form the attempt to install?

**Comment by louanfontenele** [comment] 2023-07-02 22:23
> Can't reproduce can you provide the PrismLauncher-0.log form the attempt to install?

How can i see this?

**Comment by Ryex** [comment] 2023-07-03 05:03
> > Can't reproduce can you provide the PrismLauncher-0.log form the attempt to install?
> 
> How can i see this?

it's in your data folder next to where prism stores your instances

> Where Prism Launcher stores your data (e.g. instances).
**Portable (Windows / Linux)**
In the PrismLauncher folder
**Windows**
%APPDATA%/PrismLauncher
**Scoop**
%HOMEPATH%\scoop\persist\prismlauncher
**macOS**
~/Library/Application Support/PrismLauncher
**Linux**
~/.local/share/PrismLauncher
**Flatpak**
~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher

**Comment by louanfontenele** [comment] 2023-07-03 12:13
Windows 11
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/11936647/PrismLauncher-0.log)
[PrismLauncher-1.log](https://github.com/PrismLauncher/PrismLauncher/files/11936648/PrismLauncher-1.log)
[PrismLauncher-2.log](https://github.com/PrismLauncher/PrismLauncher/files/11936649/PrismLauncher-2.log)
[PrismLauncher-3.log](https://github.com/PrismLauncher/PrismLauncher/files/11936651/PrismLauncher-3.log)
[PrismLauncher-4.log](https://github.com/PrismLauncher/PrismLauncher/files/11936652/PrismLauncher-4.log)

**Comment by louanfontenele** [comment] 2023-07-03 13:18
> > > Can't reproduce can you provide the PrismLauncher-0.log form the attempt to install?
> > 
> > 
> > How can i see this?
> 
> it's in your data folder next to where prism stores your instances
> 
> > Where Prism Launcher stores your data (e.g. instances).
> > **Portable (Windows / Linux)**
> > In the PrismLauncher folder
> > **Windows**
> > %APPDATA%/PrismLauncher
> > **Scoop**
> > %HOMEPATH%\scoop\persist\prismlauncher
> > **macOS**
> > ~/Library/Application Support/PrismLauncher
> > **Linux**
> > ~/.local/share/PrismLauncher
> > **Flatpak**
> > ~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher

Windows 11 
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/11937170/PrismLauncher-0.log)

**Comment by Ryex** [comment] 2023-07-03 16:30
interesting. it's crashing during or just after the mod resolution process

**Comment by louanfontenele** [comment] 2023-07-03 16:32
> interesting. it's crashing during or just after the mod resolution process

During

**Comment by louanfontenele** [comment] 2023-07-03 18:16
> interesting. it's crashing during or just after the mod resolution process

See this video.
https://github.com/PrismLauncher/PrismLauncher/assets/2886066/7b6c1c07-92b5-491b-92e1-647a4d202a2e

**Comment by Trial97** [comment] 2023-07-03 18:26
I know this may be a stretch on my part but can you test this on a nightly build:https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/5445237186
As this may be already fixed(I hope)

**Comment by IThundxr** [comment] 2023-07-03 18:27
related to: https://discord.com/channels/1031648380885147709/1031823065937629267/1125262542571323462?

**Comment by Ryex** [comment] 2023-07-03 20:46
> I know this may be a stretch on my part but can you test this on a nightly build:https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/5445237186 As this may be already fixed(I hope)

sadly I don't think it is.
I've had people reproducing it on nightlys even though I can't

> related to: https://discord.com/channels/1031648380885147709/1031823065937629267/1125262542571323462?

yep. same issue

I think we need to add address sanitizer to our debug builds to help debug this.

**Comment by IThundxr** [comment] 2023-07-03 21:05
> > I know this may be a stretch on my part but can you test this on a nightly build:https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/5445237186 As this may be already fixed(I hope)
> 
> 
> 
> sadly I don't think it is.
> 
> I've had people reproducing it on nightlys even though I can't
> 
> 
> 
> > related to: https://discord.com/channels/1031648380885147709/1031823065937629267/1125262542571323462?
> 
> 
> 
> yep. same issue
> 
> 
> 
> I think we need to add address sanitizer to our debug builds to help debug this.

try {} catch {} :think:

**Comment by louanfontenele** [comment] 2023-07-06 16:41
no way to fix? :(

**Comment by Ryex** [comment] 2023-07-06 18:19
if you can try to replicate the crash while running a a nightly from this branch
https://github.com/PrismLauncher/PrismLauncher/actions/runs/5478067456?pr=1306
we may be able to get better logs and trace the issue.
The catch is that you  will need to run the build from the terminal so that you can catch the Address Sanitiser logs

**Comment by Ryex** [comment] 2023-07-08 21:43
Still cant duplicate.

If anyone can try to replicate this on latest develop that would be great.

**Comment by louanfontenele** [comment] 2023-07-08 22:37
Sorry, I had to format the computer, and go back to Windows 10. I can try now in Windows 10 to see if the problem was in Windows 11 or if it really is an application problem.

**Comment by Ryex** [comment] 2023-07-08 22:51
> Sorry, I had to format the computer, and go back to Windows 10. I can try now in Windows 10 to see if the problem was in Windows 11 or if it really is an application problem.

no worries. I don't think it was a windows 11 issue. it _may_ have been related to #1302 though

**Comment by ScreamErimas** [comment] 2023-07-09 16:57
Same problem here

**Comment by Tenrys** [comment] 2023-07-09 22:57
This is also happening for me, on Windows 11

https://github.com/PrismLauncher/PrismLauncher/actions/runs/5501955210

This build doesn't seem to crash though.

**Comment by echthesia** [comment] 2023-07-10 06:46
Nightly builds do not appear to be crashing. Builds 2173, 2174, and 2181 I know work, and judging by Tenrys's comment seemingly everything later does. That both 2173 and 2174 work seems to imply that it's not #1302, since 2174 was the first build to include that fix. It seems to have been fixed _somewhere_ along the line, though.

**Comment by Carterpersall** [comment] 2023-07-10 13:27
I was able to replicate the issue by downloading the portable build and trying to import AoF6 from a zip

After some troubleshooting, I was able to track the issue to some point in the range [`f24211...ce2d58b`](https://github.com/PrismLauncher/PrismLauncher/compare/f24211e8b5d9af24ac3e27b0fdb50000a962c35f...ce2d58bb7d7e99da61b906253c0fea7815a82862#diff-38f4cfa244b5a3c395962484edc073d5e5e28f48a730d4591d6c4d4a67c5618a)

The last thing the log shows in the debug build is `Resolve slug progress`([PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/12002392/PrismLauncher-0.log)), which leads to https://github.com/PrismLauncher/PrismLauncher/blob/ce2d58bb7d7e99da61b906253c0fea7815a82862/launcher/modplatform/flame/FileResolvingTask.cpp at line 52, 120, and 198

**Comment by Spirevipp** [comment] 2023-07-11 13:28
i had the same issue.
first i downloaded a 1.20 pack, no issues.
then attempting to download some 1.19 packs, it crashes.

i then removed any manually downloaded mods in Downloads folder and it now works fine.
might there be some bug when checking for manual download mods?

**Comment by Zyrille** [comment] 2023-07-11 18:23
I have the same issue. I'm unable to download any modpacks (tested in 1.19.2 by downloading AOF6, and 1.20 by downloading ATM9). Both would just close the client without any crash logs or crash notification/popup etc. Running windows 11, tested on two different machines. Same issue. I also tried importing AOF6 as a zip instead of getting it from cursforge via the launcher, but it still did the same thing.

**Comment by Ryex** [comment] 2023-07-12 16:50
> I was able to replicate the issue by downloading the portable build and trying to import AoF6 from a zip
> 
> After some troubleshooting, I was able to track the issue to some point in the range [`f24211...ce2d58b`](https://github.com/PrismLauncher/PrismLauncher/compare/f24211e8b5d9af24ac3e27b0fdb50000a962c35f...ce2d58bb7d7e99da61b906253c0fea7815a82862#diff-38f4cfa244b5a3c395962484edc073d5e5e28f48a730d4591d6c4d4a67c5618a)
> 
> The last thing the log shows in the debug build is `Resolve slug progress`([PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/12002392/PrismLauncher-0.log)), which leads to https://github.com/PrismLauncher/PrismLauncher/blob/ce2d58bb7d7e99da61b906253c0fea7815a82862/launcher/modplatform/flame/FileResolvingTask.cpp at line 52, 120, and 198

Thank you for your effort. Were you able to replicate on the latest develop?

**Comment by Carterpersall** [comment] 2023-07-12 17:29
> > I was able to replicate the issue by downloading the portable build and trying to import AoF6 from a zip
> > After some troubleshooting, I was able to track the issue to some point in the range [`f24211...ce2d58b`](https://github.com/PrismLauncher/PrismLauncher/compare/f24211e8b5d9af24ac3e27b0fdb50000a962c35f...ce2d58bb7d7e99da61b906253c0fea7815a82862#diff-38f4cfa244b5a3c395962484edc073d5e5e28f48a730d4591d6c4d4a67c5618a)
> > The last thing the log shows in the debug build is `Resolve slug progress`([PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/12002392/PrismLauncher-0.log)), which leads to [`ce2d58b`/launcher/modplatform/flame/FileResolvingTask.cpp](https://github.com/PrismLauncher/PrismLauncher/blob/ce2d58bb7d7e99da61b906253c0fea7815a82862/launcher/modplatform/flame/FileResolvingTask.cpp) at line 52, 120, and 198
> 
> Thank you for your effort. Were you able to replicate on the latest develop?

I was not able to replicate using the #2227 build from GitHub Actions

**Comment by Trial97** [comment] 2024-01-15 15:09
Hi, can you please try to reproduce this using the latest nightly builds: https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop

**Comment by Trial97** [comment] 2024-04-04 07:01
@louanfontenele  does this still happen in 8.2?

**Comment by willmorong** [comment] 2024-04-08 01:51
> @louanfontenele does this still happen in 8.2?

Happens for me in 8.2, segfaults on NixOS when importing a Curseforge modpack zip from my friend running Windows

**Comment by Trial97** [comment] 2024-04-08 09:22
@willmorong  are you using the import from zip function?

**Comment by willmorong** [comment] 2024-04-08 19:57
> @willmorong are you using the import from zip function?

yes

**Comment by Trial97** [comment] 2024-04-08 20:11
Then that's a different issue: please open a new ticket where you post the logs and if you can the archive

**Comment by Trial97** [comment] 2024-05-12 20:26
Closing this as there were no updates.
If you still experience this in that latest version please feel free to reopen this.

**Closed as completed by Trial97** 2024-05-12 20:26 UTC
Labels: status: not enough info
