### ISSUE TITLE
The "System" theme doesn't switch between dark and light on Windows 11.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [PrismLauncher/PrismLauncher#2920] opened 2024-10-15 22:28 UTC
### Operating System

Windows

### Version of Prism Launcher

https://github.com/PrismLauncher/PrismLauncher/releases/tag/8.4

### Version of Qt

6.6.3

### Description of bug

When I switch to the dark theme via Settings, Prism doesn't reflect this. https://github.com/PrismLauncher/PrismLauncher/issues/237#issuecomment-1288022118 corroborates this.

### Steps to reproduce

1.	```PS1
	winget install --id 'PrismLauncher.PrismLauncher'
	```
1.	Change from "System" to "Dark" to see what it should be set to.

### Suspected cause

I've not much idea. I generally use Fedora 40 with KDE Plasma 6.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-10-16 05:37
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/362

**Closed as not planned by Trial97** 2024-10-16 05:37 UTC
