### ISSUE TITLE
Change the modpack updater to be triggered from the "Version" tab instead of by creating a new instance

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#261] opened 2022-10-23 12:47 UTC
### Role

I use the launcher.

### Suggestion

I want the launcher not to offer one to update an existing instance when a modpack is downloaded and instead add a button to update an instance from a modpack in instance options.

### Benefit

Because the current modpack updater is: 
- annoying 
- does not specify the instance(-es?!) it wants to update 
- can't even be disabled for some reason 
- for whatever reason pressing X on the popup counts as "update the existing instance, i totally do not want to abort the operation" 

This change would make it so the updater is only ever triggered willfully by the user + is beter communicated to them.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment] 2022-10-23 12:50
https://github.com/PrismLauncher/PrismLauncher/pull/32

we'll prob remove the existing one once that is ready, i agree it's not very good rn

**Comment by TayouVR** [comment] 2022-10-23 12:57
imo the existing one can stay, can still be useful. if e.g. someone forgets, that they already have a modpack, being asked to update isn't too bad of a thing to have.

**Comment by ghost** [comment] 2022-10-23 13:00
> imo the existing one can stay, can still be useful. if e.g. someone forgets, that they already have a modpack, being asked to update isn't too bad of a thing to have.

yes but it'd be annoying in more cases and redundant if a way to properly update a modpack via the instance menu is implemented

**Comment by Scrumplex** [comment] 2022-11-27 22:43
Duplicate of #180. Will be implemented in #32

**Closed as not planned by Scrumplex** 2022-11-27 22:43 UTC
Labels: type: enhancement

**Comment by ghost** [comment] 2023-03-12 11:12
( @Scrumplex the obsolete updater dialogue is still around as of latest develop)
