### ISSUE TITLE
Have support for lost/missing versions of Minecraft

### ISSUE THREAD

**Issue by RowanSkie** [PrismLauncher/PrismLauncher#169] opened 2022-10-20 11:49 UTC
### Role

Better support for lost versions of Minecraft

### Suggestion

An upgraded meta server to support these versions

### Benefit

Ability to download versions that have been missing

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This issue is closer to https://github.com/PolyMC/PolyMC/issues/481, https://github.com/PolyMC/PolyMC/issues/681, and derivatives.

This is also similar to #77 which is more akin to https://github.com/PolyMC/PolyMC/issues/603 that is also related to above issues.

**Comment by Scrumplex** [comment] 2022-11-27 22:28
Duplicate of #101

**Closed as not planned by Scrumplex** 2022-11-27 22:28 UTC
Labels: type: enhancement
