### ISSUE TITLE
Multiple crashing issues.

### ISSUE THREAD

**Issue by MagmaSlime123** [PrismLauncher/PrismLauncher#1153] opened 2023-06-11 03:50 UTC
### Operating System

Windows

### Version of Prism Launcher

7.0.

### Version of Qt

Qt isn't mentioned, but here you go anyway.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/51277766/04f02f1b-b524-4c60-a819-0c28c482dbf8)

### Description of bug

Scrolling up/down in the mod downloader fast
Having lots of stuff selected
Downloading lots of mods
Right-clicking to edit an instance

All will sometimes crash the launcher.

### Steps to reproduce

Do any of the above.

### Suspected cause

Unknown.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment] 2023-06-11 04:43
Duplicate of #1138 #863

**Closed as completed by Ryex** 2023-06-11 04:43 UTC
