### ISSUE TITLE
Could not rename the overrides folder: overrides when installing a modpack

### ISSUE THREAD

**Issue by Endrock6** [PrismLauncher/PrismLauncher#1629] opened 2023-09-16 08:03 UTC
### Operating System

Windows

### Version of Prism Launcher

7.2

### Version of Qt

6.5.1

### Description of bug

Whenever I try to install any modpack with Prism launcher I get the same error over and over, no matter whether I have opened it with admin or not. The error is shown in the screenshot below. On some rare occasions, it has worked and have been able to install a modpack. But that has only been 4 out of nearly 100 attempts. Just to be specific this issue only affects the installation of mod packs from 3rd party sources and importing from files.
![image_2023-09-16_155559558](https://github.com/PrismLauncher/PrismLauncher/assets/101973300/1ec1e2d6-d6d4-4cca-b56a-aa78d18fed82)

### Steps to reproduce

- Launch Prism launcher 7.2
- Click Add Instance
- import a modpack or install one from a 3rd party source
- wait for the error to appear

### Suspected cause

I only have suspicions on what the issue might be because I'm no specialist at this but I suspect It might possibly be that Prism launcher doesn't have permission to rename files on my computer.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-09-16 15:06
As you guessed the issue is that Prism doesn't have permissions.
Please make sure that Prism can write/read files in the Prism root folder and instances folder.

**Comment by Endrock6** [comment] 2023-09-19 00:32
Well I'm not sure how to change or see those permissions. But from the properties of the exe all sections said full access.

**Comment by Trial97** [comment] 2023-09-19 13:20
The exe is normal to have those permissions (you would not be able to run it otherwise).
What you need to check is the permission for the instances and root folder.
The error occurs when the process can not create files in the mentioned folders.
The permissions are not specific to one executable but are specific to the user that runs the executable.
You can try to open instances folder and then see if you can create a file there.

**Comment by Trial97** [comment] 2023-10-04 21:08
Are there any updates on this issue?
Can we close this as completed?

**Comment by Endrock6** [comment] 2023-10-05 04:26
Yes I do have an update. I have been on a holiday for the past week so I have not had an opportunity to update this issue but before my holiday I did find that the entire prism launcher folder was read only. I have not had time to test if it has been fixed but I will in the next few days.

**Comment by bhavithnYT** [comment] 2023-10-15 08:34
this happens to me to and i was using prism launcher 6.3. i updated to 7.2 and it is still a issue i tried changing the folder from read only to the normal setting but nothing worked

**Comment by bhavithnYT** [comment] 2023-10-15 09:56
i found a similar tread
https://github.com/MultiMC/Launcher/issues/2199

**Comment by bhavithnYT** [comment] 2023-10-15 10:05
ITS THE ANTI VIRUS

**Comment by P3rf3ctXZer0** [comment] 2023-11-02 21:59
This is not the antivirus per se but a specific module. If you have the ability to disable ``scan memory processes`` you can also get by. I never recommend none power users disable system wide protection. I have seen the havoc a skilled virus or worse actual hacker can do to a network. 

The issue is the way prism is handling temp files in windows. As I believe prism was ``originally Linux Centric.`` Some habits such as keeping ``temps anywhere`` upset windows 11 and at least ``most antiviruses.``

This is why failure only occurs when ``importing`` not exporting.

**Comment by Endrock6** [comment] 2023-11-23 10:19
I have finally got it working. In the end, it was my antivirus that was causing the issue. But the only way for it to work is to end the entire process of my antivirus (not just disabling it in the app) and then I could install modpacks again. Thank you everyone for helping me solve this.

**Comment by Trial97** [comment] 2023-11-23 10:21
I will reopen it as I already found a solution for it and have a PR for it

**Comment by moosetwin0** [comment] 2024-02-14 10:41
I also had this issue, I solved it by taking ownership of the files (both .exe folder and the Roaming/PrismLauncher folder), unsetting read only, and running the executable with admin permissions.

**Closed as completed** 2024-06-06 21:11 UTC
Labels: platform: Windows
