### ISSUE TITLE
Invalid Session login when using PrismLauncher

### ISSUE THREAD

**Issue by OatmealRaisins** [PrismLauncher/PrismLauncher#2010] opened 2024-01-05 15:00 UTC
### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

QT 6.6.0

### Description of bug

When joining a server, I would often get an error stating "Failed to log in, Invalid Session(Try restarting your game and your launcher)

This would happen to any instance of minecraft I created in the Prism Launcher, modded or unmodded. 
Upon booting up the official Minecraft launcher instead, everything worked fine, with no issues joining servers.
The only fix I found was to restart my computer, for which the launcher would temporarily fix itself. Issue reappears if I close and then reopen the launcher)

### Steps to reproduce

Launch an instance
Once minecraft has opened, click multiplayer and try to join any server

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-01-05 20:59
Can you post your Minecraft logs?

**Comment by OatmealRaisins** [comment] 2024-01-06 00:07
> Can you post your Minecraft logs?

My bad, here's the text-

[17:46:43] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.3
[17:46:44] [main/INFO]: Loading 96 mods:
	- appleskin 2.5.1+mc1.20.3
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.92.0+1.20.4
	   |-- fabric-api-base 0.4.35+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.45+78d798af4f
	   |-- fabric-biome-api-v1 13.0.15+78d798af4f
	   |-- fabric-block-api-v1 1.0.14+78d798af4f
	   |-- fabric-block-view-api-v2 1.0.3+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.45+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.6+78d798af4f
	   |-- fabric-command-api-v1 1.2.40+f71b366f4f
	   |-- fabric-command-api-v2 2.2.19+78d798af4f
	   |-- fabric-commands-v0 0.2.57+df3654b34f
	   |-- fabric-containers-v0 0.1.81+df3654b34f
	   |-- fabric-content-registries-v0 5.0.9+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.9+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.22+78d798af4f
	   |-- fabric-data-generation-api-v1 13.1.17+78d798af4f
	   |-- fabric-dimensions-v1 2.1.60+78d798af4f
	   |-- fabric-entity-events-v1 1.5.28+4ced05924f
	   |-- fabric-events-interaction-v0 0.7.0+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.71+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.45+78d798af4f
	   |-- fabric-item-api-v1 2.1.34+78d798af4f
	   |-- fabric-item-group-api-v1 4.0.20+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.40+78d798af4f
	   |-- fabric-keybindings-v0 0.2.38+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.2.29+78d798af4f
	   |-- fabric-loot-api-v2 2.1.4+78d798af4f
	   |-- fabric-message-api-v1 6.0.4+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.59+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.7+78d798af4f
	   |-- fabric-models-v0 0.4.6+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.2+78d798af4f
	   |-- fabric-object-builder-api-v1 13.0.8+06274a474f
	   |-- fabric-particles-v1 1.1.6+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.15+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.13+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.3+78d798af4f
	   |-- fabric-renderer-indigo 1.5.3+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.50+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.41+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.32+78d798af4f
	   |-- fabric-rendering-v0 1.1.53+df3654b34f
	   |-- fabric-rendering-v1 3.0.12+78d798af4f
	   |-- fabric-resource-conditions-api-v1 2.3.13+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.15+78d798af4f
	   |-- fabric-screen-api-v1 2.0.16+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.50+78d798af4f
	   |-- fabric-sound-api-v1 1.0.16+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.6+78d798af4f
	   \-- fabric-transitive-access-wideners-v1 5.0.13+78d798af4f
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- fallingleaves 1.15.4
	- gammautils 1.7.18
	- iris 1.6.14
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- litematica 0.17.0
	- make_bubbles_pop 0.2.0-fabric
	- malilib 0.18.0
	- minecraft 1.20.4
	- modmenu 9.0.0
	- shulkerboxtooltip 4.0.7+1.20.2
	- sodium 0.5.5
	- xaerominimap 23.9.6
	- xaeroworldmap 1.37.6
	- yet_another_config_lib_v3 3.3.1+1.20.4
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- zoomify 2.12.0
	   |-- com_akuleshov7_ktoml-core-jvm 0.5.0
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6
[17:46:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/N%20/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:46:44] [main/INFO]: Compatibility level set to JAVA_17
[17:46:44] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[17:46:45] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:46:45] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:46:45] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:46:45] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:46:45] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[17:46:45] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[17:46:45] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[17:46:45] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[17:46:45] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[17:46:45] [main/INFO]: Searching for graphics cards...
[17:46:46] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce RTX 2070 SUPER, version=DriverVersion=31.0.15.4584]
[17:46:46] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[17:46:46] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[17:46:46] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[17:46:51] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 148 milliseconds
[17:46:54] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[17:46:54] [Render thread/INFO]: Setting user: goldminecraft111
[17:46:54] [Render thread/INFO]: Make Bubbles Pop by Tschipcraft initialized!
[17:46:54] [Render thread/INFO]: [ShulkerBoxTooltip] Could not find configuration file, creating default file
[17:46:54] [Download-2/ERROR]: Failed to fetch user properties
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:150) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_310.method_55608(class_310.java:467) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121) ~[authlib-6.0.52.jar:?]
	... 5 more
[17:46:54] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[17:46:55] [Worker-Main-1/INFO]: Checking mod updates...
[17:46:55] [Render thread/INFO]: Loading Xaero's Minimap - Stage 1/2
[17:46:56] [Render thread/INFO]: Loading Xaero's World Map - Stage 1/2
[17:46:56] [Worker-Main-1/INFO]: Update available for 'fabric-api@0.92.0+1.20.4', (-> 0.92.1+1.20.4)
[17:46:57] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[17:46:57] [Render thread/WARN]: Applying workaround: Prevent the NVIDIA OpenGL driver from using broken optimizations (NVIDIA_THREADED_OPTIMIZATIONS)
[17:46:58] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[17:46:58] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
[17:46:58] [Render thread/INFO]: OpenGL Version: 3.2.0 NVIDIA 545.84
[17:46:58] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] This version doesn't have an update index, skipping.
[17:46:58] [Render thread/INFO]: Debug functionality is disabled.
[17:46:58] [Render thread/INFO]: ARB_direct_state_access detected, enabling DSA.
[17:46:58] [Render thread/INFO]: Shaders are disabled because enableShaders is set to false in iris.properties
[17:46:58] [Render thread/INFO]: Shaders are disabled
[17:46:58] [Render thread/INFO]: Hardware information:
[17:46:58] [Render thread/INFO]: CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
[17:46:58] [Render thread/INFO]: GPU: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 545.84)
[17:46:58] [Render thread/INFO]: OS: Windows 10 (10.0)
[17:46:59] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (appleskin, cloth-config, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, gammautils, iris, litematica, make_bubbles_pop, malilib, modmenu, shulkerboxtooltip, sodium, xaerominimap, xaeroworldmap, yet_another_config_lib_v3, zoomify), file/Xray_Ultimate_1.20.2_v5.0.0.zip
[17:46:59] [Worker-Main-2/ERROR]: Failed to retrieve profile key pair
com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.post(MinecraftClient.java:65) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.getKeyPair(YggdrasilUserApiService.java:61) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_7434.method_43605(class_7434.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_7434.method_44291(class_7434.java:79) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[17:46:59] [Worker-Main-2/WARN]: Invalid path in datapack: sandwichable:models/item/tomato_slice - Copy.json, ignoring
[17:46:59] [Worker-Main-6/INFO]: Found unifont_all_no_pua-15.1.04.hex, loading
[17:46:59] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_equip1.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[17:46:59] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_equip1.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[17:46:59] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_equip2.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[17:46:59] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_equip2.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[17:46:59] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_unequip1.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_unequip
[17:46:59] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_unequip2.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_unequip
[17:46:59] [Render thread/INFO]: Loading Xaero's World Map - Stage 2/2
[17:46:59] [Render thread/INFO]: New world map region cache hash code: 1538208889
[17:46:59] [Render thread/INFO]: Registered player tracker system: map_synced
[17:46:59] [Render thread/INFO]: Xaero's WorldMap Mod: Xaero's minimap found!
[17:46:59] [Render thread/INFO]: Registered player tracker system: minimap_synced
[17:46:59] [Render thread/INFO]: No Optifine!
[17:46:59] [Render thread/INFO]: Xaero's World Map: No Vivecraft!
[17:46:59] [Render thread/INFO]: Xaero's World Map: Iris found!
[17:46:59] [Render thread/INFO]: Loading Xaero's Minimap - Stage 2/2
[17:47:00] [Render thread/INFO]: Registered player tracker system: minimap_synced
[17:47:00] [Render thread/INFO]: Xaero's Minimap: World Map found!
[17:47:00] [Render thread/INFO]: No Optifine!
[17:47:00] [Render thread/INFO]: Xaero's Minimap: No Vivecraft!
[17:47:00] [Render thread/INFO]: Xaero's Minimap: Iris found!
[17:47:01] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[17:47:01] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[17:47:01] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[17:47:01] [Render thread/INFO]: Sound engine started
[17:47:01] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[17:47:01] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[17:47:01] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17:47:01] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17:47:01] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[17:47:01] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17:47:01] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[17:47:01] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17:47:01] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:47:01] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[17:47:01] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[17:47:01] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:47:01] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:47:01] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[17:47:01] [Render thread/INFO]: Successfully reloaded the minimap shaders!
[17:47:01] [Render thread/INFO]: Successfully reloaded the world map shaders!
[17:47:01] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[17:47:02] [IO-Worker-1/INFO]: Could not authorize you against Realms server: Invalid session id
[17:47:02] [IO-Worker-1/ERROR]: Couldn't connect to realms
net.minecraft.class_4355: Realms authentication error with message 'Invalid session id'
	at net.minecraft.class_4341.method_20998(class_4341.java:447) ~[client-intermediary.jar:?]
	at net.minecraft.class_4341.method_21027(class_4341.java:232) ~[client-intermediary.jar:?]
	at net.minecraft.class_8647.method_52627(class_8647.java:45) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Trial97** [comment] 2024-01-07 10:45
Next time please use mclo.gs to upload your crash(preferably using the upload button from prism).
Also from what I see you are using a modpack, make sure that the server uses the same mod pack version as you.

>`Could not authorize you against Realms server: Invalid session id`

Are you trying to access realms with a moded instance?

**Comment by OatmealRaisins** [comment] 2024-01-07 15:16
> Next time please use mclo.gs to upload your crash(preferably using the upload button from prism). Also from what I see you are using a modpack, make sure that the server uses the same mod pack version as you.
> 
> > `Could not authorize you against Realms server: Invalid session id`
> 
> Are you trying to access realms with a moded instance?

Not realms specifically, just any multiplayer server. Though even with the vanilla instances, I still get the same error prompt when I try to join...

**Comment by Trial97** [comment] 2024-01-07 20:57
Can you upload the logs from a Vanila instance, where you try to connect to a server? or join a realm?

**Comment by OatmealRaisins** [comment] 2024-01-08 14:15
> Can you upload the logs from a Vanila instance, where you try to connect to a server? or join a realm?

Alright, one sec-
I loaded in a clean 1.20.4 instance, and tried joining Hypixel.net with it.
https://mclo.gs/LYy68w0

**Comment by Trial97** [comment] 2024-01-08 14:24
> Can you upload the logs from a Vanila instance, where you try to connect to a server? or join a realm?

I meant the full log.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/cc52ba36-cea2-4dce-abaa-3306d71bbb68)

**Comment by OatmealRaisins** [comment] 2024-01-08 22:28
> > Can you upload the logs from a Vanila instance, where you try to connect to a server? or join a realm?
> 
> I meant the full log. ![image](https://private-user-images.githubusercontent.com/42720688/294931889-cc52ba36-cea2-4dce-abaa-3306d71bbb68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NTMyMDksIm5iZiI6MTcwNDc1MjkwOSwicGF0aCI6Ii80MjcyMDY4OC8yOTQ5MzE4ODktY2M1MmJhMzYtY2VhMi00ZGNlLWFiYWEtMzMwNmQ3MWJiYjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDIyMjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMmE3OGIyZTUxMDRmNzQ5MDMxNGVmYWNmN2IyMDQyZjE1NDU3ZmIxMjc1NDllNDQyNGRhY2M3MDFkMTBkNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ggzOgPTCAt7skZIsvNGQ_gQ0Uvu7jQqpXwHilJ0kJ7Q)

Apologies, here it is https://mclo.gs/KVfGzgH

**Comment by Trial97** [comment] 2024-01-09 06:48
> Apologies, here it is https://mclo.gs/KVfGzgH

Looks like you are starting the game using an offline account.
Try removing all offline accounts from prism(leaving only the Microsoft one that owns minecraft -"MSA") and do not launch the instance in offline mode.
If that doesn't work, send the prism logs(they differ from Minecraft ones).
They are located inside the prism data root directory inside the logs folder. There should be multiple files that are numbered from 0 to 4(0 means the most recent).
So once it reproduces please upload the file `PrismLauncher-0.log` to a Pastebin service like mclo.gs but make sure you check for personal data (replace the data with a placeholder and do not delete entire rows please).

**Comment by Trial97** [comment] 2024-02-03 07:07
Closing this as there was no more info provided.

**Closed as not planned by Trial97** 2024-02-03 07:07 UTC
Labels: area: auth, status: not enough info

**Comment by AndreyKrasnov06** [comment] 2024-02-24 15:56
the problem is still there! If a player with an offline account opens the world to the network, then it will be possible to join him through any other launcher (for example Tlauncher), but not through prism launcher with an offline account, there are no problems with the license, but there should not be any without it, because that the host does not have it and it works through other launchers.

**Comment by PATAPOsha** [comment] 2025-01-12 18:43
Same for me using Prism Launcher 10.0 on two computers in same local network. Using offline accounts.
Works in TLauncher, but no in Prism. Should re-opened.

**Comment by soulja4l** [comment] 2025-01-27 01:27
My friends can only join my worlds opened to the Internet through https://e4mc.link installed on Prism Launcher through the Fabulously optimized modpack when they are on another launcher different to Prism Launcher even using the same modpack or not as me.
PD: Both of us are using offline accounts.

**Comment by Cosmoros-git** [comment] 2025-03-16 19:56
[2025-03-16-1.log.gz](https://github.com/user-attachments/files/19274643/2025-03-16-1.log.gz)

Would like to add to the thread. I get the same issue with the account when playing a modpack. I am self-hosting locally. 

I tend to play it for a while and then leave the server. on trying to rejoin, it gets an invalid session, even tho I was just on the server on the same session.

**Comment by sleyv** [comment] 2025-09-09 22:40
just use mods where host can disable online mode, like "LAN World Plug-n-Play" mod

**Comment by nlienard** [comment] 2025-12-31 10:00
same issue, it is sad that only Prism have this issue. with MultiMC, offline mode works good.
Why can't it be fixed ?
thanks

**Comment by taimasthedog** [comment] 2026-02-10 21:39
As sleyv mentioned, we also installed "LAN World Plug-n-Play (mcwifipnp)" mod to the host, and others could enter with offline accounts. No need to install the mod to everyone, just the host. Just make sure to disable online mode when opening the LAN world.

**Comment by americanexplorer13** [comment] 2026-06-04 13:29
The problem is still here. I have win11 and MacOS PCs. When I try to connect via LAN from MacOS (offline account) to win11 (same microsoft account but online) it says: "Failed to log in, Invalid Session(Try restarting your game and your launcher)". I don't have this problem using MultiMC.

**Comment by mymirai-nikki** [comment] 2026-06-10 09:24
why playing offline in LAN requires microsoft account?

**Comment by AndreyKrasnov06** [comment] 2026-06-10 10:33
> why playing offline in LAN requires microsoft account?

Stop using prism launcher and download normal freesm launcher. At least they listen to their users.

**Comment by aetriusgx** [comment] 2026-06-23 04:50
Got this issue today. Was disappointing since I just bought Minecraft for my partner :\
