### ISSUE TITLE
"Working..." Unable to authorize and play Minecraft

### ISSUE THREAD

**Issue by wereretot** [PrismLauncher/PrismLauncher#1888] opened 2023-11-22 22:05 UTC
### Operating System

Linux

### Version of Prism Launcher

8.0 and 8.0-develop installed via AUR

### Version of Qt

6.6.0

### Description of bug

Launched prismlauncher to encounter the offline bug then logged out then tried to log back in only to be stuck at "working..."

### Steps to reproduce

1. Launch prismlauncher
2. Log out
3. Log back in
4. Working...

### Suspected cause

I've recently moved physical locations, maybe something with the network change broken it because I cannot login into the normal minecraft launcher either.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by wereretot** [comment] 2023-11-23 05:04
![Screenshot_20231123_000358](https://github.com/PrismLauncher/PrismLauncher/assets/28990565/09c43433-3850-4307-9001-b8a0f08be9fa)

**Comment by wereretot** [comment] 2023-11-24 04:10
27.582 D | AuthFlow: "Logging in with Microsoft account."
    27.582 D | DeviceFlow::link
    27.582 D | DeviceFlow::setLinked: false
    27.582 D | [katabasis.credentials]: new refresh token: ""
    27.647 D | DeviceFlow::onDeviceAuthReplyFinished
    30.783 D | [launcher.task.net.metacache.http]: Saving metacache with 20 entries

**Comment by deviantsemicolon** [comment] 2023-11-24 13:01
Also facing issues with authorization. Authorization just outright fails after doing the microsoft.com/link thing. It could be a network issue because I also moved physical locations(went home for Thanksgiving break)

**Comment by wereretot** [comment] 2023-11-25 00:07
> Also facing issues with authorization. Authorization just outright fails after doing the microsoft.com/link thing. It could be a network issue because I also moved physical locations(went home for Thanksgiving break)

Same, I went home and then no more Minecraft

**Comment by Trial97** [comment] 2023-11-25 06:52
looks like a duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1429 or https://github.com/PrismLauncher/PrismLauncher/issues/1031. 
You can try the following suggestions: https://github.com/PrismLauncher/PrismLauncher/issues/1875#issuecomment-1826238656 .

**Closed as not planned by Trial97** 2023-11-25 06:52 UTC
Labels: area: auth

**Comment by wereretot** [comment] 2023-11-25 07:53
> looks like a duplicate of: #1429 or #1031. You can try the following suggestions: [#1875 (comment)](https://github.com/PrismLauncher/PrismLauncher/issues/1875#issuecomment-1826238656) .

None of these helped, what do I do?

**Comment by Trial97** [comment] 2023-11-25 07:56
If not even the portable version did not work then please upload your logs in one of the mentioned issues and let's continue this there.

**Comment by embermctillhawk** [comment] 2023-12-05 01:57
Coming in a little late for this but I had identical issues and had to delete my Minecraft account from Prism and re-grant Prism authorization on the Microsoft end of things.

Based on the fact that multiple other people are also reporting this, wonder if maybe Microsoft dropped something and all affected persons will have to give Prism permission again? Might not be a Prism issue at all.
