### ISSUE TITLE
Modpacks imported from a downloaded mrpack file cannot be updated

### ISSUE THREAD

**Issue by Rakned** [PrismLauncher/PrismLauncher#2741] opened 2024-08-21 21:25 UTC
### Goal

Allow modpacks imported from a mrpack file (or other methods) to have their mods updated with a new modlist file, rather than requiring a new instance to be created just for a pack update.

### Motivation

I am playing on a custom mod pack with some friends of mine, on a private server hosted by the pack's creator.  Every so often, the mod pack gets updated, updating some mods, and occasionally adding new mods or removing old mods that are no longer useful or necessary.  Unfortunately, every time this happens, I must manually replace all the updated mods in my installation, or set up an entirely new instance and lose all my saved EMI recipes, map markers, etc.  I don't like either of those options!

### Specification

A new feature would be added that would allow instances installed through a downloaded file (for me, in the .mrpack format) to be themselves updated through the use of an updated distribution file.

### Drawbacks

Right now, the only potential drawback I can see is the amount of work it might take to implement.

### Unresolved Questions

How much work would this take to implement?

### Alternatives Considered

I don't really see any alternatives beyond "change the thing" and "don't change the thing, encourage people to import updating packs in different ways (or not at all) instead."

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Rakned** [comment] 2024-08-21 21:35
Update: Apparently a newly imported pack in 8.4 has the option to update from a file, but a pack previously imported in Prism Launcher 7.0 does not.  Maybe this should've been a bug report?  IDK

**Comment by Kationor** [comment] 2024-08-21 21:38
I don't remember how 7.0 works, but it most likely simply didn't include the metadata that tells Prism that this is a modpack instance, so there isn't much future versions can do.

**Comment by Trial97** [comment] 2024-08-22 05:13
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1394
And yes if the pack was not created from a curseforge/modrinth pack file that option it will not appear as it misses the metadata stuff to tell what files are managed by the pack.
No is not a bug: just recreate the pack on the newer version of prism.

**Closed as not planned by Trial97** 2024-08-22 05:13 UTC
Labels: status: needs discussion
