### ISSUE TITLE
Mrpack export has download field with spaces in the URL

### ISSUE THREAD

**Issue by pythongirl325** [PrismLauncher/PrismLauncher#1386] opened 2023-07-17 06:59 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

When exporting an instance in Modrinth pack format the download fields in the Modrinth manifest should not contain unescaped spaces. (according to the [Modrinth modpack format definition](https://docs.modrinth.com/docs/modpacks/format_definition/#downloads))

The resulting .mrpack file cannot be uploaded to modrinth as a result of this issue.

### Steps to reproduce

Create a new instance using Minecraft version 1.18.2 and Forge version 40.2.0. Edit the instance and download the the "Psi" mod (version 1.18.2-98) through the "Download Mods" interface. Next, Export the instance in .mrpack format and the resulting mrpack will have the download URL with a space in it. 

I have attached my exported .mrpack for comparison.
[modpack 1.18.2.mrpack.zip](https://github.com/PrismLauncher/PrismLauncher/files/12066721/modpack.1.18.2.mrpack.zip)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment] 2023-07-17 07:04
Duplicate of #1226 which is already patched and will be in the next release

**Closed as not planned by Ryex** 2023-07-17 07:04 UTC
Labels: status: duplicate
