### ISSUE TITLE
Modrinth  Texture pack downloader

### ISSUE THREAD

**Issue by elchupe123** [PrismLauncher/PrismLauncher#188] opened 2022-10-20 21:46 UTC
### Role

I play minecraft in general

### Suggestion

I want a texture pack downloader inside the luncher like the mod downloader, we can use modritnh texturepack library 

### Benefit

This would make easier to download texturepack 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment] 2022-10-20 21:51
Duplicate of  #153

**Closed as not planned by flowln** 2022-10-20 21:51 UTC
Labels: status: duplicate, type: enhancement
