### ISSUE TITLE
Custom Modpack Sources/Server

### ISSUE THREAD

**Issue by DoctorApparatus** [PrismLauncher/PrismLauncher#2071] opened 2024-01-26 10:41 UTC
### Role

I make modpacks

### Suggestion

It would be really useful to be able to create own modpack sources

### Benefit

Not being locked behind modrinth/curseforge

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

So my idea was, that it would be extremely useful to be able to set custom sources for modpacks. What I mean is:
Let's say I have a webserver and I upload my modpacks there because some things aren't on modrinth or curseforge and so the whole packaging from them doesn't work anymore.

By being able to set for example https://example.com/modpacks/awesome_modpack/versions/ (the zip format is the prismlauncher zip file) in the modpacks config as a provider/source, inside the prism launcher could be checked if a new version is available.

Maybe even instead of relying on some arbitrary versioning system a "versions.json" could be placed on the server, which for exampe has values like "latest" or "beta" or whatever, which get's downloaded, then the currently installed version of the modpack gets checked against it and then a update popup or something like that could open informing the player "hey time to update"

**Comment by Trial97** [comment] 2024-01-26 11:44
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/101 or https://github.com/PrismLauncher/PrismLauncher/issues/1984

**Closed as not planned** 2024-01-26 11:44 UTC
Labels: type: enhancement
