### ISSUE TITLE
Make forge instances recognize fabric mods

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#2544] opened 2024-06-20 20:40 UTC
### Role

I play Forgefied fabric

### Suggestion

The search bar and the updater recognize mods from both Fabric and Forge.

### Benefit

It's a bit annoying to manually look for and update Fabric mods when the launcher doesnt recognize them.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-06-20 20:48
it should already be there 
and this is a duplicate of [search for the issue]

**Closed as not planned by Trial97** 2024-06-20 20:48 UTC
Labels: type: enhancement

**Comment by TayouVR** [comment] 2024-06-20 21:21
also in the (hopefully soon to be released) 9.0 you will have filters that can overwrite the mod loader, which prism launcher selects by default.

The updater is still a bit difficult though.
