### ISSUE TITLE
Prism Launcher cannot connect to the internet

### ISSUE THREAD

**Issue by HowDidYouKillMe** [PrismLauncher/PrismLauncher#2413] opened 2024-05-18 15:18 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

QT 6.6.3

### Description of bug

When trying to start up any instance, I get a "Choose your offline mode player name" prompt, and my account is marked offline in the accounts section. I have tried uninstalling and reinstalling, trying the portable version, refreshing account, etc. But they all ended up not working.
This error would happen to any instances, regardless if vanilla or modded, on any version
The main minecraft launcher works fine, and I can login to servers without issue.
 I found a similar connection problem also when running forge on curseforge, as it would not allow me to log onto servers or realms also. Could it be related?

### Steps to reproduce

launch Prism launcher, and then open an instance. 

### Suspected cause

It might be something with the firewall..? Though I have checked, and nothing I could find was blocked.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-05-18 15:20
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-05-18 15:20 UTC
