### ISSUE TITLE
Add support for managing and running minecraft java servers

### ISSUE THREAD

**Issue by renhiyama** [PrismLauncher/PrismLauncher#2022] opened 2024-01-10 08:52 UTC
### Role

Not every gamer wants to run terminals to run a modded server with their friends

### Suggestion

I have seen the auto mod updater and adding mods from modrinth been a breeze. So supporting the same for a server sounds great! Also we can then run server and client straight away from the launcher itself.

### Benefit

Easy to manage mods for server side too. Non-technical players can run server on their own PCs too.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-01-10 08:54
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/864

**Closed as not planned by Trial97** 2024-01-10 08:54 UTC
Labels: type: enhancement
