### ISSUE TITLE
crash on adding instance from curseforge (gets stuck on "Fixing permissions for extracted pack files..." and crashes)

### ISSUE THREAD

**Issue by MoritzHinterleitner** [PrismLauncher/PrismLauncher#637] opened 2022-12-17 15:57 UTC
### Version of Prism Launcher

6.0

### Version of Qt

6.4.0

### Description of bug

should add it but crashes (i opened it from cmd and the last line it said was "19.369 D Fixing permissions for extracted pack files..."

### Steps to reproduce

open the add instance menu and add any instance from an exported curseforge profile

### Suspected cause

error fixing permissions for the files?

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment] 2022-12-17 15:57
importing from zip is broken on 6.0, already fixed on develop

**Comment by DioEgizio** [comment] 2022-12-17 15:58
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/609

**Comment by markmus123098** [comment] 2022-12-17 15:58
wow this was fast thank you :) is it just another branch?

**Closed as not planned by DioEgizio** 2022-12-17 15:58 UTC
