### ISSUE TITLE
Concerns regarding Contributor Covenant Code of Conduct

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#19] opened 2022-10-18 09:54 UTC
### Goal

To raise concerns regarding the Contributor Covenant Code of Conduct.

### Motivation

The Contributor Covenant has been explicitly stated by its creator Coraline Ada Ehmke to be political. ([tweet](https://mobile.twitter.com/coralineada/status/1041465346656530432)) She has also tried to remove a core contributor of Opal from the project based on some of his controversial opinions. (opal/opal#941, opal/opal#942) The current Code of Conduct can be used to push an agenda, such as [post-meritocracy](https://postmeritocracy.org/).

&#x200B;
Terms such as
> - The use of sexualized language or imagery, and sexual attention or advances of any kind

and

> - Public or private harassment

can leave some room for interpretation (e.g. using 'he' as a pronoun, or using 'dongle' can be interpreted as sexual language: 'he' is associated with the male sex, and 'dongle' might be used as a euphemism for the male genitalia), and bias can be introduced into the enforcement of the Code of Conduct.

> - Community leaders have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, and will communicate reasons for moderation decisions when appropriate.

This would mean that code is not only accepted/rejected based on the quality of the code, but the opinions of the person who submitted the code (not agreeing with this CoC would be 'not aligned to this Code of Conduct', if I'm not mistaken). While it is a matter of personal opinion whether this is beneficial or not, I believe it should be brought up, if the community is not aware.

### Proposal

Remove 'CODE_OF_CONDUCT.md'.

### Drawbacks of Proposal

Without a Code of Conduct, people may feel unwelcome to contribute to the project. While people can feel unwelcome for any reason, including having a code of conduct or not, no code of conduct may lead to toxicity in the community.

### Unresolved Questions

What are the stances that Prism Community members hold towards the Contributor Covenant, and codes of conduct in general?

### Alternatives Considered

I understand that a code of conduct is beneficial to keeping a community healthy. I would like to propose [Opal's Code of Conduct](https://github.com/opal/opal/blob/master/CONDUCT.md) as a replacement: 

- It requires that the participant be tolerant of opposing views
- It requires that participants' language be without personal attacks and disparaging personal attacks
- It requires that participants assume good intentions when interpreting the words and actions of others
- Does not tolerate behaviour that can be _reasonably_ considered harassment.

The Code of Conduct is not explicitly politically charged, and, in my opinion, will lead to a more open community.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### Further Elaboration

>inb4 paradox of tolerance

Popper does not support the suppression of uttering intolerant philosophies itself so long as it can be countered by rational argument and kept in check with public opinion; he claims in the name of tolerance the right not to tolerate the intolerant should they begin to denounce all argument, and meet arguments with violence. Arguably in the current state of politics online it's a shouting match on both sides, but as far as I know if there are any incidents of violence they are extremely rare and likely actions of radicalised individuals acting on their own.

I do not stand for PolyMC's creator nuking all contributors for the sake of 'owning the leftoids', but I personally do not agree on having a Code of Conduct - it is of my opinion that even if politics is not avoidable we should not be actively bringing it into a block game launcher. An alternative has been proposed regardless.

### Edits
I would also like to mention that the scope of the Contributor Covenant has been expanded to target said Opal core contributor ([opal 817321e](https://github.com/opal/opal/pull/948/commits/817321e27eccfffb3841f663815c17eecb8ef061#diff-a1ee87dafebc22cbd96979f1b2b7e837R11), opal/opal#948). The Contributor Covenant can potentially be used as a weapon against people who do not agree with the politics of the creators.

Changed 'overtly' to 'explicitly' in the "Alternatives Considered" section as I felt that word was more apt.

**Comment by JoakimThorsen** [comment] 2022-10-18 10:14
Using someone's preferred pronouns is not sexual language. It is simply addressing someone the way they wish to be addressed, which usually algins with that persons gender identity, something that is not equivalent to sexuality, and is definitely not inherently sexual in nature.

**Comment by SplendidAlakey** [comment] 2022-10-18 10:16
> can leave some room for interpretation (e.g. using 'he' as a pronoun, or using 'dongle' can be interpreted as sexual language: 'he' is associated with the male sex, and 'dongle' might be used as a euphemism for the male genitalia)

That's one hell of a stretch to try and make your point. And if you had to go that far, I feel like you just don't have any real concerns.

> This would mean that code is not only accepted/rejected based on the quality of the code, but the opinions of the person who submitted the code (not agreeing with this CoC would be 'not aligned to this Code of Conduct', if I'm not mistaken)

I personally don't want bigots having any presence at all. You could invite the best coder in the world to contribute to the project, and if they turned out to be a bigot I'd want them kicked out.

> While people can feel unwelcome for any reason, including having a code of conduct

If someone feels unwelcome because a CoC tells them they can't just use the F-word in a community Discord, then, well.. they are unwelcome.

> It requires that the participant be tolerant of opposing views

That's the very first point of an alternative CoC you suggested and it's already inherently flawed. You simply can't tolerate intolerance, period. And yes, I've read your further comment on that.

> The Contributor Covenant can potentially be used as a weapon against people who do not agree with the politics of the creators.

There's no such thing as "disagreeing" with politics, if said politics are "please respect my existence". If you "disagree" with the fact that trans people are people, then go ahead and disagree elsewhere, where you are still welcome. Unfortunately, there are many places like that.

**Comment by JoakimThorsen** [comment] 2022-10-18 10:27
The intent of your proposal seems unclear to me, do you intend to remove the Code of Conduct entirely, or do you mainly wish to replace it with a different one? You seem to switch back and forth between arguing for no CoC vs a different CoC.

Similar to a pr from the owner of PolyMC which was closed in mid May (https://github.com/PolyMC/PolyMC/pull/601), this pull request seems ill-intentioned. This seems to be a push against the ideals presented in the document on the basis of nitpicking and intentional misinterpretation of the CoC in order to hold the entire document at fault.

> This would mean that code is not only accepted/rejected based on the quality of the code, but the opinions of the person who submitted the code (not agreeing with this CoC would be 'not aligned to this Code of Conduct', if I'm not mistaken)

Correct. The point of rules, just like the ones you proposed as an alternative, is for the community members and contributors to adhere to them, otherwise they would be pointless. Continuing to allow rule-breaking individuals to continue contributing without repercussions would be allowing the unacceptable behavior to persist.

**Comment by T0x1cL** [comment] 2022-10-18 11:14
> The intent of your proposal seems unclear to me, do you intend to remove the Code of Conduct entirely, or do you mainly wish to replace it with a different one? You seem to switch back and forth between arguing for no CoC vs a different CoC.

I personally am not in favour of CoC, but I believe that an alternative CoC is preferable to this one, should one be needed, due to this one's explicitly political nature.

> Similar to a pr from the owner of PolyMC which was closed in mid May ([PolyMC/PolyMC#601](https://github.com/PolyMC/PolyMC/pull/601)), this pull request seems ill-intentioned. This seems to be a push against the ideals presented in the document on the basis of nitpicking and intentional misinterpretation of the CoC in order to hold the entire document at fault.
>
> > This would mean that code is not only accepted/rejected based on the quality of the code, but the opinions of the person who submitted the code (not agreeing with this CoC would be 'not aligned to this Code of Conduct', if I'm not mistaken)
> 
> Correct. The point of rules, just like the ones you proposed as an alternative, is for the community members and contributors to adhere to them, otherwise they would be pointless. Continuing to allow rule-breaking individuals to continue contributing without repercussions would be allowing the unacceptable behavior to persist.

My intention was to point out some flaws (namely, how some words can be deliberately loosely interpreted for the purpose of attacking some people. Apologies, by 'not agreeing with this CoC' I mean 'not agreeing with the ideals of this CoC', rather than 'not agreeing to adhere to the CoC'. My grasp on the language is not particularly well, so my expressions are flawed in this regard. Apologies again for the poor expression.

> There's no such thing as "disagreeing" with politics, if said politics are "please respect my existence". If you "disagree" with the fact that trans people are people, then go ahead and disagree elsewhere, where you are still welcome. Unfortunately, there are many places like that.

From what I've heard, without comment on whether or not I agree and endorse said views, those on the other side of the issue do not disagree that trans people are people, but rather that transitioning is not the only treatment for gender dysphoria, and possibly that transitioning is not beneficial (for instance, people who have de-transitioned). I do not doubt that there are likely people who think all trans people should die or something along the lines of that, but that seems to be a fringe minority, similar to people who unironically think that, for instance, men should be reduced to 10% of the population. I will not go into further detail here, as the discussion regarding this topic is highly controversial.

I see this issue overall as which way the community wishes that the direction on whether or not to accept code: Whether to look at the code only or to look at the person. While I may have my personal opinions, I acknowledge and the community's viewpoints on the matter.

**Comment by Evrey** [comment] 2022-10-18 12:29
> From what I've heard, […]

That’s a long paragraph full of »none of any of ours business«. And this whole trans-whatever that you put a lot of effort into focusing on, is not mentioned anywhere in the CoC.

I think we should indeed modify the CoC, by adding rainbow emoji, so more people that *want* to read strange things into it rat themselves out. 🌈

**Comment by Evrey** [comment] 2022-10-18 12:34
Addendum to your final paragraph which seems to be your main pain point:

- People are interchangable.
- If a twat wrote »good code«, that’s not a unique skill. I can kick the twat out and just wait for another one to write similar »good code«. Or do it myself.
- If i however accept a twat’s code, often even, i give that person leverage over the project.
- In conclusion, i’d rather take code wasting RAM than code written by a »C programming god« who’s a twat.

**Comment by aprilthepink** [comment] 2022-10-18 12:45
> > From what I've heard, […]
> 
> That’s a long paragraph full of »none of any of ours business«. And this whole trans-whatever that you put a lot of effort into focusing on, is not mentioned anywhere in the CoC.

In fact, its a lot of bigotry and misinformation to the trans-* topic in that paragraph. 

Without wanting to be mean, I think that the timing of this issue with the PolyMC controversities kinda says that their views don't seem to allign with the views of the contributors over here. And hearsay has no place in a CoC. Period.

**Comment by JoakimThorsen** [comment] 2022-10-18 13:21
> I personally am not in favour of CoC, but I believe that an alternative CoC is preferable to this one, should one be needed, due to this one's explicitly political nature.

I do not believe that the contents of the CoC, specifically the marginalized groups mentioned, are inherently political in any way. Rather the support of these groups has been heavily *politicized* by (mostly) right-wing actors who campaign to deny acknowledgement of-, rights for-, and proper facilitation for these marginalized groups to live their lives. Statements like "gay people deserve equal rights" and "trans men are men and trans women are women" should not be topics up for political discussion.

 > My intention was to point out some flaws (namely, how some words can be deliberately loosely interpreted for the purpose of attacking some people.
 
 Again, this seems like an *attempt at finding something to nitpick/criticize,* and then using those cirtiques as an argument for its removal, rather than actually looking to make/suggest improvements. I don't think anyone who looks to follow the spirit of this document would have difficulty making good decisions regarding when and where to take action. 
 
> Apologies, by 'not agreeing with this CoC' I mean 'not agreeing with the ideals of this CoC', rather than 'not agreeing to adhere to the CoC'. My grasp on the language is not particularly well, so my expressions are flawed in this regard. Apologies again for the poor expression.

I respect and appreciate this apology. I understand you don't wish to break the community's rules or standards, but what I mean is in a sense that your change suggestions seem to go against the ideas of explicit inclusion and acceptance, which I believe could be harmful to take a step back on. As I said I do not believe the existance of this document will lead to any considerable number of wrongful accusations on the basis of semantics and technicalities.

**Comment by getchoo** [comment] 2022-10-18 13:36
> The Contributor Covenant has been explicitly stated by its creator Coraline Ada Ehmke to be political. (...)

and? codes of conduct are supposed to be a way to govern your project's collaborators, they will always be political. i understand what you're trying to say though, but i still have to ask: in what way does the text itself lean towards a specific political stance? or implicitly enforce one? text being politically charged doesn't matter much when it can be interpreted and enforced in different ways.

> Terms such as (..) can leave some room for interpretation (e.g. using 'he' as a pronoun, or using 'dongle' can be interpreted as sexual language: 'he' is associated with the male sex, and 'dongle' might be used as a euphemism for the male genitalia)

i'm not sure if these are any actual examples of "room of interpretation." misgendering someone (especially if you have been corrected before) is pretty cut and dry, and unless 'dongle' is being used as an actual euphemism for male genitalia, i'm not sure where it could be misinterpreted.

> This would mean that code is not only accepted/rejected based on the quality of the code, but the opinions of the person who submitted the code

no, the acceptance or rejecting of code is based on the contributor's behavior compared to the expected behaviors outlined by the CC. if someone's "opinion" - which i'm not sure if that's a good word for it when we're talking about general behavior, not what your views are - goes against the CC, it's because the content of that "opinion" is not respectful of others or their age, race, sexuality, etc. this is an over-generalization and is not how the CC is used in reality.

> The current Code of Conduct can be used to push an agenda, such as post-meritocracy.

so how can this happen exactly?

> Popper does not support the suppression of uttering intolerant philosophies itself so long as it can be countered by rational argument and kept in check with public opinion (...)

to me, this puts more up to interpretation than anything in the CC (since people have different views on what a rational argument or public opinion is), which seems to be your main issue with it, so i'm not sure why you're bringing this up as a positive

> (..) he claims in the name of tolerance the right not to tolerate the intolerant should they begin to denounce all argument, and meet arguments with violence. Arguably in the current state of politics online it's a shouting match on both sides, but as far as I know if there are any incidents of violence they are extremely rare and likely actions of radicalised individuals acting on their own.

i don't have much to say for this besides it seeming like a political statement in itself. i also don't find the opinions of the creator of a 4 point code of conduct to be very relevant when just like the CC, it's up to the interpretation of those implementing it (i.e., the maintainers of Prism)

> inb4 paradox of tolerance

just because you brought it up doesn't mean it isn't still a valid point. both of these enforce tolerance up to the maintainers discretion. however, the CC sets more specific standards and doesn't leave as much up to that discretion, which in turn allows for easier enforcement against specific harmful behavior. with opal though, it's extremely vague and every point you have made could also be applied to it in a greater extent because of that.

>  (..) it is of my opinion that even if politics is not avoidable we should not be actively bringing it into a block game launcher.

again, how is the CC bringing in politics specifically?


> I would also like to mention that the scope of the Contributor Covenant has been expanded to target said Opal core contributor

i'm not sure how specificity "regardless of ethnicity" in the goal of the CC to make a harassment-free experience targets the opal contributor, same with expanding the scope to behavior when representing projects outside of project spaces. these are great additions imo - people shouldn't be harassed because of their ethnicity, and people should be held accountable when representing the project

> The Contributor Covenant can potentially be used as a weapon against people who do not agree with the politics of the creators.

gotta say it one more time: how could this be done in non-hypothetical circumstances? or how could this same logic not be applied to other codes of conduct?

**Closed as completed** 2022-10-18 13:36 UTC

**Comment by ghost** [comment] 2022-10-25 06:49
Most people who have spoken up against the current CoC have a problem with "political language" or "pushing an agenda" from the Code of Conduct, which I really don't care about.

What's more problematic for me is rules like
> "Being respectful of differing opinions, viewpoints, and experiences"

I don't think I should be respectful of every single opinion. Some opinions are false, and they don't deserve some baseline respect. People deserve respect, which is why we should be careful when telling them that their opinion is false, but the opinions in themselves don't deserve respect based purely on the fact that they're opinions.

> "Focusing on what is best not just for us as individuals, but for the overall community"

I'm under the impression a lot of people contributing code _don't_ do it out of a sense of "focusing for the overall community", but just out of pure convenience. It's mutual cooperation, that bring mutual benefits, not the need to belong to a community, that drives people to participate in free software projects.

> "Demonstrating empathy and kindness toward other people"

In the same way, you might think of this as "unwelcoming", but if I contribute to some project, I don't want to feel obligated to demonstrate empathy or kindness towards anyone. I probably just want to make a pull request to fix something that I believe is missing. Don't get me wrong, I'll make sure to treat anyone respectfully, but I don't think this is an obligation to demonstrate empathy or kindness.

> "Trolling (antagonistic, inflammatory, insincere behaviour), insulting or derogatory comments, and personal or political attacks"

I believe this is too subjective for a code of conduct. "Trolling" or "insincere" are mostly unprovable accusations, and also undisprovable (You can't prove that I'm not insincere in my action, and not just a big troll that wants to see the Contributor Covenant being burned at the stake for no reason except that I'm mean and evil.).

> "to any behavior that they deem inappropriate, threatening, offensive, or harmful."
Behavior can be offensive without being wrong. For example, any criticism can be deemed offensive by some people, and this rule empowers them to silence said criticism (since it is, after all, offensive). Offense is something that only exists in relation to the listener (as opposed to harmful or threatening, which are objective qualities of a statement.).

You might argue that the Code of Conduct defines most of those as "Examples of behavior that contribute to a positive environment", that that'd be technically true, but it's a Code of Conduct, not a Suggestion of Conduct.
