### ISSUE TITLE
Prism can't recognize two different versions of a mod with the same name correctly

### ISSUE THREAD

**Issue by xErrorAmelie** [PrismLauncher/PrismLauncher#2728] opened 2024-08-15 21:47 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

I tried to get the QFAPI version with the api version 0.76.0.
Instead I got the QFAPI version with the api version 0.77.0 all the time.

The following QFAPI versions provide different Fabric API versions, but they have the same name. It doesn't matter which one you select, you will always get the newest one which provides api version 0.77.0. Downloading it directly from https://modrinth.com/ works, just prism launcher doesn't recognize the difference.
[1.19.2] QFAPI 4.0.0-beta.30 and QSL 3.0.0-beta.29
[1.19.2] QFAPI 4.0.0-beta.30 and QSL 3.0.0-beta.29

### Steps to reproduce

- Click on "download mod" in the mods tab of an 1.19.2 Quilt Loader instance.
- Search for "QFAPI"
- In the dropdown of "version selected" select the second newest QFAPI version ([1.19.2] QFAPI 4.0.0-beta.30 and QSL 3.0.0-beta.29)
- Check the filename where it tells you the API Version, in this case: "qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.77.0_mc-1.19.2.jar"

Repeat the same, but select the newest 1.19.2 QFAPI Version instead, the result will be the exact same file with the name: "qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.77.0_mc-1.19.2.jar".

### Suspected cause

These two QFAPI versions have the same name, maybe prism launcher always choose the newest version then, instead of the selected one.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-08-15 22:20
I'm not able to reproduce it at all. And I'm sure the code there is solid(like using the index from the combo box to get the selected version to download).
Are you able to reproduce this with any other mod?

**Comment by xErrorAmelie** [comment] 2024-08-16 00:08
Here is a video of the problem, prism launcher always provides the same file, despite selecting different versions.
Video link: https://www.youtube.com/watch?v=f2mbvXpl2Vk

On modrinth you can also see that these two versions should be different:
![image](https://github.com/user-attachments/assets/c4d2cf3a-af92-4855-a65a-826a164b3e01)
![image](https://github.com/user-attachments/assets/d7927d2c-e5e3-4738-93d5-39a1a1f67aec)
![image](https://github.com/user-attachments/assets/1cd2514d-0858-40b8-a754-0fa1e2889ce7)

I can also reproduce the same problem with my own mod. I added two different files, but with the same name. Same problem happens.

**Comment by Trial97** [comment] 2024-08-16 06:25
If you want to change the version you need to deselect the mod and select it again. (You choose only the first time, the second time when you change the version you need to deselect the mod and select it again with the new version.
Also, try reproducing this by closing and reopening the mod download dialog.

**Comment by xErrorAmelie** [comment] 2024-08-16 09:55
I can reproduce it with your suggested variant of doing it. 
I can also reproduce it on the machine of my friend. 

No matter how I do it, it is not possible to get the file that provides fabric api 0.76.0. (Except downloading it without prism)
And as I said, it is also reproducible with my own mod, one file/version can't be downloaded, when the version names are the same.

**Comment by Trial97** [comment] 2024-08-16 09:58
can you provide a screen recording where you just select the 76 version(not the latest) and display the filename in the review dialog?

**Comment by Kationor** [comment] 2024-08-16 10:01
I am also consistently able to reproduce this issue.
Looks like the culprit is `ResourcePage::onVersionSelectionChanged` (which takes a QString representing version, not the version index).
I'll submit a PR once I figure out why my build cache stopped working.

**Comment by Trial97** [comment] 2024-08-16 10:07
@Kationor I reopened it but I can't find what exactly you mean as the string is not used for selection: https://github.com/PrismLauncher/PrismLauncher/blob/d6a825dd4704172c6115919ff8550d3074b950f9/launcher/ui/pages/modplatform/ResourcePage.cpp#L331 

P.S. if you do manage to fix it we appreciate it if you open a PR with the fix.

**Comment by xErrorAmelie** [comment] 2024-08-16 10:22
> can you provide a screen recording where you just select the 76 version(not the latest) and display the filename in the review dialog?

The recording: https://www.youtube.com/watch?v=nA8gTUfjOiM
The version I selected in the recording: https://modrinth.com/mod/qsl/version/4.0.0-beta.30+0.76.0-1.19.2

**Comment by Kationor** [comment] 2024-08-16 10:22
@Trial97 The issue is less with the function itself, and more with *when* it's called.

By default, the QComboBox has the newest version selected. If you then select another version with the same name, the index of the selected version changes, but *the version text stays constant*, which means that `QComboBox::currentTextChanged` never fires and `ResourcePage::onVersionSelectionChanged` never gets called.

This is only an issue when switching *between* two versions that have the same name, which may explain your reproduction difficulties.

**Comment by Trial97** [comment] 2024-08-16 10:28
> This is only an issue when switching _between_ two versions that have the same name, which may explain your reproduction difficulties.

I'm trying to reproduce it with the exact versions that xErrorAmelie was done in the videos, but I have no success.
So I don't know exactly if is what you say. 
Also, I did try to switch between the two versions with the same name and I always got the correct file.
Maybe it is something that only happens on windows.

**Comment by Trial97** [comment] 2024-08-16 12:05
@xErrorAmelie  or @Kationor  can you try and see if you can still reproduce this using this build: https://github.com/PrismLauncher/PrismLauncher/actions/runs/10419392489 ?

**Comment by xErrorAmelie** [comment] 2024-08-16 12:22
> @xErrorAmelie or @Kationor can you try and see if you can still reproduce this using this build: https://github.com/PrismLauncher/PrismLauncher/actions/runs/10419392489 ?

Tested it, looks like it's fixed now :)

**Closed as completed** 2024-08-18 16:00 UTC
