### ISSUE TITLE
Search for modpacks by Minecraft version

### ISSUE THREAD

**Issue by beckkake** [PrismLauncher/PrismLauncher#2427] opened 2024-05-20 13:33 UTC
### Role

I would like to play some modpacks that are on a specific version (1.12.2), but it is difficult to search for them solely off of the Prism UI. I would have to visit the websites that the modpacks are hosted on, filter my search on there, then go back to Prism and search for a specific modpack that I saw to fully know if it is the version I want.

### Suggestion

I want the modpack search under "Add Instance" for each of the mod platforms to have more precise filtering options (currently, it is just a few that sort by popularity, downloads, etc.), such as Minecraft version or even more types of filtering.

### Benefit

It is beneficial to users that would like to play on a specific version. This would be a good feature.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I am not 100% sure the issue does not already exist, but I could not find it. Thanks!

**Comment by Trial97** [comment] 2024-05-20 16:24
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/873

**Closed as not planned by Trial97** 2024-05-20 16:24 UTC
Labels: type: enhancement
