### ISSUE TITLE
GitHub integration

### ISSUE THREAD

**Issue by Djspac3** [PrismLauncher/PrismLauncher#2335] opened 2024-04-23 20:47 UTC
### Role

playing with GitHub only mods (will not disclose unless fully needed)

### Suggestion

adding a GitHub mod provider option

### Benefit

using mods that cant/won't be on Modrinth or Curse Forge

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-04-23 21:28
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1393

**Closed as not planned** 2024-04-23 21:28 UTC
Labels: type: enhancement

**Comment by Djspac3** [comment] 2024-04-24 23:42
Oh
