### ISSUE TITLE
Last Played Time Incorrect

### ISSUE THREAD

**Issue by WarpZephyr** [PrismLauncher/PrismLauncher#1884] opened 2023-11-22 00:53 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

I created a new 1.20.2 instance, the first instance I've created since updating to 8.0,
I had it download the stuff for 1.20.2 but did not start it,

Then I noticed the last played time,
![image](https://github.com/PrismLauncher/PrismLauncher/assets/107563368/f7b69594-360e-4a1a-a093-b5a0076fdc28)

"Minecraft 1.20.2, last played on 12/31/69 7:00 PM for 13min 32s, total played for 13min 32s"
I haven't played this instance yet at all, and it isn't 2069 yet.

Some additional details:
I had an older version of PrismLauncher and saw the 8.0 release,
So I downloaded 8.0 and deleted all the files in the PrismLauncher program folder,
I left my AppData folders of it though so I wouldn't lose my instances
Then I installed the new release

Later I made a new 1.20.2 instance with no additional settings and noticed it had the odd playtime.

### Steps to reproduce

1. Create a new instance of 1.20.2 with no additional settings
2. Double click it to let the required files be downloaded
3. Do not begin the instance
4. Move the instance to an existing group that has old instances
5. Change the icon to grass_legacy
6. Check the last played date

### Suspected cause

I'm not sure.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-11-22 06:56
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1051

**Closed as not planned by Trial97** 2023-11-22 06:56 UTC

**Comment by WarpZephyr** [comment] 2023-11-22 16:32
It wasn't just that time, it also said it was in 2069 for some reason

**Comment by Trial97** [comment] 2023-11-22 16:37
Most probably has the same cause (the fact that we start that timer with the download assets)
