### ISSUE TITLE
prism says all mods are up-to-date while they aren't

### ISSUE THREAD

**Issue by CapToad** [PrismLauncher/PrismLauncher#3085] opened 2024-11-09 18:00 UTC
### Version of Prism Launcher

Prism 9.1

### Version of Qt

Qt 6.7.3

### Description of bug

when checking for mod updates prism says that a mod is up to date when it is using and older version

### Steps to reproduce

check a mod for update i guess

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-11-09 18:47
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/3040

**Closed as not planned by Trial97** 2024-11-09 18:47 UTC
