### ISSUE TITLE
Beta and alpha versions of minecraft are broken

### ISSUE THREAD

**Issue by 3pical** [PrismLauncher/PrismLauncher#717] opened 2023-01-08 11:32 UTC
### Operating System

Windows, Linux

### Version of Prism Launcher

Prism launcher 6.1

### Version of Qt

Qt 5.15.7

### Description of bug

When playing any beta or alpha versions of minecraft clicking causes you to lose focus of the game window for a bit

### Steps to reproduce

choose any beta or alpha version, start a singleplayer world, try punching.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment] 2023-02-17 18:04
Duplicate of #775 (Actually this one came first, but since that one has more information about the issue, we'll keep that one up to have more easy access to the info)

**Closed as not planned by flowln** 2023-02-17 18:04 UTC
