### ISSUE TITLE
Window is too big for small resolutions

### ISSUE THREAD

**Issue by ripsivis** [PrismLauncher/PrismLauncher#674] opened 2022-12-24 20:05 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt 5.15.7+kde-blabla (edit: 5.15.7+kde+r177)

### Description of bug

Buttons and stuff are inaccessible at small resolutions like 1336x768.

![Screenshot_20221224_214522](https://user-images.githubusercontent.com/57156687/209449740-53e0c931-391c-4d68-8498-e25d8dbc8fec.png)

![Screenshot_20221224_214552](https://user-images.githubusercontent.com/57156687/209449743-a9cd7690-b124-4b72-a596-f013f193e328.png)

### Steps to reproduce

Lower the resolution and open Settings or Add Instance page

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment] 2022-12-24 23:09
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/220

**Closed as not planned by DioEgizio** 2022-12-24 23:09 UTC
