### ISSUE TITLE
Update doesn't include all mods

### ISSUE THREAD

**Issue by Undeadlord** [PrismLauncher/PrismLauncher#2211] opened 2024-03-11 18:39 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism 8.2

### Version of Qt

6.6.2

### Description of bug

Updating ATM9 to the latest 0.2.51, the update happens as normal, with no errors and all progress bars appear complete and close as appropriate, but when you start the instance, Minecraft quickly tells you that 7 - 8 mods are missing from the mods folder. 

After adding the mods manually, the instance will start but there were still mods that needed to be removed and added. Overall maybe 10 mods needed to be added for the instance to start as normal.

### Steps to reproduce

I had v0.2.48 installed, right-clicked on the instance, went to Edit, then CurseForge and selected Update Pack when 0.2.51 was selected.

Also I can confirm that a new instance with .0.2.51 works fine, and copying the files from that new instance to the "updated" one copies all the needed files over, but the basic "update" option doesn't seem to work.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by glektarssza** [comment] 2024-03-12 01:43
Potentially a duplicate of #2111

**Comment by Trial97** [comment] 2024-04-04 06:50
Duplicate of #2111

**Closed as not planned by Trial97** 2024-04-04 06:50 UTC
