### ISSUE TITLE
Prism may fail to use latest in-game translations

### ISSUE THREAD

**Issue by coinvariant** [PrismLauncher/PrismLauncher#2723] opened 2024-08-12 12:35 UTC
### Operating System

Windows, Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 5.15.2

### Description of bug

Prism sometimes fails to use the latest translations released by Mojang with each new version.

This bug affects a particular existing instance. It seems that when it happens, it is persistent and does not go away on its own. I am aware of two cases of this bug: myself and another person. The only commonality known to me is that the systems underwent a time zone switch at some point in time, but the analysis was not exhaustive.

### Steps to reproduce

I can't provide particular steps, so I've attached a minimal portable version of Prism that exhibits this behavior. It contains a `meta` folder with an index file for 1.20.1 and some other files (`meta/index.json`, `meta/net.minecraft/index.json`, some other indexes that I just did not touch and which seem irrelevant), as well as a pre-made 1.20.1 instance. When the index file for 1.20.1 is present, the launcher uses incorrect translations. If you delete it, the launcher will regenerate a correct index file and will use proper translations.

I have noticed that: the `sha256` value inside `meta/net.minecraft/index.json` for `meta/net.minecraft/1.20.1.json` disagrees with the actual sha256 of `meta/net.minecraft/1.20.1.json`.

Nonetheless, the game launches and this discrepancy is not fixed.

I would recommend trying to reproduce the bug before the next snapshot. You can validate the bug's presence by noticing the absence of a language "Biełaruskaja" among the available languages.

[minreproduction.tar.gz](https://github.com/user-attachments/files/16581407/minreproduction.tar.gz)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-08-12 12:37
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/574

**Closed as not planned by Trial97** 2024-08-12 12:37 UTC
