### ISSUE TITLE
Prism launches in offline mode if it is still open when Windows awakes from sleep.

### ISSUE THREAD

**Issue by FamroFexl** [PrismLauncher/PrismLauncher#2244] opened 2024-03-26 23:56 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 6.5.1

### Description of bug

When I leave Prism launcher open and I sleep Windows, when I boot up Windows again and attempt to open an instance, it asks me for an offline player name. I am using ethernet to connect to the internet, and it is always operational when this problem occurs.

### Steps to reproduce

* Open Prism Launcher
* Launch an instance in online mode (not sure if this step is required)
* Sleep Windows
* Startup Windows from sleep (I'm not sure if this issue requires Windows to be asleep for a minimum period of time)
* Launch an instance from the open Prism Launcher Window

### Suspected cause

I suspect Prism launcher checks if the system is online when it is opened and after a windows sleep. When this occurs, I presume Prism checks the internet status before Windows has recognized it is online and displays the offline mode prompt.

Since Windows is still connected to internet while offline to allow Wake for LAN packets (at least I have this enabled in my BIOS), this might be a incorrect cause.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-03-27 06:14
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/592
Steps to fix: update Prismlauncher to the latest version

**Closed as not planned by Trial97** 2024-03-27 06:14 UTC
