### ISSUE TITLE
Every version of minecraft in the version selection

### ISSUE THREAD

**Issue by creaturekatze** [PrismLauncher/PrismLauncher#679] opened 2022-12-26 18:09 UTC
### Role

I use prism launcher to play oldschool versions of the game

### Suggestion

Add every lost version rediscoverd by Omniarchive to the version selection. 

### Benefit

This would be very useful for instance managing, accesibility of old interesting versions and especially modding of old versions

### This suggestion is unique

- [ ] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This would _really_ improve modding old versions of the game. 
You don't have to select a version similar to the version you'd like to mod with _very specific requirements_ for it to work, then add a custom jar with the actual version you'd like to mod, which you had to download directly from the Minecraft wiki, then add your jarmod to that custom jar. And even without the last step, that's literally how you install these old versions of the game. 

Modding these versions and installing them in general is an absolute pain. You have to do so much, adding all versions to the list would make it so much easier.

This is already a feature in the betacraft launcher, and it's something that it has over most other launchers as it's a launcher specifically designed to make old Minecraft versions as easy as possible. I think a lot of people would switch over to prism launcher if you made version selection easier.

[Here is the index for every version found by omniarchive over the years.](https://omniarchive.org/sheet)
There is so much more than the few versions found in the default launcher, it's crazy.

**Comment by flowln** [comment] 2022-12-26 18:24
Duplicate of #101

**Closed as not planned by flowln** 2022-12-26 18:24 UTC
Labels: status: duplicate, type: enhancement
