### ISSUE TITLE
Give the ability to create and run Minecraft servers using Prism Launcher

### ISSUE THREAD

**Issue by floofyneko69** [PrismLauncher/PrismLauncher#2378] opened 2024-05-06 16:44 UTC
### Role

I play modded Minecraft and test server capabilities with mods

### Suggestion

Be capable of creating Minecraft servers using Mojang's public server files

### Benefit

To ease the process of updating from one version to another with mods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Even though Mojang gives public access to Minecraft server files, and creating a server is fairly straightforward apart from port forwarding, updating a server to the newest version isn't just as easy, it requires having to backup files before you delete the previous version just to install the newest version and replace some of the created files with your backups-

So, why not make this process even more straightforward with Prism Launcher, since it's just as, if not better to have a program capable of doing the exact same thing for you

If you would like a better idea of how this should look, here's what I had in mind, though changes may be necessary

Edit Menu:
- Version (Controls the server file version and applicable mod loaders if installed)
  - Mods
- Resource Packs (Zips all added resource packs and links the file path to the `resource-pack` text in `server.properties`)
- Notes
- World (Singular, not plural)
- Settings (Where `server.properties`, `ops.json`, `whitelist.json`, etc, can be edited, including `start.bat/sh` for ram allocation and gui)
- Other Logs

Extra possible features:
1. A map gui that displays the world like common web map mods, including players, mobs, structures, etc.
2. A modified command menu that allows the server owner to run commands from the terminal/gui instead of in-game, and makes use of expanded autofill similar to the NBT Autocomplete mod

**Comment by Trial97** [comment] 2024-05-06 16:51
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/864

**Closed as not planned by Trial97** 2024-05-06 16:51 UTC
Labels: type: enhancement
