### ISSUE TITLE
Ability to download and/or use server packs

### ISSUE THREAD

**Issue by TheInfamousAlk** [PrismLauncher/PrismLauncher#2736] opened 2024-08-20 17:23 UTC
### Role

I would like to easily spin up servers or simply acquire server files without using my browser

### Suggestion

Minimum - download server packs like you can client packs. Maximum - allow installation and use of servers just like clients

### Benefit

I can use Prism for my entire minecraft modding ecosystem EXCEPT for server file download and running

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

So for many modpacks, there are optional "server packs" for certain versions, though not all versions and not all packs include server packs. Technic, Curseforge, and Modrinth have server packs available. FTB requires their stupid app to download server files so that would be out of the question, and I'm not sure about the remaining platforms. But the big 3 do have publicly available server packs that could be downloaded just as easily as client packs. 

While downloading modpacks, mods, etc, and playing them, the only thing I need to leave prism for right now is downloading server files, which I do frequently. It would be very nice to not have to leave Prism to get all of my minecraft-related tasks done. 

Example of server pack links:
Curseforge: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5564414
(On the main page of a pack, click on Files, choose a version, then click "Additional Files", then click the available server pack.)

Modrinth: https://modrinth.com/modpack/create_plus/version/5.1.0c
(Scroll ALL THE WAY DOWN the page, past the mod list to see server pack link)

Technic: https://www.technicpack.net/modpack/tekkit-2.1935271
(On the right of the page, under the "Followers" section.

Some server packs are incorrectly formatted, but I'd say 90% of them are formatted correctly in a .zip file with runnable mod loader .jars and sometimes custom start scripts included. 

In the event that it's too hard to automate detection of run method, I would also be very happy with the ability to simply download server packs and that's it. Whether that be for an already installed client instance, or just in the modpack browser directly, ideally both.

**Comment by Trial97** [comment] 2024-08-20 17:28
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/864

**Closed as not planned by Trial97** 2024-08-20 17:28 UTC
Labels: type: enhancement

**Comment by TheInfamousAlk** [comment] 2024-08-20 20:25
This is not a duplicate, that one is about making servers from existing instances. This suggestion is about specifically server packs provided by authors - both downloading and using them, or just downloading. If there's no server pack, there's no additional feature. I want a way to access hosted server files through the app, not make a server with an existing instance.
