### ISSUE TITLE
Make it possible to easily add custom "cat" images

### ISSUE THREAD

**Issue by cs-deathmatch** [PrismLauncher/PrismLauncher#1715] opened 2023-10-15 22:16 UTC
### Role

I'm a casual player, who likes customization options

### Suggestion

I want there to be a folder i can put PNGs in, that will add them as options to display on the main menu with the cat button

### Benefit

I want to put my fursona on my menu, and i bet other people would want to do similar things too

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

after googling around a bit, it looks like the only way to add a custom image would be to compile the launcher from source. allowing easy customization just by putting image(s) in a folder would be much appreciated

maybe also a shuffle button?

**Comment by Trial97** [comment] 2023-10-16 05:09
Duplicate of #668
And for the random cat button: #693

**Closed as completed by Trial97** 2023-10-16 05:09 UTC
Labels: type: enhancement
