### ISSUE TITLE
Prism no internet conectivity despite me being able to connect to github and post this error message.

### ISSUE THREAD

**Issue by spencershoe** [PrismLauncher/PrismLauncher#869] opened 2023-02-17 07:07 UTC
### Operating System

Windows

### Version of Prism Launcher

prism launcher 6.3.
Prism launcher refuses to connect to anything. my account is offline and it isn't even able to load the news.
i have no clue how it started and closing and opening it again does not fix the issue.

### Version of Qt

Qt 6.4.2.

### Description of bug

No communication with internet services, refuses to even time out when attempting to log in to a Microsoft linked account.

### Steps to reproduce

Open Prism Launcher.
Close prism launcher then open again.
Delete all config files excluding instances then relaunch Prism Launcher.
Delete all config files excluding instances then delete program files located in %appdata%\local\programs then reinstall prism launcher; fixes the issue.

### Suspected cause

Silent crash of networking module.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by pandaninjas** [comment] 2023-02-17 07:21
Might be a duplicate of #660

**Comment by Xetaxheb** [comment] 2023-02-17 18:22
I consistently have this issue on some install, solution is to essentially delete prism install while keeping instances folder and install with a fresh download. 
I believe I was also able to keep accounts.json and prismlauncher.cfg but if it still doesn't work try ditching the latter.
Almost certainly a duplicate of #660 as pandaninjas said.

**Comment by FireMasterK** [comment] 2023-02-22 01:29
I have a similar issue, it happens to me when I have an ipv6 broken network (on linux).

**Comment by Scrumplex** [comment] 2023-03-02 10:45
Duplicate of #660

**Closed as not planned by Scrumplex** 2023-03-02 10:45 UTC

**Comment by FireMasterK** [comment] 2023-03-02 12:17
I can replicate this on linux however, so it this really a duplicate? Using an ipv4 only network works fine. However, if I have an unroutable ipv6 network, it doesn't fall back to ipv4 correctly.

**Comment by Xetaxheb** [comment] 2023-03-02 16:25
> I can replicate this on linux however, so it this really a duplicate? Using an ipv4 only network works fine. However, if I have an unroutable ipv6 network, it doesn't fall back to ipv4 correctly.

@FireMasterK Your issue sounds separate and unrelated to what we're talking about here, you should open another (and more importantly your own) issue with any details and steps and logs you can provide about that ipv4/ipv6 issue. This one was about broken installs from updating not properly removing unnecessary and interfering dlls, consistently reproducible by improperly updating from 5->6 and reliably fixable by creating a fresh install environment. I am not seeing other issues mentioning your problem and that sounds worth fixing.
