### ISSUE TITLE
Improve Logs Filtering and Readability

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#2068] opened 2024-01-25 14:27 UTC
### Role

Dev Modpacks & Play

### Suggestion

I'd like to suggest the feature that already exists in vanilla launcher where you could filter the logs for ("Fatal" "warn" "info"...etc)

### Benefit

This feature could really ease dev-ing on Prism and provide more user-friendly logs that are easy to read.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This feature also includes different colour for each type and so on.

**Comment by Trial97** [comment] 2024-01-25 14:34
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/453

**Closed as not planned by Trial97** 2024-01-25 14:34 UTC
Labels: type: enhancement
