### ISSUE TITLE
Installing a modpack tells me it's 'unziping' the modpack

### ISSUE THREAD

**Issue by eastcw** [PrismLauncher/PrismLauncher#3253] opened 2024-12-30 16:13 UTC
### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.7.3

### Description of bug

When installing a modpack using British English, the launcher tells me it's unziping the modpack rather than unzipping it, see below screenshot

![image](https://github.com/user-attachments/assets/6046965c-04fb-4755-bf82-2291d35ed91c)

### Steps to reproduce

* Have the launcher in UK English
* Install a modpack

### Suspected cause

I couldn't see this string in weblate, but I've never used it before so apologies if I should be reporting there and just don't know how to use it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-12-30 16:49
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/3000
Also already fixed and planned to be released in the next 9.2

**Closed as not planned by Trial97** 2024-12-30 16:49 UTC
