### ISSUE TITLE
Custom sources for launcher versions, modloaders, modpacks, mods, etc.

### ISSUE THREAD

**Issue by DexrnZacAttack** [PrismLauncher/PrismLauncher#1984] opened 2023-12-26 03:40 UTC
### Role

Allowing players to get custom versions of Minecraft from other sources, like versions not shown on the MC Launcher (a great example would be Omniarchive's found versions)

### Suggestion

Allow sources to be added, from a text file or URL that will show those custom versions inside, allowing you to download and play them as if it was an official version in the MC Launcher (and more... read the elaboration)

### Benefit

It would be nice to not have to download the jars manually and import them... as well as having alternatives to all/any of the existing sources.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This could also expand to modloaders, having custom modloader sources instead of just the default Fabric, Forge, Quilt, etc.
We should also be able to get mods from custom sources as well through the mod browser, although it will be pretty hard if there isnt a standard on formatting for mod websites.

I would like to elaborate on this further when I have a better idea of what I'm trying to get across.
as I am not very good at trying to explain everything when it comes to my head.

**Comment by Blizzardfur-Maxxx** [comment] 2023-12-26 03:54
1984

**Comment by Trial97** [comment] 2023-12-26 07:07
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/101

**Closed as not planned by Trial97** 2023-12-26 07:07 UTC
Labels: type: enhancement

**Comment by DexrnZacAttack** [comment] 2023-12-27 00:06
> Duplicate of #101
It wasn't meant to be a duplicate, rather using that as an example, but I feel that this suggestion is different enough to #101 as this suggestion is more about a matter of allowing decentralization.

**Comment by Trial97** [comment] 2023-12-27 07:07
I'm pretty sure that one should be able to cover your case to.
Regarding the other stuff like mod providers and modloaders there are already a bunch of issues that require us to add for example a legacy version of fabric and so on(just search for them).
As for adding a mechanism to extend the launcher to support these: https://github.com/PrismLauncher/PrismLauncher/issues/1240 and https://github.com/PrismLauncher/PrismLauncher/pull/1879
