### ISSUE TITLE
When copying a instance the playtime gets copied.

### ISSUE THREAD

**Issue by Viktoranderas** [PrismLauncher/PrismLauncher#897] opened 2023-03-01 12:01 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcer 6.3

### Version of Qt

Qt 6.4.2.

### Description of bug

I copied a instance with a little bit more then a day of playtime. I then checked the playtime on the copy instance which i had played on for only a couple of minutes. And it was over a day like the original instance. I've tried it with multiple instances and each time the playtime from the original is duplicated.

### Steps to reproduce

- Copy any instance with playtime. 
- That amount of playtime is on the copy of the instance and has been added to your total playtime.

### Suspected cause

Playtime is stored in a file that is copied when copying a instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment] 2023-03-01 12:03
There is already an option to disable this! Although it could be turned off by default.

**Comment by Viktoranderas** [comment] 2023-03-01 12:21
> There is already an option to disable this! Although it could be turned off by default.

I tried finding the option but I couldn't. I might just have misunderstood what the Game time settings actually do. 
Where do I find this?

**Comment by TheKodeToad** [comment] 2023-03-01 12:42
![image](https://user-images.githubusercontent.com/57493648/222142403-efcc541e-0698-4816-af1b-c1e397e305b3.png)
It's in this dialog.

**Comment by Scrumplex** [comment] 2023-04-26 07:23
Closing this as this is intended behavior.

**Closed as not planned by Scrumplex** 2023-04-26 07:23 UTC
