### ISSUE TITLE
Prism Launcher not Connecting to the Internet.

### ISSUE THREAD

**Issue by Gratting** [PrismLauncher/PrismLauncher#2648] opened 2024-07-16 00:26 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

My Prism Launcher can't log in to my account or load news, but I can still use other software online. I have tried to delete and redownload the launcher, but was greeted be the same issue.

### Steps to reproduce

- Randomly get Blue screened
- Wait for PC to turn on
- Log in
- Notice that WiFi icon in the corner is hidden
- Boot up Prism Launcher 8.4
- Add account, but fail

### Suspected cause

Unknown

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-07-16 05:39
But you did not try to search for another issue. See one of the proposed solutions from here: https://github.com/PrismLauncher/PrismLauncher/issues/1248#issuecomment-2206963435
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1248

**Closed as not planned by Trial97** 2024-07-16 05:39 UTC
