### ISSUE TITLE
Installing Mods

### ISSUE THREAD

**Issue by Marks12520** [PrismLauncher/PrismLauncher#2485] opened 2024-06-08 20:40 UTC
### Role

Creating Modpacks

### Suggestion

When you switch between curseforge and modrinth the thing you had searched on the other should auto-search too when you change

### Benefit

If you search for a mod on modrinth (which is the default) and it's not there you can just click on curseforge and the mod will show up without the need to type the name again

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I think it's a pretty easy thing to implement and would make the launcher less frustrating to use :grin

**Comment by desbarmitar** [comment] 2024-06-27 11:14
https://github.com/PrismLauncher/PrismLauncher/issues/1925

**Comment by Trial97** [comment] 2024-06-27 11:15
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1925

**Closed as not planned by Trial97** 2024-06-27 11:15 UTC
Labels: type: enhancement
