### ISSUE TITLE
Prism Launcher Auto-Update.

### ISSUE THREAD

**Issue by kicekkic** [PrismLauncher/PrismLauncher#177] opened 2022-10-20 15:04 UTC
### Role

In every way.

### Suggestion

Auto-update itself after a new release releases.

### Benefit

You don't have to go to github, then download the release and then install it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by forkiesassds** [comment] 2022-10-20 15:48
There is an updater already for macOS and also there is an existing issue for Windows (#94), however there is none for Linux.

**Comment by Jorma17** [comment] 2022-10-20 16:17
@forkiesassds 
Doesn't the launcher update with other packages on Linux though? At least for me it updates when I update my AUR packages

**Comment by ananace** [comment] 2022-10-20 16:41
For Flatpak on Linux there's an existing [DBus API](https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Flatpak.UpdateMonitor) (as well as [an API in libportal](https://github.com/flatpak/libportal/blob/main/libportal/updates.h)) for detecting and doing automatic updates, and - without any DBus/libportal usage - there's the `/app/.updated` file which will be created if an updated version is installed beneath the application, which can then be restarted to with the `flatpak-spawn` tool.

**Comment by Scrumplex** [comment] 2022-11-27 22:30
Duplicate of #94.
We are probably not gonna add update capabilities on Linux, as you should just use distro packages / Flatpak / Snap (soon).

**Comment by ananace** [comment] 2022-11-28 09:30
@Scrumplex Not even in regards to hooking the notifications and such that Flatpak (and maybe Snap? Can't find any docs) provide for applications to know when they've been updated?

**Comment by Scrumplex** [comment] 2022-11-28 09:41
I don't know about update notifications in Flatpak or Snap. Most people probably have a software center that will handle these already.

**Comment by ananace** [comment] 2022-11-28 09:52
I don't primarily mean in regards to notifying that an update is available, but rather - for Flatpak at least - detecting that an update has been installed and can be restarted onto

**Comment by Scrumplex** [comment] 2022-11-28 15:10
Oh, that sounds interesting for Flatpak. But then again, you probably restart Prism often enough that it might not matter much.

**Comment by Scrumplex** [comment] 2022-11-28 15:10
wrong button :|

**Closed as not planned by Scrumplex** 2022-11-28 15:10 UTC
Labels: type: enhancement
