### ISSUE TITLE
Prism launcher suddenly stops connecting to account api

### ISSUE THREAD

**Issue by CowIzBeef** [PrismLauncher/PrismLauncher#2473] opened 2024-06-06 04:19 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt version 6.6.3

### Description of bug

i just get this error after trying to re add my account after being unable to launch the game: Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: 

### Steps to reproduce

Just trying to sign in

### Suspected cause

not enough evidence to give a possible cause, this was working fine earlier today

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-06-06 05:22
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-06-06 05:22 UTC
