### ISSUE TITLE
Mod Compatibility Check 

### ISSUE THREAD

**Issue by Slugiish** [PrismLauncher/PrismLauncher#1634] opened 2023-09-18 12:35 UTC
### Role

I play modded Minecraft. 

### Suggestion

check modlist compatibility based on collected telemetry data from other users

### Benefit

so that the auto updater potentially wont update mods into a state where they are incompatible with eachother and cause crash on startup.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I recently switched to prism and have been loving one click updating all of my mods, however today I ran into a very expected issue in that sodium updated to a version that made it incompatible with mods that require it such as indium. This obviously made Minecraft crash on startup and I had to backdate sodium so that things would work again. This was all expected and not a problem at all however it made me think that it might be possible to detect crash on startup failures like this with a little bit of telemetry data. If prism made an opt in telemetry system where it would collect a list of your mods and their exact versions and send that off on successful launch to main menu or on crash on startup it could then use a big database of those successful and unsuccessful modlists to judge whether a new list of mods is likely to crash on startup or make it to main menu. This is obviously a huge undertaking and not something I expect to ever see but I just wanted to bring it up as a potential idea that I think could be really cool.

**Comment by Trial97** [comment] 2023-09-18 12:43
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/450
But as mentioned here:https://github.com/PrismLauncher/PrismLauncher/issues/450#issuecomment-1636854995 the APIs(at least curseforge one) don't really return the incompatible mods only the dependencies. 
Also, the telemetry is not really wanted.

**Closed as not planned by Trial97** 2023-09-18 12:43 UTC
Labels: type: enhancement

**Comment by Slugiish** [comment] 2023-09-18 13:23
Ah sorry I missed the duplicate. I totally understand not wanting telemetry and had just wanted to bring it up in case it was not on anyone's mind. Thank you for the quick response and closure.
