### ISSUE TITLE
Curseforge downloads occasionally break

### ISSUE THREAD

**Issue by Hedwig7s** [PrismLauncher/PrismLauncher#1569] opened 2023-08-26 15:12 UTC
### Operating System

Windows

### Version of Prism Launcher

Commit [094cee8](https://github.com/PrismLauncher/PrismLauncher/commit/094cee8ec61135db4c569a3a72016c9c84c60cdd)

### Version of Qt

Qt 6.5.2

### Description of bug

Sometimes, when downloading certain mods, the mod downloader will freeze near completion (ex: 38/42). Mainly observed with curseforge and when dependencies are automatically added. There will also always be as "Requesting" loading bars as there are mods not downloaded (e.g. 64/68 would have 4 "Requesting" bars). Copying mods from a bugged instance to a new one will sometimes fix the issues

### Steps to reproduce

1. Make a new instance (I used 1.15.2 with the recommended Forge version)
2. Select a bunch of curseforge mods to download 
3. Click "Download mods" and confirm

### Suspected cause

It is likely related to how mod metadata is handled

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-08-26 16:17
Can you upload the logs from when this happens?
Can you identify the certain mods? And on what Minecraft version and loader did this happen?

**Comment by Hedwig7s** [comment] 2023-08-26 18:58
> Can you upload the logs from when this happens? Can you identify the certain mods? And on what Minecraft version and loader did this happen?

No logs right now since I since downgraded my Prism again, but Forge 1.15.2 Recommended Version, and I did not identify any mods, however the curseforge download breaking seems to occur with mods with dependencies (I think JEI has one) but adding a lot of mods (except APIs since that might mess with the dependencies thing) usually did it and the no provider issue a good chunk of featured mods did that on modrinth

**Comment by Trial97** [comment] 2023-08-26 19:38
JEI doesn't have any kind of dependencies.
And sadly I can't reproduce it with just this little information.

**Comment by Hedwig7s** [comment] 2023-08-26 20:02
Here's a (hopefully) sanitized log where I got the freezing to occur
[PrismLauncher-4.log](https://github.com/PrismLauncher/PrismLauncher/files/12446651/PrismLauncher-4.log)

**Comment by Hedwig7s** [comment] 2023-08-26 20:09
It might not be if you want I can repeat it and give you a fresh log

**Comment by Hedwig7s** [comment] 2023-08-26 20:16
Retried and got a full on crash this time
[PrismLauncher-1.log](https://github.com/PrismLauncher/PrismLauncher/files/12446666/PrismLauncher-1.log)

**Comment by Trial97** [comment] 2023-08-26 20:26
Thanks, found the error: the dependency check doesn't use APIDownload object([lines](https://github.com/PrismLauncher/PrismLauncher/pull/1560/files#diff-da4c8e16ed8b731070638a3188f28c443575b981ad56a0a991d30cbdbbf3691fL134-R134) and will be fixed with the following PR: https://github.com/PrismLauncher/PrismLauncher/pull/1560

**Comment by Hedwig7s** [comment] 2023-08-26 20:36
Good to know I'm not going insane

**Closed as completed** 2023-08-27 17:21 UTC
