### ISSUE TITLE
Add the ability to search and install Texture Packs/Resoure Packs and shaders from the launcher

### ISSUE THREAD

**Issue by mateowoetam** [PrismLauncher/PrismLauncher#544] opened 2022-12-03 20:05 UTC
### Role

I would use in my Steam Deck game mode interface.

### Suggestion

Similar to the way you lookf or mods, add Resource Pack and Shader support.

### Benefit

I will no longer have to go back and forward between game mode and desktop mode in my Steam Deck and it is also more secure becuase I don't have to brwse random websites.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Both Modrinth and Curesforge already have a library of Texture Packs, so I believe It is possible to implement the following:

Modrinth:
https://modrinth.com/resourcepacks

CurseForge:
https://www.curseforge.com/minecraft/texture-packs

I also would like to inspire the same for everything, including maps, plugins, skins and more.

**Comment by DioEgizio** [comment] 2022-12-03 20:08
Duplicate of #153

**Closed as not planned by DioEgizio** 2022-12-03 20:08 UTC
Labels: status: duplicate
