### ISSUE TITLE
Fresh Windows install does not launch

### ISSUE THREAD

**Issue by emneo-dev** [PrismLauncher/PrismLauncher#2860] opened 2024-09-25 19:23 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Unknown (Most likely whatever that latest is on Windows)

### Description of bug

Cannot launch the apllication after a fresh install, even a debug build from nightly.link does not seem to make it better.
Windows reports that there is an app crash in the event viewer:
![image](https://github.com/user-attachments/assets/5e4065a5-76c5-495f-b892-33e09056f497)
![image](https://github.com/user-attachments/assets/82ede681-b843-47c5-914a-203faca48ab9)
Report.wer from the Windows event viewer when launching a debug build:
```
Version=1
EventType=APPCRASH
EventTime=133717650629884081
ReportType=2
Consent=1
UploadTime=133717650636637580
ReportStatus=268435456
ReportIdentifier=80cac53f-16d1-4820-87eb-114b49721c03
IntegratorReportIdentifier=5f4204c2-7884-4889-a795-fa3f5f1b3b55
Wow64Host=34404
NsAppName=prismlauncher.exe
AppSessionGuid=00001654-0001-0008-92e0-45a97e0fdb01
TargetAppId=W:0006fa7c5bcdb786e6087f3cf4800c96724b00000000!0000ef2d264ce0972bb27124b60d389a4748c6df5052!prismlauncher.exe
TargetAppVer=2024//09//25:00:14:05!0!prismlauncher.exe
BootId=4294967295
TargetAsId=367
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=0e21fed5a606ea5a036345324982f0b9
Response.BucketTable=4
Response.LegacyBucketId=1397036391698985145
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=prismlauncher.exe
Sig[1].Name=Application Version
Sig[1].Value=9.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=66f355cd
Sig[3].Name=Fault Module Name
Sig[3].Value=MSVCP140.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=14.22.27821.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5d0c1832
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000012aa0
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.22631.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=3072
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=50a1
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=50a145fa0ffae0d79c2e70e42d025697
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=f7ce
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=f7ced6cb5a862a2a4bf4439a630b8d00
UI[2]=C:\Users\hunte\Desktop\tmp\prismlauncher.exe
LoadedModule[0]=C:\Users\hunte\Desktop\tmp\prismlauncher.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\System32\SHELL32.dll
LoadedModule[5]=C:\Windows\System32\msvcp_win.dll
LoadedModule[6]=C:\Windows\System32\ucrtbase.dll
LoadedModule[7]=C:\Windows\System32\USER32.dll
LoadedModule[8]=C:\Windows\System32\win32u.dll
LoadedModule[9]=C:\Windows\System32\GDI32.dll
LoadedModule[10]=C:\Windows\System32\gdi32full.dll
LoadedModule[11]=C:\Windows\System32\ole32.dll
LoadedModule[12]=C:\Windows\System32\combase.dll
LoadedModule[13]=C:\Windows\System32\RPCRT4.dll
LoadedModule[14]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[15]=C:\Windows\System32\msvcrt.dll
LoadedModule[16]=C:\Windows\System32\sechost.dll
LoadedModule[17]=C:\Windows\System32\bcrypt.dll
LoadedModule[18]=C:\Users\hunte\Desktop\tmp\Qt6Xml.dll
LoadedModule[19]=C:\Users\hunte\Desktop\tmp\Qt6NetworkAuth.dll
LoadedModule[20]=C:\Users\hunte\Desktop\tmp\Qt6Network.dll
LoadedModule[21]=C:\Windows\System32\WS2_32.dll
LoadedModule[22]=C:\Users\hunte\Desktop\tmp\Qt6Core5Compat.dll
LoadedModule[23]=C:\Windows\SYSTEM32\MSVCP140.dll
LoadedModule[24]=C:\Windows\SYSTEM32\VCRUNTIME140_1.dll
LoadedModule[25]=C:\Windows\SYSTEM32\VCRUNTIME140.dll
LoadedModule[26]=C:\Users\hunte\Desktop\tmp\Qt6Widgets.dll
LoadedModule[27]=C:\Windows\SYSTEM32\MSVCP140_1.dll
LoadedModule[28]=C:\Users\hunte\Desktop\tmp\Qt6Core.dll
LoadedModule[29]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[30]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[31]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[32]=C:\Windows\SYSTEM32\Secur32.dll
LoadedModule[33]=C:\Windows\SYSTEM32\WINHTTP.dll
LoadedModule[34]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[35]=C:\Windows\SYSTEM32\UxTheme.dll
LoadedModule[36]=C:\Windows\SYSTEM32\MPR.dll
LoadedModule[37]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[38]=C:\Windows\SYSTEM32\AUTHZ.dll
LoadedModule[39]=C:\Windows\SYSTEM32\NETAPI32.dll
LoadedModule[40]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[41]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[42]=C:\Windows\SYSTEM32\SSPICLI.DLL
LoadedModule[43]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[44]=C:\Windows\SYSTEM32\SRVCLI.DLL
LoadedModule[45]=C:\Windows\SYSTEM32\NETUTILS.DLL
LoadedModule[46]=C:\Users\hunte\Desktop\tmp\Qt6Gui.dll
LoadedModule[47]=C:\Windows\SYSTEM32\d3d11.dll
LoadedModule[48]=C:\Windows\SYSTEM32\dxgi.dll
LoadedModule[49]=C:\Windows\SYSTEM32\DWrite.dll
LoadedModule[50]=C:\Windows\SYSTEM32\d3d12.dll
LoadedModule[51]=C:\Windows\SYSTEM32\MSVCP140_2.dll
LoadedModule[52]=C:\Windows\System32\IMM32.DLL
LoadedModule[53]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[54]=C:\Windows\System32\NSI.dll
LoadedModule[55]=C:\Windows\SYSTEM32\windows.storage.dll
LoadedModule[56]=C:\Windows\SYSTEM32\wintypes.dll
LoadedModule[57]=C:\Windows\System32\SHCORE.dll
LoadedModule[58]=C:\Windows\System32\shlwapi.dll
LoadedModule[59]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[60]=C:\Users\hunte\Desktop\tmp\platforms\qwindows.dll
LoadedModule[61]=C:\Windows\System32\SETUPAPI.dll
LoadedModule[62]=C:\Windows\System32\COMDLG32.dll
LoadedModule[63]=C:\Windows\SYSTEM32\WTSAPI32.dll
LoadedModule[64]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.3672_none_2713b9d173822955\COMCTL32.dll
LoadedModule[65]=C:\Windows\SYSTEM32\d3d9.dll
LoadedModule[66]=C:\Windows\SYSTEM32\dxcore.dll
LoadedModule[67]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[68]=C:\Windows\SYSTEM32\powrprof.dll
LoadedModule[69]=C:\Windows\SYSTEM32\UMPDC.dll
LoadedModule[70]=C:\Windows\System32\MSCTF.dll
LoadedModule[71]=C:\Windows\SYSTEM32\DEVOBJ.dll
LoadedModule[72]=C:\Windows\SYSTEM32\cfgmgr32.dll
LoadedModule[73]=C:\Windows\System32\clbcatq.dll
LoadedModule[74]=C:\Windows\System32\Windows.UI.dll
LoadedModule[75]=C:\Windows\System32\Windows.UI.Immersive.dll
LoadedModule[76]=C:\Users\hunte\Desktop\tmp\styles\qmodernwindowsstyle.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=22631
OsInfo[3].Key=ubr
OsInfo[3].Value=4169
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=2057
OsInfo[7].Key=geoid
OsInfo[7].Value=84
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222859872
OsInfo[15].Key=osinsty
OsInfo[15].Value=2
OsInfo[16].Key=iever
OsInfo[16].Value=11.1.22621.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32679
OsInfo[19].Key=svolsz
OsInfo[19].Value=464
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=220506
OsInfo[22].Key=bldtm
OsInfo[22].Value=1250
OsInfo[23].Key=bldbrch
OsInfo[23].Value=ni_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.22621.4169.amd64fre.ni_release.220506-1250
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=MD:283BAEF,ME:2E30985,ME:2E30A2A,ME:3036FD6,MD:3037091
OsInfo[34].Key=fconid
OsInfo[34].Value=19194309,0,2,0;19638787,0,2,0;23877894,1,2,0;26742989,0,1,0;35681102,0,1,0;36803287,0,2,1;36803295,0,2,0;38277973,0,1,0;39145991,0,2,0;39263329,1,2,0;39281392,0,2,0;40025975,0,1,0;40616880,0,1,0;40883769,0,1,0;40981503,0,1,0;41135193,0,1,1;41137130,0,1,0;41267076,0,2,0;41342175,0,1,0;41655236,0,2,0;42105254,0,2,0;43133808,1,2,1;43169616,0,1,0;43203978,0,2,1;43772553,0,1,0;43844371,0,1,0;43978769,0,1,1;44325080,0,1,0;44521793,0,1,0;44552141,0,1,0;44776738,0,2,0;45009259,0,1,0;45185354,0,2,0;45286373,0,1,0;45732051,0,2,0;45796396,0,2,0;45825686,0,1,0;45991456,0,1,1;46457961,0,1,0;46541070,0,2,0;46551074,0,1,0;46557400,0,1,0;47115450,0,1,0;47134595,0,1,0;47205155,0,2,0;47268464,2,2,0;47557358,0,2,1;47681899,0,1,0;47916854,0,1,0;47973375,0,1,0;48057519,0,2,0;48296377,0,1,0;48433541,0,2,0;48433706,0,2,0;48433719,0,1,0;48468527,0,2,0;48468541,0,2,0;48503047,0,2,0;48540091,0,2,1;49006888,0,1,1;49084341,0,1,1;49175271,0,2,1;49204591,0,1,1;49239926,0,1,1;49309588,0,1,1;49408394,0,1,0;49577493,0,1,1;49615603,0,1,1;49689210,0,1,0;49822061,0,1,0;50174338,0,1,1;50288426,0,1,1;50480279,0,1,0;50556886,0,2,0;50557073,0,1,0;50564196,0,1,0;50564332,0,1,0;50565209,0,1,0;50565295,0,1,0;50762615,0,1,1;51578581,0,1,0;51944598,0,1,0;52087985,0,1,0
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
OsInfo[38].Key=servicinginprogress
OsInfo[38].Value=0
OsInfo[39].Key=featureupdatependingreboot
OsInfo[39].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Prism Launcher
AppPath=C:\Users\hunte\Desktop\tmp\prismlauncher.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=963E639C8E84796BA7CA0965702CFEE6
MetadataHash=-1848966789
```
Debug build used: https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/11023749965/PrismLauncher-Windows-MSVC-3e60713-Debug.zip
Windows Version: Windows 11 Pro (It is a fresh install from 2 days ago)

### Steps to reproduce

Launch the app after a fresh install

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by emneo-dev** [comment] 2024-09-25 19:25
The only place where I got any logs is the Windows event viewer.
Launching Prism from the explorer.exe or from the terminal yielded absolutely nothing.

**Comment by emneo-dev** [comment] 2024-09-25 19:27
Just realized I sent the event viewer from the debug launches, but it doesn't matter at all because the output from the 8.4 stable launch is the exact same.

**Comment by Trial97** [comment] 2024-09-25 19:27
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2555

**Comment by Trial97** [comment] 2024-09-25 19:28
vcredist is required to run Prism on Windows
Like most apps on Windows, you have to install vcredist for Prism to run. Depending on what version of Prism you are using, you may need a different version.

You need:

    [vcredist 2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe) if you're using PrismLauncher-Windows-MSVC (the recommended version for Windows 10 64 bit/Windows 11).
    [vcredist 2022 arm64](https://aka.ms/vs/17/release/vc_redist.arm64.exe) if you're using PrismLauncher-Windows-MSVC-arm64 (the recommended version for Windows 10/11 on ARM).


See the [wiki page](https://prismlauncher.org/wiki/overview/frequent-issues/#%22msvcp140_2.dll-was-not-found%22) on Prism's website for more information.

**Closed as not planned by Trial97** 2024-09-25 19:27 UTC
