### ISSUE TITLE
Required offline name input on every launch

### ISSUE THREAD

**Issue by vampire369** [PrismLauncher/PrismLauncher#662] opened 2022-12-22 03:40 UTC
### Operating System

Windows

### Version of Prism Launcher

6.1

### Version of Qt

6.4.0

### Description of bug

**What did you expect to happen:**
Click Launch button, instance launched.

**What happened:** 
Clicked Launch button, get a prompt asking "Choose your offline mode player name."

**Why is it incorrect:**
Didn't happen prior to updating to 6.1 from 5.x (unsure what version it was exactly).

### Steps to reproduce

Everytime i start up prism launcher and click to launch an instance it asks for a offline mode, even though i clearly have internet access.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by minelolpride** [comment] 2022-12-22 04:07
This might be #660. You probably have to reinstall the launcher to fix it by the looks of it. (make sure to back up the `instances` `accounts.json` `prismlauncher.cfg`)

**Comment by vampire369** [comment] 2022-12-22 04:36
Reinstalled it and that fixed my issue, not sure what the actual cause is though

**Comment by DioEgizio** [comment] 2022-12-22 06:47
Duplicate of #660

**Closed as not planned by DioEgizio** 2022-12-22 06:47 UTC
