### ISSUE TITLE
Prism Launcher 8.4 not launching on Windows OS

### ISSUE THREAD

**Issue by CRxFT** [PrismLauncher/PrismLauncher#2591] opened 2024-06-29 19:07 UTC
### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Program will not run

### Description of bug

Program not launching/running on windows os

### Steps to reproduce

Prism launcher not running on windows os

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-06-29 19:12
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2564

**Closed as not planned by Trial97** 2024-06-29 19:12 UTC

**Comment by Pacomatic1** [comment] 2024-06-30 02:07
They did something with the C++ Redistributables, so go to prismlauncher.org and see the download page. It'll show what C++ Redistributables you need to download.

**Comment by CRxFT** [comment] 2024-06-30 09:35
Solved. Thanks for the help guys.
