### ISSUE TITLE
PrismLauncher 8.3 on NixOS 429 error on login

### ISSUE THREAD

**Issue by JackPala** [PrismLauncher/PrismLauncher#2526] opened 2024-06-16 21:03 UTC
### Version of Prism Launcher

8.3

### Version of Qt

6.7.1

### Description of bug

    55.719 D | AuthFlow: "Accessing Mojang services."
    55.720 D | Getting Minecraft access token...
    56.243 W | AuthRequest::onRequestError: Error 299
    56.243 W | AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/launcher/login - server replied: "
    56.243 W | AuthRequest::onRequestError: HTTP status 429 ""
    56.243 W | Reply error: QNetworkReply::UnknownContentError

### Steps to reproduce

Try to sign in with microsoft account

### Suspected cause

Other tickets appear open but the causes was related to outages. There does not appear to be a mojang outage at this time.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-06-16 21:05
429 =To many requests
and duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-06-16 21:05 UTC
