### ISSUE TITLE
Support for Sinytra Connector

### ISSUE THREAD

**Issue by pizzav-xyz** [PrismLauncher/PrismLauncher#2249] opened 2024-03-28 08:40 UTC
### Role

So I don't have to go to modrinth and download the jar file and put in mod folder.

### Suggestion

If Sinytra Connector is detected display mods for forge and fabric in the downloader.

### Benefit

Time save

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by pizzav-xyz** [comment] 2024-03-28 08:41
https://modrinth.com/mod/connector

**Comment by Trial97** [comment] 2024-03-28 09:31
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1521
And the answer was: we will not support this.
But I have a PR that allows you to filter mods for different loaders:https://github.com/PrismLauncher/PrismLauncher/pull/1728

**Closed as not planned by Trial97** 2024-03-28 09:31 UTC
Labels: type: enhancement
