### ISSUE TITLE
Make unchecked mods updatable

### ISSUE THREAD

**Issue by ColonelGerdauf** [PrismLauncher/PrismLauncher#1019] opened 2023-04-20 18:46 UTC
### Role

I have a modlist with some disabled due to the lack of a suitable version for the time being.

### Suggestion

Remove the mechanism where mods do not update when unchecked (disabled)

### Benefit

The function that restricts mod updates in that situation is pointless.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I need to question why this restriction exists in the first place. It is more annoying that when someone initiates mass updates, they are constantly bombarded with a list of "mods cannot be updated when they are disabled". Especially when they are jumbled alongside mods that lack a valid update URL, or mismatch in Minecraft version.

If this is needed, there should be an opt-in parameter where the update mechanism can SILENTLY ignore mods that are not loaded into the instance.

**Comment by Ryex** [comment] 2023-04-20 19:23
Duplicate of #603

**Comment by ColonelGerdauf** [comment] 2023-06-14 12:34
Now by explicitly selecting unchecked mods for update, we get an error instead of a notice

**Closed as completed** 2024-08-03 14:38 UTC
Labels: type: enhancement
