### ISSUE TITLE
Mod Profiles

### ISSUE THREAD

**Issue by rojebd** [PrismLauncher/PrismLauncher#1770] opened 2023-10-30 22:31 UTC
### Role

I play Modded Minecraft a LOT

### Suggestion

I want Prism Launcher to have the ability to have mod profiles

### Benefit

So that mods can be better organized and not having to load way too many mods for no reason

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I have a 1.20 Instance that I use for Skyblock and playing Anarchy Servers

In my Skyblock profile, I have Skyblock mods enabled and my Anarchy server stuff disabled (such as cheats)
In my Anarchy profile, I have my anarchy mods enabled and my Skyblock mods disabled

*Another feature (although I don't know if possible would be being able to switch profiles in-game)

This feature could help with not having to load too many mods such as loading Skyblock mods when I'm not playing Skyblock, or disabling and enabling certain mods every time I don't want them, since I could just add them to a certain profile where they are disabled or enabled.

Thus this feature would greatly help organizing mods for people who play modded Minecraft.

**Comment by Trial97** [comment] 2023-10-30 22:42
What is stopping you from using separate instances? One instance for Skyblock and one for Anarchy Servers?
And if you just want mod categories there is already a ticket for that: https://github.com/PrismLauncher/PrismLauncher/issues/1431

**Comment by SettingDust** [comment] 2023-11-01 06:37
https://modrinth.com/mod/mod-sets (ad for my mod). A restart is required

**Comment by SettingDust** [comment] 2023-11-01 06:48
> What is stopping you from using separate instances? 

For this issue. I have a different reason. I'm gonna to export more variant packs like server and client. A single instance will make it easier to sync the mods. I think two instance with recursive symlink may work. But need add mods twice.
(Haven't tested the recursive symlink since it's crashing when checking with development build
https://github.com/PrismLauncher/PrismLauncher/issues/864

**Comment by Trial97** [comment] 2023-11-01 09:10
Closing this as duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1431

**Closed as completed by Trial97** 2023-11-01 09:10 UTC
Labels: type: enhancement
