### ISSUE TITLE
Auto binary search

### ISSUE THREAD

**Issue by pizzav-xyz** [PrismLauncher/PrismLauncher#2475] opened 2024-06-06 07:09 UTC
### Role

I want to know which mod is making me crash

### Suggestion

Add a button to auto disable and enable mods for binary search 

### Benefit

I can be more lazy

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-06-06 07:15
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1924

**Closed as not planned by Trial97** 2024-06-06 07:15 UTC
Labels: type: enhancement

**Comment by pizzav-xyz** [comment] 2024-06-06 08:12
> Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1924

This is only for crash on Launch but my game crashes when I do a certain action

**Comment by Trial97** [comment] 2024-06-06 08:38
the requirements are the same: add a way to binary search mods
