### ISSUE TITLE
Change default pack import selection to include all available import file types

### ISSUE THREAD

**Issue by znepb** [PrismLauncher/PrismLauncher#2494] opened 2024-06-10 05:53 UTC
### Role

I play modded Minecraft and make modpacks.

### Suggestion

When importing modpacks from either .zip files or .mrpack files, it would be quicker and easier if the default selection included .zip files and .mrpack files, with individual file types still available.

### Benefit

It would make importing modpacks from local files quicker.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-06-10 05:55
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1865
And already implemented in 8.3

**Closed as not planned by Trial97** 2024-06-10 05:55 UTC
Labels: type: enhancement

**Comment by znepb** [comment] 2024-06-10 05:58
I apologize, I just realized I hadn't updated my client in a while. Thank you!
