### ISSUE TITLE
While getting auth for an account show error codes from HTTP requests

### ISSUE THREAD

**Issue by maxsupermanhd** [PrismLauncher/PrismLauncher#1938] opened 2023-12-10 18:26 UTC
### Role

I play modded Minecraft.

### Suggestion

Sometimes when auth servers having a moment it might be wise to either detect it or at least show user an error code instead of "failed 3 times, do you want to keep failing?"

### Benefit

Will reduce load from downed auth servers and better inform user about the ongoing auth server moment.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by dark-steveneq** [comment] 2023-12-10 18:47
Same thing's happening to me!

**Comment by Fedan27** [comment] 2023-12-10 18:53
I have the same thing, I logged out of my account to re-login, now I can’t log back in

**Comment by kittech0** [comment] 2023-12-10 18:57
same thing

**Comment by KeiBoogie** [comment] 2023-12-10 19:00
wtf is going on, pls fix!!!

**Comment by Fedan27** [comment] 2023-12-10 19:01
![image](https://github.com/PrismLauncher/PrismLauncher/assets/90526777/05097a2f-dde4-4a07-bffd-1b80450caf5b)

**Comment by gxtu** [comment] 2023-12-10 19:05
Looks like there are currently problems with login/authentication on Microsoft's side **unrelated to PrismLauncher**. Please have some patience.

**Comment by Hi-ImKyle** [comment] 2023-12-10 19:08
Maybe Prism needs a status indicator somewhere to show users that Minecraft is down or having issues

**Comment by Trial97** [comment] 2023-12-10 19:10
> Maybe Prism needs a status indicator somewhere to show users that Minecraft is down or having issues

The status API was removed a long time ago. So until there is an alternative this is not doable

**Comment by Fedan27** [comment] 2023-12-10 19:28
![image](https://github.com/PrismLauncher/PrismLauncher/assets/90526777/3b4b5fef-8c20-4368-991a-d6bf13c4d760)

**Comment by CompaqDisc** [comment] 2023-12-10 19:42
I have verified Prism does not work when adding an account.

Authentication seems to work correctly on the Modrinth launcher for both adding an account and launching. This issue could be Prism-specific, but I do not know for sure.

**Comment by dark-steveneq** [comment] 2023-12-10 19:49
That's a bit weird. At least you can still launch the game using an offline account.

**Comment by Chifilly** [comment] 2023-12-10 19:53
Same issue. My related post in #1904 is similar; other launchers work fine except Prism

**Comment by dark-steveneq** [comment] 2023-12-10 19:55
Maybe something broke with the current API key?

**Comment by CompaqDisc** [comment] 2023-12-10 20:00
> Same issue. My related post in #1904 is similar; other launchers work fine except Prism

Technic Launcher and ATLauncher are also broken, it seems.

Although most of the comments here seem to be more related to #1904 
Should discussion move over there?

![image](https://github.com/PrismLauncher/PrismLauncher/assets/12076803/7dfbd6e8-b01e-4a13-85e6-a5c5ea38ba98)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/12076803/0880ff8c-3856-43c0-ad14-51e3a49efbec)

**Comment by maxsupermanhd** [comment] 2023-12-10 20:01
Issue is not about auth servers being down but about launcher not informing user that it is down. Please stop spamming with "it does not work for me too" type of messages, it will not help. (for me it already works)

**Comment by CompaqDisc** [comment] 2023-12-10 20:03
@maxsupermanhd 
> Issue is not about auth servers being down but about launcher not informing user that it is down. Please stop spamming with "it does not work for me too" type of messages, it will not help. (for me it already works)

Which is why I suggested moving most of the discussion here to #1904 because that seems to be getting confused with your unrelated issue.

**Comment by Trial97** [comment] 2024-04-12 16:30
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2171

**Closed as not planned by Trial97** 2024-04-12 16:30 UTC
Labels: type: enhancement, area: auth
