### ISSUE TITLE
Instance Backup System

### ISSUE THREAD

**Issue by Rafii2198** [PrismLauncher/PrismLauncher#142] opened 2022-10-19 21:53 UTC
### Role

Player

### Suggestion

Ability to make an backups within Prism and rollback to them

### Benefit

Very easy way for users to prevent corruption of their instances

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This feature is now more beneficial because of modpack updating, it could suggest making a backup when updating a modpack for safety, the updater suggests it already, but there is no automatic way to do it.
I imagine it being another entry in instance option (like next to mods, resource packs, world, setting, etc.), with buttons to create one and rollback to one when any is selected. The default name for a backup would be just a current date-time and for updating modpack an additional suffix of `-before_update` or something to make it stand out a bit. Obviously, the user is able to choose their own name and rename current ones. Maybe more options like compression settings and auto deletion for old ones would be nice too.

**Comment by Scrumplex** [comment] 2022-11-27 22:21
Duplicate of #109

**Closed as not planned by Scrumplex** 2022-11-27 22:21 UTC
Labels: type: enhancement
