### ISSUE TITLE
allow mods to be grouped like instances

### ISSUE THREAD

**Issue by microlith57** [PrismLauncher/PrismLauncher#217] opened 2022-10-21 23:54 UTC
### Goal

allow users to group mods within instances, collapse groups to take up only one row in the mod list, disable whole groups, and so on.

### Motivation

currently, long modlists are difficult to organise, because it is not possible to put mods in folders.
by allowing mods to be grouped in a similar way to instances, long modlists could be more easily organised and managed; for example, library mods could be separated from optimisation mods, and kept in separate places in the modlist.

### Specification

- add an optional group field to the mod metadata
- group mods in the list based on this field, leaving them at the top level if it isn't present
- fold groups using a disclosure triangle
- disable mods based on both the group's checkbox and the mod's checkbox
  - somehow remember the mod's checkbox state separately to whether the mod is actually enabled, probably in the metadata

### Drawbacks

- this might be confusing when folders are involved
- people might not notice a group is disabled and wonder why a mod isn't loading when its checkbox is ticked
  - maybe the group-disabled mods could be greyed out?

### Unresolved Questions

what happens if metadata information is lost?

### Alternatives Considered

- putting the mods in folders and symlinking them (platform dependent, potentially problematic)
- storing the group in the jar filename, eg. `performance__sodium-fabric-mc1.19.2-0.4.4+build.18.jar` (what if a mod is named inconveniently?)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment] 2022-10-21 23:56
Duplicate of #154

**Closed as completed by flowln** 2022-10-21 23:56 UTC
Labels: status: duplicate, status: needs discussion

**Comment by microlith57** [comment] 2022-10-22 00:01
didn't search well enough haha
