### ISSUE TITLE
[Linux] [MangoHud] Prism makes MangoHud load default config

### ISSUE THREAD

**Issue by Splarkszter** [PrismLauncher/PrismLauncher#989] opened 2023-04-11 17:06 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 5.15.8

### Description of bug

MangoHud loads it's default config ONLY when using Prism.

MultiMC, PolyMC, any other 3D renderer loads the MangoHud config correctly. Prism doesn't.

Prism and PolyMC are installed as Flatpak, MultiMC isn't.

Config has been set by GOverlay.

### Steps to reproduce

Using: Linux Mint Cinnamon 21.1 | AMD Kavery GPU

* In my case i have Built MangoHud from source due to some library thing or something with the binary.
* Do the `$PATH=` thing for mangohud to be usable.
* Configure MangoHud either manually or with GOverlay.
* Install the [org.freedesktop.Platform.VulkanLayer.MangoHud](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud)
* Add wrapper command `mangohud --dlsym` on Prism (DO NOT enable `Enable MangoHud` on Prism GUI yet)
* Load game, config should load correctly... or maybe it doesn't.
* Now do `Enable MangoHud` on Prism GUI.
* When minecraft loads MangoHud it's on it's default setting.

### Suspected cause

When only using the wrapper command `mangohud --dlsym` Prism worked fine and loaded the config correctly. But when i pressed the `Enable MangoHud` on the GUI of Prism i started having this problem.

Even if i disable it, togle it, restart the system, rewrite the config, delete the command, load, re-add the command. Nothing solves it, AND it ONLY happens on Prism.

If i use the same wrapper command on either MultiMC or PolyMC... both load MangoHud config correctly.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Splarkszter** [comment] 2023-04-11 23:41
Ummmmmm... the problem solved itself after restarting my PC just now... only thing i did differently in that session that could have solved it was running `apt update` and `apt upgrade` because i was installing something... so... that's weird. I do believe it was that because otherwise i have no idea.

**Comment by Splarkszter** [comment] 2023-04-12 22:14
I'm going to leave this open just in case it's possible to reproduce it, if not, feel free to close the issue.

**Comment by Scrumplex** [comment] 2023-04-13 05:28
If someone else can reproduce this, we can just reopen the issue or they can create a new issue.

Therefore I am closing this for now

**Closed as not planned by Scrumplex** 2023-04-13 05:28 UTC

**Comment by JordanPlayz158** [comment] 2024-03-03 21:11
This may happen when Prism Launcher does not have access to the config file, just make sure that prism launcher has access to `xdg-config/MangoHud:ro` (assuming your MangoHud config is stored at `~/.config/MangoHud`), either via Flatseal or via command `flatpak override --user --filesystem=xdg-config/MangoHud:ro org.prismlauncher.PrismLauncher`

**Comment by sgtM-devs** [comment] 2026-05-29 06:44
> `xdg-config/MangoHud:ro` (assuming your MangoHud config is stored at `~/.config/MangoHud`), either via Flatseal or via command `flatpak override --user --filesystem=xdg-config/MangoHud:ro org.prismlauncher.PrismLauncher`

I can confirm this as a solution

I was a bit confused: because this didn't work in Flatseal: `~/.config/MangoHud:ro`
But this DOES work: `xdg-config/MangoHud:ro`
