### ISSUE TITLE
Deleted instances should go to the trash folder

### ISSUE THREAD

**Issue by ActuallyTheOwner** [PrismLauncher/PrismLauncher#2618] opened 2024-07-07 02:12 UTC
### Role

I manage several modded and vanilla instances

### Suggestion

I want deleted instances to go into the trash folder

### Benefit

This mitigates accidental instance deletion

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Deleted instances could be put in the trash folder by default, or this option could be turned off. This saves headaches if the wrong instance is deleted. 

I found a similar request, but it does not seem to be working on my Debian machine.
I use a backported kernel 6.7.12+bpo-amd64 
I am on DE: Plasma 5.27.5 and use the flatpak version of Prismlauncher version 8.4

https://github.com/PrismLauncher/PrismLauncher/pull/561

**Comment by Trial97** [comment] 2024-07-07 05:47
Duplicate of:https://github.com/PrismLauncher/PrismLauncher/issues/289
Also, another reference if this is strictly for just adding an option to control what happens with the deleted instance: https://github.com/PrismLauncher/PrismLauncher/issues/1009

**Closed as not planned by Trial97** 2024-07-07 05:47 UTC
Labels: type: enhancement

**Comment by Aces-and-Jacks** [comment] 2024-07-08 01:21
I thought this is already a thing. My instances go into system trash, and if I want to recover I just move it back

**Comment by Trial97** [comment] 2024-07-08 05:13
> I thought this is already a thing. My instances go into system trash, and if I want to recover I just move it back

It does work, but on some systems(and probably Flatpak) qt fails to find the path to the trash can; when Prism removes an instance it tries to trash it, and only if that fails it deletes the filles/folders.

**Comment by ActuallyTheOwner** [comment] 2024-07-15 19:17
> > I thought this is already a thing. My instances go into system trash, and if I want to recover I just move it back
> 
> It does work, but on some systems(and probably Flatpak) qt fails to find the path to the trash can; when Prism removes an instance it tries to trash it, and only if that fails it deletes the filles/folders.

I was on flatpak on Debian bookworm, but need to test trixie
I don't think this is a duplicate as I was suggesting use of system trash, not perm deleting as a suggestion
