### ISSUE TITLE
Instance Shortcuts

### ISSUE THREAD

**Issue by Shoddyy** [PrismLauncher/PrismLauncher#251] opened 2022-10-23 11:24 UTC
### Role

I play modded MC

### Suggestion

Return the "Create Instance Shortcut" Button

### Benefit

Easily launch instances right from your desktop without even opening the launcher

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The developer version of MultiMC already has this feature, so I believe Prism might already have it within the code, it's just not accessible by the user. If not, it should be easy to implement by pasting straight from MultiMC's developer version. (I have no knowledge of how coding works, I'm just assuming)
Please add this feature so I can switch off MultiMC!

**Comment by flowln** [comment] 2022-10-23 11:32
Duplicate of #210

**Closed as not planned by flowln** 2022-10-23 11:32 UTC
Labels: status: duplicate, type: enhancement
