### ISSUE TITLE
Downloads stop working part way through downloading mods

### ISSUE THREAD

**Issue by minnie1089** [PrismLauncher/PrismLauncher#1199] opened 2023-06-15 18:03 UTC
### Version of Prism Launcher

Prism Launcher 7.0

### Version of Qt

Qt 6.5.1

### Description of bug

When trying to download a modpack (only tested with curseforge packs), it will download most of the mods, but some of them will stop downloading part way through, causing the modpack download to never complete.

Attached is an image example. It stayed like this for at least an hour before I manually aborted the download
![2023-06-15T15:12:24+00:00](https://github.com/PrismLauncher/PrismLauncher/assets/67824161/02a3cbfc-a566-4aa5-a890-432eddc18234)

### Steps to reproduce

Download a modpack (only tested for curseforge)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by minnie1089** [comment] 2023-06-15 18:12
I tested an FTB legacy modpack and it seemed to be fine as well as an ATLauncher pack and a Modrinth pack. Technic also works fine. I can't test modern FTB modpacks because the option hasn't appeared for me since the latest update.

The download speeds on non curse forge modpacks seemed to reflect my internet speed better than the KiB/s I got with curseforge packs.

Probable curseforge being curseforge

**Comment by minnie1089** [comment] 2023-06-21 14:22
Just checked for version 7.1, issue is still present for Curseforge packs, haven't checked others on this version
![2023-06-21T14:20:46+00:00](https://github.com/PrismLauncher/PrismLauncher/assets/67824161/50a22f4f-10dd-4b92-8f7a-35ce6f70b4fd)

**Comment by Trial97** [comment] 2023-06-28 06:51
Can you try the nightly build(https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/5394098599) and see if this is still reproducing?

**Comment by minnie1089** [comment] 2023-06-30 15:35
Still not fixed on the latest version on the AUR, I can try it with the one on the link, but I don't like downloading applications outside of the AUR unless I have to
![2023-06-30T15:32:36+00:00](https://github.com/PrismLauncher/PrismLauncher/assets/67824161/84f6f67f-1600-47d3-be77-b5965f4e9d0a)

**Comment by minnie1089** [comment] 2023-06-30 15:36
The slow download speed may be on my part because downloading mods manually from curse through firefox is at a similar slow speed

**Comment by Trial97** [comment] 2023-08-09 21:47
Here is a small update regarding this:
- another try to fix this was made in:https://github.com/PrismLauncher/PrismLauncher/pull/1102
- it was not yet merged in develop but in staging(due to code formatting conflicts) https://github.com/PrismLauncher/PrismLauncher/pull/1486
- you can try to see if you are still reproducing this using the artifacts from here: https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/5784443314

**Comment by Trial97** [comment] 2024-01-15 15:10
Hi, can you please try to reproduce this using the latest nightly builds: https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop

**Comment by minnie1089** [comment] 2024-01-15 18:21
I can have a go, but since this issue was started, my laptop has kicked the bucket, and I haven't checked if the issue is still present on my new computer. Should be because it has mostly the same software.

**Comment by minnie1089** [comment] 2024-01-19 20:52
I just downloaded ATM 9 with no issues on my current computer on Prism Launcher 8.0, so either it has been fixed, or my computer is not affected. Trying on my old laptop is not really an option as it is dead as doornails

**Comment by Trial97** [comment] 2024-01-19 22:18
> I just downloaded ATM 9 with no issues on my current computer on Prism Launcher 8.0, so either it has been fixed, or my computer is not affected. Trying on my old laptop is not really an option as it is dead as doornails

In that case, I will close this as completed. If you encounter this in the future please feel free to reopen it.

**Closed as completed by Trial97** 2024-01-19 22:18 UTC
Labels: status: not enough info
