### ISSUE TITLE
Add an automatic java installer to launcher???

### ISSUE THREAD

**Issue by steazzy** [PrismLauncher/PrismLauncher#1460] opened 2023-07-29 19:27 UTC
### Role

yes

### Suggestion

Add an automatic java installer to launcher to

### Benefit

that`s more comfortable in most ways

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment] 2023-07-29 19:45
nice idea =)

but it's a duplicate of #734 :(

**Closed as not planned by TheKodeToad** 2023-07-29 19:45 UTC
Labels: type: enhancement
