### ISSUE TITLE
Prism hangs on the main screen after closing an instance that has been running for long periods

### ISSUE THREAD

**Issue by Eutropios** [PrismLauncher/PrismLauncher#1928] opened 2023-12-09 04:37 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher v8.0.0 on Windows 11 23H2

### Version of Qt

Qt v6.6.0

### Description of bug

After playing for a significant amount of time (ex: 4 hours) and closing out Minecraft, if you click on the `edit` button for the instance, Prism hangs. It continues to hang until the Windows report popup appears. This has only started to occur since Prism 8.0.0, and occurs regardless of whether or not mods are used.

Windows specs:
Edition:	Windows 11 Home
Version:	23H2
Installed on:	‎2023-‎05-‎01
OS build:	22631.2792
Experience:	Windows Feature Experience Pack 1000.22681.1000.0

Laptop specs:
Device name:	noahj-Lenovo
Processor:	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   2.00 GHz
Installed RAM:	8.00 GB
System type:	64-bit operating system, x64-based processor

### Steps to reproduce

1. Play any instance for long periods of time (exact length is undetermined, but from experience, play sessions greater than 4 hours cause the bug), making sure that Prism Launcher is still open, but the instance settings are closed.
2. Close Minecraft by clicking Quit Game button on the main menu, or by clicking the red x button on the top right.
3. Click the Edit button on the right side of the Prism Launcher Window for a specific instance.
4. Prism Launcher window becomes unresponsive and hangs. No amount of waiting frees the program.

### Suspected cause

I did some digging. First, I went to Event Viewer and found the following error log (in XML format for easier reading):
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" Guid="{c631c3dc-c676-59e4-2db3-5c0af00f9675}" /> 
    <EventID>1002</EventID> 
    <Version>0</Version> 
    <Level>2</Level> 
    <Task>101</Task> 
    <Opcode>0</Opcode> 
    <Keywords>0x8000000000000000</Keywords> 
    <TimeCreated SystemTime="2023-12-08T05:19:58.8693199Z" /> 
    <EventRecordID>49286</EventRecordID> 
    <Correlation /> 
    <Execution ProcessID="292" ThreadID="17892" /> 
    <Channel>Application</Channel> 
    <Computer>noahj-Lenovo</Computer> 
    <Security UserID="S-1-5-18" /> 
  </System>
  <EventData>
    <Data Name="AppName">prismlauncher.exe</Data> 
    <Data Name="AppVersion">8.0.0.0</Data> 
    <Data Name="ProcessId">0x5104</Data> 
    <Data Name="StartTime">0x1da29517d499b66</Data> 
    <Data Name="TerminationTime">37</Data> 
    <Data Name="ExeFileName">C:\Users\noahj\AppData\Local\Programs\PrismLauncher\prismlauncher.exe</Data> 
    <Data Name="ReportId">b0922577-96ca-4688-94ae-05e393cb2441</Data> 
    <Data Name="PackageFullName" /> 
    <Data Name="PackageRelativeAppId" /> 
    <Data Name="HangType">Unknown</Data> 
  </EventData>
</Event>
```

The description led me to the `Security and Maintenance` program, which showed the following error logs:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/64815328/4842a33a-e96b-4e24-a30c-df6b478dd3b9)
The Hang Type and Hang Signature 1 are consistent across all logs of each crash instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-12-09 10:55
Duplicate of #463

**Closed as not planned by Trial97** 2023-12-09 10:55 UTC
