### ISSUE TITLE
Prism closes when deleting instance

### ISSUE THREAD

**Issue by DJDrWright** [PrismLauncher/PrismLauncher#2162] opened 2024-02-25 13:23 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

I highlight an instance, click delete, Prism closes/crashes. When I reopen the instance is gone.

### Steps to reproduce

*highlight instance
*click delete in right side menu
*Prism closes
*reopen Prism, instance is gone.

### Suspected cause

Do not know.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-02-28 07:47
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1675

**Closed as not planned by Trial97** 2024-02-28 07:47 UTC
