### ISSUE TITLE
Prism can't reach to microsoft for account authication, and can't even add an account to it

### ISSUE THREAD

**Issue by AsrielDewitt** [PrismLauncher/PrismLauncher#1904] opened 2023-12-01 14:57 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

6.6.0

### Description of bug

The launcher couldn't reach to auth server and can't reach to Microsoft to log in

[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/13528017/PrismLauncher-0.log)
[PrismLauncher-0 (1).log](https://github.com/PrismLauncher/PrismLauncher/files/13528018/PrismLauncher-0.1.log)

### Steps to reproduce

Just refresh or try to click add account

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-12-01 15:46
Something is blocking PrismLauncher network requests.
Similar to: https://github.com/PrismLauncher/PrismLauncher/issues/1875

Try:
Make sure you do not have any firewall rules that would block PrismLauncher.
Try using the portable version if that works go do a reinstall of prism but make sure you delete all the files from the previous version(https://github.com/PrismLauncher/PrismLauncher/issues/1031#issuecomment-1580782178). And I mean the ones found in the installation directory, not the data directory ones.

**Comment by AsrielDewitt** [comment] 2023-12-01 16:29
> Something is blocking PrismLauncher network requests. Similar to: #1875
> 
> Try: Make sure you do not have any firewall rules that would block PrismLauncher. Try using the portable version if that works go do a reinstall of prism but make sure you delete all the files from the previous version([#1031 (comment)](https://github.com/PrismLauncher/PrismLauncher/issues/1031#issuecomment-1580782178)). And I mean the ones found in the installation directory, not the data directory ones.

Firewalls isn't blocking prism, I already am using portable version and I am using a fresh portable version, nothing else touch beside account

**Comment by Chifilly** [comment] 2023-12-10 18:10
I have the same issue. I played perfectly fine 2 days ago, but trying to play today I can't log in. I tried to remove my account and log back in, and after authenticating with Microsoft I get `Error transferring https://api.minecraftservices.com/launcher/login - server replied: Service Unavailable`.

These are the relevant parts of the logs:
```
     8.636 D | AuthFlow: "Logging in with Microsoft account."
     8.636 D | DeviceFlow::link
     8.636 D | DeviceFlow::setLinked: false
     8.636 D | [katabasis.credentials]: new refresh token: ""
     9.034 D | DeviceFlow::onDeviceAuthReplyFinished
     9.034 D | DeviceFlow::onDeviceAuthReplyFinished: Tokens returned:

     9.041 D | "device_code" :  "[REDACTED]"
     9.041 D | "expires_in" :  "900"
     9.041 D | "interval" :  "5"
     9.041 D | "message" :  "To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code 6SRW5TGA to authenticate."
     9.041 D | "user_code" :  "[REDACTED]"
     9.041 D | "verification_uri" :  "https://www.microsoft.com/link"
     9.041 D | DeviceFlow::onDeviceAuthReplyFinished: Device auth request response
     9.042 D | DeviceFlow::startPollServer: device_ and user_code expires in 900 seconds
     9.910 D | Opening URL "https://www.microsoft.com/link"
    14.467 D | PollServer::onPollTimeout: retrying
    19.468 D | PollServer::onPollTimeout: retrying
    24.467 D | PollServer::onPollTimeout: retrying
    25.022 D | DeviceFlow::onVerificationReceived: Emitting closeBrowser()
    25.022 D | DeviceFlow::onVerificationReceived: Access token returned for implicit or device flow
    25.022 D | DeviceFlow::onVerificationReceived: Token expires in 3600 seconds
    25.022 D | [katabasis.credentials]: new refresh token: "[REDACTED]"
    25.022 D | DeviceFlow::setLinked: true
    25.022 D | AuthFlow: "Logging in as an Xbox user."
    25.022 D | First layer of XBox auth ... commencing.
    25.884 D | Parsing "UToken" :
    25.884 D | "UToken" is valid.
    25.884 D | AuthFlow: "Getting authorisation to access Xbox services."
    25.884 D | Getting authorization token for  "http://xboxlive.com"
    26.445 D | Parsing "Xbox" :
    26.445 D | "Xbox" is valid.
    26.445 D | AuthFlow: "Getting authorisation to access Mojang services."
    26.445 D | Getting authorization token for  "rp://api.minecraftservices.com/"
    26.695 D | Parsing "Mojang" :
    26.695 D | "Mojang" is valid.
    26.695 D | AuthFlow: "Accessing Mojang services."
    26.695 D | Getting Minecraft access token...
    26.896 W | AuthRequest::onRequestError: Error 403
    26.896 W | AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/launcher/login - server replied: Service Unavailable"
    26.896 W | AuthRequest::onRequestError: HTTP status 503 "Service Unavailable"
    26.896 W | Reply error: QNetworkReply::ServiceUnavailableError
```

The official Minecraft Launcher and the FTB App both work fine.

I tried the portable version, the deb and the AppImage, and they're not working either (I normally use the Flatpak).

**Comment by KTrain5169** [comment] 2023-12-11 10:46
Visiting the site throws an "The request is blocked" error, so that may be why it's not connecting.

Edit: After posting this comment, I went and tested removing and re-adding an alt account, and it works perfectly. Which is weird because I just said that on the API website mentioned above, it says "The request is blocked" and based on other reports here it shouldn't be working?

**Comment by Chifilly** [comment] 2023-12-11 14:11
It started working for me again too. I'm not sure what happened initially though, especially considering I only had an issue with Prism Launcher

**Comment by Trial97** [comment] 2024-04-12 16:27
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-04-12 16:27 UTC
Labels: area: auth
