### ISSUE TITLE
Mods tab "Change Version" crash when clicking 'reinstall' when 'No valid version found.' selected

### ISSUE THREAD

**Issue by P3NG00** [PrismLauncher/PrismLauncher#3118] opened 2024-11-20 04:00 UTC
### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.7.3

### Description of bug

Mods tab "Change Version" crash when clicking 'reinstall' when 'No valid version found.' selected

### Steps to reproduce

When editing an instance in the Mods tab. Click a mod and click "Change Version". If no valid version can be found it will report 'No valid version found' in the dropdown. If you continue to click 'reinstall' for some reason like I did, the entire program crashes instantly.

### Suspected cause

Probably wasn't expecting someone stupid like me to come along, but here we are.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-11-20 07:38
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/3001
(Already fixed in nightly builds)

**Closed as not planned by Trial97** 2024-11-20 07:38 UTC
