### ISSUE TITLE
Prism Launcher hangs when launching an instance, and giving up after 3-4~ minutes. Saying it crashed.

### ISSUE THREAD

**Issue by foognocchie** [PrismLauncher/PrismLauncher#3120] opened 2024-11-20 19:41 UTC
### Operating System

Windows

### Version of Prism Launcher

9.1

### Version of Qt

6.3.7

### Description of bug

When launching the instance (be it vanilla, fabric or forge) i get a window starting up the launcher.

![image](https://github.com/user-attachments/assets/81942ddf-88dc-4b14-9652-ae6618366272)

Then after some time, the window closes, saying the instance has crashed. Looking at the game log it says the following

```
Instance update failed because: Component metadata update task failed while downloading from remote server:
One or more subtasks failed
One or more subtasks failed
One or more subtasks failed
```

(here's the log file if needed https://pastebin.com/mZ5SFQEG)

### Steps to reproduce

I installed the launcher

Logged in my Microsoft account

Tried to launch my imported instance (and failed)

### Suspected cause

When reading the final lines at the log, i saw something failing to download something. **I probably expect a firewall blocking something important on my home router (which is not managed by me)**

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by foognocchie** [comment] 2024-11-20 22:31
After a through investigation i found out that `meta.prismlauncher.org` is being blocked due to court action(?) [as found here before on issue #3039 ](https://github.com/PrismLauncher/PrismLauncher/issues/3039#issuecomment-2467708278)

**Comment by Trial97** [comment] 2024-11-21 10:01
So you are also not able to access that link in the browser?

**Comment by foognocchie** [comment] 2024-11-21 16:21
Nope, I can’t, my cellular data works fine (since its a completely different ISP, being Vivo)

**Comment by Trial97** [comment] 2024-11-21 16:23
Ok then I will close this as a duplicate of the issue you mentioned previously

**Closed as not planned by Trial97** 2024-11-21 16:23 UTC
