### ISSUE TITLE
Allow mods from other modloader to be downloaded when certain mods are active

### ISSUE THREAD

**Issue by cylian914** [PrismLauncher/PrismLauncher#1890] opened 2023-11-23 21:00 UTC
### Role

Downloading mods

### Suggestion

add a buton do download mods from other modloader 

### Benefit

Some mods allow mods from other modloader to be loaded.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Hi,
Currently prism launcher detect the modloader to propose only mods compatible for that modloader in the download tabs.
This is good but it doesn't detect if there is a mods that allow you to load mods on other mod loader (like [synitra connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector)).

**Comment by Trial97** [comment] 2023-11-23 21:19
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1616
Implemented on: https://github.com/PrismLauncher/PrismLauncher/pull/1728

**Closed as not planned by Trial97** 2023-11-23 21:19 UTC
Labels: type: enhancement
