### ISSUE TITLE
Automagically refresh expired account sessions as an instance is launched

### ISSUE THREAD

**Issue by eizengan** [PrismLauncher/PrismLauncher#2027] opened 2024-01-11 21:50 UTC
### Role

End user

### Suggestion

Automagically refresh expired account sessions as an instance is launched

### Benefit

Prism would no longer require toil to start the instance with the selected account

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The status quo:
- I set up Prism with a working Microsoft account
- I start Prism
- I do something else for a while - my account session expires
- I come back, and try to launch an instance
- Prism attempts to launch the instance in offline mode instead of using the selected account
- To launch with my account I have to restart Prism or refresh the account in "account management"

Prism seems to be aware of the account's state (e.g. in account management the account has "not ready" status), so it seems reasonable to refresh a "not ready" account before attempting to launch an instance. This could happen after user confirmation if there is some concern I've overlooked.

**Comment by Trial97** [comment] 2024-01-11 21:57
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/520
Also already fixed in develop

**Closed as not planned by Trial97** 2024-01-11 21:57 UTC
Labels: type: enhancement

**Comment by eizengan** [comment] 2024-01-11 22:10
That's what I get for only looking at _open_ issues, I suppose 😅 

Thanks for triaging~
