### ISSUE TITLE
Constant Microsoft account "Logout"

### ISSUE THREAD

**Issue by ChippyLa** [PrismLauncher/PrismLauncher#2782] opened 2024-09-04 23:01 UTC
### Operating System

Windows

### Version of Prism Launcher

8.4

### Version of Qt

6.6.2

### Description of bug

I constantly have to remove and re-add my microsoft account to Prism because of a bug causing constant "invalid login" error when trying to join servers. The error on minecraft says to restart the launcher, but it never works and I have to remove and re-add my microsoft account to prism to fix it. I have to do it multiple times a day.

### Steps to reproduce

Launch minecraft, join sevrers until it gives "invalid login" or session or whatever it says

### Suspected cause

No idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-09-05 06:27
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/520
and more specifically: https://github.com/PrismLauncher/PrismLauncher/issues/520#issuecomment-2189835136
There was an issue with the refresh that was fixed in the nightly version.

Here are a few solutions for you:
- Try nightly:
You can download unstable builds [here](https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop).

    :warning: Caution
    Unstable builds have more bugs and are therefore more likely to break! By using the latest commit you are using software which has not been properly tested. For this reason we recommend using Portable or AppImage builds, or least making a backup.

If the issue persists nightly: 
- change your account password then  - navigate to https://account.live.com/consent/Manage
-  Make sure to log in using the account where you have your issue
-  Find Prism Launcher -> Edit -> Remove these permissions (remove any permissions that you do not use)
-  Do the login with Prism Launcher again and see if that fixes it

**Closed as not planned** 2024-09-05 06:27 UTC
