### ISSUE TITLE
Automatic Update Check - Disable Messagebox on Update Check

### ISSUE THREAD

**Issue by TheBrambleShark** [PrismLauncher/PrismLauncher#2685] opened 2024-07-27 18:24 UTC
### Role

Automatic Update of Launcher

### Suggestion

Disable the "no updates available" popup when automatically checking for updates.

### Benefit

Automatic update checks should take place in the background.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Currently, when automatically checking for updates, a prompt appears to indicate that there are no new versions. This is fine when manually checking for updates as users expect feedback about the availability of an update. However, when checking for updates in the background, this function should operate silently unless there is an update available to download.

This suggestion is to:
1. Disable the "no updates available" prompt when checking for updates automatically.
2. Optionally, place this status in a different field, such as in the status bar at the bottom of the launcher. This label could read "Last checked for updates at 2:43 PM." This gives feedback to the user that the automatic update check is checking, but without being in your face and needing to dismiss the prompt before you can interact with the launcher.

**Comment by Trial97** [comment] 2024-07-27 21:44
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2579

**Closed as not planned by Trial97** 2024-07-27 21:44 UTC
Labels: type: enhancement
