### ISSUE TITLE
Open Instance folder not working

### ISSUE THREAD

**Issue by Blacky25** [PrismLauncher/PrismLauncher#3151] opened 2024-11-30 10:54 UTC
### Version of Prism Launcher

9.1

### Version of Qt

6.2.4

### Description of bug

Open instance folder Button does nothing

### Steps to reproduce

Right click on open instance folder

### Suspected cause

Output i get:
`Opening URL "file:///xxx/PrismLauncher/instances/1.20.1(1)"
nemo: /xxx/PrismLauncher/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libexempi.so.8)
`

GLIBCXX_3.4.29 is missing?

i navigated in the lib folder and executed:
`strings libstdc++.so.6 | grep GLIBCXX`

output was:
`GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH`

Looks like GLIBCXX_3.4.29 is missing in the PrismLauncher/lib/libstdc++.so.6 file if I understand it correctly

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-12-05 08:11
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/3140
Portable on linux is known to cause this kind of issue.

**Closed as not planned by Trial97** 2024-12-05 08:11 UTC
