### ISSUE TITLE
In-app downloader crash

### ISSUE THREAD

**Issue by CaitlynMC** [PrismLauncher/PrismLauncher#1116] opened 2023-06-06 18:51 UTC
### Operating System

Windows 11

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2

### Description of bug

The app crashes while scrolling through the in-app downloader, the cursor will load for a second or so before Prism crashes

### Steps to reproduce

Go to Download Mods on any instance, go to either the Modrinth or Curseforge, and scroll down rapidly until the crash occurs.

### Suspected cause

Right before the crash it does the NetJob Modrinth::Search twice with the modrinth tab crash

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TayouVR** [comment] 2023-06-06 19:56
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1002 and https://github.com/PrismLauncher/PrismLauncher/issues/1006

I believe this is fixed in develop, will be in the next release (soon™)

**Closed as completed** 2023-06-06 19:57 UTC
Labels: status: duplicate
