### ISSUE TITLE
One or more subtasks failed

### ISSUE THREAD

**Issue by Binbosusi** [PrismLauncher/PrismLauncher#3136] opened 2024-11-24 20:40 UTC
### Operating System

Windows

### Version of Prism Launcher

9.1

### Version of Qt

I don't know

### Description of bug

[PrismLauncher-0.log](https://github.com/user-attachments/files/17894790/PrismLauncher-0.log)

### Steps to reproduce

When I try to launch my modpack

### Suspected cause

No ideia

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-11-24 20:49
sounds like a duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/3039

**Comment by Binbosusi** [comment] 2024-11-24 21:25
> sounds like a duplicate of #3039

Reading the mentioned problem I noticed the similarities, other strange things that I noticed in my prism, was that the button to edit the instances takes time to work normally and also when I try to create a new instance In the box to select the versions, the message appears: no versions are currently available. This is my first time using prism have no idea if these issues are connected.

**Comment by Trial97** [comment] 2024-11-25 12:45
yep duplicate, try some of the comments there

**Closed as not planned by Trial97** 2024-11-25 12:45 UTC
