### ISSUE TITLE
Large mod operations can be really unstable

### ISSUE THREAD

**Issue by Hedwig7s** [PrismLauncher/PrismLauncher#2822] opened 2024-09-15 14:57 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 5.15.13

### Description of bug

When doing large operations involving mods (updating, creating metadata, checking dependencies, downloading large amounts of mods, etc...), the launcher will often randomly crash with no explanation

### Steps to reproduce

* Do a heavy operation as mentioned previously
* The launcher might crash (may take a few attempts)

### Suspected cause

Likely an operation failing propagating to the rest of the launcher instead of being handled

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Hedwig7s** [comment] 2024-09-15 14:58
Note: This doesn't seem to be OS specific, as I've experienced it on Windows too

**Comment by Trial97** [comment] 2024-09-16 09:01
This should be a duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1638
But most probably, it is a regression.
Out of curiosity how many mods are we talking about?
As I tried to reproduce it with ATM9 modpack( download an older version and update the mods: from 410 mods 173 updated) and have had no luck.  
Can you reproduce it on the nightly version: https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop ?
Also can you provide any backtraces? if yes please specify the commit

**Comment by Hedwig7s** [comment] 2024-09-17 11:21
I'll try to catch the next crash and post logs
It's not easy to catch it can be pretty random

**Comment by DeisDev** [comment] 2024-09-26 19:04
I haven't had this problem when installing modpacks. It's only happened to me when I've selected a bunch of mods for downloading. Sometimes it works flawlessly sometimes it'll run for a few seconds then it will crash. It hasn't happened in a while but IRC it usually happened after trying to download a number of mods over like 30. But yes like Hedwig said its pretty random overall.

**Comment by FifthTundraG** [comment] 2024-10-09 02:41
This issue has plagued me for a while now as well. As has been the case with most of the people here it is pretty random when it occurs, usually with a relatively large number of mods (for me ~20), but it's certainly not just these two who've been affected. I'll keep my eyes peeled for a log next time it happens.

Please don't disregard this issue, it truly is infuriating whenever this occurs.

**Closed as completed** 2024-10-22 14:38 UTC
