### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by DorkYBru** [PrismLauncher/PrismLauncher#2613] opened 2024-07-06 09:51 UTC
### Version of Prism Launcher

8.4 stable

### Version of Qt

6.7.2

### Description of bug

No matter how many times i go to microsoft.net/link and input the code i can't log in, I've already given up on it few months ago thinking that it will be fixed in the future but ig not.

### Steps to reproduce

>be on debian 12
>launch prism
>try to log in

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment] 2024-07-06 10:05
Duplicate of #2302

Try the various fixes listed over there.

**Closed as completed by Ryex** 2024-07-06 10:05 UTC
