### ISSUE TITLE
Add support for NeoForge

### ISSUE THREAD

**Issue by Yupoman** [PrismLauncher/PrismLauncher#1473] opened 2023-08-01 09:28 UTC
### Role

I play modded Minecraft.

### Suggestion

Add support for NeoForge.

### Benefit

It is good for there to be greater compatibility between different versions.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Given what happened with [the Forge leaders](https://neoforged.net/), it will surely stagnate a bit and NeoForge will gradually become another important alternative in the Minecraft world.
As far as I know you can't manually install a version of Forge or another mod so I suggest you add this option.

They already made the suggestion in MultiMC, I don't know how a fork works exactly (if it's their job or yours) so I apologize if this doesn't go here.

**Comment by TheKodeToad** [comment] 2023-08-01 09:31
Duplicate of #1356

(I'm so quick :rocket:)

**Closed as not planned by TheKodeToad** 2023-08-01 09:31 UTC
Labels: status: duplicate, status: invalid
