### ISSUE TITLE
options.txt Editor

### ISSUE THREAD

**Issue by fizzzydev** [PrismLauncher/PrismLauncher#898] opened 2023-03-01 13:41 UTC
### Role

I play modded Minecraft

### Suggestion

Add options.txt to the log/mods/textures/worlds/... tab

### Benefit

Ease of use

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TayouVR** [comment] 2023-03-01 14:15
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/774

and also WIP here: https://github.com/TayouVR/PrismLauncher/tree/gameOptionsPage-cleanup

I will open the PR for it after some further cleanup and finalizing steps. You may see the work on this finished in 1 to 2 weeks if all goes well, so it should make it in the next release
Sneak peek in the current progress:
![image](https://user-images.githubusercontent.com/31988415/222165496-8d8b5442-3ad2-4401-8dde-9fa78d7a8ddf.png)

**Closed as not planned** 2023-03-01 14:40 UTC
Labels: status: duplicate
