### ISSUE TITLE
make "wrap lines" become a option in console settings

### ISSUE THREAD

**Issue by rhjdvsgsgks** [PrismLauncher/PrismLauncher#2488] opened 2024-06-09 01:53 UTC
### Role

i play minecraft, some mod may print a ascii table. wrap lines will break this

### Suggestion

make "wrap lines" become a persist option in console settings

### Benefit

so that i dont need to uncheck wrap lines everytime on game start

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-06-09 16:42
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/484

**Closed as not planned by Trial97** 2024-06-09 16:42 UTC
Labels: type: enhancement
