### ISSUE TITLE
Skins not being downloaded through proxy.

### ISSUE THREAD

**Issue by yagmire** [PrismLauncher/PrismLauncher#2202] opened 2024-03-07 22:20 UTC
### Operating System

Windows

### Version of Prism Launcher

PrismLauncher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

Skins are not downloaded through proxy, all players appear as Steve or Alex. The head does show in the account preview in PrismLauncher, but not in-game.

### Steps to reproduce

Block Minecraft skin request url, then use a HTTP proxy. You will notice that the skins will default to either Steve or Alex, even on servers.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-05-09 05:21
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/797

**Closed as not planned by Trial97** 2024-05-09 05:21 UTC
