### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by 12345-mcpython** [PrismLauncher/PrismLauncher#3186] opened 2024-12-10 14:00 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.1 (latest)

### Version of Qt

Qt 6.7.3

### Description of bug

The app crash when i edit a curseforge instance.

[prismlauncher.exe.14932.dmp](https://github.com/user-attachments/files/18080519/prismlauncher.exe.14932.dmp)

it may hard to reproduce.

### Steps to reproduce

1. edit curseforge instance
2. click curseforge
3. crash

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-12-10 14:40
Can you try reproducing the dump using https://github.com/Trial97/prism_gdb
- download https://github.com/Trial97/prism_gdb/blob/master/PrismLauncher-Windows-MinGW-w64-Portable-8359443-Debug.zip
- extract that portable
- start prism using `gdbprismlauncher.bat` (the extension may be missing); do not touch the opened command prompt(black thing with text)
- reproduce the crash
- Share with develeopers the gdbcrash.log file generated on same level as the gdbprismlauncher.bat

I'm on linux and dmp files are really hard to decode(at least for me) 
PS. if you can't reproduce it with that build that means it was fixed and will be released in 9.2

**Comment by 12345-mcpython** [comment] 2024-12-11 14:18
> Can you try reproducing the dump using https://github.com/Trial97/prism_gdb
> 
> * download https://github.com/Trial97/prism_gdb/blob/master/PrismLauncher-Windows-MinGW-w64-Portable-8359443-Debug.zip
> * extract that portable
> * start prism using `gdbprismlauncher.bat` (the extension may be missing); do not touch the opened command prompt(black thing with text)
> * reproduce the crash
> * Share with develeopers the gdbcrash.log file generated on same level as the gdbprismlauncher.bat
> 
> I'm on linux and dmp files are really hard to decode(at least for me) PS. if you can't reproduce it with that build that means it was fixed and will be released in 9.2

i try to reproduce but it can't be reproduce.

**Comment by Trial97** [comment] 2024-12-11 17:09
ok then it was fixed in nightly

**Closed as completed by Trial97** 2024-12-11 17:09 UTC
