### ISSUE TITLE
"Invalid Account Authorization" Can't sign in to microsoft minecraft account on deck

### ISSUE THREAD

**Issue by Riftibility** [PrismLauncher/PrismLauncher#2288] opened 2024-04-07 04:56 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

IDK (sorry, I don't know much about tech!)

### Description of bug

I expected to click add microsoft account, follow instructions, and be done. Instead, I followed the steps, got the 'success, you may safely close this window' page, closed that page, and then in Prism it said 'Invalid Account Authorization'.  Tried several more times to no avail!

### Steps to reproduce

- Install deck version of prism on deck. 
- Open Prism on deck. 
- Add instance and customize to your liking.
- Go to accounts and click add microsoft account. 
- Follow instructions. 
- Agree to app permissions and all that. 
- Get the success you may safely close this window screen. 
- Get the notification listed in title. 

### Suspected cause

Unknown. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-04-12 16:27
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-04-12 16:27 UTC
Labels: area: auth
