### ISSUE TITLE
Backup Worlds from the launcher

### ISSUE THREAD

**Issue by oceanmallik** [PrismLauncher/PrismLauncher#2517] opened 2024-06-15 08:41 UTC
### Role

Survival World Player

### Suggestion

I want to Backup Worlds from the launcher. I sometime backup my worlds for avoid loosing my world. 

### Benefit

so I can avoid unwanted deletion or corruption of my world. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-06-15 09:00
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1411

**Closed as not planned by Trial97** 2024-06-15 09:00 UTC
Labels: type: enhancement
