### ISSUE TITLE
Old neoforge installer versions are broken

### ISSUE THREAD

**Issue by Fiibii853** [PrismLauncher/PrismLauncher#2234] opened 2024-03-22 23:57 UTC
### Operating System

Windows, Linux

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

Trying to install old versions of neoforge is broken.
I tested with neoforge 47.1.28 but I think it's possible that all versions below .185 are effected.
Testing with the modrinth app worked with no problems.

I am using Minecraft 1.20.1

### Steps to reproduce

Create a new 1.20.1 instance with neoforge 47.1.28
Attempt to run
See that console has an error: `Caused by: java.lang.RuntimeException: java.lang.SecurityException: no manifest section for signature file entry com/google/gson/internal/bind/JsonTreeWriter.class
	at io.github.zekerzhayard.forgewrapper.installer.Installer.createInstaller(Installer.java:40)`

### Suspected cause

I believe this is a problem with the forgewrapper used, probably due to https://github.com/neoforged/NeoForge/issues/671.
I would guess that whatever was done to fix the broken installers has not been taken into account in the wrapper.

Might be related to this https://github.com/PrismLauncher/PrismLauncher/issues/2128?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-03-23 06:16
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2170

Remove the `meta` folder that is inside prism root folder and try again.

**Comment by Fiibii853** [comment] 2024-03-23 10:19
The error still occurs after deleting the meta folder.

I should also note that this was a fresh prism install, so I don't think that the solution mentioned in https://github.com/PrismLauncher/PrismLauncher/issues/2170 has fixed the neoforge installer.

**Comment by Trial97** [comment] 2024-03-23 10:36
Looks like is not the meta issue it is something else: reopening it

**Comment by Trial97** [comment] 2024-03-23 10:53
Just for tracking: the first version that works is 47.1.83

**Comment by TheKodeToad** [comment] 2024-03-23 11:13
This also happens when running the jar directly: [download link](https://maven.neoforged.net/releases/net/neoforged/forge/1.20.1-47.1.81/forge-1.20.1-47.1.81-installer.jar)

**Comment by Trial97** [comment] 2024-03-23 22:40
Opened an issue on neoforge to clarify things:https://github.com/neoforged/NeoForge/issues/740

**Comment by Trial97** [comment] 2024-05-02 20:19
This works now

**Closed as completed by Trial97** 2024-05-02 20:19 UTC
