### ISSUE TITLE
[Suggestion] favorite system, similar to github stars

### ISSUE THREAD

**Issue by BamsyTheSergal** [PrismLauncher/PrismLauncher#1785] opened 2023-11-03 17:45 UTC
### Role

I play modded minecraft, and make modpacks.

### Suggestion

it would be very interesting to have a system to "favorite" or "pin" mods when going to download them. sorta like the star system for github, adding onto that, have a open from source page or something when right clicking the mod in the mods tab.

### Benefit

i think this would be very helpful for mods that almost everyone uses. instead of always having to remember where that awesome mod was. and for new users of the launcher.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2023-11-03 20:29
This looks like a duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1702 
If you want to add more info please do so on that one.
Or if you just want a custom category for mods: https://github.com/PrismLauncher/PrismLauncher/issues/1431

**Closed as completed by Trial97** 2023-11-03 20:29 UTC
Labels: type: enhancement
