### ISSUE TITLE
Add groups for Mods and Data packs

### ISSUE THREAD

**Issue by kevinyyca** [PrismLauncher/PrismLauncher#2309] opened 2024-04-16 11:03 UTC
### Role

I play modded Minecraft

### Suggestion

I want it so i can create groups of datapcks and mods

### Benefit

So that i can create groups for Visual enhancments and things like World Edit and Litematica

### This suggestion is unique

- [ ] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

There should be a button that says something like `New group` or `Create new group` In the mods and datapacks tab.
And when you press it it will
1. Create a new group
2. Let you select a name like instance groups

This would let you sort things like this:
## Performance
  Sodium
  Lithium
  Indium
## Visual
  Visuality
## Other
  World Edit

**Comment by Trial97** [comment] 2024-04-17 13:34
Duplicate of:
- https://github.com/PrismLauncher/PrismLauncher/issues/154
- https://github.com/PrismLauncher/PrismLauncher/issues/880
- https://github.com/PrismLauncher/PrismLauncher/issues/1055

**Closed as not planned by Trial97** 2024-04-17 13:34 UTC
Labels: type: enhancement
