### ISSUE TITLE
Folder button should have more options such as Launch

### ISSUE THREAD

**Issue by StarskyXIII** [PrismLauncher/PrismLauncher#385] opened 2022-11-03 03:53 UTC
### Role

I want to access mods folder instantly, instead press Edit instance button first.

### Suggestion

Make Folder button have more options such as Launch button.
https://github.com/PolyMC/PolyMC/pull/1190

### Benefit

We can access mods, resourcepacks and saves folders faster.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2023-08-12 21:42
duplicate of #144

**Closed as not planned by Trial97** 2023-08-12 21:42 UTC
Labels: status: duplicate, status: invalid
