### ISSUE TITLE
Text background display bug

### ISSUE THREAD

**Issue by EvanHsieh0415** [PrismLauncher/PrismLauncher#1206] opened 2023-06-16 13:35 UTC
### Version of Prism Launcher

7.1

### Version of Qt

6.5.1

### Description of bug

When I turn off the cat, the text background of the instance's name disappears
![圖片](https://github.com/PrismLauncher/PrismLauncher/assets/74277414/38c224c8-4367-44c1-a499-a0c7a7dcf5c5)
![圖片](https://github.com/PrismLauncher/PrismLauncher/assets/74277414/b5563c43-93a5-4c12-8f43-9912bdafe747)

### Steps to reproduce

1. Observe the textual background of the name of the instance
2. Close/open the cat
3. Observe the text background of the instance name

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment] 2023-06-16 13:58
This has been a bug for a while! This is duplicate of #212 though

**Closed as not planned by TheKodeToad** 2023-06-16 13:58 UTC
Labels: status: duplicate
