### ISSUE TITLE
Set default-account to specific instances

### ISSUE THREAD

**Issue by LunaticWasTaken** [PrismLauncher/PrismLauncher#812] opened 2023-02-03 07:23 UTC
### Role

Using multiple accounts

### Suggestion

be able to start specific instances automatically with specific accounts

### Benefit

I often start Instances with the wrong account when using multiple Accounts at the same time.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When i'm using multiple accounts, it's kind of annoying to change it on the top-right manually everytime i start an instance, and almost everytime after restarting the game i start it with the wrong account, because i have to use 2 different instances for this (because you cannot launch one instances more than once).

It would be a nice feature to be able to say "Hey, this Instance will always use this Account" somewhere in the Instance-Settings.

**Comment by Scrumplex** [comment] 2023-02-03 07:31
Implemented by #685. It will be included in version 7.0 which will release in the future.

Also duplicate of #341

**Closed as not planned by Scrumplex** 2023-02-03 07:31 UTC
Labels: type: enhancement
