### ISSUE TITLE
Pull manually downloaded mods from the users download folder during installation.

### ISSUE THREAD

**Issue by bcmpinc** [PrismLauncher/PrismLauncher#418] opened 2022-11-08 07:37 UTC
### Role

As a modpack player

### Suggestion

During installation of FTB & CurseForge packs, pull the manually downloaded mods from the browsers download folder automatically.

### Benefit

It's unclear what the user needs to do with the mods they downloaded manually. Pulling them in automatically would solve that.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As PolyMC stopped working for me, I switched to [modpack-installer](https://github.com/cdbbnnyCode/modpack-installer). It has a great feature that while installing a modpack, it asks to download a few mods manually and when you've done that it pulls them from your browsers download folder automatically. This ensures the pack gets installed correctly.

Unfortunately modpack-installer doesn't support FTB packs. Using the FTB app is not an option, as their Linux installer just crashes. I heard someone mentioning prism, so I tried it out. It works, thanks! Though I noticed it missing this feature so I thought I'd let you know.

**Comment by Scrumplex** [comment] 2022-11-08 07:40
Duplicate of #222 

Will be implemented by #304

**Closed as not planned by Scrumplex** 2022-11-08 07:40 UTC
Labels: type: enhancement
