### ISSUE TITLE
Search CurseForge by ProjectID

### ISSUE THREAD

**Issue by tloskpd** [PrismLauncher/PrismLauncher#2374] opened 2024-05-04 20:13 UTC
### Role

Modpack Player

### Suggestion

Search CurseForge by ProjectID

### Benefit

To more easily find the pack that I am trying to download

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Searching for some packs with multiple words or part of the title does not always bring up the correct pack and have to search through the results to find them.  Searching by ProjectID like the linux FTBApp works will make finding the pack quick.

**Comment by Trial97** [comment] 2024-05-04 22:57
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/843
It is already implemented: just add the prefix `#` followed by the project id and the search will return the project that you are searching(works on both curse and modrinth).
Be careful when using this as prism doesn't assume the project type(you can view mods in modpack search).

**Closed as not planned by Trial97** 2024-05-04 22:57 UTC
Labels: type: enhancement
