### ISSUE TITLE
Refresh Accounts/Internet Connection

### ISSUE THREAD

**Issue by CyanoticShoe** [PrismLauncher/PrismLauncher#2622] opened 2024-07-07 11:45 UTC
### Role

Simply Launching Minecraft with an account

### Suggestion

Have a button to easily refresh/reload accounts or a new function that tries to load the selected account everytime you launch rather than just defaulting to offline.

### Benefit

Often when trying to launch an instance for an online account, it asks you to choose an offline name and launch you into an offline game. In order to remedy this one must close and relaunch everytime. A simple button would be extremely convenient to just refresh after switching networks or waking up your system from sleep.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-07-07 12:03
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/520
We have already done this and in 9.0 I also added a check if the token expires (from this https://github.com/PrismLauncher/PrismLauncher/issues/520#issuecomment-2189835136)
The internet refresh is not a thing.

**Closed as not planned by Trial97** 2024-07-07 12:03 UTC
Labels: type: enhancement
