### ISSUE TITLE
Attempting to view installation details while running causes hanging

### ISSUE THREAD

**Issue by T0RNATO** [PrismLauncher/PrismLauncher#1959] opened 2023-12-16 10:59 UTC
### Operating System

Windows

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

When you select the currently running installation for, and click Edit, for the purposes of viewing the live log for debugging, it goes not responding for quite a while, or indefinitely. If you close the launcher and try again, then it pretends that there is no instance open at all, and shows no live log of the game.

### Steps to reproduce

Click the edit button with a running installation. Not sure if this will really be reproducible on another machine but oh well

### Suspected cause

I imagine prism attempts to load the entire log file into memory, and at this specific time I was having an issue which was spamming the log, so maybe this was too much - Prism should realistically only load the last 500-1000 lines of the log

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-12-16 11:02
Duplicate of #463

**Comment by T0RNATO** [comment] 2023-12-16 11:02
Oh, thanks for the rapid response. I searched for "not responding" but not "freezing" sorry
Btw, the log in question had 107k lines

**Closed as not planned by Trial97** 2023-12-16 11:02 UTC
