### ISSUE TITLE
When I launch an old version of Minecraft on my macbook, the colors are inverted.

### ISSUE THREAD

**Issue by MrGlitchWasTaken** [PrismLauncher/PrismLauncher#959] opened 2023-03-31 01:52 UTC
### Operating System

_MacOS Ventura_

### Version of Prism Launcher

6.3

### Version of Qt

6.3.0

### Description of bug

The colors inverted when loading an old version of minecraft on Macbook!

### Steps to reproduce

- Run an old version of minecraft (mine is 1.2.1)
- The colors will immediately look different when you see the Mojang logo.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jn64** [comment] 2023-04-04 16:43
Duplicate of #698

**Comment by Trial97** [comment] 2023-10-23 21:24
> Duplicate of #698

**Closed as completed by Trial97** 2023-10-23 21:24 UTC
