### ISSUE TITLE
account bug

### ISSUE THREAD

**Issue by Albedook** [PrismLauncher/PrismLauncher#2414] opened 2024-05-18 18:02 UTC
### Operating System

Windows

### Version of Prism Launcher

prism launcher 5.0

### Version of Qt

Qt 6.3.0

### Description of bug

* whenever I enter my Microsoft account, it appears that it was not authenticated, and other times, it appears that there was an error obtaining authorization from the Xbox, the operation was canceled

### Steps to reproduce

* I didn't understand

### Suspected cause

i don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment] 2024-05-18 18:06
Update to a modern version of prism, also see #2302

**Comment by Trial97** [comment] 2024-05-18 18:07
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-05-18 18:07 UTC

**Comment by Albedook** [comment] 2024-05-18 18:35
but I'm on the most updated version

Em sáb., 18 de mai. de 2024 15:06, DioEgizio ***@***.***>
escreveu:

**Comment by Albedook** [comment] 2024-05-18 18:36
I got the wrong version of Prism Launcher, I'm on version 8.3

Em sáb., 18 de mai. de 2024 15:06, DioEgizio ***@***.***>
escreveu:
