### ISSUE TITLE
Prism Launcher, lunched 2 instances instead of 1

### ISSUE THREAD

**Issue by Count-MHM** [PrismLauncher/PrismLauncher#437] opened 2022-11-11 17:19 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.1

### Version of Qt

Qt 6.4.0

### Description of bug

Tried lunching `FTB Stone Block 3` in `offline mode`, but it launched 2 separate instances of it.
[log.txt](https://github.com/PrismLauncher/PrismLauncher/files/9992222/log.txt)
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/9992223/PrismLauncher-0.log)
[discord report](https://discord.com/channels/1031648380885147709/1040345512378912818)
![2022-11-10_22_37_28-Greenshot](https://user-images.githubusercontent.com/71083058/201394111-a3edf076-4d4e-432d-ae0a-27b72a8a50a1.png)

### Steps to reproduce

couldn't replicate it.

### Suspected cause

I tried launching it in demo mode to see what happens but before it launched I killed it
then launched it in offline mode, and it launched 2 instances of it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-10-01 19:16
Sorry, I could not reproduce it at all on the latest version.
As it looks like a one-time thing that is not reproducible I will close this issue, if you happen to reproduce it on the latest release, feel free to reopen it.

**Closed as completed by Trial97** 2023-10-01 19:16 UTC
