### ISSUE TITLE
Possibility to pin a mod version

### ISSUE THREAD

**Issue by emneo-dev** [PrismLauncher/PrismLauncher#2710] opened 2024-08-06 13:06 UTC
### Role

I play modded Minecraft

### Suggestion

A way to pin a mod to a specific version

### Benefit

So that when I click the update mods button it doesn't prompt to update that mod

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I currently have a lightly modded server that I play on which only has 5 mods, the thing is that I use way more mods client side for performance and administration purposes. I would like to update my client side mods without having to update the mods that are also used server side which are not always up to date for stability reasons.

**Comment by Trial97** [comment] 2024-08-06 13:08
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/764

**Closed as not planned by Trial97** 2024-08-06 13:08 UTC
Labels: type: enhancement

**Comment by emneo-dev** [comment] 2024-08-06 13:10
> Duplicate of: #764

Oops indeed I did not find that issue when looking at the list.
