### ISSUE TITLE
Custom Commands don't escape extra environment variable paths

### ISSUE THREAD

**Issue by dannypas00** [PrismLauncher/PrismLauncher#2690] opened 2024-07-28 17:48 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

QT 6.6.3

### Description of bug

When using the special env vars (`$INST_MC_DIR` in my case), the given path is not escaped and cannot be quoted, since quotes are stripped somewhere in the process.

### Steps to reproduce

- Create an instance with a space in the directory path, either the instance itself or somewhere higher up.  
- Set post-exit command to something that uses one of the env variables, e.g. copying screenshots:  
```powershell
xcopy /c /v /q /d /s "$INST_MC_DIR\screenshots\*" "some_other_location\$INST_NAME"
```
Adding own escapes or other quotes doesn't work either:
```powershell
xcopy /c /v /q /d /s \"$INST_MC_DIR\screenshots\*\" \"some_other_location\$INST_NAME\"
xcopy /c /v /q /d /s '$INST_MC_DIR\screenshots\*' 'some_other_location\$INST_NAME'
```

### Suspected cause

The `prismlauncher.cfg` entry removes quotes when parsed / echoed to the shell, and the env variables don't escape special characters like spaces when filled.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-07-28 18:08
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/707 and https://github.com/PrismLauncher/PrismLauncher/issues/634

**Closed as not planned by Trial97** 2024-07-28 18:08 UTC
