### ISSUE TITLE
Customizable Cat Picture

### ISSUE THREAD

**Issue by octo-kumo** [PrismLauncher/PrismLauncher#728] opened 2023-01-10 02:32 UTC
### Role

I use the launcher

### Suggestion

Add more customization options to the cat image on the main launcher screen.

### Benefit

Cats are cute and cuddly

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Interesting features I have in mind are as following.

- [ ] Cat alignment (top, center, right, left etc)
- [ ] Cat scale (fit, fill, crop etc)
- [ ] Cat gif support
- [ ] Cat gallery support (cycles through N images, possible online gallery or local folder)
- [ ] *CSS Style-able Cat?* (meow) on hover, filter, etc
  - [ ] (theme support)
- [ ] Putting cat onto the title bar (may vary from platform to platform)

I found other issues on this topic but most are not descriptive of what improvements to make.
Not sure if this is in anyway useful, but cats are cute.

**Comment by Scrumplex** [comment] 2023-01-31 10:57
Duplicate of #668

**Closed as not planned by Scrumplex** 2023-01-31 10:57 UTC
Labels: type: enhancement
