### ISSUE TITLE
Downloading mods stalls at 99% indefinitely.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [PrismLauncher/PrismLauncher#1646] opened 2023-09-23 19:21 UTC
### Operating System

Linux

### Version of Prism Launcher

> 7.2

per

> ![Screenshot_20230923_202053](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/7b1a7a92-ec87-45b4-8b98-55c3556745b3)

### Version of Qt

> 5.15.10

per

> ![Screenshot_20230923_202025](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/3c476cfa-07fd-43cc-abe5-b378d70df4b8)

### Description of bug

It indefinitely stalls at 99% overall completion, but 0% download of the last item. Is there no option even to skip?

> ![Screenshot_20230923_191729](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/c98fdc0f-c136-4381-b7b4-16c59ed7b2c5)

### Steps to reproduce

0.	Create new instance of 1.20.2 with Forge.
	> ![Screenshot_20230923_201604](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/6ac9f16a-c0ec-4b2d-a284-95cdfe0da1be)
0.	Add the modification.
	> ![Screenshot_20230923_201621](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/dd64ca13-ecb7-4a1f-b0ee-aaf022939bbb)
0.	Allow Prism to automatically download most of the dependencies.
0.	Acquire dependencies which necessitate manual acquisition.
	> ![Screenshot_20230923_201718](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/6f5b8820-e109-43a1-b8f8-c5f480cba709)

	<blockQuote>
	
	BetterDefaultBiomes-1.16.4+-Alpha 2.6.1.jar: https://www.curseforge.com/minecraft/mc-mods/better-default-biomes/download/3570618 
	Hash: b8f151abb48321d7bdaeeaaaf21f08904bde9307 ✔ Found at /home/RokeJulianLockhart/Downloads/BetterDefaultBiomes-1.16.4+-Alpha+2.6.1.jar 
	
	HarderBranchMining-1.16.5-1.36.0.11.jar: https://www.curseforge.com/minecraft/mc-mods/harder-branch-mining/download/3632692 
	Hash: eada733c063b7316717670de295c14fc82f0922f ✔ Found at /home/RokeJulianLockhart/Downloads/HarderBranchMining-1.16.5-1.36.0.11.jar 
	
	magicaljewelry-1.16.5_1.2.12.jar: https://www.curseforge.com/minecraft/mc-mods/magical-jewelry/download/3751662 
	Hash: 404af451ff24088686ffbb4f8d4d5bb71b006fc0 ✔ Found at /home/RokeJulianLockhart/Downloads/magicaljewelry-1.16.5_1.2.12.jar 
	
	Fancy, GUI Overhaul v0.1.2.6.zip: https://www.curseforge.com/minecraft/texture-packs/fancy-gui-overhaul/download/4018354 
	Hash: 6dfb8d9eb597726be992e4d419c4e9ed28ba4959 ✔ Found at /home/RokeJulianLockhart/Downloads/Fancy,+GUI+Overhaul+v0.1.2.6.zip 
	
	Enhanced Boss Bars 1.1.zip: https://www.curseforge.com/minecraft/texture-packs/enhanced-boss-bars/download/4178196 
	Hash: fb41ff9ee2b8ea1540ca450b0dff7f89b12aa3b5 ✔ Found at /home/RokeJulianLockhart/Downloads/Enhanced+Boss+Bars+1.1.zip 
	
	</blockQuote>

	> [/home/RokeJulianLockhart/Downloads](https://github.com/home/RokeJulianLockhart/Downloads)

0.	Allow Prism to download remnant dependencies automatically.
	> ![Screenshot_20230923_201734](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/11e60e56-9b1b-44bf-8210-93e38bccaba3)
0.	> It indefinitely stalls at 99% overall completion, but 0% download of the last item.
	> ![Screenshot_20230923_191729](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/c98fdc0f-c136-4381-b7b4-16c59ed7b2c5)

### Suspected cause

I don't know, but I know that the solution is the ability to skip an item even if it breaks a dependency.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RokeJulianLockhart** [comment] 2023-09-24 17:52
Same with DawnCraft.

![Screenshot_20230924_185219](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/4e675f1c-ea4c-4ae2-b2f7-96b9fa482627)

It is guaranteed to fail even before the others have been downloaded

![Screenshot_20230924_195645](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/10405951-36fb-46e7-9030-34cf8c634bea)

**Comment by RokeJulianLockhart** [comment] 2023-09-24 19:02
See https://canary.discord.com/channels/1031648380885147709/1155576415740248135/1155576415740248135 for additional information.

**Comment by Trial97** [comment] 2023-10-01 20:19
Duplicate of :https://github.com/PrismLauncher/PrismLauncher/issues/1199

**Closed as completed by Trial97** 2023-10-01 20:19 UTC
