### ISSUE TITLE
Server support

### ISSUE THREAD

**Issue by Leonardo5681** [PrismLauncher/PrismLauncher#2524] opened 2024-06-16 18:27 UTC
### Role

I play all type of Minecraft

### Suggestion

Add the Server support (such as PaperMC, Spigot)

### Benefit

So anyone who wants can create a Minecraft Server easily

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It would be nice to make many things easy like installing plugins, configuring server.properties, easily configuring plugins, configuring worlds in the server etc.

**Comment by Trial97** [comment] 2024-06-16 18:32
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/864

**Closed as not planned by Trial97** 2024-06-16 18:32 UTC
Labels: type: enhancement
