### ISSUE TITLE
Unexpected interaction with winget, deleted shortcuts

### ISSUE THREAD

**Issue by wisnoskij** [PrismLauncher/PrismLauncher#1348] opened 2023-07-12 04:44 UTC
### Operating System

Windows

### Version of Prism Launcher

Version: 7.1

### Version of Qt

Qt: 6.5.1

### Description of bug

When using winget to upgrade versions resulted in my shortcuts being removed. meaning the only way to launch Prism is to browse to its appdata folder.

### Steps to reproduce

install older version of Prism
run `winget update --all` in admin terminal

### Suspected cause

It looks like Prism version 7 .1 defaults to no shortcuts for a manual install, and however winget installs updates seems to match this. I don't particularly care what defaults you use in the manual installer, but I would suggest that an automatic update should result in the same settings that you already had, shortcuts should not get deleted.

I suspect installing the program from winget would also result in no shortcuts, this also seems non-optimal.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment] 2023-07-12 04:48
duplicate of #1220

**Closed as not planned by Ryex** 2023-07-12 04:48 UTC
