### ISSUE TITLE
Java Presets & Selector

### ISSUE THREAD

**Issue by Alyaqdhans** [PrismLauncher/PrismLauncher#2289] opened 2024-04-07 13:00 UTC
### Role

Modding Minecraft

### Suggestion

Java presets for multiple paths

### Benefit

So it's easier to change the Java version later on

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Make a Java presets for example Java 8 and Java 17 and save the path on them, when you make instances they retrieve the path from the preset, this makes it easier to change Java versions or/and update them whithout the need to modify every instances Java path again. This is useful especially when you have multiple modpack versions.
If possible also, make it pick the Java preset on it's own. For example, 1.16 and below Java 8 & 1.17 and above Java 17.

Example Image:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/58079015/4d4053e9-01ec-49bd-8e15-dbd4980fca27)

It can also be upgraded later on so that the presets are custom made by the user, specify the preset name and path, then there will be a selector in the instances.

**Comment by Alyaqdhans** [comment] 2024-04-07 13:08
Because right now it's pain, to change every instance's Java path if you made 17 the default then you have to specify the Java path for Java 8 instances every time and if your default Java is 8 then the opposite.

Let alone if you changed the Java file completely you will have to change every instance Java path again.

**Comment by Trial97** [comment] 2024-04-07 14:47
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/762 or https://github.com/PrismLauncher/PrismLauncher/issues/789

**Closed as not planned by Trial97** 2024-04-07 14:47 UTC
Labels: type: enhancement

**Comment by TayouVR** [comment] 2024-04-08 15:07
in #2069 a system to automatically pick the correct java version for your instance is included.
We want to have a more customizable system in the future, where users can make their own profiles with whatever version they want, but that feature will suffice for the vast majority of users.

Stay tuned for the next major release as it will include the java downloader.

**Comment by Alyaqdhans** [comment] 2024-04-15 10:00
> in #2069 a system to automatically pick the correct java version for your instance is included. We want to have a more customizable system in the future, where users can make their own profiles with whatever version they want, but that feature will suffice for the vast majority of users.
> 
> Stay tuned for the next major release as it will include the java downloader.

Modrinth Launcher implementation for the auto selection is a good example
![image](https://github.com/PrismLauncher/PrismLauncher/assets/58079015/4391660b-d4f2-4ed4-88cb-4a0add4f7f27)
