### ISSUE TITLE
gui Scaling setting

### ISSUE THREAD

**Issue by lilsherm09** [PrismLauncher/PrismLauncher#1854] opened 2023-11-15 17:51 UTC
### Role

The gui

### Suggestion

A setting that lets you change the scale of parts of the gui, like the instance icons, mod edit page, and the mod icons and buttons on the “download mod page

### Benefit

QoL and makes using prism and making modpacks easier for some people

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Something like the gui scale setting minecraft has where there is a few preset sizes you can pick.

**Comment by LostQuasar** [comment] 2023-12-31 21:19
I think this also falls under accessibility imo as someone with vision issues it is one of the only reasons I do not use Prism.

**Comment by Trial97** [comment] 2024-01-15 14:58
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/324

**Closed as duplicate by Trial97** 2024-01-15 14:58 UTC
Labels: type: enhancement

**Comment by Flexico** [comment] 2025-07-22 02:51
Someone says they don't use your program because of an accessibility issue and you say "not planned to fix"? Yeah ok

**Comment by Trial97** [comment] 2025-07-22 05:42
You did not read the comment before the closing: this is a duplicate issue https://github.com/PrismLauncher/PrismLauncher/issues/324 
It is planed but we do not want to keep track of the same issue in two places
