### ISSUE TITLE
Microsoft login issue

### ISSUE THREAD

**Issue by mine2k8r** [PrismLauncher/PrismLauncher#2502] opened 2024-06-10 21:57 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0 and 8.3

### Version of Qt

Qt 5/6

### Description of bug

When I try to connect my Microsoft account. There's an error message : "Impossible to authenticate Microsoft's user."
![Capture d’écran 2024-06-10 235426](https://github.com/PrismLauncher/PrismLauncher/assets/78564899/bc42689f-e926-4479-bd34-6c32fa6b8ffc)

I tried everything I could find on the thread but nothing worked.

### Steps to reproduce

Connect to Microsoft account.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by twl-surrogate** [comment] 2024-06-10 23:52
also happening to me

Prism Launcher 8.3 AppImage

**Comment by Trial97** [comment] 2024-06-11 05:26
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302
> There is an outage currenty going on which affects the xbox servers and in turn, the Minecraft licensing/auth servers. 

Please do not open issues without checking if there aren't others that describe your bug.

**Closed as not planned by Trial97** 2024-06-11 05:26 UTC
