### ISSUE TITLE
idek what to say

### ISSUE THREAD

**Issue by no12356** [PrismLauncher/PrismLauncher#2720] opened 2024-08-10 03:21 UTC
### Version of Prism Launcher

8.4

### Version of Qt

I can't get it

### Description of bug

After I download Prism Launcher It works perfectly well, Then once I reboot my device, Things go wrong, Such as Linux not working and Linux giving me errors (I'm using debian to install prism launcher) I Asked many people about the problem, And I realized it was Prism launcher causing the problem. Please help

### Steps to reproduce

I couldn't fix anything

### Suspected cause

It was Prism Launcher causing the problem

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by no12356** [comment] 2024-08-10 03:21
I used the debian commands

**Comment by Trial97** [comment] 2024-08-10 05:48
I am sorry to hear that; it is unlikely prism fault. Even so try uninstalling prism and see if the issues persist or not.
How did you install prism? did you install it following the instructions from: https://prismlauncher.org/download/linux/?
If you are sure is prism fault uninstall it and use either Flatpak or Appimage versions of prism.
As a side note how did you conclude that the errors were caused by PrismLauncher? Was it a log or it was just guessing?

**Comment by no12356** [comment] 2024-08-10 15:56
I used the debian instructions, I Powerwashed my device 3 times, And I am pretty sure it was the launcher It self, As I decided not to install prism launcher, the terminal worked perfectly.

**Comment by eleanordoesntcode** [comment] 2024-08-11 09:15
what errors do you get exactly?

**Comment by DinkTheTink** [comment] 2024-08-15 09:27
You've mentioned you have 'powerwashed' which sounds like you're using a Chromebook with a Linux environment?

I also had an issue similar and it was resolved by using an earlier version of the Flatpack version (8.3).

**Comment by no12356** [comment] 2024-08-22 20:44
Alright, I'll use the prism launcher version 8.3

**Comment by TheKodeToad** [comment] 2024-08-24 22:01
I don't think this issue is related to the launcher itself

**Closed as not planned by TheKodeToad** 2024-08-24 22:01 UTC
Labels: status: not enough info
