### ISSUE TITLE
Allow launching the same instance multiple times

### ISSUE THREAD

**Issue by ItsCryptic** [PrismLauncher/PrismLauncher#847] opened 2023-02-11 20:06 UTC
### Role

I'm a developer / do a lot of mod testing

### Suggestion

Allow launching the same instance multiple times

### Benefit

This makes it quite a bit easier if you have multiple accounts and want to launch both (or multiple) accounts at the same time without cloning the instance

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This has been requested on PolyMC and MultiMC respectively https://github.com/MultiMC/Launcher/issues/2175 and https://github.com/PolyMC/PolyMC/issues/179

**Comment by Scrumplex** [comment] 2023-02-11 20:08
Duplicate of #250

**Closed as not planned by Scrumplex** 2023-02-11 20:08 UTC
Labels: type: enhancement
