### ISSUE TITLE
Login does not respond to Microsoft web auth

### ISSUE THREAD

**Issue by DArkHekRoMaNT** [PrismLauncher/PrismLauncher#1429] opened 2023-07-24 19:36 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher Portable MSVC 7.1 (and 6.1)

### Version of Qt

Qt 6.5.1

### Description of bug

I'm trying to login to my account. Launcher gives a link and a code. I follow the link, log in, the Microsoft account page opens. The launcher does not react to this in any way and continues to offer to open the link and enter the code. Tried on 7.1 and 6.1 versions.

### Steps to reproduce

* Try login to Microsoft account
* Click Open page and copy code
* Paste code and login
* Return to app
* Wait for progress bar end and get "Microsoft user authentication failed."

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DArkHekRoMaNT** [comment] 2023-07-28 16:36
I tried the latest version of MultiMС - same problem. FTB App works and unlike Prism/MultiMC it redirects me to "Would you like to allow this app to use..." page. And not just immediately to my profile after auth

**Comment by AuroraBee** [comment] 2023-08-15 07:58
I am experiencing this same issue on version 7.2

**Comment by Nishmound** [comment] 2023-09-19 10:09
I had the same issue on version 7.2 when i opened the link in MS Edge. I tried it with Google Chrome instead and it worked first time. Maybe this works for you too.

**Comment by scaledteam** [comment] 2023-09-19 10:16
I used to login in Microsoft account through GitHub, because i wasn't able to solve Microsoft captcha when i created account. Now, to successfully login in PrismLauncher i added separate password in Microsoft account settings, and forced login through password, and now it works. It's probably caused by Microsoft, because i saw similar discussions about other launchers, based on MultiMC.

**Comment by DArkHekRoMaNT** [comment] 2023-09-19 11:25
> I had the same issue on version 7.2 when i opened the link in MS Edge. I tried it with Google Chrome instead and it worked first time. Maybe this works for you too.

I use Chrome

**Comment by runlevel5** [comment] 2023-09-26 12:51
I also experienced the same issue

**Comment by romatthe** [comment] 2023-12-04 21:27
I have the exact same issue on Prism 8.0, using Linux and Firefox.

The log looks like this, until I'm forced to close the window after time has expired:

```
10.601 D | AuthFlow: "Logging in with Microsoft account."
10.601 D | DeviceFlow::link
10.601 D | DeviceFlow::setLinked: false
10.601 D | [katabasis.credentials]: new refresh token: ""
11.021 D | DeviceFlow::onDeviceAuthReplyFinished
11.021 D | DeviceFlow::onDeviceAuthReplyFinished: Tokens returned:
11.021 D | "device_code" :  "CAQABAAEAAAAmoFfGtYxvRrNriQdPKIZ-Axr9Y6Pc0XnFv3Wgaf6IInngSQzGE2_-w6WqgEl76sPCBwB-o9bsQahQ5t-i7-wXfTxiG7dCcXiL6gyycmg6CZj67UaN13pazG0G8oEsayCB8kbWBporJIXzIySB3jgaTxaPM6VEnU-6T1w__hE8EBo_k0i3AJ40Ivj2MwCOQZ5NEpYJpeDKFFir92zhnqTjUoLCRl4zC_2UB59iQW-4VU7M4jjROrlB4CUGxU2DVXJUJSWyBCH4Pffp5pQH8w4vyucVeXReRO2vZNbzUzt7dQ8kKgGAbfZD0XqlbuFWObUBhkzmZGEZ9YefU1ARML0k7-EFN4XaNj5XeRwf9dAtIaaBowouVfdCOBuKWWNLA0KcyYRkV29h06sx9bhS5R95IAA"
11.021 D | "expires_in" :  "900"
11.021 D | "interval" :  "5"
11.021 D | "message" :  "To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code VSN2DJMX to authenticate."
11.021 D | "user_code" :  "VSN2DJMX"
11.021 D | "verification_uri" :  "https://www.microsoft.com/link"
11.021 D | DeviceFlow::onDeviceAuthReplyFinished: Device auth request response
11.022 D | DeviceFlow::startPollServer: device_ and user_code expires in 900 seconds
16.387 D | PollServer::onPollTimeout: retrying
17.790 D | Opening URL "https://www.microsoft.com/link"
22.387 D | PollServer::onPollTimeout: retrying
27.387 D | PollServer::onPollTimeout: retrying
30.388 D | [launcher.task.net.metacache.http]: Saving metacache with 20 entries
32.388 D | PollServer::onPollTimeout: retrying
37.388 D | PollServer::onPollTimeout: retrying
42.388 D | PollServer::onPollTimeout: retrying
47.387 D | PollServer::onPollTimeout: retrying
52.387 D | PollServer::onPollTimeout: retrying

  ...

907.379 D | PollServer::onPollTimeout: retrying
979.749 D | Paged dialog close requested   
```

Like the OP, logging in takes me to the Microsoft account page, not to a page allowing me to authorize Prism. One small thing to point out is that I'm logging in via my Github account.

**Comment by DArkHekRoMaNT** [comment] 2023-12-05 00:21
I also use GitHub account 🤔

**Comment by ghost** [comment] 2023-12-14 19:43
Hey everyone, I also stumpled across this issue, it only occurs for me when authorizing through GitHub, with credentials everything works fine. I guess this one is on Microsoft, their auth module is just 🤮.

**Comment by runlevel5** [comment] 2023-12-14 23:03
The best way is to unassociate the Microsoft account with Github account

**Comment by RowenStipe** [comment] 2024-03-19 18:20
> I used to login in Microsoft account through GitHub, because i wasn't able to solve Microsoft captcha when i created account. Now, to successfully login in PrismLauncher i added separate password in Microsoft account settings, and forced login through password, and now it works. It's probably caused by Microsoft, because i saw similar discussions about other launchers, based on MultiMC.

I came across this same issue due to my Microsoft account being a GitHub account but I followed your advice and added a separate password for my Microsoft account then used the "Other Sign-in" option and used the password and it worked for me.

**Comment by Trial97** [comment] 2024-04-12 16:26
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-04-12 16:26 UTC
Labels: area: auth
