### ISSUE TITLE
flatpak version cannot open folders

### ISSUE THREAD

**Issue by DowneyX** [PrismLauncher/PrismLauncher#2691] opened 2024-07-28 17:52 UTC
### Operating System

arch linux

### Version of Prism Launcher

Prism laucher 8.4

### Version of Qt

Qt version 6.7.2.

### Description of bug

cannot open folders.
does not seem to adjust user interface based on system theme (dark mode/ light mode)
can not create shortcuts.

### Steps to reproduce

install through flathub.
add an instance.
click on folder button.

### Suspected cause

maybe its a permission issue. i have no clue

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-07-28 18:24
This sounds like a duplicate of: 
https://github.com/PrismLauncher/PrismLauncher/issues/1490

try:  open your wanted file explorer > right click on a folder >open with>set default aplication and in the dialog select the file explorer executable
also ensure that you have a xdg-portal installed

**Comment by DowneyX** [comment] 2024-07-28 22:07
the command `xdg-mime default org.gnome.Nautilus.desktop inode/directory`
seemed to have resolved the folder issue. thanks for the quick reply!

**Closed as completed** 2024-07-28 22:24 UTC

**Comment by nycki93** [comment] 2025-06-27 02:19
> This sounds like a duplicate of: [#1490](https://github.com/PrismLauncher/PrismLauncher/issues/1490)
> 
> try: open your wanted file explorer > right click on a folder >open with>set default aplication and in the dialog select the file explorer executable also ensure that you have a xdg-portal installed

this worked for me! can you please add this info to the program itself? it took me hours and several restarts, thinking there was a bug with flatpak or with xdg-portal, before I found this.
