### ISSUE TITLE
Prism Launcher 8.4 wont open. Version 8.3 does open.

### ISSUE THREAD

**Issue by dragon3025** [PrismLauncher/PrismLauncher#2640] opened 2024-07-12 22:36 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Unable to get this.

### Description of bug

Prism Launcher 8.4 wont open. I tried version 8.3 and it does open. I checked the most recent log at `AppData\Roaming\PrismLauncher\logs`, but the file is blank.

### Steps to reproduce

Installed 8.4, right clicked prism launcher, clicked open, it loads then does nothing. I tried with both a shortcut and the exe in `AppData\Local\Programs\PrismLauncher`.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment] 2024-07-12 23:25
duplicate of #2564

Solutions: reinstall the vcredist.

**Closed as completed** 2024-07-13 00:48 UTC
