### ISSUE TITLE
Add Microsoft account failing to authenticate

### ISSUE THREAD

**Issue by Chieftain-10** [PrismLauncher/PrismLauncher#2389] opened 2024-05-09 16:23 UTC
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

Adding a Microsoft account results in the error: `Failed to get authorisation for Xbox services: Operation canceled`
The browser Microsoft log in works (both for email-code and password), and is all successful, but Prism gets stuck at 'Logging in as an Xbox user' and then returns the error above. 
My Microsoft account works for the standard Minecraft launcher. I tried changing my password, no difference. 

### Steps to reproduce

- 'Add Microsoft'
- Sign-in online
- Error

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-05-09 16:35
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-05-09 16:35 UTC
