### ISSUE TITLE
[Bug] Modrinth Downloads show "unavailable" mods

### ISSUE THREAD

**Issue by AlienXtream** [PrismLauncher/PrismLauncher#1948] opened 2023-12-13 03:42 UTC
### Version of Prism Launcher

8.0

### Version of Qt

Qt 6.6.0

### Description of bug

when browsing Modrinth mods via the launcher in circumstances where a mod has updated for one loader but not the other (e.g has a neo/forge version on version 1.20.2 but latest fabric version on 1.20.1) the mod shows up in the list, despite having no files for that version. only mods that have a download for the applicable loader should be shown, even if they have a counterpart for a different loader.

### Steps to reproduce

attempt to download a mod that does not have a file for the active MC/loader version

### Suspected cause

probably boolean logic headaches. its confusing enough to explain it to a human, let alone the computer. when its filtering results its as if its doing the "has matching loader version?" BoolAND "has matching minecraft version?". where it sould be more like "has matching loader for *this* minecraft version?". idk exactly. boolean logic (assuming its the root cause) can be confusing. not because its difficult but because it gets messy so quickly its hard for us squishy brains to keep track of whats what...

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by AlienXtream** [comment] 2023-12-13 03:45
as of the time of this issue post (and the mod in question in this case) i was attempting to download a fabric version Applied Energistics 2 from modrinth, where in it has a neoforge version for 1.20.2 but not a fabric/forge version. it DOES have a fabric version for 1.20.1

**Comment by Trial97** [comment] 2023-12-13 12:19
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/416

**Closed as not planned by Trial97** 2023-12-13 12:19 UTC

**Comment by AlienXtream** [comment] 2023-12-13 19:31
i did try and look... i swear... its just one of those things thats hard to describe/search XD
