### ISSUE TITLE
Extreme freeze when viewing large logs

### ISSUE THREAD

**Issue by wahfl2** [PrismLauncher/PrismLauncher#2326] opened 2024-04-21 04:07 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

The launcher becomes entirely unresponsive for 20+ seconds when viewing a large log, such as this one:
https://mclo.gs/cb4GHWh

### Steps to reproduce

* Generate a large log in an instance (the example shown is GregTech: New Horizons)
* Exit the instance window
* Press edit on the instance to reopen it and view the log
  * This also works by clicking on the "other logs" section, if there is a large log to display there
* Observe unresponsive launcher

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-04-21 06:13
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/485 or https://github.com/PrismLauncher/PrismLauncher/issues/1450
But thanks for the log example

**Closed as not planned by Trial97** 2024-04-21 06:13 UTC
