### ISSUE TITLE
Cannot connect Microsoft account "Failed to get Minecraft access token: Operation canceled"

### ISSUE THREAD

**Issue by yorshex** [PrismLauncher/PrismLauncher#2283] opened 2024-04-06 13:54 UTC
### Operating System

Linux

### Version of Prism Launcher

8.2

### Version of Qt

6.6.3

### Description of bug

When trying to add a Microsoft account, it gets stuck on "Getting authorization to access Mojang services." for a minute before failing with "Failed to get Minecraft access token: Operation canceled"

### Steps to reproduce

* Got to Settings > Accounts;
* Press "Add Microsoft";
* Authorize to Microsoft account;
* Wait.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by rprije** [comment] 2024-04-11 11:42
I'm experiencing a similar issue to what's being reported but I don't get an explicit failure. For me the "Working..." progress bar just stays stuck at around 20% forever. My log prints only the following upon attempting to add the account:

```   127.187 D | AuthFlow: "Logging in with Microsoft account."
   127.187 D | DeviceFlow::link
   127.187 D | DeviceFlow::setLinked: false
   127.187 D | [katabasis.credentials]: new refresh token: ""
   127.210 D | DeviceFlow::onDeviceAuthReplyFinished
```

I'm running PrismLauncher 8.0 with QT 6.6.1. A completely fresh install on a fresh computer (not upgrade related) running Linux NixOS.

**Comment by Trial97** [comment] 2024-04-12 16:27
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-04-12 16:27 UTC
Labels: area: auth
