### ISSUE TITLE
Intermediary Mappings does not change version when Minecraft version is changed

### ISSUE THREAD

**Issue by pog5** [PrismLauncher/PrismLauncher#1358] opened 2023-07-13 10:41 UTC
### Operating System

Windows, Linux

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt version 6.5.1 running on Windows 10 x64 on a NVIDIA GPU running driver version 414

### Description of bug

![image](https://github.com/PrismLauncher/PrismLauncher/assets/62222436/48d6d02b-2c02-464c-9d3d-02fe6603ce85)
Changing the Minecraft version using the Change Version button while having Minecraft highlighted does not also change the Intermediary Mappings version.

This is easily fixable by clicking Remove while having Intermediary Mappings selected, which removes the old version mappings and adds the correct mappings.

### Steps to reproduce

1. (Create and) Open the Edit dialog of a modded instance
2. go in the Version tab, click on Minecraft
3. Click on Change Version on the right side and change it to another Minecraft version
4. Click OK and as you can see, Mappings still have the old version
5. As a consequence, the game crashes when you launch it.

### Suspected cause

Changing the Minecraft version is not linked to also switching the mappings version.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by byquanton** [comment] 2023-07-13 12:50
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/562

**Comment by TheKodeToad** [comment] 2023-07-13 14:55
I don't think so personally.

**Closed as completed** 2024-09-08 22:44 UTC
