### ISSUE TITLE
Save custom command fields even when the checkbox isnt clicked, currently they are wiped on prism restart

### ISSUE THREAD

**Issue by GrahamKracker** [PrismLauncher/PrismLauncher#3084] opened 2024-11-09 17:27 UTC
### Role

I develop mods and use xcopy on a prism instance to test it

### Suggestion

save the custom command fields (and hence the commands within) even when the checkbox is disabled

### Benefit

so i dont have to recopy the command each time, sometimes i dont want to execute the custom command but i still want it saved.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://github.com/user-attachments/assets/c3fc150d-ba47-4746-9813-ad564a99b25b)
it would be great for that to be saved, current behavior is that it will get wiped on prism restart

**Comment by Trial97** [comment] 2024-11-09 17:36
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/3012

**Closed as not planned by Trial97** 2024-11-09 17:36 UTC
Labels: type: enhancement

**Comment by GrahamKracker** [comment] 2024-11-09 18:37
bruh how tf did i not see that
