### ISSUE TITLE
Categories on mods

### ISSUE THREAD

**Issue by Marks12520** [PrismLauncher/PrismLauncher#2491] opened 2024-06-09 19:24 UTC
### Role

Creating modpacks

### Suggestion

Be able to sort by categories that modrinth/curseforge have such as "magic", "exploration", "dimensions", etc

### Benefit

It'll be easier to search specific mods without having to leave the app to search them online

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Ryex** [comment] 2024-06-09 19:37
duplicate of #1314
WIP on #1728

**Closed as not planned by Ryex** 2024-06-09 19:37 UTC
Labels: type: enhancement
