### ISSUE TITLE
Mouse doesn't work on GUI but works in game

### ISSUE THREAD

**Issue by SrBurns-rep** [PrismLauncher/PrismLauncher#2912] opened 2024-10-12 18:16 UTC
### Operating System

Linux

### Version of Prism Launcher

8.4-5 (Arch linux package)

### Version of Qt

6.7.3

### Description of bug

I can move between menu and GUI buttons only using keyboard arrow keys, mouse isn't selecting or right/left clicking on anything. In game I can move the characters head, can break and place blocks but  cant drag and drop any items in GUI.

### Steps to reproduce

Install prismlaucher Arch Linux package
run an 1.21.1 instance
try to click on GUI buttons

### Suspected cause

Some java update or Qt update, idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-10-13 05:44
Are you referring to the launcher UI or in-game UI?

**Comment by SrBurns-rep** [comment] 2024-10-13 06:35
> Are you referring to the launcher UI or in-game UI?

in game UI

**Comment by Trial97** [comment] 2024-10-13 06:43
Then is not launcher-related:
if it is a mod pack then report that to the project 
if is vanilla it may be due to Wayland (if you use it) or the drivers
Also are you able to reproduce this on other launchers? (at least check the official launcher)

**Comment by SrBurns-rep** [comment] 2024-10-13 17:16
thanks, I'm using sway, I will try another compositor to see if the problem persists

**Comment by Trial97** [comment] 2024-10-13 17:29
Wailand does break Minecraft so as is not launcher related I'm gonna close this issue.
For running Minecraft have a look at https://github.com/Admicos/minecraft-wayland it may help you

**Closed as not planned by Trial97** 2024-10-13 17:29 UTC
