### ISSUE TITLE
Mod Update functions does not recognise mods from different providers

### ISSUE THREAD

**Issue by ffuentesm** [PrismLauncher/PrismLauncher#1926] opened 2023-12-08 16:55 UTC
### Operating System

Windows

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

If I have a mod from a provider (Curse Forge) and the mod dependencies are from another provider (Modrinth), the Check for Updates functions will try to download the same mods from the first provider even if they are already downloaded. 

ei: If I have Ars Nouveu installed from Curse Forge, but I have Ars Elemental from Modrinth, it will try to download Ars Nouveu again from Modrdrinth, leaving it duplicated on my mod list. 

### Steps to reproduce

Just install a mod from curse forge and its dependency mods from modrinth, then try to check for updates. Curse Forge

### Suspected cause

For some reason, the check for update function is seeing mod providers and exclusives from each other, something that did not happen before. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2023-12-08 16:57
Duplicate of #1745

**Closed as not planned by Trial97** 2023-12-08 16:57 UTC
