### ISSUE TITLE
Add support for the Modrinth tagging system.

### ISSUE THREAD

**Issue by LunarPidgeon** [PrismLauncher/PrismLauncher#2157] opened 2024-02-22 17:39 UTC
### Role

I play modded minecraft.

### Suggestion

I want to be able to filter mods (in the built in mod browser) by modrinth tags such as client side, server side, etc.

### Benefit

Currently it's hard to know what mods will require serverside installation/if they are compatible with vanilla servers and/or clients.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment] 2024-02-22 17:42
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1568
Will be fixed with: https://github.com/PrismLauncher/PrismLauncher/pull/1728

**Closed as not planned by Trial97** 2024-02-22 17:42 UTC
Labels: type: enhancement
