### ISSUE TITLE
Toggle to enable Ability to download mods/files regardless of if the game has launched.

### ISSUE THREAD

**Issue by Lylythii** [PrismLauncher/PrismLauncher#1415] opened 2023-07-21 14:30 UTC
### Role

Needing to grab an additional mod/file after the game has launched. Sometimes you forget a mod that isn't *desperately* needed *right now*, & doesn't warrant closing/relaunching the game. Of course this can be done after you're done playing, but can also be forgotten about by mistake.

### Suggestion

Currently. Prism Launcher restricts the ability to download mod files while the game is running. Personally find this to be a nuisance. Though recognise *why* such a restriction exists.

### Benefit

It makes assembling personal *&* in-development modpacks significantly easier.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment] 2023-07-21 15:14
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/852

**Closed as not planned by TheKodeToad** 2023-07-21 15:14 UTC
Labels: type: enhancement
