### ISSUE TITLE
Opening .mrpack files sometimes results in wrong location

### ISSUE THREAD

**Issue by Rafii2198** [PrismLauncher/PrismLauncher#1183] opened 2023-06-14 14:08 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.0

### Version of Qt

Qt 6.5.1

### Description of bug

I have a folder on my E: drive with my modpack, when I generate the .mrpack file and open it, the path to that file sometimes is weird, and thus it doesn't even let me import the pack.
* The path that it should look like: 
```
E:\Projects\WynnicEnchantments\Wynnic Enchantments-0.0.0.mrpack
```
* The path that actually appeared in launcher: 
```
C:\Users\rafii\AppData\Roaming\PrismLauncher\file:\E:\Projects\WynnicEnchantments\Wynnic Enchantments-0.0.0.mrpack
```

![image](https://github.com/PrismLauncher/PrismLauncher/assets/26695327/3fa24c91-969e-4629-b334-b525aad7c6bc)
Again that doesn't always happen, but I can't identify what is the cause of it.

### Steps to reproduce

* Open any .mrpack file using Prism
* The location field will be prefixed with path to Prism Launcher's directory

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by MenacingPerson** [comment] 2023-06-17 06:45
It ALWAYS happens, when using `--import` command

**Comment by Trial97** [comment] 2023-10-03 20:49
This may be solved in the future 8.0 already(aka. current develop build).

**Comment by Rafii2198** [comment] 2023-10-03 20:54
I dragged and dropped the file onto the portable develop version I got from actions and it works fine. I would have to mess with windows for it to open on develop with double click, but I assume it would be basically the same

**Comment by Rafii2198** [comment] 2023-10-03 21:06
Wait, actually dragging and dropping works on 7.2 but double-clicking doesn't.... But I tried a different approach, I dragged and dropped it onto the .exe which doesn't work on 7.2 but on that develop version works, so it all seems to be good for sure.

**Comment by MenacingPerson** [comment] 2023-10-04 02:19
I figured out how to replicate (7.2):

1. Ensure Prism Launcher is already open
2. `prismlauncher --import file.mrpack`

If it's not open, then it works properly.

**Comment by Trial97** [comment] 2023-10-04 06:22
Hi @MenacingPerson, 
Thank you for confirming that is still reproducible on the 7.2 release.
But it looks like on the latest develop build this is not reproducible in any of the mentioned ways.
As there we some changes in how we handle the import flag(we added a curseforge URL handler), and that may fixed the current issue.
If you want you can try the nightly builds to see if you can reproduce it yourself.
But I will leave this open until the 8.0 release when I will request from you if the issue still persists.

**Comment by MenacingPerson** [comment] 2023-10-04 07:23
I can confirm it is fixed on an 8.0 dev build.

```
QLocalSocket::setServerName() called while not in unconnected state
```

this error/warn is still logged though when using --import when the launcher is open.

**Comment by Trial97** [comment] 2023-10-04 07:25
Ignore it.

**Comment by Trial97** [comment] 2024-04-06 05:42
Closing as 8.0 was released and it was confirmed that this was fixed

**Closed as completed by Trial97** 2024-04-06 05:42 UTC
