### ISSUE TITLE
View folder not working

### ISSUE THREAD

**Issue by FormBurden** [PrismLauncher/PrismLauncher#993] opened 2023-04-13 19:46 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.5.0

### Description of bug

Not entirely sure if it could be Linux-issue, because I remember seeing it work while in 6.3. But as of now, it does not.

What happens, is while trying any of the "Open"... buttons to open any of the folders within the Linux-system's filebrowser, nothing happens. Nothing opens. 

Arch-Linux, regular Desktop, as well as Steam Deck on Flatpak and the AUR.

### Steps to reproduce

Trying to click the many "Open" buttons on Prism.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Fredrikke0** [comment] 2023-04-18 10:24
I have the same issue, also running Arch. Firefox is able to open my file manager, so I suspect this is an issue with Prism. 

"xdg-mime query default inode/directory"  returns "thunar.desktop". 

I am running wayland if that makes a difference.

**Comment by JeffHenson** [comment] 2023-04-18 16:47
I'm on Arch as well and I believe this is a problem with qt6.5.

I downgraded all qt6 packages back to 6.4 and the the Open Folder menu items/buttons work again.

**Comment by Guanran928** [comment] 2023-06-06 14:58
I am experiencing the same thing with *-git version of PrismLauncher

Infos:
  PrismLauncher version: local/prismlauncher-git 6.0.r566.g3dccc38f4-1
  OS: Arch Linux x64
  Compositer: Hyprland (wayland)
  File manager: Nautilus (the gnome one)
  Qt version: 6.5.1-1


Apparently, `❯ xdg-open ~/.local/share/PrismLauncher/instances/` does work
I have those xdg stuff installed:
```
❯ sudo pacman -Qs xdg
local/libcanberra 1:0.30+r2+gc0620e4-3
    A small and lightweight implementation of the XDG Sound Theme Specification
local/libxdg-basedir 1.2.3-1
    An implementation of the XDG Base Directory specifications.
local/xdg-dbus-proxy 0.1.4-1
    Filtering proxy for D-Bus connections
local/xdg-desktop-portal 1.16.0-3
    Desktop integration portals for sandboxed apps
local/xdg-desktop-portal-gtk 1.14.1-1
    A backend implementation for xdg-desktop-portal using GTK
local/xdg-desktop-portal-hyprland 0.4.0-1
    xdg-desktop-portal backend for hyprland
local/xdg-utils 1.1.3+25+g8ae0263-1
    Command line tools that assist applications with a variety of desktop integration
    tasks
```



Log shows:
```
     4.363 D | Opening directory "/home/guanranwang/.local/share/PrismLauncher/instances/Simply Optimized"
     4.537 D | Opening directory "/home/guanranwang/.local/share/PrismLauncher/instances/Simply Optimized"
     4.695 D | Opening directory "/home/guanranwang/.local/share/PrismLauncher/instances/Simply Optimized"
     4.870 D | Opening directory "/home/guanranwang/.local/share/PrismLauncher/instances/Simply Optimized"
     5.095 D | Opening directory "/home/guanranwang/.local/share/PrismLauncher/instances/Simply Optimized"
     5.237 D | Opening directory "/home/guanranwang/.local/share/PrismLauncher/instances/Simply Optimized"
```
But no file manager was opened.



What I've tried:
- Install Dolphin (KDE Plasma file manager), did not work
- Tried different prismlauncher version: `prismlauncher-qt5-bin`, worked

**Comment by Ryex** [comment] 2023-06-06 15:30
Arch broke their qt binaries in relatiosn to our CI builds
building from source seems to be the only option.

**Comment by wanesty** [comment] 2023-06-08 04:35
> building from source seems to be the only option.

do you mean prism or qt ?
i would assume qt because i just compiled the dev branch (9b9d439fce9408712a594bb294e3bd5f108e31bc) and i'm having the same issue with both this version and the previous 6.3 release.

**Comment by Zailer43** [comment] 2023-06-08 23:02
![image](https://github.com/PrismLauncher/PrismLauncher/assets/63565983/4f6c9d41-fdfa-40f3-8ddf-97d9e91f3e35)
```Process 8512 (xdg-desktop-por) of user 1000 dumped core.

Stack trace of thread 8515:
#0  0x00007f979837026c n/a (libc.so.6 + 0x8926c)
#1  0x00007f9798320a08 raise (libc.so.6 + 0x39a08)
#2  0x00007f9798309538 abort (libc.so.6 + 0x22538)
#3  0x00007f979830a2db n/a (libc.so.6 + 0x232db)
#4  0x00007f979837a1b7 n/a (libc.so.6 + 0x931b7)
#5  0x00007f979837d80c n/a (libc.so.6 + 0x9680c)
#6  0x00007f979837e72d malloc (libc.so.6 + 0x9772d)
#7  0x00007f9798977e1a g_malloc (libglib-2.0.so.0 + 0x5ee1a)
#8  0x00007f97989b6a95 g_variant_new_dict_entry (libglib-2.0.so.0 + 0x9da95)
#9  0x00007f97988828ff n/a (libgio-2.0.so.0 + 0x13e8ff)
#10 0x00007f9798882f62 n/a (libgio-2.0.so.0 + 0x13ef62)
#11 0x00007f979884cdd5 g_dbus_message_new_from_blob (libgio-2.0.so.0 + 0x108dd5)
#12 0x00007f979885b19e n/a (libgio-2.0.so.0 + 0x11719e)
#13 0x00007f97987ec3f4 n/a (libgio-2.0.so.0 + 0xa83f4)
#14 0x00007f97987ec42d n/a (libgio-2.0.so.0 + 0xa842d)
#15 0x00007f979897353b g_main_context_dispatch (libglib-2.0.so.0 + 0x5a53b)
#16 0x00007f97989d0219 n/a (libglib-2.0.so.0 + 0xb7219)
#17 0x00007f9798972c7f g_main_loop_run (libglib-2.0.so.0 + 0x59c7f)
#18 0x00007f9798852d3c n/a (libgio-2.0.so.0 + 0x10ed3c)
#19 0x00007f97989a0315 n/a (libglib-2.0.so.0 + 0x87315)
#20 0x00007f979836e44b n/a (libc.so.6 + 0x8744b)
#21 0x00007f97983f1e40 n/a (libc.so.6 + 0x10ae40)

Stack trace of thread 8514:
#0  0x00007f97983ea2ed syscall (libc.so.6 + 0x1032ed)
#1  0x00007f97989c97b5 g_cond_wait (libglib-2.0.so.0 + 0xb07b5)
#2  0x00007f979893dfb4 n/a (libglib-2.0.so.0 + 0x24fb4)
#3  0x00007f97989a4f9e n/a (libglib-2.0.so.0 + 0x8bf9e)
#4  0x00007f97989a0315 n/a (libglib-2.0.so.0 + 0x87315)
#5  0x00007f979836e44b n/a (libc.so.6 + 0x8744b)
#6  0x00007f97983f1e40 n/a (libc.so.6 + 0x10ae40)

Stack trace of thread 8518:
#0  0x00007f97983e4c0f __poll (libc.so.6 + 0xfdc0f)
#1  0x00007f97989d017f n/a (libglib-2.0.so.0 + 0xb717f)
#2  0x00007f97989721a2 g_main_context_iteration (libglib-2.0.so.0 + 0x591a2)
#3  0x00007f9797377fde n/a (libdconfsettings.so + 0x5fde)
#4  0x00007f97989a0315 n/a (libglib-2.0.so.0 + 0x87315)
#5  0x00007f979836e44b n/a (libc.so.6 + 0x8744b)
#6  0x00007f97983f1e40 n/a (libc.so.6 + 0x10ae40)

Stack trace of thread 8513:
#0  0x00007f97983e4c0f __poll (libc.so.6 + 0xfdc0f)
#1  0x00007f97989d017f n/a (libglib-2.0.so.0 + 0xb717f)
#2  0x00007f97989721a2 g_main_context_iteration (libglib-2.0.so.0 + 0x591a2)
#3  0x00007f97989721f2 n/a (libglib-2.0.so.0 + 0x591f2)
#4  0x00007f97989a0315 n/a (libglib-2.0.so.0 + 0x87315)
#5  0x00007f979836e44b n/a (libc.so.6 + 0x8744b)
#6  0x00007f97983f1e40 n/a (libc.so.6 + 0x10ae40)

Stack trace of thread 8521:
#0  0x00007f97983f2266 epoll_wait (libc.so.6 + 0x10b266)
#1  0x00007f9795209779 n/a (libspa-support.so + 0x16779)
#2  0x00007f97951fb213 n/a (libspa-support.so + 0x8213)
#3  0x00007f979861f4cf n/a (libpipewire-0.3.so.0 + 0x444cf)
#4  0x00007f979836e44b n/a (libc.so.6 + 0x8744b)
#5  0x00007f97983f1e40 n/a (libc.so.6 + 0x10ae40)

Stack trace of thread 8522:
#0  0x00007f97983e4c0f __poll (libc.so.6 + 0xfdc0f)
#1  0x00007f97989d017f n/a (libglib-2.0.so.0 + 0xb717f)
#2  0x00007f97989721a2 g_main_context_iteration (libglib-2.0.so.0 + 0x591a2)
#3  0x000055f24ad2a5ca n/a (xdg-desktop-portal + 0x505ca)
#4  0x00007f97989a0315 n/a (libglib-2.0.so.0 + 0x87315)
#5  0x00007f979836e44b n/a (libc.so.6 + 0x8744b)
#6  0x00007f97983f1e40 n/a (libc.so.6 + 0x10ae40)

Stack trace of thread 8512:
#0  0x00007f97983e4c0f __poll (libc.so.6 + 0xfdc0f)
#1  0x00007f97989d017f n/a (libglib-2.0.so.0 + 0xb717f)
#2  0x00007f9798972c7f g_main_loop_run (libglib-2.0.so.0 + 0x59c7f)
#3  0x000055f24acfe601 n/a (xdg-desktop-portal + 0x24601)
#4  0x00007f979830a850 n/a (libc.so.6 + 0x23850)
#5  0x00007f979830a90a __libc_start_main (libc.so.6 + 0x2390a)
#6  0x000055f24acfea85 n/a (xdg-desktop-portal + 0x24a85)
ELF object binary architecture: AMD x86-64
```

uninstalling visualstudio code fixed this for me, error is not present in AUR, only in flatpak

(I am using manjaro plasma, qt6-base 6.5.0-3, prism launcher 6.3)

**Comment by wanesty** [comment] 2023-06-11 09:08
![image](https://github.com/PrismLauncher/PrismLauncher/assets/98633588/6151e90e-a9ea-471d-a9b7-90fce6de141a)
no error both with and without vscodium (aur) (ignore the pipewire logs it's from something else)

prism is from the aur and as [`aur/prismlauncher 7.0-1`](https://aur.archlinux.org/packages/prismlauncher)

**Comment by wanesty** [comment] 2023-11-12 02:05
still relevant with the new 8.0 update,
even tho ksystemlog shows the opening correctly without error, as my last comment,
and `xdg-open ~/.local/share/PrismLauncher/instances/Qreate-015a-devtest/.minecraft/mods/` do open the folder correctly.

**Comment by Trial97** [comment] 2024-01-17 16:13
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1490
And fixed in: https://github.com/PrismLauncher/PrismLauncher/pull/1954

**Closed as completed by Trial97** 2024-01-17 16:13 UTC

**Comment by wanesty** [comment] 2024-01-18 22:46
pog, ty all !! :)

**Comment by blockninja124** [comment] 2025-09-06 14:21
I'm experiencing this issue on Linux Mint 22.1, kernel 6.8.0-78-generic. My prism launcher is latest, Build date: 2025-04-07 Channel: stable. I installed it using the app image download on the website. Its installed in portable mode. Other applications, such as firefox or Visual Studio Code, can open Files fine. All of the prism buttons that are meant to open Files simply do nothing.
