### ISSUE TITLE
Settings window move down when try to scale it down from the top.

### ISSUE THREAD

**Issue by ElSanster** [PrismLauncher/PrismLauncher#3146] opened 2024-11-29 01:50 UTC
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

6.7.3

### Description of bug

When I scale the settings window of the launcher vertically, the window moves down, even it surpasses the screen and it becomes the launcher inaccesible, having to finish the task, I have to do this because I can't get the close button on my screen.

Here's a video showing the bug:
https://github.com/user-attachments/assets/21761b2c-1cae-4b20-8e05-20b63d8c0db4
Thanks for reading.

### Steps to reproduce

Go to settings and scale down from the top of the settings window of the launcher.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-11-29 07:19
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/220
And this one should be fixed by https://github.com/PrismLauncher/PrismLauncher/pull/3070

**Closed as not planned by Trial97** 2024-11-29 07:19 UTC
