### ISSUE TITLE
Cat PNG Bug

### ISSUE THREAD

**Issue by TheBestOf1204** [PrismLauncher/PrismLauncher#2316] opened 2024-04-19 08:34 UTC
### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

When scrolling in the launcher beacause there are more packs then fitting, some parts of the cat dont go with the rest
<img width="605" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/167515563/cb7abb2c-e19f-4987-b655-2077adfa03d4">
it's a small only visual bug, yet still a bug

### Steps to reproduce

enabling the cat via the button, then scrolling, and the "distortion" happens

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-04-19 08:44
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1504

**Closed as not planned by Trial97** 2024-04-19 08:44 UTC
