### ISSUE TITLE
Wrapper command executable can't be `$INST_JAVA`

### ISSUE THREAD

**Issue by quat1024** [PrismLauncher/PrismLauncher#2787] opened 2024-09-06 05:49 UTC
### Operating System

Windows

### Version of Prism Launcher

8.4

### Version of Qt

6.6.3

### Description of bug

Setting the prelaunch command to something starting with `$INST_JAVA` will use the currently configured Java VM as the prelaunch executable. This is a common way to write prelaunch commands in Java without needing to manually specify a path to Java. This trick is often used by packwiz-installer-bootstrap projects.

The same does not work for the wrapper command. Setting the wrapper command to `$INST_JAVA` just prints

> The wrapper command "$INST_JAVA" couldn't be found.

in the console.

### Steps to reproduce

* Set the prelaunch command to `$INST_JAVA -version`
* Set the wrapper command to `$INST_JAVA -version`
* The prelaunch command works. The wrapper command doesn't.

### Suspected cause

PreLaunchCommand.executeTask calls this "substituteVariables" function. https://github.com/PrismLauncher/PrismLauncher/blob/828acef7e938800a693343a0bb51e5fcd7349680/launcher/launch/steps/PreLaunchCommand.cpp#L53

No such function is called on the wrapper command. https://github.com/PrismLauncher/PrismLauncher/blob/828acef7e938800a693343a0bb51e5fcd7349680/launcher/minecraft/launch/LauncherPartLaunch.cpp#L133-L137

("Why on earth would you write the wrapper command in Java" - would be fun to try and automate the "remove half the mods to debug a modpack crash" process? launch mc thru the wrapper so it can be restarted when it dies)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by quat1024** [comment] 2024-09-06 05:51
Maybe a dupe of #707 actually

**Comment by Trial97** [comment] 2024-09-06 06:13
Yes it is a duplicate of  the mentioned issue

**Closed as not planned** 2024-09-06 06:13 UTC
