### ISSUE TITLE
Game log isn't encoded with UTF-8

### ISSUE THREAD

**Issue by StrangeOne101** [PrismLauncher/PrismLauncher#2419] opened 2024-05-19 03:05 UTC
### Operating System

Windows 10 

### Version of Prism Launcher

8.3

### Version of Qt

6.6.3

### Description of bug

When non english characters (in this case, Russian) characters appear in the log (the log within Prism), they appear encoded incorrectly. 

This is copied and pasted from the log
```
[14:52:54] [Render thread/INFO]: [CHAT] Ð¸Ð³Ñ€Ð¾ÐºÐ°, Ð¿Ñ€Ð¸Ð³Ð»Ð°ÑÐ¸Ð²ÑˆÐµÐ³Ð¾ Ð’Ð°Ñ Ð½Ð° ÑÐµÑ€Ð²ÐµÑ€.
[14:52:54] [Render thread/INFO]: [CHAT] 
[14:52:54] [Render thread/INFO]: [CHAT] ÐÐ°Ð³Ñ€Ð°Ð´Ð°: á´‡á´á´‡Ê€á´€ÊŸá´… Ð½Ð° 3 Ð´Ð½Ñ (Ð’Ð°Ð¼ Ð¸ ÐŸÑ€Ð¸Ð³Ð»Ð°ÑÐ¸Ð²ÑˆÐµÐ¼Ñƒ)
[14:52:54] [Render thread/INFO]: [CHAT] Ð•ÑÐ»Ð¸ Ñƒ Ð’Ð°Ñ ÑƒÐ¶Ðµ ÐµÑÑ‚ÑŒ á´‡á´á´‡Ê€á´€ÊŸá´…, Ñ‚Ð¾Ð³Ð´Ð°
```

### Steps to reproduce

1. Copy and paste something in russian in chat
2. Open Prism log
3. See how the chat message appears incorrectly

### Suspected cause

I suspect the log isn't using UTF-8 like it should be.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-05-19 06:50
This may be due to how your locale is set up, as this works as intended for me on linux. 
Make sure your windows locale is set correctly(no I have no idea how to do stuff on windows so search for it on google).

**Comment by StrangeOne101** [comment] 2024-05-19 08:53
I've looked it up, and it says the locale for Windows is only used when the application doesn't support unicode. This makes me think that there is some program field somewhere that says whether the program supports it or not.

My current locale was set to English US, which is fine. The locales available are only regional locales (every language with variants for location).
![image](https://github.com/PrismLauncher/PrismLauncher/assets/2769013/0ea96a2f-074f-41c8-951e-2e1690bc3a35)

**Comment by Trial97** [comment] 2024-05-19 09:30
Prism uses that locale to decode the std output of Minecraft: https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/LoggedProcess.h#L84 
try adding Russian or something there

**Comment by Frenzied-Dog** [comment] 2024-06-16 08:30
Will it be fix by maybe adding an option to force using utf-8? I have same problem and I'm a traditional chinese user.

**Comment by mat9369** [comment] 2024-06-16 12:15
I think this is due to the fact that the default character encoding has been changed from the system character encoding to UTF-8 since Java 18. (JEP 400: UTF-8 by Default)
https://openjdk.org/jeps/400

In my case (playing Minecraft 1.20.6 on a computer with Japanese settings (system character encoding is MS932)):
1. Minecraft uses Java 21 (Java 18 or higher) from version 1.20.5, so logs are saved in UTF-8.
2. The console tries to display logs in the system character encoding (MS932).
3. The character encoding of the logs (UTF-8) and the console (MS932) do not match, resulting in garbled characters on the console.
![prism_log_screenshot](https://github.com/PrismLauncher/PrismLauncher/assets/118247917/e358a514-f13c-4f02-a647-2dbdb66fdf32)

Possible solutions:
A. Make it possible to arbitrarily set the character encoding of the console to either UTF-8 or the system character encoding.
B. Fix the character encoding of the console to UTF-8 and add "-Dfile.encoding=UTF-8" to the Java argument by default.

Currently possible workarounds:
Add "-Dfile.encoding=COMPAT" to the Java argument only if Minecraft is running on Java 18 or higher (Minecraft 1.20.5 or higher). 
This will save the logs in the system character encoding (as in Java 17 and earlier) and should prevent garbled characters on the console.

(I used a Deepl translation and ChatGPT)

**Comment by Frenzied-Dog** [comment] 2024-06-16 12:50
Thanks for replying! I've tried your solution and it works, but here comes another problem.
In "Minecraft log" tab, the launcher tries to display logs in the system character encoding.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/86578837/e28043c6-387e-4bc1-88c9-2c058fd7b250)
In "Other logs" tab, however, it uses utf-8 to read the existing log file...
![image](https://github.com/PrismLauncher/PrismLauncher/assets/86578837/0369af1e-52ff-4e4f-aebe-c314cbe415e4)
For the second image I read the latest.log from the "Other logs" tab, and yeah it become garbled characters.
(btw before I Add "-Dfile.encoding=COMPAT" to the argument, the "Other logs" tab is working well without garbled characters)

**Comment by mat9369** [comment] 2024-06-16 15:20
The reason why logs are garbled in the "Other logs" tab is because they are saved with the system's character encoding using "-Dfile.encoding=COMPAT".

The console displays logs in the system's character encoding.
https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/LoggedProcess.h#L84

The "Other logs" tab displays logs in UTF-8.
https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/pages/instance/OtherLogsPage.cpp#L168-L170

If "-Dfile.encoding=COMPAT" is used (system's character encoding), there won't be garbled characters in the console, but there will be in the "Other logs" tab. 
If "-Dfile.encoding=COMPAT" is not used (UTF-8), there won't be garbled characters in the "Other logs" tab, but there will be in the console.

Therefore, until PrismLauncher resolves this issue, it's not possible to simultaneously display the console and "Other logs" tab without garbled characters.

(There may be some uncertainty in my explanation.)

**Comment by Frenzied-Dog** [comment] 2024-06-16 16:28
I just do a fork and make a little change ( simply replace "codecForLocale()" with "codecForName("UTF-8")" )
Then it WORKS!
![image](https://github.com/PrismLauncher/PrismLauncher/assets/86578837/89d9632f-fb57-4aa3-ba77-13e73e4b96f5)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/86578837/9f6402f6-2c15-4c29-a3ba-ffd714c13005)
Now both of the tabs are using utf-8 to decode logs.

**Comment by BoBkiNN** [comment] 2024-09-01 11:44
Same issue on 8.4. Hoping that `codecForName("UTF-8")` will be used in next version

**Closed as completed** 2024-10-11 17:10 UTC
