### ISSUE TITLE
Prism Launcher wont start on Steam Deck

### ISSUE THREAD

**Issue by JannikGHG** [PrismLauncher/PrismLauncher#2886] opened 2024-10-04 05:58 UTC
### Operating System

Linux

### Version of Prism Launcher

8.4

### Version of Qt

Unknown since I can't open it

### Description of bug

Hey folks,

i use Prism Launcher on Steam Deck and it won't start (it only opens in taskbar and then crashes) on Desktop Mode and Gaming Mode even after reinstalling through Flatpak

Any help appreciated

### Steps to reproduce

Open Prism Launcher

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-10-04 06:02
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2388
(same idea: Wayland+Flatpack+QT6+Prism)

**Closed as not planned by Trial97** 2024-10-04 06:02 UTC
