### ISSUE TITLE
Visual glitch with external windows overlapping with Prism

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#2401] opened 2024-05-13 18:29 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.0-develop (f15981d786c23b724fb9028b157ffafb574f7d01)
Built from the prismlauncher-git AUR package

### Version of Qt

6.7.0

### Description of bug

The weird overlapping window glitch that most people have seen once in their life but don't know how to describe. Here is a vid of what I am talking about.

https://github.com/PrismLauncher/PrismLauncher/assets/96212687/b2ffd731-4172-435a-aaa1-69d710d7936d (OBS straight up cannot capture this for some reason but hopefully this helps. I'll try a few more things when I get a chance) 
~~This happens with every "external" window I have tested with except the "About QT" window for some reason.~~
It fixed itself on everything but Create Instance when I was trying to rerecord????

### Steps to reproduce

1. Open Prism Launcher
2. Open a window such as the Add Instance window or Prism Launcher's settings window
3. Move window around
4. Bug

### Suspected cause

Probably i3 tiling window manager weirdness.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment] 2024-05-13 19:11
You mention i3 as the cause can you reproduce it using another window manager?

**Comment by ghost** [comment] 2024-05-13 23:17
> You mention i3 as the cause can you reproduce it using another window manager?

I don't have anything else setup to test on right now. I can try to set something up later to verify.

**Comment by Trial97** [comment] 2024-08-10 06:00
Closing this as there were no follow-ups regarding whether it can be reproduced on other window managers.
I will consider reopening this once it is confirmed with multiple window managers, until then we can consider this a bug on I3 side.

**Closed as not planned by Trial97** 2024-08-10 06:00 UTC
