### ISSUE TITLE
Add Auto Java Installer to PrismMC

### ISSUE THREAD

**Issue by therabug** [PrismLauncher/PrismLauncher#1765] opened 2023-10-30 07:33 UTC
### Role

I play modded Minecraft.

### Suggestion

I want to when I setup PrismMC it will need to install java automatically

### Benefit

My life will be easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TayouVR** [comment] 2023-10-30 23:01
duplicate of #734

**Closed as not planned by TayouVR** 2023-10-30 23:01 UTC
Labels: type: enhancement
