### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Martmists-GH** [PrismLauncher/PrismLauncher#1223] opened 2023-06-18 09:48 UTC
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.1 (Build date: 2023-06-17)

### Version of Qt

Qt 6.5.1

### Description of bug

Trying to launch any instance results in `The account has expired and needs to be logged into manually again.` Refreshing in the accounts tab shows the account is ready, and removing and re-adding it doesn't resolve the issue.

### Steps to reproduce

1. Log in with a Microsoft account
2. Try launching an instance

### Suspected cause

<details>
<summary>Logs after hitting Launch</summary>
<pre><code>     9.101 D | [launcher.task]: Task "LaunchController(0x7f82ec1b6760 ID: c2de9af2-13de-4eea-a0d9-73ba706857f7)" starting for the first time
     9.103 D | Instance-type specific settings were loaded!
     9.105 D | [launcher.task]: Task "MSASilent(0x55d5c176c360 ID: dbb79680-69fe-474c-be9f-30c4b7d7dd30)" starting for the first time
     9.105 D | AuthFlow: "Logging in with Microsoft account."
     9.105 D | DeviceFlow::refresh: Token: ... ""
     9.105 W | DeviceFlow::refresh: No refresh token
     9.105 C | [launcher.task]: Task "MSASilent(0x55d5c176c360 ID: dbb79680-69fe-474c-be9f-30c4b7d7dd30)" failed:  "Microsoft user authentication failed."
     9.105 D | Writing account list to "accounts.json"
     9.105 D | Building JSON data structure.
     9.105 D | Building account array.
     9.105 D | Writing account list to file.
     9.106 D | Saved account list to "accounts.json"
     9.119 D | DeviceFlow::onRefreshFinished: Error 204  -  "No Reply"
    11.286 C | [launcher.task]: Task "LaunchController(0x7f82ec1b6760 ID: c2de9af2-13de-4eea-a0d9-73ba706857f7)" failed:  "The account has expired and needs to be logged into manually again."</code></pre></details>

I initially assumed the authentication servers were down, but according to [DownDetector](https://downdetector.com) it seems neither XBox Live nor Minecraft are getting many reports at the moment.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by nzsmk** [comment] 2023-06-24 07:42
I am also having this issue with 2 ubuntu os.
"The account has expired and needs to be logged into manually again."

**Comment by MMK21Hub** [comment] 2023-07-18 12:22
Note that this issue also affects offline accounts - even though it doesn't even make sense for those accounts to suffer from authentication issues.

Just to clarify, this bug **entirely prevents users from being able to play Minecraft** through Prism Launcher, effectively rendering the app unusable. I will ask if there's a workaround in the Discord server.

![A dialog box with the title "Account refresh failed" and body "The account has expired and needs to be logged into manually again."](https://github.com/PrismLauncher/PrismLauncher/assets/50421330/a21d3b3f-473c-4d1c-93fc-88958cf65892)

**Comment by MMK21Hub** [comment] 2023-07-20 09:39
As a workaround for this issue, you can rename the `accounts.json` file in the Launcher Root Folder (usually `~/.local/share/PrismLauncher`) to something like `accounts.json.bak`, which will let Prism start from a clean slate in terms of accounts. Then, you can re-add your accounts without any issues.

**Comment by dexterlabsnz** [comment] 2023-07-20 22:25
Not sure why but this issue resolved its self about 9-14 days ago. sorry for the slow update!!

**Comment by nzsmk** [comment] 2023-07-20 22:32
This issue resolved it self around 9-14 days ago, not sure why. Sorry for the lack of update!!

**Comment by Severus157** [comment] 2023-07-24 17:02
Facing the same issue on Prismlauncher 7.1; Build date: 2023-07-02 on Archlinux. Got the info the Account has expired and I need to login again. Microsoft Login correctly gives the correct HTTP Request, but Prismlauncher doesn't log in the account.

Error found in Logs:
` 13446.264 W | DeviceFlow::onVerificationReceived: Verification failed: QMap(("correlation_id", "707679d6-8f4d-4cb6-af18-c493d0e6179f")("error", "invalid_grant")("error_codes", "")("error_description", "AADSTS70000: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope.\r\nTrace ID: 6354b568-97a8-410a-bc36-f1e75b413b00\r\nCorrelation ID: 707679d6-8f4d-4cb6-af18-c493d0e6179f\r\nTimestamp: 2023-07-23 19:23:46Z")("error_uri", "https://login.microsoftonline.com/error?code=70000")("timestamp", "2023-07-23 19:23:46Z")("trace_id", "6354b568-97a8-410a-bc36-f1e75b413b00"))`

Renaming the file accounts.json doesn't solve the issue. Still a few Accounts cannot be logged in. Also the File Accounts.json File is not regenerated.

https://pastebin.com/tL0dLHUm

**Comment by Trial97** [comment] 2023-10-23 21:09
Are you still having this issue?

**Comment by MMK21Hub** [comment] 2023-11-04 07:14
Personally, I can still reproduce this in 7.2 by reverting my `accounts.json` to the state it was before I reset it (i.e. the workaround I mentioned). However, I have never had the issue persist after resetting the `accounts.json`, like others describe.

**Comment by richardbizik** [comment] 2023-11-08 11:47
I am having the same issue as @Severus157 with error AADSTS70000 and version 8.0. I tried the suggested steps to rename `accounts.json` but it did not help. I tried reinstalling the launcher and completely removing `~/.var/apps/org.prismlauncher.PrismLauncher`.
I tried logging in on ubuntu/arch machines in incognito mode and normal browser session.
```
52.260 D | DeviceFlow::onVerificationReceived: Emitting closeBrowser()
52.260 W | DeviceFlow::onVerificationReceived: Verification failed: QMap(("correlation_id", "a294907a-e79a-4e6d-b845-370a9c3711a5")("error", "invalid_grant")("error_codes", "")("error_description", "AADSTS70000: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope. Trace ID: 4d4ca1f8-0ecf-4654-9e2b-168cc57cd801 Correlation ID: a294907a-e79a-4e6d-b845-370a9c3711a5 Timestamp: 2023-11-07 14:25:27Z")("error_uri", "https://login.microsoftonline.com/error?code=70000")("timestamp", "2023-11-07 14:25:27Z")("trace_id", "4d4ca1f8-0ecf-4654-9e2b-168cc57cd801"))
```

**Comment by Severus157** [comment] 2023-11-11 09:03
One thing I found to actually cause the Issue with Prismlauncher:
When you sign in with a Microsoft Account and you just use the Email Verification. Where Microsoft just sends you a MailCode to Login.

As this is standard method for Microsoft they use when you create a new Account and so on it's quite annoying. 

But as a Workaround,when you switch the Account to Password authentication it magically begins to work...

**Comment by stephen-smith** [comment] 2023-11-26 15:18
Got hit with this today.  Renaming accounts.json and adding the account "from scratch" seemed to work.  Might have been complicated by an MS TOS update, which caused an extra step in my browser login process.

**Comment by deviantsemicolon** [comment] 2023-11-27 02:57
> One thing I found to actually cause the Issue with Prismlauncher: When you sign in with a Microsoft Account and you just use the Email Verification. Where Microsoft just sends you a MailCode to Login.
> 
> As this is standard method for Microsoft they use when you create a new Account and so on it's quite annoying.
> 
> But as a Workaround,when you switch the Account to Password authentication it magically begins to work...

Seconding this. Had the same issue and switching to password authentication fixed it

**Comment by jensfriisnielsen** [comment] 2024-02-07 11:33
> But as a Workaround,when you switch the Account to Password authentication it magically begins to work...

This is also fixed it for me. As a side note the Email Verification setting also caused an infinite logon redirect between Microsoft pages. I had to go directly to https://account.live.com/password/Change

**Comment by ChillerDragon** [comment] 2024-03-11 11:20
I also managed to fix it by changing my microsoft password. Going to account.microsoft.com in my browser resulted in an infinite loop. Apparently that was caused by too many login attempts. So I clicked forgot password and set a new one. This is clearly microsoft being horrible. But it would be nice if the PrismLauncher showed a helpful error message in the ui. Something like:

**Try going to https://account.live.com/password/Change and change your password. And also switch to password authentication.**

When it logs the following

```
13446.264 W | DeviceFlow::onVerificationReceived: Verification failed: QMap(("correlation_id", "707679d6-8f4d-4cb6-af18-c493d0e6179f")("error", "invalid_grant")("error_codes", "")("error_description", "AADSTS70000: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope.\r\nTrace ID: 6354b568-97a8-410a-bc36-f1e75b413b00\r\nCorrelation ID: 707679d6-8f4d-4cb6-af18-c493d0e6179f\r\nTimestamp: 2023-07-23 19:23:46Z")("error_uri", "https://login.microsoftonline.com/error?code=70000")("timestamp", "2023-07-23 19:23:46Z")("trace_id", "6354b568-97a8-410a-bc36-f1e75b413b00"))
```

**Comment by Rinske153** [comment] 2024-03-21 19:08
> This is also fixed it for me. As a side note the Email Verification setting also caused an infinite logon redirect between Microsoft pages. I had to go directly to https://account.live.com/password/Change

Thank you for this info!  I wanted to play a bit in a local world while I didn't have Internet access to fix the issue, and with this info, I realized I could make an "offline" account that Prism wouldn't check with Microsoft about :). It also logged me in as y character, just without my skin.

So glad there are so many helpful people in this community.

**Comment by Trial97** [comment] 2024-04-12 16:26
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Closed as not planned by Trial97** 2024-04-12 16:26 UTC
Labels: area: auth
