### ISSUE TITLE
that very common issue where i can't sign into my microsoft acc

### ISSUE THREAD

**Issue by SnailzFly** [PrismLauncher/PrismLauncher#2673] opened 2024-07-21 23:12 UTC
### Operating System

macOS

### Version of Prism Launcher

8.4

### Version of Qt

qt 6.6.3

### Description of bug

after saying its logging me in `Failed to get authorization for Xbox services: Operation canceled` pops up in red [here's the log](https://mclo.gs/3LLYiYU)

### Steps to reproduce

follow given steps to sign into microsoft acc

### Suspected cause

no idea. i tried every troubleshooting method

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment] 2024-07-21 23:15
Duplicate of #2302
See remedies there.

Also Microsoft is still having occasional regional server issues related cloudstrike's silliness

**Closed as completed by Ryex** 2024-07-21 23:15 UTC

**Comment by SnailzFly** [comment] 2024-07-21 23:30
i looked at that issue and tried all the remedies :/

**Comment by Ryex** [comment] 2024-07-22 01:12
you can try one of our dev builds to see if that helps. But, best we can tell you is to wait out the network issues.
