### ISSUE TITLE
Register a custom protocol for mod quick install from Modrinth/Curseforge

### ISSUE THREAD

**Issue by Yumeo0** [PrismLauncher/PrismLauncher#2403] opened 2024-05-15 15:56 UTC
### Role

I create Modpacks

### Suggestion

Register a custom protocol for mod quick install from Modrinth/Curseforge

### Benefit

It's easier to find mods on the websites

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I have likes and collections on modrinth and a one-click install button would make it easier.

How would this be implemented?

PrismLauncher: 
Would need to register a custom protocol. Idk how exactly this would work but I found this https://medium.com/swlh/custom-protocol-handling-how-to-8ac41ff651eb
Protocol would look something like "prismlauncher://[modloader]/[mod-id]"
Like the medium article says input validation here is very important.
Which instance would the mod be installed to? Idk maybe the currently opened one. Idk how Prism handles it's windows and stuff. Neither do I have the expertise and time to find out. So if anything sounds not doable tell me please xD

Websites:
I could just write a simple browser extension that adds a button to each page that calls the protocol. This is the easy part.

**Comment by Trial97** [comment] 2024-05-15 16:04
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2300

And until modrinth doesn't provide something like curseforge this will not be implemented.

**Closed as not planned by Trial97** 2024-05-15 16:04 UTC
Labels: type: enhancement

**Comment by Yumeo0** [comment] 2024-05-15 16:05
Ah I didn't see that one sorry. Understandable.
